activepieces/activepieces

src/worker/.gitignore
src/worker/package-lock.json
src/worker/package.json
src/worker/src/executors/component-executer.ts
src/worker/src/model/action/action-factory.ts
src/worker/src/model/action/types/component-action.ts
src/worker/test/executors/component-executer.test.ts
src/worker/test/models/action-factory.test.ts
src/worker/test/models/component-action.test.ts

- Add a component executer
- Add a component action
- Update the action factory to use the component action for actions of type component

Feature (TS Worker): Component execution

---

.github/workflows/release-backend.yml
.github/workflows/release-frontend.yml
src/backend/Dockerfile
src/backend/backend-loader/pom.xml
src/frontend/package.json

- Build and deploy docker images for frontend and backend
- Fail if tags already exist on Docker Hub
- Document how to release a new version: https://github.com/activepieces/activepieces/wiki/Release-new-version
closes #74

Feature automate releases #74

---

src/worker/package-lock.json
src/worker/packages/components/index.ts
src/worker/packages/components/src/apps/index.ts
src/worker/packages/components/src/apps/slack/index.ts
src/worker/packages/components/src/framework/component-not-found.ts
src/worker/packages/components/src/framework/component.ts
src/worker/packages/components/src/framework/trigger/trigger-not-found-error.ts
src/worker/packages/engine/src/executors/component-executor.ts
src/worker/packages/engine/src/index.ts
src/worker/packages/server/package.json
src/worker/packages/server/src/app/app.ts
src/worker/packages/server/src/controller/components.controller.ts
src/worker/packages/server/src/helper/activepieces-error.ts
src/worker/packages/shared/src/dto/components/component-option-request.ts

Migrated two endpoints:
- Listing Components Metadata
- Return dynamic config options inside the components.
Added as well
- ActivepiecesError Class and new three error code.
- ErrorHandler on application
- Schema for options endpoint request

Updated Component Controller

---

src/worker/package-lock.json
src/worker/packages/backend/docker-compose.yml
src/worker/packages/backend/package.json
src/worker/packages/backend/src/app.ts
src/worker/packages/backend/src/authentication/authentication.controller.ts
src/worker/packages/backend/src/authentication/authentication.service.ts
src/worker/packages/backend/src/authentication/lib/token-utils.ts
src/worker/packages/backend/src/authentication/token-verify-middleware.ts
src/worker/packages/backend/src/collections/collection-entity.ts
src/worker/packages/backend/src/collections/collection.controller.ts
src/worker/packages/backend/src/collections/collection.service.ts
src/worker/packages/backend/src/components/components.controller.ts
src/worker/packages/backend/src/entity/instance-run-entity.ts
src/worker/packages/backend/src/instance/instance.service.ts
src/worker/packages/backend/src/project/project.controller.ts
src/worker/packages/backend/src/project/project.service.ts
src/worker/packages/backend/src/workers/flow-worker/flow-worker.ts
src/worker/packages/components/index.ts
src/worker/packages/shared/package.json
src/worker/packages/shared/src/authentication/dto/authentication-request.ts
src/worker/packages/shared/src/authentication/model/principal-type.ts
src/worker/packages/shared/src/authentication/model/principal.ts
src/worker/packages/shared/src/common/id-generator.ts
src/worker/packages/shared/src/index.ts

- Request validation
- Principal type

Feature authentication

---

packages/backend/src/app.ts
packages/backend/src/helper/activepieces-error.ts
packages/backend/src/helper/public-ip-utils.ts
packages/backend/src/helper/trigger-utils.ts
packages/backend/src/webhooks/webhook-controller.ts
packages/backend/src/webhooks/webhook-module.ts
packages/backend/src/webhooks/webhook-service.ts

- get public address using Google DNS for webhooks
- webhook controller

Feature: Webhooks

---

docker-compose.yml
packages/backend/package.json
packages/backend/src/app.ts
packages/backend/src/authentication/authentication.service.ts
packages/backend/src/flags/flag.service.ts
packages/backend/src/helper/system/system-prop.ts
packages/backend/src/helper/trigger-utils.ts

Feature: webhook flag and unlimited registrations

---

docs/contributing/building-pieces/quickstart.mdx
packages/pieces/package.json
packages/pieces/src/apps/discord/common/index.ts
packages/pieces/src/apps/github/common/index.ts
packages/pieces/src/apps/github/trigger/new-star.ts
packages/pieces/src/apps/hackernews/actions/top-stories-in-hacker-news.ts
packages/pieces/src/apps/hubspot/actions/create-contact.action.ts
packages/pieces/src/apps/mailchimp/common/index.ts
packages/pieces/src/apps/slack/actions/send-message-action.ts
packages/pieces/src/common/http/axios/axios-http-client.ts
packages/pieces/src/common/http/core/authentication/authentication-converter.ts
packages/pieces/src/common/http/core/authentication/bearer-authentication-converter.ts
packages/pieces/src/common/http/core/authentication/delegating-authentication-converter.ts
packages/pieces/src/common/http/core/base-http-client.ts
packages/pieces/src/common/http/core/http-client.ts
packages/pieces/src/common/http/core/http-headers.ts
packages/pieces/src/common/http/core/http-request.ts
packages/pieces/src/common/http/core/http-response.ts
packages/pieces/src/common/http/core/request-headers.ts

Feature: Pieces `HttpClient` update to expose `HttpResponse` and fix query params concatenation

---

docs/mint.json
docs/pieces/apps/mailchimp.mdx
packages/docs-generator/.eslintrc
packages/docs-generator/package-lock.json
packages/docs-generator/package.json
packages/docs-generator/src/index.js
packages/docs-generator/src/index.ts
packages/pieces/src/apps/discord/discord.mdx
pnpm-lock.yaml

Linked to: https://github.com/activepieces/activepieces/issues/256

Extend to predefined templates

---

packages/pieces/package.json
packages/pieces/src/apps/index.ts
packages/pieces/src/apps/openai/actions/send-prompt.ts
packages/pieces/src/apps/openai/index.ts
packages/pieces/tsconfig.json

Implement question answering feature using text-davinci-003 and OpenAI API

Openai piece

---

packages/backend/src/app/webhooks/webhook-service.ts
packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.html
packages/frontend/src/app/modules/common/components/form-controls/array-form-control/array-form-control.component.html
packages/frontend/src/app/modules/common/components/form-controls/code-artifact-form-control/code-artifact-form-control.component.html
packages/frontend/src/app/modules/common/components/form-controls/code-artifact-form-control/code-artifact-form-control.component.ts
packages/frontend/src/app/modules/common/components/form-controls/dictionary-form-control/dictionary-form-control.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/builder-autocomplete-mentions-dropdown/builder-autocomplete-mentions-dropdown.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/builder-autocomplete-mentions-dropdown/builder-autocomplete-mentions-dropdown.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/builder-autocomplete-mentions-dropdown/builder-autocomplete-mentions-dropdown.service.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/interpolating-text-form-control.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/interpolating-text-form-control.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mentions-list.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/webhook-trigger-mention-item/webhook-trigger-mention-item.component.ts
packages/frontend/src/app/modules/flow-builder/components/test-flow-modal/test-flow-modal.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/input-forms/storage-step-input-form/storage-step-input-form.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-list/step-type-list.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-list/step-type-list.component.scss
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-list/step-type-list.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-sidebar.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-sidebar.component.ts
packages/frontend/src/assets/scss/utlis.scss
packages/shared/src/lib/flow-run/create-flow-run-request.ts

1)Now the auto complete only closes on the click of the close button and clicking on another control that uses auto complete.
2)Added search bar for steps list.
3)Hidden the replace trigger/remove step in readonly mode (Runs).
4)The tooltip for fullscreen on the code editor now shows once the code step is clicked so people can notice it.
5)The trigger sample data gets sent to test flow when it is an app trigger, if no sample data is provided we send an empty object.

fixed all comments in pr

---

docs/_snippets/apps.mdx
docs/contributing/building-pieces/quickstart.mdx
docs/pieces/overview.mdx
packages/pieces/src/lib/docs-generator/index.ts

Auto generate app overview icon

docs: add pieces overview generator

---

docs/_snippets/apps.mdx
packages/pieces/src/lib/docs-generator/index.ts

docs: regenerated apps overview

---

docs/_snippets/apps.mdx
packages/pieces/src/lib/docs-generator/index.ts

docs: fixed pieces link

---

packages/pieces/src/lib/apps/index.ts
packages/pieces/src/lib/apps/typeform/common/index.ts
packages/pieces/src/lib/apps/typeform/index.ts
packages/pieces/src/lib/apps/typeform/trigger/new-submission.ts

Creates a trigger when typeform receives a new submission

feat: add typeform new submission

---

packages/pieces/src/lib/apps/hubspot/actions/add-contact-to-list-action.ts
packages/pieces/src/lib/apps/hubspot/actions/create-contact.action.ts
packages/pieces/src/lib/apps/hubspot/actions/create-or-update-contact-action.ts
packages/pieces/src/lib/apps/hubspot/common/client.ts
packages/pieces/src/lib/apps/hubspot/common/index.ts
packages/pieces/src/lib/apps/hubspot/common/models.ts
packages/pieces/src/lib/apps/hubspot/common/props.ts
packages/pieces/src/lib/apps/hubspot/index.ts

Add HubSpot actions:
- Create or update contact
- Add contact to list
Closes #367 

Feature hubspot contact added trigger

---

packages/pieces/src/lib/apps/asana/actions/create-task.ts
packages/pieces/src/lib/apps/asana/common/index.ts
packages/pieces/src/lib/apps/asana/index.ts
packages/pieces/src/lib/apps/index.ts
packages/shared/src/lib/authentication/dto/sign-up-request.ts

Pieces that has action to create tasks on asana project.

feat: add asana create task

---

packages/backend/src/app/flow-run/flow-run-service.ts
packages/backend/src/app/helper/telemetry.utils.ts
packages/backend/src/app/project/project.service.ts
packages/shared/src/lib/common/telemetry.ts

Count number of runs to know the number of active flows.
- [] Chore (refactoring code, technical debt, workflow improvements)

feat: count runs

---

packages/pieces/src/lib/apps/stripe/index.ts
packages/pieces/src/lib/apps/stripe/trigger/new-customer.ts
packages/pieces/src/lib/apps/stripe/trigger/new-payment.ts
packages/pieces/src/lib/apps/stripe/trigger/new-subscription.ts
packages/pieces/src/lib/apps/stripe/trigger/payment-failed.ts

Add new trigger on customer subscription.

feat: add new customer subscription

---

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.html
packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.ts
packages/frontend/src/app/modules/common/components/configs-form/connector-action-or-config.ts
packages/frontend/src/app/modules/common/components/form-controls/code-artifact-form-control/code-artifact-control-fullscreen/test-code-form-modal/test-code-form-modal.component.html

New Property type an Json Editior

feat: added JSON control to pieces forms

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/pieces/src/lib/apps/http/actions/send-http-request-action.ts
packages/pieces/src/lib/apps/http/common/props.ts
packages/pieces/src/lib/apps/http/index.ts
packages/pieces/src/lib/apps/index.ts
packages/pieces/src/lib/framework/action/action.ts
packages/pieces/src/lib/framework/property/base-prop.ts
packages/pieces/src/lib/framework/property/property.ts

HTTP send request action
Closes #271 

feat: HTTP piece #271

---

docker-compose.yml
package.json
packages/backend/package.json
packages/frontend/package.json

chore: release 0.2.3

---

packages/frontend/src/app/modules/common/common-layout.module.ts
packages/frontend/src/app/modules/common/components/ap-button/ap-button.component.scss
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/code-step-mention-item/code-step-mention-item.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/code-step-mention-item/code-step-mention-item.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/generic-mention-item/generic-mention-item.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/generic-mention-item/generic-mention-item.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/generic-step-mention-item/generic-step-mention-item.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mention-list-item-template/mention-list-item-template.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mention-list-item-template/mention-list-item-template.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mentions-list.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mentions-list.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/mentions-tree-cache.service.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/step-mentions-tree/step-mentions-tree.component.html
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/step-mentions-tree/step-mentions-tree.component.scss
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/mentions-list/step-mentions-tree/step-mentions-tree.component.ts
packages/frontend/src/app/modules/common/components/form-controls/interpolating-text-form-control/utils.ts
packages/frontend/src/app/modules/flow-builder/service/action-meta.service.ts
packages/frontend/src/app/modules/flow-builder/store/builder/flow-item-details/flow-items-details.effects.ts
packages/frontend/src/assets/scss/ng-material-override.scss
packages/frontend/src/assets/scss/utlis.scss

Issue 363 tweaks to autocomplete

---

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.html
packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.ts

Activates beautify for json control and default value

chore: activated beautify and default value

---

docker-compose.yml
package.json
packages/backend/package.json
packages/frontend/package.json

Release 0.2.4

---

packages/backend/src/app/database/database.module.ts
packages/backend/src/main.ts

Run migeration outside since it times out, this is just temporary solution.

fix: run migeration outside since it timesout

---

packages/pieces/src/lib/apps/index.ts
packages/pieces/src/lib/apps/todoist/actions/create-task-action.ts
packages/pieces/src/lib/apps/todoist/common/client.ts
packages/pieces/src/lib/apps/todoist/common/models.ts
packages/pieces/src/lib/apps/todoist/common/props.ts
packages/pieces/src/lib/apps/todoist/index.ts

- Todoist: create task action
Closes #434 
create a new task using Todoist

feat(todoist): create task action

---

docker-compose.yml
package.json
packages/backend/package.json
packages/frontend/package.json

chore: bump version to 2.5

---

docker-compose.yml
package.json
packages/backend/package.json
packages/frontend/package.json

chore: bump version to 0.2.6

---

docker-compose.yml
package.json
packages/backend/package.json
packages/frontend/package.json

Replaced localhost with 127.0.0.1, as it's no longer getting resolved.

chore: bump version to 0.2.7

---

docker-compose.yml
package.json
packages/backend/package.json
packages/backend/src/app/helper/engine-helper.ts
packages/frontend/package.json

After manually define the DNS, localhost is not longer working, replaced it with local ip.

Release 0.2.7

---

packages/frontend/.eslintrc.json
packages/frontend/src/app/modules/common/service/authentication.service.ts
packages/frontend/src/app/modules/flow-builder/flow-builder.module.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/feedback/feedback.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/feedback/feedback.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/flow-builder-header.component.html
packages/frontend/src/assets/scss/ng-material-override.scss

Adds a feedback button.
#441 
In the flow builder you will see a feedback button, once you click on it, fill in the feedback and submit, you will see an snackbar saying "Feedback submitted"

Issue 441 in app feedback

---

packages/backend/src/app/instance/instance.service.ts
packages/frontend/src/app/modules/common/validators/cronjob-validator.ts
packages/shared/src/lib/flows/triggers/trigger.ts

1- Prohibit the use of seconds in cron jobs as it can be abuse the system.
2- Execute side effects upon instance deletion.

fix: remove instance seconds & instance effects on delete

---

packages/pieces/src/lib/apps/blackbaud/actions/create-contacts.ts
packages/pieces/src/lib/apps/blackbaud/actions/list-contacts.ts
packages/pieces/src/lib/apps/calendly/common/index.ts
packages/pieces/src/lib/apps/calendly/trigger/invitee-canceled.trigger.ts
packages/pieces/src/lib/apps/calendly/trigger/invitee-created.trigger.ts
packages/pieces/src/lib/apps/drip/actions/add-subscriber-to-campaign.action.ts
packages/pieces/src/lib/apps/drip/actions/apply-tag-to-subscriber.action.ts
packages/pieces/src/lib/apps/drip/actions/upsert-subscriber.action.ts
packages/pieces/src/lib/apps/drip/common/index.ts
packages/pieces/src/lib/apps/drip/trigger/new-subscriber.trigger.ts
packages/pieces/src/lib/apps/drip/trigger/new-tag.trigger.ts
packages/pieces/src/lib/apps/github/common/index.ts
packages/pieces/src/lib/apps/github/trigger/new-star.ts
packages/pieces/src/lib/apps/google-calendar/common/helper.ts
packages/pieces/src/lib/apps/google-sheets/common/common.ts
packages/pieces/src/lib/apps/hubspot/common/client.ts
packages/pieces/src/lib/apps/pipedrive/actions/add-person.action/add-person.action.ts
packages/pieces/src/lib/apps/pipedrive/common/index.ts
packages/pieces/src/lib/apps/sendgrid/actions/send-email.ts
packages/pieces/src/lib/apps/slack/actions/send-direct-message-action.ts
packages/pieces/src/lib/apps/slack/actions/send-message-action.ts
packages/pieces/src/lib/apps/stripe/common/index.ts
packages/pieces/src/lib/apps/todoist/common/client.ts
packages/pieces/src/lib/apps/typeform/common/index.ts
packages/pieces/src/lib/apps/zoom/actions/create-meeting-registrant.ts
packages/pieces/src/lib/common/http/core/http-request.ts
packages/pieces/src/lib/common/http/core/http-response.ts

Make HTTP request optional instead of required.

chore: make http request body type optional

---

packages/frontend/src/app/modules/common/service/authentication.service.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/feedback/feedback.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/feedback/feedback.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-list/step-type-list.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-list/step-type-list.component.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-sidebar.component.ts

feat: added request piece button

---

.github/workflows/release-backend.yml
.github/workflows/release-frontend.yml

Update pipeline to publish a unified version for backend and frontend

ci: unified version for backend and frontend

---

docs/contributing/building-pieces/reference.mdx

Fixes a small typo in the building pieces reference docs 
No tests should be necessary - only touched docs

(typo) Fixes typo in building piece reference docs 

---

docs/building-flows/passing-data.mdx
docs/building-flows/triggers.mdx
docs/changelog.mdx
docs/contributing/building-pieces/reference.mdx
docs/install/docker.mdx
docs/multi-tenancy/overview.mdx
docs/pieces/apps/blackbaud.mdx

Fixes some minor typos in the documentation.

chore: corrected typos in the docs

---

packages/pieces/src/lib/apps/binance/actions/fetch-pair-price.ts
packages/pieces/src/lib/apps/binance/index.ts
packages/pieces/src/lib/apps/index.ts

Adds a very basic Binance connector.

Binance Connector

---

packages/pieces/framework/src/lib/apps/http/actions/send-http-request-action.ts
packages/pieces/framework/src/lib/common/http/core/http-method.ts

1- Rearranged the HTTP methods.
2- Removed CONNECT due that it's crash the engine without an error.
3- Body is Optional

fix: Connect in HTTP Request

---

packages/backend/src/app/app-connection/app-connection.service.ts

chore: fix oauth2 refresh expired method

---

package-lock.json
package.json
packages/backend/src/app/authentication/authentication.controller.ts
packages/backend/src/app/authentication/authentication.service.ts
packages/backend/src/app/flags/flag.service.ts
packages/frontend/src/app/app.component.html
packages/frontend/src/app/app.component.ts
packages/frontend/src/app/app.module.ts
packages/frontend/src/app/modules/common/components/ap-button/ap-button.component.scss
packages/frontend/src/app/modules/common/components/ap-button/ap-button.component.ts
packages/frontend/src/app/modules/common/service/authentication.service.ts
packages/shared/src/index.ts
packages/shared/src/lib/flag/flag.ts

Show upgrade notification when a new version gets rolled out, this is depending on the package.json within the repo on the main branch.
Adresses #504

Issue 504 upgrade notification

---

packages/engine/src/lib/action/loop-action-handler.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/executors/code-executer.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/engine/src/lib/executors/piece-executor.ts
packages/engine/src/lib/globals.ts
packages/engine/src/lib/helper/trigger-helper.ts
packages/engine/src/lib/services/storage.service.ts
packages/engine/src/lib/services/variable-service.ts
packages/engine/src/main.ts
packages/pieces/framework/src/index.ts
packages/pieces/framework/src/lib/framework/context.ts

To prevent conflicts between triggers store entries saved in a collection, I made the default flow scope with an optional value to be collection scope. If a trigger is not found in the flow scope, it falls back to the collection to avoid breaking changes.

chore: default scope for store is flow

---

docker-compose.yml
docs/changelog.mdx
package.json
packages/pieces/framework/src/lib/docs-generator/index.ts

- #510 
- #511 
- #512 
- #514 
- #545 
- #534 
- #548 
- #549 
- #533 
- #528 
- #554 
- #539 
- #553 
- #559 
- #555 
- #562 
- #569 
- #561 
- #568 
- #574 
- #576 
- #547 
- #582 
- #570 
- #578 
- #573

chore: release `v0.3.1`

---

packages/pieces/apps/src/lib/google-calendar/triggers/calendar-event.ts

Update sample data for google calendar piece
https://github.com/activepieces/activepieces/issues/606
- Connect google calendar trigger
- Run test flow

fix: add more sample data for google calendar

---

docs/contributing/building-pieces/create-action.mdx
docs/contributing/building-pieces/create-trigger.mdx
docs/contributing/building-pieces/overview.mdx
docs/contributing/building-pieces/reference.mdx
docs/contributing/development-setup/codespaces.mdx
docs/mint.json

Documentations for different triggers & Fix Tutorial

docs: how to create triggers

---

packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/pieces/pieces.controller.ts
packages/engine/src/lib/helper/piece-helper.ts
packages/engine/src/main.ts
packages/pieces/framework/src/lib/framework/property/dynamic-prop.ts
packages/pieces/framework/src/lib/framework/property/index.ts
packages/pieces/framework/src/lib/framework/property/oauth2-prop.ts
packages/pieces/framework/src/lib/framework/property/property.ts
packages/shared/src/lib/engine/engine-operation.ts
packages/shared/src/lib/pieces/model/property-type.ts

feat: dynamic props

---

docker-compose.yml
package.json
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/triggers/trigger.ts

- Fix Trigger Saving Form
- Remove duplicate cal.com trigger

Release 0.3.3

---

packages/backend/src/app/pieces/piece-metadata-loader.ts
packages/pieces/apps/src/docs-generator/index.ts
packages/pieces/framework/src/lib/framework/piece.ts
packages/shared/src/lib/pieces/model/piece-metadata.ts

fix: display actions / triggers

---

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.ts
packages/frontend/src/app/modules/common/components/configs-form/connector-action-or-config.ts
packages/pieces/framework/src/lib/framework/property/base-prop.ts

feat: added default value for props

---

packages/ee/usage/frontend/runs-left-snackbar/runs-left-snackbar.component.html
packages/ee/usage/frontend/runs-left-snackbar/runs-left-snackbar.component.scss
packages/ee/usage/frontend/runs-left-snackbar/runs-left-snackbar.component.ts
packages/frontend/src/app/modules/common/components/ap-button/ap-button.component.scss

fixing ee layout of tasks left snackbar.

fix: fixed ee tasks snackbar layout

---

packages/pieces/apps/src/lib/clickup/actions/comments/create-task-comment.ts
packages/pieces/apps/src/lib/clickup/actions/tasks/create-subtask.ts
packages/pieces/apps/src/lib/clickup/index.ts

- Adds action: Create Subtask
- Adds action: Post Task Comment
Fixes #644 
**Create Subtask**
1. Create a new flow
2. Set ClickUp as action, choose 'Create Subtask' as the action
3. Select a workspace
4. Select a space
5. Select a list
6. Enter in a parent task ID
7. Enter task name
8. Enter task description
9. Test flow
10. Ensure subtask appears in expected place in ClickUp
**Create Task Comment**
1. Create a new flow
2. Set ClickUp as action, choose 'Create Subtask' as the action
6. Enter in task ID
7. Enter comment
9. Test flow
10. Ensure comment appears in the expected place in ClickUp

Pieces: ClickUp Actions [#644]

---

packages/pieces/apps/src/lib/clickup/actions/comments/create-task-comment.ts
packages/pieces/apps/src/lib/clickup/actions/tasks/create-subtask.ts
packages/pieces/apps/src/lib/clickup/common/index.ts
packages/pieces/apps/src/lib/google-contacts/trigger/new-contact.ts
packages/pieces/apps/src/lib/google-sheets/triggers/new-row-added.ts
packages/pieces/apps/src/lib/posthog/actions/create-event.ts
packages/pieces/apps/src/lib/posthog/common/models.ts
packages/pieces/apps/src/lib/stripe/trigger/new-subscription.ts
packages/pieces/apps/src/lib/stripe/trigger/payment-failed.ts
packages/pieces/apps/src/lib/twilio/trigger/new-incoming-sms.ts
packages/pieces/apps/src/lib/typeform/trigger/new-submission.ts

chore(clickup): tasks id is now dropdown

---

packages/frontend/src/app/modules/common/components/form-controls/code-artifact-form-control/code-artifact-form-control.component.ts

Temporary fix for codemirror with typescript

fix: correct mode for typescript and removed linting there

---

packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/input-forms/piece-input-forms/basic-auth-connection-dialog/basic-auth-connection-dialog.component.html

Puts correct tooltips for basic auth dialog.

fix: take description from fields

---

packages/backend/src/app/authentication/token-verify-middleware.ts
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/app/webhooks/webhook-service.ts
packages/backend/src/main.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/edit-step-accodion.component.ts
packages/frontend/src/app/modules/flow-builder/service/action-meta.service.ts

Support both types of url.
Fixes #697

chore: support webhooks with path variables only

---

packages/pieces/apps/src/lib/rss/triggers/new-item-trigger.ts

fix: support atom feeds

---

.github/workflows/release-latest.yml
.github/workflows/release-nightly.yml

chore: release latest workflow only

---

packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-builder-header/publish-button/publish-button.component.ts
packages/frontend/src/app/modules/flow-builder/store/builder/builder.selector.ts

added a new publish button tooltip and force at least one flow to have a step

feat: added a new publish button tooltip and force at least one flow to have a step

---

packages/ee/billing/backend/billing.service.ts
packages/ee/billing/backend/usage.service.ts

chore(billing): update plans

---

packages/backend/src/app/helper/trigger-utils.ts
packages/backend/src/app/workers/flow-worker/flow-queue.ts

Remove completed jobs from redis.

chore: remove completed jobs

---

docs/pieces/apps/generatebanners.mdx
packages/pieces/apps/src/index.ts
packages/pieces/generatebanners/.eslintrc.json
packages/pieces/generatebanners/README.md
packages/pieces/generatebanners/actions/renderTemplate.action.ts
packages/pieces/generatebanners/index.ts
packages/pieces/generatebanners/package.json
packages/pieces/generatebanners/project.json
packages/pieces/generatebanners/src/index.ts
packages/pieces/generatebanners/tsconfig.json
packages/pieces/generatebanners/tsconfig.lib.json
tsconfig.base.json

Migrate GenerateBanners to Standalone package

Migrate GenerateBanners to Standalone package 

---

packages/backend/src/app/webhooks/webhook-controller.ts

Support all methods for webhooks.

chore: add all methods to webhooks

---

packages/backend/src/app/helper/system/system.ts

chore: remove env from the logs

---

packages/pieces/apps/src/index.ts
packages/pieces/youtube/.eslintrc.json
packages/pieces/youtube/README.md
packages/pieces/youtube/package.json
packages/pieces/youtube/project.json
packages/pieces/youtube/src/index.ts
packages/pieces/youtube/src/lib/common/props.ts
packages/pieces/youtube/src/lib/triggers/new-video.trigger.ts
packages/pieces/youtube/tsconfig.json
packages/pieces/youtube/tsconfig.lib.json
tsconfig.base.json

Add a new trigger that is fired when a new video is uploaded to a YouTube channel.
Used the YouTube XML feed to poll for new entries.
Closes #522

feat: add youtube piece

---

docs/install/docker.mdx
tools/update.sh

1. Adds an update script into the tools folder which will enable users to quickly update their Activepieces instance.
2. Update the documentation to include the script
3. Update the documentation to link to the correct breaking changes URL
Install an older version of Activepieces on the machine, then run the tools/update.sh script and it should update the Activepieces instance.

Feat: Update Script

---

packages/frontend/src/app/modules/common/model/flow-builder/flow-item.ts
packages/frontend/src/app/modules/flow-builder/service/flowFactoryUtil.ts
packages/frontend/src/app/modules/flow-builder/service/flowStructureUtil.ts
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/flow-helper.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/shared/src/lib/flows/triggers/trigger.ts

chore: clean action/trigger schema

---

packages/backend/src/app/app-connection/app-connection.controller.ts
packages/backend/src/app/app-connection/app-connection.service.ts
packages/backend/src/app/instance/instance-side-effects.ts

chore: decrypt connection on upsert

---

packages/backend/src/app/app-event-routing/app-event-routing.service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/webhooks/webhook-service.ts
packages/engine/src/lib/helper/trigger-helper.ts
packages/pieces/apps/src/index.ts
packages/pieces/framework/src/lib/framework/piece.ts
packages/pieces/square/.eslintrc.json
packages/pieces/square/README.md
packages/pieces/square/package.json
packages/pieces/square/project.json
packages/pieces/square/src/index.ts
packages/pieces/square/src/lib/common/props.ts
packages/pieces/square/src/lib/triggers/index.ts
packages/pieces/square/tsconfig.json
packages/pieces/square/tsconfig.lib.json
packages/shared/src/lib/engine/engine-operation.ts
tsconfig.base.json

Triggers:
New Customer
Customer Updated
New Payment
New Order
Order Updated
New Booking
New Invoice

feat: square triggers

---

docs/install/easypanel.md
docs/install/overview.mdx

Added EasyPanel as deployment method to documentation

Add Easypanel as a deployment method

---

packages/pieces/gmail/src/index.ts
packages/pieces/gmail/src/lib/actions/get-thread-action.ts
packages/pieces/gmail/src/lib/common/props.ts

chore: change gmail oauth2 scope

---

.devcontainer/codespaces.sh

Replace webhook url in codespaces with codespace url

chore: replace webhook url with github codespaces url

---

packages/backend/src/app/helper/trigger-utils.ts
packages/shared/src/lib/common/activepieces-error.ts

This will cause a noise, and some false alerting, for example someone revoked oauth2 or entered wrong settings.
But my suggestion let's take look what's there and then filter the wrong ones.

chore: capture errors from the trigger

---

packages/ee/product-embed/product-sdk/src/app/app.component.scss

fix: product embed css fix

---

.github/workflows/build-everything.yml
.github/workflows/validate-publishable-packages.yml
tools/scripts/utils/package-pre-publish-checks.ts
tools/scripts/utils/publish-nx-project.ts
tools/scripts/validate-publishable-packages.ts

This pipeline fails if any publishable package is updated but the package version is not incremented

ci: validate publishable packages pipeline

---

.github/workflows/validate-publishable-packages.yml
packages/backend/src/app/pieces/piece-metadata-loader.ts
packages/frontend/src/app/modules/common/service/flag.service.ts
packages/frontend/src/app/modules/flow-builder/service/action-meta.service.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/framework/piece.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/common/index.ts
packages/shared/src/lib/common/utils/semVer.ts
packages/shared/src/lib/pieces/dto/get-piece-request-query.ts
packages/shared/src/lib/pieces/model/piece-metadata.ts
tools/scripts/update-pieces-metadata/generate-metadata.ts
tools/scripts/update-pieces-metadata/upload-metadata.ts
tools/scripts/update-pieces-metadata/validate-metadata.ts
tools/scripts/utils/package-pre-publish-checks.ts

minimum and maximum supported releases for pieces
Fixes #844

feat: piece supported releases #844

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/webhooks/webhook-service.ts

If the flow is not published but the instance is published, It will not return FLOW NOT FOUND

fix: null flow version id

---

packages/pieces/schedule/package.json
packages/pieces/schedule/project.json

chore: bump schedule piece to 0.0.2

---

packages/pieces/schedule/package.json

chore(schedule): override version 0.0.1

---

packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/code-worker/code-runner.ts
packages/backend/src/app/workers/sandbox.ts

chore: fix read sync

---

packages/backend/src/app/app-connection/app-connection.service.ts
packages/backend/src/app/collections/collection.service.ts
packages/backend/src/app/flow-run/flow-run-service.ts
packages/backend/src/app/flows/flow.service.ts
packages/backend/src/app/flows/trigger-events/trigger-event.service.ts
packages/backend/src/app/helper/pagination/build-paginator.ts
packages/backend/src/app/helper/pagination/pagination-utils.ts
packages/backend/src/app/helper/pagination/paginator.ts
packages/ee/product-embed/backend/app-credentials/app-credentials.service.ts
packages/ee/product-embed/backend/connection-keys/connection-key.service.ts

fix: pagination

---

packages/pieces/gmail/package.json
packages/pieces/gmail/src/lib/actions/search-email-action.ts
packages/pieces/gmail/src/lib/common/data.ts
packages/pieces/gmail/src/lib/triggers/new-email.ts

piece: limit google search email to one result

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/index.ts
packages/pieces/google-sheets/src/lib/actions/delete-row.action.ts
packages/pieces/google-sheets/src/lib/common/common.ts
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

- Adds a new action called 'delete-row' to google sheets which will delete a row from a spreadsheet
- Return a Row ID value from new row action
Fixes #920

Action: Added delete row action to Google Sheets

---

packages/frontend/src/app/modules/common/components/json-view/json-view-dialog/json-view-dialog.component.html
packages/frontend/src/app/modules/common/pipe/output-log.ts
packages/pieces/airtable/package.json
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/common/polling/index.ts
packages/pieces/gmail/package.json
packages/pieces/gmail/src/lib/common/data.ts
packages/pieces/gmail/src/lib/common/models.ts
packages/pieces/gmail/src/lib/triggers/new-email.ts
packages/pieces/rss/package.json
packages/pieces/salesforce/package.json

fix: polling library & parse gmail body

---

packages/pieces/smtp/package.json
packages/pieces/smtp/src/index.ts

chore: fix smtp typo

---

package-lock.json
package.json
packages/pieces/apps/src/index.ts
packages/pieces/mailer-lite/.eslintrc.json
packages/pieces/mailer-lite/README.md
packages/pieces/mailer-lite/package-lock.json
packages/pieces/mailer-lite/package.json
packages/pieces/mailer-lite/project.json
packages/pieces/mailer-lite/src/index.ts
packages/pieces/mailer-lite/src/lib/actions/create-or-update-subscription.ts
packages/pieces/mailer-lite/tsconfig.json
packages/pieces/mailer-lite/tsconfig.lib.json
tsconfig.base.json

Add MailerLite piece, with create or update subscription action.

Piece: MailerLite

---

.github/workflows/build-everything.yml

chore: improve build everything

---

packages/pieces/sendgrid/package.json
packages/pieces/sendgrid/src/index.ts
packages/pieces/sendgrid/src/lib/actions/send-dynamic-template.ts
packages/pieces/sendgrid/src/lib/actions/send-email.ts

chore: update sendgrid piece

---

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.ts
packages/pieces/sendgrid/package.json
packages/pieces/sendgrid/src/lib/actions/send-dynamic-template.ts

fix: sendgrid dynamic template & json formater

---

packages/pieces/airtable/package.json
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/common/polling/index.ts
packages/pieces/gmail/package.json
packages/pieces/rss/package.json
packages/pieces/salesforce/package.json
packages/pieces/zendesk/package.json
packages/pieces/zoho-crm/package.json

fix: polling library timebased

---

packages/pieces/apps/src/index.ts
packages/pieces/google-forms/.eslintrc.json
packages/pieces/google-forms/README.md
packages/pieces/google-forms/package.json
packages/pieces/google-forms/project.json
packages/pieces/google-forms/src/index.ts
packages/pieces/google-forms/src/lib/common/common.ts
packages/pieces/google-forms/src/lib/triggers/new-form-response.ts
packages/pieces/google-forms/tsconfig.json
packages/pieces/google-forms/tsconfig.lib.json
tsconfig.base.json

feat: google forms

---

package-lock.json
package.json
packages/backend/src/app/app-event-routing/app-event-routing.service.ts
packages/backend/src/app/flows/step-run/step-run-controller.ts
packages/backend/src/app/flows/step-run/step-run-dto.ts
packages/backend/src/app/flows/step-run/step-run-module.ts
packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/main.ts
packages/ee/billing/shared/plan.ts
packages/ee/billing/shared/usage.ts
packages/ee/product-embed/shared/app-credentials/app-credentials.ts
packages/ee/product-embed/shared/connection-keys/connection-key.ts
packages/ee/tsconfig.json
packages/engine/src/lib/executors/piece-executor.ts
packages/engine/src/lib/helper/piece-helper.ts
packages/engine/src/lib/helper/trigger-helper.ts
packages/engine/src/main.ts
packages/shared/src/index.ts
packages/shared/src/lib/common/index.ts
packages/shared/src/lib/engine/engine-operation.ts
packages/shared/src/lib/flows/index.ts
packages/shared/src/lib/flows/step-run/dto/test-step-request.ts
packages/shared/src/lib/flows/step-run/index.ts
tsconfig.base.json

This PR creates a test step endpoint.
the test endpoint just tests a single action in isolation
next pr will introduce flow context to test step 
relates to #828

feat: test action

---

packages/backend/src/app/webhooks/webhook-controller.ts

Some services expect a fast response such as github, waiting for handler to complete will cause fail delivery status on 3p services.

fix(webhooks): dont wait for handler to complete

---

packages/backend/src/main.ts

chore: edit the message on the start

---

packages/backend/src/app/flows/flow.module.ts
packages/backend/src/app/flows/flow/flow.module.ts
packages/backend/src/app/flows/step-run/step-run-controller.ts
packages/backend/src/app/flows/step-run/step-run-dto.ts
packages/backend/src/app/flows/step-run/step-run-module.ts
packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/main.ts
packages/engine/src/lib/helper/piece-helper.ts
packages/shared/package.json
packages/shared/src/lib/common/activepieces-error.ts
packages/shared/src/lib/engine/engine-operation.ts
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/sample-data.ts
packages/shared/src/lib/flows/step-run/dto/test-step-request.ts
packages/shared/src/lib/flows/triggers/trigger.ts

feat: test step #828

---

packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/input-forms/piece-input-forms/piece-trigger-input-form/piece-trigger-input-form.component.html

chore: fix stepname in trigger props

---

.github/workflows/release-beta.yml
packages/frontend/src/app/modules/flow-builder/components/test-flow-modal/test-flow-modal.component.ts

fix: send sample data with piece trigger

---

packages/ui/common/src/lib/pipe/output-log.pipe.ts

fix: escape html tags

---

.github/workflows/release-pieces.yml
packages/backend/src/app/pieces/piece-metadata-loader.ts
tools/scripts/update-pieces-metadata/generate-metadata.ts
tools/scripts/utils/get-available-piece-names.ts

Add `common` package to some missing places

chore: incorporate common package into flow

---

.github/workflows/release-beta.yml
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/edit-step-accodion.component.ts

Prevent some triggers to be edited.

fix: input ui info

---

packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1681107443963-AddInputUiInfo.ts
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/edit-step-accodion.component.html
packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/edit-step-accodion.component.ts

chore: migrate old pieces

---

packages/shared/src/lib/flows/sample-data.ts

fix: currentSelectData should be optional

---

docs/contributing/building-pieces/create-polling-trigger.mdx
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts
packages/pieces/zendesk/package.json
packages/pieces/zendesk/src/lib/trigger/new-ticket-in-view.ts

fix: change poll to test

---

packages/backend/src/app/workers/sandbox.ts

Bind `/workspace` directory to fix `pnpm link` for dev container

chore: fix `pnpm link` for dev container

---

packages/pieces/xml/package.json
packages/pieces/xml/src/lib/actions/convert-json-to-xml.ts

XML Piece: add xml attributes support and header checkbox property

---

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/input-forms/piece-input-forms/piece-trigger-input-form/piece-trigger-input-form.component.html

fix: auto complete on trigger fields shouldn't show

---

packages/pieces/google-calendar/package.json
packages/pieces/google-calendar/src/lib/actions/create-quick-event.ts
packages/pieces/google-calendar/src/lib/common/helper.ts
packages/pieces/google-calendar/src/lib/common/index.ts
packages/pieces/google-calendar/src/lib/triggers/calendar-event.ts
packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html

fix(google-calendar): typo & calendar list

---

packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/branch-condition-form-control/branch-condition-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/input-forms/loop-step-input-form/loop-step-input-form.component.html
packages/ui/feature-builder-test-steps/src/lib/test-code-step/test-code-step.component.ts
packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.html
packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.ts

Re-enables closing autocomplete dropdown on pressing "Esc" and shows empty output for undefined/null after running steps.

Hotfix 17 4 2023

---

packages/backend/src/app/app-event-routing/app-event-routing.module.ts
packages/backend/src/app/helper/engine-helper.ts
packages/engine/src/lib/helper/trigger-helper.ts
packages/engine/src/main.ts
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts

Huge overhead are coming from preparing sandbox, while this is not needed.

fix: remove sandbox for extract events

---

packages/ui/core/src/app/app.component.html
packages/ui/core/src/app/app.module.ts
packages/ui/feature-authentication/src/index.ts
packages/ui/feature-builder-right-sidebar/src/lib/ui-feature-builder-right-sidebar.module.ts

Upgrade notification buttons aren't working because UiCommonModule, this PR imports it.

fix: imported uiCommonModule

---

packages/backend/src/app/database/migration/1680986182074-RemoveCollections.ts

- Create Folder Table
- Migrate Collection to Folder
- Migrate Instance to Folder Instance
- Change Store Scope Collection Id -> Project ID

chore: migrate collections to folders

---

packages/backend/src/app/flows/flow-instance/flow-instance.service.ts
packages/backend/src/app/flows/flow/flow.service.ts

fix: query flows by null

---

docs/changelog.mdx
packages/pieces/notion/package.json
packages/pieces/notion/src/lib/triggers/new-database-item.ts

fix: notion trigger metadata

---

packages/backend/src/app/flows/step-run/step-run-service.ts

Webhook sample data wasn't being resolved when testing steps that use its sample data.

fix: added webhook trigger type to steps whom sample data we resolve

---

packages/ee/product-embed/backend/connection-keys/connection-key.module.ts

chore: delete connection key

---

packages/backend/src/app/store-entry/store-entry.controller.ts
packages/backend/src/app/store-entry/store-entry.service.ts
packages/engine/src/lib/services/storage.service.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts
packages/pieces/store/package.json
packages/pieces/store/src/index.ts
packages/pieces/store/src/lib/actions/store-add-to-list.ts
packages/pieces/store/src/lib/actions/store-get-action.ts
packages/pieces/store/src/lib/actions/store-remove-from-list.ts
packages/pieces/store/src/lib/actions/store-remove-value.ts
packages/shared/package.json
packages/shared/src/lib/store-entry/dto/store-entry-request.ts

feat: add / remove item from list

---

packages/pieces/store/package.json
packages/pieces/store/src/index.ts

chore(store): remove minimum verison

---

docs/pieces/apps/slack.mdx
docs/pieces/apps/store.mdx
packages/pieces/slack/package.json
packages/pieces/slack/src/index.ts

feat: add slack triggers back

---

.github/workflows/release-beta.yml
docker-compose.yml
docs/changelog.mdx
package.json

chore: release 0.3.11

---

packages/pieces/freshsales/package.json
packages/pieces/freshsales/src/lib/actions/create-contact.ts

Fixes # (issue) https://github.com/activepieces/activepieces/issues/1124

chore(freshsales): make first name optional

---

README.md
docs/pieces/custom-pieces.mdx

Fixed url that leads to building pieces.

fix: fixed urls in docs

---

packages/backend/src/app/flows/folder/folder.service.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/new-folder-dialog/new-folder-dialog.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/new-folder-dialog/new-folder-dialog.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/rename-folder-dialog/rename-folder-dialog.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/rename-folder-dialog/rename-folder-dialog.component.ts
packages/ui/feature-dashboard/src/lib/services/folders.service.ts
packages/ui/feature-dashboard/src/lib/validators/folderName.validator.ts

Added validation when renaming/creating folder for its name.

chore: added folder name validation frontend and backend wise

---

packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.html
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/code-step-mention-item/code-step-mention-item.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/custom-path-mention-dialog/custom-path-mention-dialog.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/mentions-list.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/input-forms/loop-step-input-form/loop-step-input-form.component.html

1)Remove connections from autocomplete dropdown.
2)Fixes #1115.
3)Fixes #1003.
closes  #1115
closes #1003

fix: remove select button for autocomplete when stpe isn't tested 

---

packages/backend/src/app/webhooks/webhook-service.ts

fix: webhook simulation trigger

---

packages/backend/src/app/flows/flow/flow.service.ts
packages/ui/core/src/app/app.component.html
packages/ui/core/src/app/app.component.ts
packages/ui/core/src/assets/scss/ng-material-override.scss
packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.html
packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts
packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html

Each commit message describes its job.

fix: frontend hot fixes

---

packages/ui/common/src/lib/components/horizontal-sidebar-separator/horizontal-sidebar-separator.component.ts
packages/ui/core/src/app/app.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts

fix: reset sizes for right sidebar sections on window resize

---

.github/workflows/e2e-tests.yml
.github/workflows/ping.yml

chore: add playwright test runner

---

packages/backend/src/app/workers/sandbox.ts

some library depend on that variables to be set such as aws s3.

fix: add home path for sandbox

---

packages/tests-e2e/tests/send-slack-message.spec.ts

fix: update playwright test for folders

---

packages/ui/feature-builder-store/src/lib/service/code.service.ts

fix: add npm package by name

---

packages/ui/common/src/lib/components/horizontal-sidebar-separator/horizontal-sidebar-separator.component.ts
packages/ui/core/src/assets/scss/horizontal-sidebar-separator.scss
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.html
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts

chore: reset height to intial state on window resize

---

packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html

Closes #1190 
I know this is duplicated code, but now that things are clear, I will extract the duplicated code in the future and make just one single component.

fix: selecting primitive sample data for piece steps

---

.github/workflows/release.yml
packages/backend/src/app/workers/sandbox.ts
packages/engine/src/main.ts
packages/ui/feature-builder-store/src/lib/service/code.service.ts

fix: unsandboxed error shouldn't be a real error

---

.github/workflows/release.yml
packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts

This code act as prevention for bugs impact in stale jobs.

fix: delete stale job

---

packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1683040965874-allow-nullable-store-entry.ts
packages/backend/src/app/flows/trigger-events/trigger-event.entity.ts
packages/backend/src/app/flows/trigger-events/trigger-event.service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/store-entry/store-entry-entity.ts
packages/backend/src/app/store-entry/store-entry.service.ts
packages/backend/src/app/webhooks/webhook-service.ts
packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.ts

fix: remove null constraints in store entry / trigger events & fix store entry project id null error

---

docker-compose.yml
docs/_snippets/apps.mdx
docs/changelog.mdx
docs/mint.json
package.json

Release 0.3.13

---

.github/workflows/e2e-tests.yml
packages/tests-e2e/tests/send-slack-message.spec.ts

chore: add playwright test

---

packages/backend/src/app/flags/flag.service.ts
packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
packages/shared/package.json
packages/shared/src/lib/flag/flag.ts
packages/ui/common/src/lib/service/flag.service.ts
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
packages/ui/feature-builder-header/src/lib/test-flow-modal/test-flow-modal.component.ts
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.html
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.scss
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.ts
packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html
packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.ts

1- Added Snackbar for Internal & Timeout Errors

fix: show snackbar on timeout & internal error

---

.github/workflows/release-beta.yml
packages/engine/src/lib/action/branch-action-handler.ts

(or result) was being calculated after every condition within an (and group)

fix: (or result) was being calculated after every condition within an (and group)

---

packages/pieces/todoist/package.json
packages/pieces/todoist/src/lib/actions/create-task-action.ts
packages/pieces/todoist/src/lib/common/client/rest-client.ts
packages/pieces/todoist/src/lib/common/models.ts

I added some of the optional fields (description, array of labels, priority and due_date) when creating a task for Todoist.

[Todoist] Added optional inputs for fields

---

packages/pieces/gotify/.eslintrc.json
packages/pieces/gotify/README.md
packages/pieces/gotify/package.json
packages/pieces/gotify/project.json
packages/pieces/gotify/src/index.ts
packages/pieces/gotify/src/lib/actions/send-notification.ts
packages/pieces/gotify/tsconfig.json
packages/pieces/gotify/tsconfig.lib.json
tsconfig.base.json

This PR adds a new piece, Gotify. The piece has a single action, send notification, which allows users to easily send notifications using their Gotify instance. An app token is required.
Auth uses an app token which the user can generate from their web panel, or using Rest API.
Configurable parameters are:
- title (required)
- message (required)
- priority (optional, a number from 0 to 10)
Can be found at https://github.com/gotify/logo

[PIECE] Gotify

---

packages/ui/core/src/assets/scss/utlis.scss
packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.scss
packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/steps-list-in-flows-table/steps-list-in-flows-table.component.ts

closes #1183 
Testing: 
Added many folders and made sure that the list is overflowing, then added a new folder and it was scrolled into view.

fix: scroll to latest folder

---

docs/install/overview.mdx
docs/mint.json

docs: remove digitalocean temprary

---

packages/pieces/gmail/package.json
packages/pieces/gmail/src/lib/actions/send-email-action.ts

feat: allow multiple to in gmail

---

.github/workflows/build-cloud-nx.yml
docs/building-flows/passing-data.mdx
docs/pieces/apps/data-mapper.mdx
packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1683898241599-ChangeVariableSyntax.ts
packages/engine/src/lib/services/variable-service.ts
packages/engine/test/services/variable-service.test.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/custom-path-mention-dialog/custom-path-mention-dialog.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/loop-step-mention-item/loop-step-mention-item.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/step-mentions-tree/step-mentions-tree.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/utils.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts

- Migrate everything from ${} to {{}} format
- Allow JS Execution inside {{}}
Fixes #1018

feat: inline functions

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/index.ts
packages/pieces/google-sheets/src/lib/actions/update-row.ts
packages/pieces/google-sheets/src/lib/common/common.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html

feat: add update row google sheets

---

packages/ee/guess-flow/src/lib/guess-flow.component.ts
packages/ee/guess-flow/src/lib/services/prompts.service.ts

Sends user email instead of id to feedback sheets.

fix: started sending user email instead of id

---

packages/ee/magic-wand/openai.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/utils.ts

Adapted to new interpolation style {{}}.

fix: adapted to new interpolation style {{}}

---

packages/backend/src/app/app-connection/app-connection.service.ts
packages/engine/src/lib/services/storage.service.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts
packages/pieces/store/package.json
packages/pieces/store/src/lib/actions/store-add-to-list.ts
packages/pieces/store/src/lib/actions/store-get-action.ts
packages/pieces/store/src/lib/actions/store-put-action.ts
packages/pieces/store/src/lib/actions/store-remove-from-list.ts

fix: delete item from store

---

packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts
packages/pieces/store/package.json

fix: store piece scope name

---

docker-compose.dev.yml
docs/contributing/development-setup/docker-compose.mdx
docs/contributing/development-setup/local-development.mdx
packages/backend/src/app/workers/sandbox.ts

This PR is intended to resolve the issues discussed in the pull request and its associated comments (https://github.com/activepieces/activepieces/pull/797)
1- The ownership of the node_modules files is no longer assigned to the root user.
2- The npm ci command is now being executed inside the development container designed for arm-based systems.
3- The isolate arm feature is no longer utilized due to its requirement for root privileges.
Testing:
To ensure the efficacy of these changes, I deleted the node_modules directory and ran the activepieces program. Subsequently, I tested a flow webhook and code piece.

fix: docker compose dev for arm machine

---

packages/backend/src/app/app-connection/app-connection.service.ts

fix: refreshing tokens

---

packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/lib/actions/create-post.action.ts
packages/pieces/wordpress/src/lib/common/index.ts

fix: list all categories & tags

---

packages/backend/.eslintrc.json
packages/backend/src/app/app-connection/app-connection.service.ts
packages/backend/src/app/database/migration/1674788714498-FlowAndFileProjectId.ts
packages/backend/src/app/database/migration/1678492809093-removeCollectionVersion.ts
packages/backend/src/app/database/migration/1680986182074-RemoveCollections.ts
packages/backend/src/app/flows/flow-instance/flow-instance.service.ts
packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/flows/flow/flow.service.ts
packages/backend/src/app/helper/error-handler.ts
packages/backend/src/app/helper/notifications.ts
packages/backend/src/app/helper/pagination/paginator.ts
packages/backend/src/app/helper/secret-helper.ts
packages/backend/src/app/pieces/pieces.controller.ts
packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/backend/src/app/workers/sandbox.ts
packages/backend/src/main.ts

1- Enabled Check on missing cases in switch
2- Enable Strict mode
3- Fix Validate Props (Props has to be not null and not undefined but unknown)

chore: enable strict mode & switch check lint rule

---

package-lock.json
packages/pieces/apps/src/index.ts
packages/pieces/mautic/.eslintrc.json
packages/pieces/mautic/README.md
packages/pieces/mautic/package-lock.json
packages/pieces/mautic/package.json
packages/pieces/mautic/project.json
packages/pieces/mautic/src/index.ts
packages/pieces/mautic/src/lib/actions/create-contact.ts
packages/pieces/mautic/src/lib/common/index.ts
packages/pieces/mautic/tsconfig.json
packages/pieces/mautic/tsconfig.lib.json
tsconfig.base.json

PIECE: Mautic

---

package-lock.json
package.json
packages/backend/src/app/workers/sandbox.ts
packages/pieces/apps/src/index.ts
packages/pieces/twitter/.eslintrc.json
packages/pieces/twitter/README.md
packages/pieces/twitter/package.json
packages/pieces/twitter/project.json
packages/pieces/twitter/src/index.ts
packages/pieces/twitter/src/lib/actions/create-tweet.ts
packages/pieces/twitter/tsconfig.json
packages/pieces/twitter/tsconfig.lib.json
tsconfig.base.json

feat(twitter): add create tweet

---

packages/backend/src/app/flags/flag.service.ts
packages/pieces/gmail/package.json
packages/pieces/gmail/src/lib/actions/send-email-action.ts

feat: add reply to gmail

---

packages/pieces/mautic/README.md
packages/pieces/mautic/package.json
packages/pieces/mautic/src/index.ts
packages/pieces/mautic/src/lib/actions/create-company.ts
packages/pieces/mautic/src/lib/actions/create-contact.ts
packages/pieces/mautic/src/lib/actions/index.ts
packages/pieces/mautic/src/lib/actions/search-company.ts
packages/pieces/mautic/src/lib/actions/search-contact.ts
packages/pieces/mautic/src/lib/actions/update-company.ts
packages/pieces/mautic/src/lib/actions/update-contact.ts
packages/pieces/mautic/src/lib/common/helper.ts
packages/pieces/mautic/src/lib/common/index.ts

**Piece: Mautic**
- Contact Creation
- Contact Search
- Contact Update
- Company Creation
- Company Search
- Company Update
`Functionality: Ensured that the user can create, update and search by all the possible fields. Just the user need to ensure that the query should be good enough just to get single data in search or else appropriate error will be thrown`

Mautic: Support for Contact:creation, updation and search and Company:creation, updation and search using all the available fields

---

docs/pieces/apps/wordpress.mdx
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts
packages/pieces/wordpress/src/lib/actions/create-page.action.ts

feat: add wordpress create page

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts

fix(openai): cast all number properties

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts

OpenAI keep responding with 429

feat(openai): add retry

---

packages/pieces/common/package.json
packages/pieces/common/src/lib/http/axios/axios-http-client.ts
packages/pieces/common/src/lib/http/core/http-error.ts
packages/pieces/common/src/lib/http/core/http-request.ts
packages/pieces/http/package.json
packages/pieces/http/src/index.ts
packages/pieces/http/src/lib/actions/send-http-request-action.ts

Fixes https://github.com/activepieces/activepieces/issues/931

feat: HTTP -> Enhancement : adding timeout feature and failsafe option

---

packages/pieces/openai/package.json
packages/pieces/openai/src/index.ts

People can't find chat gpt from search piece

feat(openai): add description for open ai

---

packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts

fix: remove beamer from builder

---

packages/pieces/common/package.json
packages/pieces/common/src/lib/polling/index.ts

chore: add last item id polling

---

packages/backend/src/app/flows/common/piece-installer.ts
packages/pieces/common/package.json
packages/pieces/common/src/lib/polling/index.ts
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

feat(google-sheets): add max poll number

---

packages/ui/feature-builder-header/src/lib/test-flow-modal/test-flow-modal.component.ts

Remove webhook sample data dialog on testing flow

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

fix(google-sheets): change polling frequency

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/ui/core/src/app/modules/import-flow/import-flow.component.ts

fix: template redirection

---

docs/pieces/apps/google-sheets.mdx
docs/pieces/apps/mautic.mdx
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/delete-row.action.ts
packages/pieces/google-sheets/src/lib/actions/insert-row.action.ts
packages/pieces/google-sheets/src/lib/actions/update-row.ts

docs: update docs & fix typo in google sheets

---

packages/ui/common/src/lib/store/project/project.effects.ts
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts

chore: check for projects before loading instances runs

---

packages/pieces/asana/package.json
packages/pieces/asana/src/lib/actions/create-task.ts
packages/pieces/asana/src/lib/common/index.ts

feat(asana): add assignee

---

packages/pieces/common/package.json
packages/pieces/common/src/lib/polling/index.ts
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

fix(google-sheets): max poll with existing data

---

packages/backend/src/app/pieces/pieces.controller.ts

fix: add null checker for trigger

---

packages/engine/src/lib/services/storage.service.ts

fix: encode storage key

---

packages/backend/src/app/pieces/pieces.controller.ts
packages/shared/package.json
packages/shared/src/lib/flows/flow-helper.ts

chore: remove unused functions

---

.github/workflows/build-cloud-nx.yml
package.json
packages/shared/jest.config.ts
packages/shared/project.json
packages/shared/test/flow/flow-helper.test.ts
packages/shared/tsconfig.spec.json

chore(flow-helper): add tests to flow helper

---

packages/pieces/salesforce/package.json
packages/pieces/salesforce/src/lib/action/create-new-object.ts
packages/pieces/salesforce/src/lib/action/update-object-by-id.ts

chore(salesforce): change version to 0.56

---

packages/engine/src/lib/action/code-action-handler.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/engine/src/lib/globals.ts
packages/shared/package.json
packages/shared/src/lib/flow-run/execution/execution-state.ts

Update task count logic to account for pauses

Fix task count

---

packages/pieces/discord/package.json

chore: bump discord version

---

packages/backend/src/app/file/file.service.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/action/branch-action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts
packages/shared/package.json
packages/shared/src/lib/flow-run/execution/execution-output.ts
packages/shared/src/lib/flow-run/execution/step-output.ts
packages/shared/src/lib/flow-run/flow-run.ts

- use one log file for paused runs
- remove redundant execution state from pause metadata

fix: test flow

---

packages/backend/src/app/app-event-routing/app-event-routing.module.ts
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/app/webhooks/webhook-service.ts

fix(webhook): correct status

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts
packages/pieces/twitter/package.json
packages/pieces/twitter/src/lib/actions/create-tweet.ts

docs: update auth instructions for open ai & twitter

---

package-lock.json
package.json
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/main.ts

fix: multipart in webhook

---

packages/engine/src/lib/action/code-action-handler.ts
packages/engine/src/lib/action/piece-action-handler.ts

fix: input section

---

packages/ui/common/src/lib/service/flow.service.ts
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts

fix: duplicate flow

---

docker-compose.yml
docs/_snippets/apps.mdx
docs/changelog.mdx
docs/mint.json
docs/pieces/apps/blackbaud.mdx
docs/pieces/apps/clockodo.mdx
docs/pieces/apps/discord.mdx
docs/pieces/apps/google-calendar.mdx
docs/pieces/apps/salesforce.mdx
package-lock.json
package.json

feat: release 0.3.15

---

packages/pieces/salesforce/package.json
packages/pieces/salesforce/src/lib/action/upsert-by-external-id.ts

fix(salesforce): add validation in records array

---

packages/backend/src/app/flows/common/piece-installer.ts
packages/backend/src/app/helper/package-manager.ts

fix: local link failure for common,framework and shared

---

packages/pieces/store/package.json
packages/pieces/store/src/index.ts
packages/pieces/store/src/lib/actions/store-append-action.ts

PIECE: Implement a store append action

---

packages/backend/src/app/flows/common/piece-installer.ts
packages/backend/src/app/workers/sandbox.ts
packages/engine/src/lib/helper/action-helper.ts

fix: binding directory sandbox

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/index.ts
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

updated the description, display name and name for the google sheets readNewRows trigger

fix(google sheets): fixed trigger description and display name

---

packages/ui/core/src/app/modules/import-flow/import-flow.component.html
packages/ui/core/src/app/modules/not-found/not-found.component.html
packages/ui/feature-authentication/src/lib/auth.component.html

Adds alt and images instead of svg-icon for logos and fixes our 404 page.

feat: enhance SEO (Issue 33)

---

packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts

Fixes importing templates within builder.

fix: fixed importing templates within builder

---

packages/ui/common/src/lib/components/markdown/markdown.component.html
packages/ui/common/src/lib/components/markdown/markdown.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts

Added a note for people who want to get a response from a webhook triggered flow.

feat: added /sync note in webhook settings

---

packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts

fix: discord invite link

---

packages/pieces/delay/package.json

fix: bump delay version

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/lib/actions/create-tweet.ts

chore: bump twitter

---

packages/pieces/google-sheets/package.json

fix: bump google sheets

---

packages/pieces/certopus/.eslintrc.json
packages/pieces/certopus/README.md
packages/pieces/certopus/package.json
packages/pieces/certopus/project.json
packages/pieces/certopus/src/index.ts
packages/pieces/certopus/src/lib/actions/create-credential.ts
packages/pieces/certopus/src/lib/common/client.ts
packages/pieces/certopus/src/lib/common/index.ts
packages/pieces/certopus/src/lib/common/models/category.ts
packages/pieces/certopus/src/lib/common/models/event.ts
packages/pieces/certopus/src/lib/common/models/oranisation.ts
packages/pieces/certopus/src/lib/common/models/recipient-field.ts
packages/pieces/certopus/tsconfig.json
packages/pieces/certopus/tsconfig.lib.json
tsconfig.base.json

PIECE: Certopus

---

tools/setup-dev.js

feat: adding support for node js 20

---

packages/ui/core/src/assets/scss/ng-material-override.scss
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/custom-path-mention-dialog/custom-path-mention-dialog.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/step-mentions-tree/step-mentions-tree.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/utils.ts
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.html
packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.ts
packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.ts

fix: support bracket notation

---

packages/ui/common/src/index.ts
packages/ui/common/src/lib/directives/element-ref.directive.ts
packages/ui/common/src/lib/ui-common.module.ts
packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.html
packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.ts

chore: add search control to apps in templates dialog

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

fix: revert google sheets change

---

packages/backend/src/app/webhooks/webhook-service.ts

fix(webhook): payload for pieces should come from execute trigger

---

docs/contributing/building-pieces/create-action.mdx
docs/contributing/building-pieces/publish-piece.mdx
docs/contributing/development-setup/getting-started.mdx
docs/contributing/development-setup/local.mdx
docs/contributing/overview.mdx
docs/mint.json
docs/overview.mdx
package.json
tools/scripts/generate-new-piece.ts
tools/scripts/utils/files.ts
tools/scripts/utils/publish-piece.ts

docs: add docs for community pieces

---

docker-compose.yml
docs/changelog.mdx
package-lock.json
package.json
packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts

feat: release 0.3.16

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/upsert-contact.ts

Fix action upsert contact (delete required parametr) 

fix: update action upsert-contact for bloomerang

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/upsert-contact.ts

change parameters type into ShortText instead of Number 

fix: fix parameters type bloomerang

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/upsert-contact_search.ts

Fix action upsert contact by search endpoint

fix: fix action upsert contact by search endpoint

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/upsert-contact_duplicates.ts
packages/pieces/bloomerang/src/lib/actions/upsert-contact_search.ts

fix: fix const with id

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/get-contacts.ts

feat: extend action get contacts

---

packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/get-contacts.ts

fix: fix get contact action

---

docker-compose.yml
docs/changelog.mdx
package.json

Hot fix the connections not loading in the frontend.

feat: release 0.3.17

---

docker-entrypoint.sh
packages/backend/src/app/helper/engine-helper.ts

chore: enable source map

---

packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/sandbox.ts

fix: enable source maps

---

packages/pieces/cal-com/package.json
packages/pieces/cal-com/src/lib/triggers/register-webhook.ts

docs: update cal-com auth instructions

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/common/common.ts

fix: google sheets

---

packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/lib/actions/create-post.action.ts
packages/pieces/wordpress/src/lib/common/index.ts

fix: upload media in wordpress

---

packages/pieces/resend/.eslintrc.json
packages/pieces/resend/README.md
packages/pieces/resend/package.json
packages/pieces/resend/project.json
packages/pieces/resend/src/index.ts
packages/pieces/resend/src/lib/actions/send-email.ts
packages/pieces/resend/tsconfig.json
packages/pieces/resend/tsconfig.lib.json

feat: add resend piece

---

docs/telemetry.mdx
packages/shared/package.json
packages/shared/src/lib/common/telemetry.ts
packages/ui/common/src/lib/service/telemetry.service.ts
packages/ui/core/src/app/app.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.ts
packages/ui/feature-templates/src/lib/template-card/template-card.component.ts

chore: update telemetry events & docs

---

packages/pieces/typeform/package.json
packages/pieces/typeform/src/lib/trigger/new-submission.ts

fix: typeform failing to delete webhook

---

packages/pieces/cal-com/package.json
packages/pieces/cal-com/src/lib/triggers/register-webhook.ts

fix: cal.com webhook api changed

---

packages/backend/src/app/app-event-routing/app-event-routing.module.ts

fix: add facebook leads to app events

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/delete-row.action.ts
packages/pieces/google-sheets/src/lib/actions/find-rows.ts
packages/pieces/google-sheets/src/lib/actions/insert-row.action.ts
packages/pieces/google-sheets/src/lib/actions/update-row.ts
packages/pieces/google-sheets/src/lib/common/common.ts
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

feat(google-sheets): add support for team drives

---

packages/backend/src/app/flows/step-run/step-run-service.ts
packages/engine/src/lib/helper/action-helper.ts
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts

fix: test step inside loop

---

docker-compose.yml
docs/changelog.mdx
package.json

feat: release 0.4.0

---

packages/pieces/linkedin/package.json
packages/pieces/linkedin/src/lib/actions/create-company-update.ts
packages/pieces/linkedin/src/lib/common/index.ts

fix(linkedin): oauth2 scope and bump version

---

packages/pieces/salsa/package.json
packages/pieces/salsa/src/lib/actions/offline-donation-upsert.ts
packages/pieces/salsa/src/lib/actions/offline-donation.ts
packages/pieces/salsa/src/lib/actions/supporter-search.ts
packages/pieces/salsa/src/lib/actions/supporter-upsert.ts
packages/pieces/salsa/src/lib/actions/supporter.ts

Salsa has own sandbox with different API url, so I added specified field for that. Now we can change the api url just typing it.

fix(salsa): Change API url for Salsa

---

packages/pieces/facebook-leads/package.json
packages/pieces/facebook-leads/src/lib/common/index.ts

fix: facebook leads permission

---

packages/pieces/salsa/package.json
packages/pieces/salsa/src/lib/actions/offline-donation-upsert.ts
packages/pieces/salsa/src/lib/actions/offline-donation.ts
packages/pieces/salsa/src/lib/actions/supporter-upsert.ts

Change some properties for salsa donations

fix: Change properties for donations

---

.github/workflows/build-cloud-nx.yml

fix: disable backend test

---

packages/backend/src/app/helper/system/system.ts
packages/backend/test/integration/piece/piece-metadata.test.ts

fix: allow multi line variable in docker by replacing escaped new line

---

packages/engine/src/lib/helper/trigger-helper.ts
packages/pieces/schedule/package.json
packages/pieces/schedule/src/lib/common/index.ts
packages/pieces/schedule/src/lib/triggers/cron-expression.trigger.ts
packages/pieces/schedule/src/lib/triggers/every-day.trigger.ts
packages/pieces/schedule/src/lib/triggers/every-hour.trigger.ts
packages/pieces/schedule/src/lib/triggers/every-month.trigger.ts
packages/pieces/schedule/src/lib/triggers/every-week.trigger.ts

feat(schedule): support timezones

---

packages/backend/src/app/flows/common/piece-installer.ts
packages/backend/src/app/flows/trigger-events/trigger-event.service.ts
packages/pieces/slack/package.json
packages/pieces/slack/src/lib/triggers/new-message.ts
packages/pieces/slack/src/lib/triggers/new-reaction-added.ts
packages/pieces/square/package.json
packages/pieces/square/src/lib/triggers/index.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts

feat: enable test for app webhooks

---

packages/pieces/schedule/package.json
packages/pieces/schedule/src/lib/triggers/every-hour.trigger.ts

fix: remove timezone from every hour

---

tools/scripts/update-pieces-metadata/validate-metadata.ts

fix: validate piece metadata script

---

packages/pieces/facebook-leads/package.json
packages/pieces/facebook-leads/src/lib/common/index.ts
packages/pieces/facebook-leads/src/lib/triggers/new-lead.ts

Fixes loading sample data for facebook leads

fix: added test function

---

packages/ui/common/src/lib/environments/environment.ts
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item.component.html
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item.component.ts

Closes #928 
Basically a delay is now added before firing the mousedown event which delays the dragging experience being triggered.

fix: distinguishing between step being clicked and dragged.

---

packages/pieces/common/package.json
packages/pieces/common/src/lib/polling/index.ts
packages/pieces/google-contacts/package.json
packages/pieces/google-contacts/src/index.ts
packages/pieces/google-contacts/src/lib/trigger/new-contact.ts

fix(google-contacts): fixed not loading from account bug

---

packages/backend/src/app/flows/flow/flow.controller.ts
packages/shared/package.json
packages/shared/src/lib/flows/dto/flow-template-request.ts
packages/ui/common/src/lib/service/templates.service.ts
packages/ui/core/src/app/modules/import-flow/import-flow.component.ts
packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html

1)Fixed pinnedOrder nullable being parsed into 0 by implicit coercion.
2)Fixed bug for checking out of index array.
3)Removed Search from disabled dropdowns and multiselect dropdowns.

fix: Removed Search from disabled dropdowns and multiselect dropdowns

---

packages/engine/src/lib/services/storage.service.ts
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
packages/ui/feature-builder-store/src/lib/utils/flowStructureUtil.ts

chore: clean up

---

packages/engine/src/lib/action/branch-action-handler.ts
packages/shared/package.json
packages/shared/src/lib/flows/actions/action.ts
packages/shared/test/flow/flow-helper.test.ts
packages/ui/feature-builder-form-controls/src/lib/branch-condition-form-control/branch-condition-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/branch-condition-form-control/branch-condition-form-control.component.ts
packages/ui/feature-builder-form-controls/src/lib/branch-conditions-group-form-control/branch-conditions-group-form-control.component.ts

feat: add case sensitive toggle for text conditions

---

packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
packages/shared/package.json
packages/shared/src/lib/pieces/dto/piece-requests.ts

feat: support query piece version by minor

---

packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1688922241747-AddAuthToPiecesMetadata.ts
packages/backend/src/app/pieces/piece-metadata-entity.ts

chore: add auth to metadata

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/insert-row.action.ts
packages/pieces/google-sheets/src/lib/actions/update-row.ts
packages/pieces/google-sheets/src/lib/common/common.ts

fix: google sheets update row

---

packages/backend/.env
packages/backend/src/app/authentication/token-verify-middleware.ts
packages/backend/src/app/flows/flow-run/flow-run-controller.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/flows/flow-run/flow-run-side-effects.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/pieces/delay/src/lib/actions/delay-for-action.ts
packages/pieces/delay/src/lib/actions/delay-untill-action.ts
packages/shared/src/lib/flow-run/execution/execution-output.ts

Delay till explicitly mentioned to resume

---

packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1689351564290-AddTasksToRun.ts
packages/backend/src/app/flows/flow-run/flow-run-controller.ts
packages/backend/src/app/flows/flow-run/flow-run-entity.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/flow-run/create-flow-run-request.ts
packages/shared/src/lib/flow-run/flow-run.ts
packages/shared/src/lib/flow-run/test-flow-run-request.ts
packages/ui/common/src/lib/service/flow.service.ts
packages/ui/feature-builder-canvas/src/lib/test-flow-widget/test-flow-widget.component.ts

chore: add tasks count to flow runs

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/common/common.ts

fix: google sheets row

---

packages/backend/src/app/flows/flow/flow.service.ts
packages/engine/src/lib/action/branch-action-handler.ts

fix: import and validation

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts

fix: lock versions on engine

---

packages/backend/src/app/helper/engine-helper.ts

fix: @activepieces/pieces-framework not found

---

packages/pieces/openai/src/lib/actions/send-prompt.ts
packages/ui/common/src/lib/service/telemetry.service.ts

fix: build errors in telemetry and openai piece

---

packages/backend/src/main.ts
packages/shared/package.json
packages/shared/src/lib/flag/flag.ts
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/environments/environment.prod.ts
packages/ui/common/src/lib/environments/environment.ts
packages/ui/common/src/lib/service/piece-meta.service.ts
packages/ui/core/src/app/app.module.ts
packages/ui/feature-builder-header/src/lib/feedback/feedback.component.html
packages/ui/feature-builder-header/src/lib/feedback/feedback.component.ts
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.html
packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts

chore: control flags in environment

---

packages/backend/src/app/app.ts
packages/pieces/surveymonkey/.eslintrc.json
packages/pieces/surveymonkey/README.md
packages/pieces/surveymonkey/package.json
packages/pieces/surveymonkey/project.json
packages/pieces/surveymonkey/src/index.ts
packages/pieces/surveymonkey/src/lib/common/index.ts
packages/pieces/surveymonkey/src/lib/triggers/new-response.ts
packages/pieces/surveymonkey/tsconfig.json
packages/pieces/surveymonkey/tsconfig.lib.json
packages/ui/common/src/lib/environments/environment.prod.ts
packages/ui/common/src/lib/environments/environment.ts
packages/ui/feature-connections/src/lib/services/oauth2.service.ts
tsconfig.base.json

Fixes typo in website title
Fixes #1652
onEnable and onDisable behavior will throw an error on a localhost connection, to run locally you will need to create the webhooks manually or override the context.webhookUrl with ngrok or similar.

feat: surveymonkey new response trigger

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/common/common.ts

fix(google-sheets): allow updating columns after z

---

packages/backend/src/app/app-connection/app-connection.entity.ts
packages/backend/src/app/app-connection/app-connection.service.ts

fix: encrypted objects

---

docker-compose.yml
package-lock.json
package.json
packages/backend/src/app/app-connection/app-connection.entity.ts
packages/backend/src/app/app-connection/app-connection.service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts

feat: release 0.5.1 quick fix

---

packages/pieces/salsa/package.json
packages/pieces/salsa/src/lib/actions/offline-donation-upsert.ts
packages/pieces/salsa/src/lib/actions/supporter-search.ts
packages/pieces/salsa/src/lib/actions/supporter-upsert.ts
packages/pieces/salsa/src/lib/actions/supporter.ts

fix: salsa auth

---

packages/pieces/common/package.json
packages/pieces/common/src/lib/http/axios/axios-http-client.ts
packages/pieces/salsa/package.json

fix: accept unauthorized requests

---

packages/backend/src/app/helper/trigger-utils.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/piece-metadata.ts
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.ts

fix: handshake is null

---

docker-compose.yml
package-lock.json
package.json

feat: upgrade to 0.5.2

---

packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.ts
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.css
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.ts

fix: code theme

---

packages/engine/src/lib/action/branch-action-handler.ts
packages/shared/package.json
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/flow-helper.ts

fix: case sensitive validation

---

packages/pieces/apitable/.eslintrc.json
packages/pieces/apitable/README.md
packages/pieces/apitable/package.json
packages/pieces/apitable/project.json
packages/pieces/apitable/src/index.ts
packages/pieces/apitable/src/lib/actions/create-record.ts
packages/pieces/apitable/src/lib/actions/find-record.ts
packages/pieces/apitable/src/lib/actions/update-record.ts
packages/pieces/apitable/src/lib/common/index.ts
packages/pieces/apitable/src/lib/triggers/new-record.ts
packages/pieces/apitable/tsconfig.json
packages/pieces/apitable/tsconfig.lib.json
tsconfig.base.json

Adds a new piece `APITable`
Fixes #1653 #1587

feat(apitable): new apitable piece

---

docker-compose.yml
package-lock.json
package.json
packages/backend/src/app/helper/trigger-utils.ts

Old Instances is failing after upgrading because there is no default value for trigger interval

feat: release 0.5.3 add default value for trigger interval

---

packages/backend/src/app/flows/flow-run/flow-run-controller.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/public-ip-utils.ts
packages/backend/src/app/webhooks/webhook-service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/globals.ts
packages/engine/src/lib/helper/action-helper.ts
packages/engine/src/main.ts
packages/pieces/approval/package.json
packages/pieces/approval/src/index.ts
packages/pieces/approval/src/lib/actions/create-approval-link.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts

fix: approval links

---

docs/pieces/apps/bloomerang.mdx
packages/pieces/bloomerang/package.json
packages/pieces/bloomerang/src/lib/actions/upsert-contact_duplicates.ts
packages/pieces/bloomerang/src/lib/actions/upsert-contact_search.ts

solved the typos in the documentation

fix: typo in documentation

---

package-lock.json
package.json
packages/ui/core/src/app/modules/import-flow-base64/import-flow-base64.resolver.ts

fixes the way we decode flow templates from query params.

fix: fix decoding flow template by using buffer and not window.atob

---

packages/pieces/hubspot/package.json
packages/pieces/hubspot/src/lib/actions/create-contact.action.ts

fix: hubspot create contact

---

packages/pieces/ghostcms/.eslintrc.json
packages/pieces/ghostcms/README.md
packages/pieces/ghostcms/package.json
packages/pieces/ghostcms/project.json
packages/pieces/ghostcms/src/index.ts
packages/pieces/ghostcms/src/lib/actions/create-member.ts
packages/pieces/ghostcms/src/lib/actions/create-post.ts
packages/pieces/ghostcms/src/lib/actions/find-member.ts
packages/pieces/ghostcms/src/lib/actions/find-user.ts
packages/pieces/ghostcms/src/lib/actions/update-member.ts
packages/pieces/ghostcms/src/lib/common/index.ts
packages/pieces/ghostcms/src/lib/triggers/member-added.ts
packages/pieces/ghostcms/src/lib/triggers/member-deleted.ts
packages/pieces/ghostcms/src/lib/triggers/member-edited.ts
packages/pieces/ghostcms/src/lib/triggers/page-published.ts
packages/pieces/ghostcms/src/lib/triggers/post-published.ts
packages/pieces/ghostcms/src/lib/triggers/post-scheduled.ts
packages/pieces/ghostcms/tsconfig.json
packages/pieces/ghostcms/tsconfig.lib.json
tsconfig.base.json

feat(ghostcms): actions and triggers

---

packages/pieces/rss/package.json
packages/pieces/rss/src/lib/triggers/new-item-trigger.ts

fix: dedupe items rss

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/index.ts
packages/pieces/google-drive/src/lib/common/index.ts
packages/pieces/google-drive/src/lib/triggers/new-file.ts
packages/pieces/google-drive/src/lib/triggers/new-folder.ts

feat(google-drive): new file and new folder triggers

---

packages/pieces/rss/package.json
packages/pieces/rss/src/lib/triggers/new-item-trigger.ts

fix: fix move filteration logic to run

---

packages/pieces/slack/package.json
packages/pieces/slack/src/lib/actions/send-direct-message-action.ts
packages/pieces/slack/src/lib/actions/send-message-action.ts
packages/pieces/slack/src/lib/common/props.ts
packages/pieces/slack/src/lib/common/utils.ts

You can now change the username and profile picture of the slack bot
Fixes #1727

feat(slack): adds a way to change username and pfp

---

packages/pieces/discord/package.json
packages/pieces/discord/src/index.ts
packages/pieces/discord/src/lib/actions/send-approval-message-webhook.ts
packages/pieces/discord/src/lib/actions/send-approval-message.ts
packages/pieces/discord/src/lib/common/index.ts
packages/pieces/discord/src/lib/trigger/new-message.ts

feat(discord): added discord approval to flow

---

docker-compose.yml
docs/install/options/docker-compose.mdx
docs/install/options/docker.mdx
docs/install/options/overview.mdx
docs/mint.json
package-lock.json
package.json

feat: release 0.6.0

---

packages/pieces/rss/package.json
packages/pieces/rss/src/lib/triggers/new-item-trigger.ts

chore: bump rss

---

packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/lib/actions/text-to-image.ts

Added new Stability.AI version / model, more info on: https://stability.ai/press-articles/stable-diffusion-xl-1-featured-amazon-aws-bedrock

feat: Added new model Stable Diffusion XL 1.0

---

packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/flow-worker/queues/queue.ts
packages/backend/src/main.ts
packages/backend/webpack.config.js

fix: webpack config and bugs caused by wrong config

---

.github/workflows/discord-notifications.yml

chore: send discord notifications using curl

---

packages/backend/src/app/helper/pagination/pagination-utils.ts

fix: add datetime to pagination

---

.github/workflows/discord-notifications.yml

- send notifications on `ci` channel instead of `on-call`
- add commit message to notification text

chore(ci): update discord notifications

---

packages/pieces/sftp/package.json
packages/pieces/sftp/src/index.ts
packages/pieces/sftp/src/lib/actions/create-file.ts
packages/pieces/sftp/src/lib/triggers/new-modified-file.ts

feat(sftp): new or modified file trigger

---

packages/pieces/sftp/package.json
packages/pieces/sftp/src/lib/actions/create-file.ts

fix: sftp put stuck

---

packages/pieces/clarifai/package.json
packages/pieces/clarifai/src/lib/actions/call-classifier-model.ts
packages/pieces/clarifai/src/lib/common/index.ts

Uses the Property.File instead of Property.ShortText so we support both urls and base64

feat(clarifai): clarifai piece changed from url to file

---

packages/backend/src/app/app.ts
packages/backend/src/app/flows/common/piece-installer.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/helper/package-manager.ts
packages/backend/src/app/pieces/pieces.controller.ts
packages/backend/src/app/workers/code-worker/code-builder.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts

chore: refactor install piece

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts
packages/pieces/slack/package.json
packages/pieces/slack/src/index.ts

fix: slack endpoint

---

packages/backend/src/app/flows/step-run/step-run-service.ts

fix: conditions

---

packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.html
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.html
packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html

fix: add loading indicator 

---

.github/workflows/release-pieces.yml

fix: release pieces

---

docker-compose.yml
docs/changelog.mdx
package-lock.json
package.json

chore: release 0.7.0

---

packages/pieces/monday/package.json
packages/pieces/monday/src/index.ts
packages/pieces/monday/src/lib/actions/get-column-value-by-item.ts
packages/pieces/monday/src/lib/actions/get-item-by-column-value.ts
packages/pieces/monday/src/lib/actions/update-item.ts

This PR will add 3 actions in monday.js piece
1- Change Multiple Columns Value in [monday.com](http://monday.com/) - with this you should be able to input the item id and input new values into the columns for that board.
2- Get column Values: input the item id and retrieve the column data for that item
3- Get item by column value: Search a column for specific data and retrieve the matched items data.

feat: Added actions [Monday.js]

---

packages/chatbots/src/lib/datasource/pdf-datasource.ts
packages/chatbots/src/lib/datasource/website-datasource.ts
packages/chatbots/src/lib/framework/datasource.ts

feat: add pdf datasource

---

docker-compose.yml
docs/changelog.mdx
package-lock.json
package.json
packages/backend/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts

feat: release 0.7.1

---

packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts

fix: flow title

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts
packages/engine/src/lib/helper/action-helper.ts
packages/pieces/woocommerce/package.json
packages/pieces/woocommerce/src/index.ts
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts

fix: woocommerce validation

---

packages/engine/src/lib/services/variable-service.ts
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts

fix: edit connection & connection name with two dots

---

packages/pieces/delay/package.json
packages/pieces/delay/src/lib/actions/delay-for-action.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/validators/validators.ts

fix: delay & validator number

---

packages/backend/src/app/flows/flow-instance/flow-instance.module.ts
packages/backend/src/app/flows/flow-run/flow-run-module.ts
packages/backend/src/app/flows/flow.module.ts
packages/backend/src/app/flows/flow/flow.controller.ts
packages/backend/src/app/store-entry/store-entry.controller.ts
packages/backend/src/app/store-entry/store-entry.module.ts

fix: verify project id flow,instance,folder

---

packages/pieces/calendly/package.json
packages/pieces/calendly/src/index.ts
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.html
packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.ts

fix: calendly validation & secret text

---

packages/pieces/google-contacts/package.json
packages/pieces/google-contacts/src/index.ts
packages/pieces/google-contacts/src/lib/action/create-contact.ts

fix(google-contacts): fix phone number

---

packages/backend/src/app/database/database-common.ts
packages/backend/src/app/database/database-connection.ts
packages/backend/src/app/database/migration/1692106268660-AddTagsToRun.ts
packages/backend/src/app/database/migration/postgres/1692106375081-AddTagsToRun.ts
packages/backend/src/app/database/migration/sqllite3/1692056190942-AddTagsToRunSqlite3.ts
packages/backend/src/app/database/postgres-connection.ts
packages/backend/src/app/database/sqllite-connection.ts
packages/backend/src/app/flows/flow-run/flow-run-controller.ts
packages/backend/src/app/flows/flow-run/flow-run-entity.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/engine/src/lib/services/variable-service.ts
packages/engine/src/main.ts
packages/shared/package.json
packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
packages/shared/src/lib/flow-run/execution/execution-output.ts
packages/shared/src/lib/flow-run/execution/execution-state.ts
packages/shared/src/lib/flow-run/flow-run.ts
packages/ui/common/src/lib/models/flow-run.interface.ts

feat: support tags in flow runs api

---

packages/pieces/rss/package.json
packages/pieces/rss/src/lib/triggers/new-item-trigger.ts

fix: sort by rss date

---

packages/pieces/github/package.json
packages/pieces/github/src/index.ts
packages/pieces/github/src/lib/actions/create-issue.ts
packages/pieces/github/src/lib/common/index.ts

Adds Create Issue action for github.

feat(github): add create issue action

---

docker-compose.dev.yml

- Fix docker compose dev for running postgres migrations only
- -full dev env is not yet working for docker compose, will work on this in a follow up PR

chore: fix docker compose dev for postgres migrations

---

packages/pieces/openai/package.json
packages/pieces/openai/src/index.ts
packages/pieces/openai/src/lib/actions/send-prompt.ts
packages/pieces/twitter/package.json
packages/pieces/twitter/src/lib/actions/create-tweet.ts

fix: twitter and open ai

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/index.ts
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts

fix: tweet & wordpress description

---

packages/pieces/kimai/.eslintrc.json
packages/pieces/kimai/README.md
packages/pieces/kimai/package.json
packages/pieces/kimai/project.json
packages/pieces/kimai/src/index.ts
packages/pieces/kimai/src/lib/actions/create-timesheet.ts
packages/pieces/kimai/src/lib/common/client.ts
packages/pieces/kimai/src/lib/common/index.ts
packages/pieces/kimai/tsconfig.json
packages/pieces/kimai/tsconfig.lib.json
tsconfig.base.json

Adds a new piece supporting Kimai (https://www.kimai.org/).
It includes an action to create a timesheet.
Details on a demo Kimai instance are available at https://www.kimai.org/en/demo.html.

feat(piece-kimai): new piece

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/update-row.ts

chore: update google sheets

---

package-lock.json
package.json
packages/pieces/supabase/.eslintrc.json
packages/pieces/supabase/README.md
packages/pieces/supabase/package.json
packages/pieces/supabase/project.json
packages/pieces/supabase/src/index.ts
packages/pieces/supabase/src/lib/actions/upload-file.ts
packages/pieces/supabase/tsconfig.json
packages/pieces/supabase/tsconfig.lib.json
tsconfig.base.json

feat: add supabase

---

packages/pieces/supabase/package.json
packages/pieces/supabase/src/lib/actions/upload-file.ts

fix(supabase): return publicUrl

---

packages/pieces/schedule/package.json
packages/pieces/schedule/src/index.ts
packages/pieces/schedule/src/lib/triggers/every-x-minutes.trigger.ts
packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/lib/actions/text-to-image.ts

feat: add every x minutes

---

packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/lib/actions/text-to-image.ts

It were returning 500 due to activepieces postgres error, the accept_format should be only json
[
](https://activepieces.sentry.io/issues/4278379817/?project=6234451&query=is%3Aunresolved&referrer=issue-stream&stream_index=8)](https://activepieces.sentry.io/issues/4278379817/?project=6234451&query=is%3Aunresolved&referrer=issue-stream&stream_index=8)

fix: stability ai

---

packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/lib/actions/text-to-image.ts
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts
packages/pieces/wordpress/src/lib/actions/create-post.action.ts

fix: wordpress image / stability url

---

packages/pieces/sftp/package.json
packages/pieces/sftp/src/lib/triggers/new-modified-file.ts

feat(sftp): new modified file has path now

---

packages/pieces/contiguity/.eslintrc.json
packages/pieces/contiguity/README.md
packages/pieces/contiguity/package.json
packages/pieces/contiguity/project.json
packages/pieces/contiguity/src/index.ts
packages/pieces/contiguity/src/lib/actions/send-sms.ts
packages/pieces/contiguity/tsconfig.json
packages/pieces/contiguity/tsconfig.lib.json
tsconfig.base.json

Sets up the initial piece for [Contiguity](https://contiguity.co) to allow texting within steps aside from twilio

feat(contiguity): initial piece - sms platform

---

packages/pieces/kimai/package.json
packages/pieces/kimai/src/index.ts

This PR returns the actual message that Kimai produces on an authentication failure.

feat(kimai): return Kimai authentication error message, if existing

---

packages/backend/src/app/webhooks/webhook-service.ts
packages/pieces/simplepdf/.eslintrc.json
packages/pieces/simplepdf/README.md
packages/pieces/simplepdf/package.json
packages/pieces/simplepdf/project.json
packages/pieces/simplepdf/src/index.ts
packages/pieces/simplepdf/src/lib/triggers/new-submission.ts
packages/pieces/simplepdf/tsconfig.json
packages/pieces/simplepdf/tsconfig.lib.json
tsconfig.base.json

fix: webhook sample data

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

feat: limit maximum poll to 10 in google sheets

---

packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/lib/actions/create-post.action.ts

fix: wordpress fix

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts

feat: add open ai errors

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/lib/actions/create-page.action.ts
packages/pieces/wordpress/src/lib/actions/create-post.action.ts

fix: open ai errors & wordpress

---

packages/backend/src/app/helper/system/system.ts
packages/pieces/framework/package.json
packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/triggers/new-row-added.ts

fix: google sheets to 0.6.3

---

packages/pieces/gmail/package.json
packages/pieces/gmail/src/lib/actions/send-email-action.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts

1) Sending empty attachment with email in gmail piece.
2)inputs were showing "undefined" in text.

fix: google attachements + default value check

---

packages/backend/src/app/workers/code-worker/code-builder.ts

fix: code build

---

.devcontainer/Dockerfile
ap-base.dockerfile
docker-compose.dev.yml
packages/backend/src/app/workers/code-worker/code-builder.ts
tools/setup-dev.js

fix: code piece logs

---

Dockerfile
docker-compose.dev.yml

chore: upgrade ap-base to v4

---

package-lock.json
package.json
packages/engine/src/lib/action/branch-action-handler.ts
packages/engine/src/lib/action/code-action-handler.ts
packages/engine/src/lib/action/loop-action-handler.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/helper/action-helper.ts
packages/engine/src/lib/helper/trigger-helper.ts
packages/engine/src/lib/services/variable-service.ts

fix: remove large object from db

---

packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/services/variable-service.ts
packages/engine/src/main.ts
packages/engine/test/services/variable-service.test.ts
packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/index.ts
packages/pieces/stability-ai/src/lib/actions/text-to-image.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/flow-run/execution/execution-state.ts

fix: limit logs to 2 mb

---

packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/engine/src/lib/helper/action-helper.ts
packages/engine/src/lib/helper/test-execution-context.ts
packages/engine/src/main.ts
packages/pieces/google-sheets/package.json
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts

fix: test branch execution context

---

docs/developers/development-setup/codespaces.mdx

added steps to resolve issues with the frontend server.

docs: add troubleshoot steps for codespaces

---

packages/pieces/imap/package.json
packages/pieces/imap/src/index.ts
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.html

fix: imap authentication

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/index.ts

fix: twitter validate auth

---

packages/backend/.env
packages/pieces/tidycal/.eslintrc.json
packages/pieces/tidycal/README.md
packages/pieces/tidycal/package.json
packages/pieces/tidycal/project.json
packages/pieces/tidycal/src/index.ts
packages/pieces/tidycal/src/lib/common/index.ts
packages/pieces/tidycal/src/lib/trigger/cancelled-booking.ts
packages/pieces/tidycal/src/lib/trigger/new-booking.ts
packages/pieces/tidycal/src/lib/trigger/new-contacts.ts
packages/pieces/tidycal/tsconfig.json
packages/pieces/tidycal/tsconfig.lib.json
tsconfig.base.json

Has all the triggers
new booking
cancelled booking
new contact
Fixes #1916

feat(tidycal): add new bookiing / cancelled booking / new contact trigger

---

packages/pieces/github/package.json
packages/pieces/github/src/lib/actions/create-issue.ts
packages/pieces/github/src/lib/common/index.ts

This PR includes following changes to **Create Issue**  action:
- makes Assignee field optional
- adds Issue description field
- adds Issue labels field

feat(github): add addtional props in Create Issue action

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/lib/action/create-new-folder.ts
packages/pieces/google-drive/src/lib/action/create-new-text-file.ts
packages/pieces/google-drive/src/lib/action/upload-file.ts
packages/pieces/google-drive/src/lib/common/index.ts
packages/pieces/google-drive/src/lib/triggers/new-file.ts
packages/pieces/google-drive/src/lib/triggers/new-folder.ts

Adds option to check team drives as well.

chore: added team drives

---

packages/pieces/google-tasks/package.json
packages/pieces/google-tasks/src/index.ts
packages/pieces/google-tasks/src/lib/common/index.ts
packages/pieces/google-tasks/src/lib/triggers/new-task.ts

Creation of a new task trigger
Fix minor issues with naming 
Fixes #2266

feat(googletasks): create new task trigger

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/lib/actions/create-tweet.ts

Fix the bug where the 400 errors has no description .
Fixes #2265

fix(twitter): 400 error description

---

packages/engine/src/lib/helper/trigger-helper.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts

feat: add files service to trigger

---

packages/pieces/monday/package.json
packages/pieces/monday/src/lib/actions/create-item.ts
packages/pieces/monday/src/lib/actions/update-item.ts

- Monday.com Create Item Query Fix
- Monday.com Update Item Query Fix 

fix(monday.js): fix Add Monday Item and Update Monday Item  queries

---

packages/backend/src/app/app-event-routing/app-event-routing.service.ts
packages/backend/src/app/authentication/lib/token-utils.ts
packages/backend/src/app/helper/lock.ts
packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
packages/backend/src/app/workers/sandbox.ts
packages/shared/package.json

fix: change update to upsert

---

packages/ui/feature-builder-test-steps/src/lib/test-steps-core.component.ts
packages/ui/feature-builder-test-steps/src/lib/test-webhook-trigger/test-webhook-trigger.component.ts

Lowers interval period for testing steps.

fix: increase testing triggers speed

---

packages/pieces/notion/package.json
packages/pieces/notion/src/lib/common/index.ts

fix: notion title

---

packages/pieces/shopify/package.json
packages/pieces/shopify/src/index.ts
packages/pieces/shopify/src/lib/common/register-webhook.ts

fix(shopify): authentication are now fixed and all triggers are available  

---

packages/pieces/framework/package.json
packages/pieces/framework/src/lib/validators/validators.ts

Fixing one is not less than or equal to one
Fixes #2379

fix: validators bug

---

packages/pieces/notion/package.json
packages/pieces/notion/src/lib/common/index.ts

fix(notion): empty database list

---

packages/pieces/tally/.eslintrc.json
packages/pieces/tally/README.md
packages/pieces/tally/package.json
packages/pieces/tally/project.json
packages/pieces/tally/src/index.ts
packages/pieces/tally/src/lib/triggers/new-submission.ts
packages/pieces/tally/tsconfig.json
packages/pieces/tally/tsconfig.lib.json
tsconfig.base.json

feat(tally): add new form submission trigger

---

packages/pieces/telegram-bot/package.json
packages/pieces/telegram-bot/src/index.ts
packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts

fix(telegram-bot): add how to find chat id instruction

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/index.ts
packages/pieces/twitter/src/lib/actions/create-tweet.ts

fix(twitter): fail on long tweet with readable error

---

docs/developers/building-pieces/triggers/create-webhook-trigger.mdx

Updates Webhook trigger example link, currently giving 404 error.

docs: update webhook trigger piece example link

---

packages/pieces/gmail/package.json
packages/pieces/gmail/src/index.ts
packages/pieces/gmail/src/lib/actions/send-email-action.ts

feat(gmail): add sender name as optional property

---

packages/pieces/imap/package.json
packages/pieces/imap/src/lib/common/index.ts

fix(imap): subject filter is now case insensitive

---

packages/pieces/linkedin/package.json
packages/pieces/linkedin/src/index.ts
packages/pieces/linkedin/src/lib/actions/create-company-update.ts
packages/pieces/linkedin/src/lib/actions/create-share-update.ts
packages/pieces/linkedin/src/lib/common/index.ts

fix(linkedin): posts with image & text

---

packages/pieces/linkedin/package.json
packages/pieces/linkedin/src/lib/actions/create-company-update.ts
packages/pieces/linkedin/src/lib/actions/create-share-update.ts
packages/pieces/linkedin/src/lib/common/index.ts

fix(linkedin): remove image title

---

packages/pieces/sendinblue/package.json
packages/pieces/sendinblue/src/index.ts

chore(sendinblue): rename to brevo

---

packages/pieces/telegram-bot/package.json
packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts

feat(telegram): add optional thread for subgroups

---

docker-compose.dev.yml
packages/backend/.env
packages/backend/src/app/flows/common/piece-installer.ts
packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/pieces/piece-metadata-service/aggregated-metadata-service.ts
packages/backend/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts
packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
packages/backend/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
packages/backend/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
packages/backend/src/app/workers/engine/engine-installer.ts
packages/backend/src/app/workers/sandbox/abstract-sandbox.ts
packages/backend/src/app/workers/sandbox/cache/cached-sandbox.ts
packages/backend/src/app/workers/sandbox/cache/sandbox-cache-pool.ts
packages/backend/src/app/workers/sandbox/file-sandbox.ts
packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-provisioner.ts
packages/backend/src/app/workers/sandbox/sandbox-manager.ts
packages/engine/src/lib/executors/code-executer.ts
packages/engine/src/lib/globals.ts
packages/shared/src/lib/flows/actions/action.ts
packages/shared/src/lib/flows/triggers/trigger.ts
packages/shared/src/lib/pieces/dto/piece-requests.ts

chore: sandbox caching

---

packages/pieces/trello/package.json
packages/pieces/trello/src/index.ts

Adding the authentication validation for trello.

feat(trello): adding authentication validation

---

packages/ui/common/src/lib/components/json-view/json-view.component.html
packages/ui/common/src/lib/pipe/output-log.pipe.ts
packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
packages/ui/feature-builder-test-steps/src/lib/test-code-step/test-code-step.component.ts
packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.ts

fix: HTML/XML output not being shown correctly 

---

package-lock.json
package.json
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html

fix: reconnect button padding and layout of piece version note

---

packages/pieces/hubspot/package.json
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts

Adding the authentication validation feature for WordPress.

feat(wordpress): validate authentication on saving

---

docker-compose.dev.yml
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
packages/backend/src/app/workers/sandbox/cache/cached-sandbox.ts

fix(sandbox): minor fixes

---

packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts
packages/pieces/wordpress/src/lib/common/index.ts

fix: validate wordpress url

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/insert-row.action.ts
packages/pieces/google-sheets/src/lib/actions/update-row.ts
packages/pieces/google-sheets/src/lib/common/common.ts

fix(google-sheets): stringify values

---

packages/ui/common/src/lib/utils/utils.ts
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts

fix: speed up saving flow

---

packages/ui/common/src/lib/directives/check-overflow.directive.ts
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
packages/ui/feature-builder-store/src/lib/model/enums/builder-state.enum.ts
packages/ui/feature-builder-store/src/lib/service/collection-builder.service.ts
packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
packages/ui/feature-builder-store/src/lib/store/flow/flows.action.ts
packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts

Changed the subscribing location for autoSave$ so it never gets destroyed.

chore: fixed debounce time structure for saving piece steps/triggers

---

packages/pieces/pushover/package.json
packages/pieces/pushover/src/lib/actions/send-notification.ts

add HTML Styling support for Pushover message
https://pushover.net/api#html

feat(pushover): add HTML/Message Styling support

---

packages/pieces/hubspot/package.json
packages/pieces/hubspot/src/lib/actions/create-contact.action.ts
packages/pieces/hubspot/src/lib/common/index.ts

Fetching all the custom properties created by the user to add for the contact at creation
Fixes #2407

feat(hubspot): add custom properties for create contact action

---

packages/pieces/amazon-s3/package.json
packages/pieces/amazon-s3/src/index.ts

fix(amazon-s3): add endpoint property to authentication and allow region customization 

---

packages/pieces/kizeo-forms/package.json
packages/pieces/kizeo-forms/src/index.ts
packages/pieces/kizeo-forms/src/lib/actions/create-list-item.ts
packages/pieces/kizeo-forms/src/lib/actions/delete-list-item.ts
packages/pieces/kizeo-forms/src/lib/actions/edit-list-item.ts
packages/pieces/kizeo-forms/src/lib/actions/get-all-list-items.ts
packages/pieces/kizeo-forms/src/lib/actions/get-list-definition.ts
packages/pieces/kizeo-forms/src/lib/actions/get-list-item.ts
packages/pieces/kizeo-forms/src/lib/common/index.ts
packages/pieces/kizeo-forms/src/lib/common/models.ts

Add actions on Kizeo Forms' advanced lists : GetListDefinition, GetListItem, GetAllListItems, CreateListItem, EditListItem, DeleteListItem. 

feat(kizeo-forms):  Add GetListDefinition, GetListItem, GetAllListItems, CreateListItem, EditListItem, DeleteListItem ACtions

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/index.ts
packages/pieces/google-drive/src/lib/action/download-file.ts
packages/pieces/google-drive/src/lib/action/read-file.ts

This PR creates a new action to download any file from Google Drive, using its file id. The specific Google formats (Google Docs, Sheets, etc.) will be converted to their equivalent Microsoft 365 (docx, xlsx, etc.) format.

feat(google-drive): add download file action

---

packages/pieces/slack/package.json
packages/pieces/slack/src/lib/common/props.ts

fix(slack): load more than 100 channel

---

packages/pieces/notion/package.json
packages/pieces/notion/src/index.ts
packages/pieces/notion/src/lib/action/update-database-item.ts
packages/pieces/notion/src/lib/common/index.ts

feat(notion): add update database item action

---

packages/pieces/telegram-bot/package.json
packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts
packages/pieces/telegram-bot/src/lib/trigger/new-message.ts

Add format support for Telegram (Markdown and HTML format)
Fix some spell

feat: add format to Telegram

---

packages/pieces/salesforce/package.json
packages/pieces/salesforce/src/index.ts

chore: fix spell salesforce

---

packages/pieces/open-router/package.json
packages/pieces/open-router/src/index.ts
packages/pieces/open-router/src/lib/actions/ask-open-router.ts
packages/pieces/open-router/src/lib/common/index.ts

loading models dynamically
Fixes #2607

feat(open-router): loading models dynamically

---

packages/packages/date-helper/package.json

fix: date helper

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/lib/common/index.ts

Adding a sharable link for the files retrieved in the response.

feat(google-drive): adding the share link url

---

packages/backend/src/app/flows/flow/flow.service.ts
packages/shared/package.json
packages/shared/src/lib/flows/dto/flow-template-request.ts
packages/ui/feature-templates/src/lib/featured-template-card/featured-template-card.component.html
packages/ui/feature-templates/src/lib/featured-template-card/featured-template-card.component.ts

feat: add is featured

---

packages/pieces/framework/package.json
packages/pieces/framework/src/lib/property/custom-auth-prop.ts
packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts
packages/pieces/wordpress/src/lib/common/index.ts

chore(wordpress): add auth troubleshoot steps

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/send-http-request-action.ts

Removes the HTTP body from the HTTP Piece in a HTTP GET request
Fixes #2087

fix(http): remove body from get request

---

packages/pieces/imap/package.json
packages/pieces/imap/src/lib/common/index.ts
packages/pieces/imap/src/lib/triggers/new-email.ts

fix: race condition in map

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/send-http-request-action.ts

fix(http): body were sent incorrectly

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/send-http-request-action.ts

fix: revert dynamic property name

---

packages/pieces/sendinblue/package.json
packages/pieces/sendinblue/src/lib/actions/create-or-update-contact.ts

Error occur while creating new contact
Fixes #2365

fix(brevo): created contact not in the correct list

---

packages/pieces/openai/package.json
packages/pieces/openai/src/index.ts
packages/pieces/openai/src/lib/actions/send-prompt.ts
packages/pieces/openai/src/lib/actions/transcriptions.ts
packages/pieces/openai/src/lib/actions/translation.ts

Fixing whisper model existing with Ask "ChatGPT" action.
Adding transcription action using whisper-1 model
Adding translate action using whisper-1 model
Fixes #2072

feat(openai): adding whisper model actions

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/insert-row.action.ts

Fixing the bug where empty fields in insert row get skipped
Fixes #2634

fix(google-sheet): Skip column insertion when value is empty

---

packages/pieces/airtable/package.json
packages/pieces/airtable/src/index.ts

Adding API key validation
Fixes #2031

feat(airtable): adding api key validation

---

packages/pieces/tidycal/package.json
packages/pieces/tidycal/src/index.ts
packages/pieces/tidycal/src/lib/trigger/cancelled-booking.ts
packages/pieces/tidycal/src/lib/trigger/new-booking.ts
packages/pieces/tidycal/src/lib/trigger/new-contacts.ts

Adding validation for the API key
Fixes #2727

feat(tidycal): adding api key validation

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts
packages/ui/common/src/index.ts
packages/ui/common/src/lib/components/icon-button/icon-button.component.html
packages/ui/common/src/lib/components/upload-file-control/upload-file-control.component.html
packages/ui/common/src/lib/components/upload-file-control/upload-file-control.component.ts
packages/ui/common/src/lib/resolvers/connections.resolver.ts
packages/ui/common/src/lib/ui-common.module.ts
packages/ui/common/src/lib/validators.ts
packages/ui/core/src/app/app.component.ts
packages/ui/core/src/app/modules/flow-builder/flow-builder.routing.ts
packages/ui/core/src/app/modules/flow-builder/resolvers/builder-route-data.ts
packages/ui/core/tailwind.config.js
packages/ui/feature-builder-header/src/lib/import-flow-dialogue/import-flow-dialogue.component.html
packages/ui/feature-builder-store/src/index.ts
packages/ui/feature-builder-store/src/lib/store/app-connections/app-connections.action.ts
packages/ui/feature-builder-store/src/lib/store/app-connections/app-connections.reducer.ts
packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html

chore: refactor file controller and resolvers

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/send-http-request-action.ts

Reverts the body property from dynamic data --> JSON.

fix: revert back to http body always being there

---

packages/pieces/salesforce/package.json
packages/pieces/salesforce/src/lib/action/upsert-by-external-id-bulk.ts

Updates the line ending setting in the createBulkJobFunction to be compatible with the JSON to CSV piece.

fix(salesforce): update line ending in bulk action

---

packages/pieces/talkable/package.json
packages/pieces/talkable/src/lib/actions/origins/create-events-batch.ts
packages/pieces/talkable/src/lib/actions/origins/create-purchases-batch.ts

Added support of new param "create_offers" for Origin batch creation

feat(Talkable): Add support of new param "create_offers" for Origin batch creation

---

packages/pieces/airtable/package.json
packages/pieces/airtable/src/index.ts
packages/pieces/airtable/src/lib/actions/create-record.ts
packages/pieces/airtable/src/lib/common/index.ts

Fixing the attachment field not uploading

fix(airtable): fixing attachment field

---

packages/pieces/hubspot/package.json
packages/pieces/hubspot/src/index.ts
packages/pieces/hubspot/src/lib/common/client.ts
packages/pieces/hubspot/src/lib/triggers/new-contact-added.ts

Now you can choose extra features to be returned with contact information for the contact created trigger.
Fixes #2755

feat(hubspot): dropdownlist for extra feature

---

docker-compose.yml
docs/changelog.mdx
package-lock.json
package.json

feat: release 0.9.0

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/return-response.ts

Adding the response returned as an output to the piece
Fixes #2752

feat(http): adding output to return response

---

packages/ui/core/src/assets/scss/variables.scss
packages/ui/core/src/index.html

Adds an arabic font so things look better: 
Now:
Before:

chore: add noto sans arabic

---

packages/ui/common/src/lib/service/piece-meta.service.ts

Adds edition as a query param for piece-metadata endpoints.

chore: added edition to piece metadata endpoint queryparams

---

packages/pieces/contentful/package.json
packages/pieces/contentful/src/index.ts
packages/pieces/contentful/src/lib/actions/records/get-record.ts
packages/pieces/contentful/src/lib/common/constants.ts

Adds an action to the contentful piece for getting an entry by it's ID.
This is dependent on #1827 

feat(contentful): Add Get Entry Action

---

packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/backend/src/app/workers/sandbox/cache/sandbox-cache-pool.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-cache-key.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-cache-type.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-provisioner.ts
packages/backend/src/main.ts

refactor: cache key

---

packages/ui/feature-templates/src/lib/featured-template-card/featured-template-card.component.html

chore: add pre-line whitespace

---

packages/pieces/kizeo-forms/package.json
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-deleted.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-finished.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-pushed.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-received.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-updated.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data.trigger.ts

Fix all the triggers of the piece that weren't working because of the Kizeo Forms API.

fix(kizeo-forms): fix triggers

---

docker-compose.yml
package-lock.json
package.json
packages/backend/src/app/helper/engine-helper.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/globals.ts
packages/engine/src/lib/helper/action-helper.ts
packages/engine/src/lib/services/connections.service.ts
packages/engine/src/lib/services/files.service.ts
packages/engine/src/lib/services/storage.service.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/context.ts

fix: use local ip instead of public ip

---

packages/pieces/smtp/package.json
packages/pieces/smtp/src/index.ts
packages/pieces/smtp/src/lib/actions/send-email.ts

fix: smtp piece

---

packages/pieces/llmrails/package.json
packages/pieces/llmrails/src/index.ts
packages/pieces/smtp/package.json
packages/pieces/smtp/src/index.ts
packages/pieces/smtp/src/lib/actions/send-email.ts

fix: smtp & llm rails logo

---

packages/pieces/clarifai/package.json
packages/pieces/clarifai/src/index.ts
packages/pieces/clarifai/src/lib/actions/ask-llm.ts
packages/pieces/clarifai/src/lib/actions/generate-IGM.ts
packages/pieces/clarifai/src/lib/actions/generate-igm.ts

Adding the ask large language model (LLM) action.
Adding the Image generation model (IGM) action.
Closes #2738

feat(clarifai): creating even more actions

---

packages/backend/src/app/helper/logger.ts

fix: logger transport

---

packages/ui/core/src/assets/scss/ng-material-override.scss
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/mentions-list.component.html

Fixes ui bugs with "data to insert" popover.

fix: collapsibles in insert data popover

---

packages/pieces/slack/package.json
packages/pieces/slack/src/lib/triggers/new-message.ts
packages/pieces/slack/src/lib/triggers/new-reaction-added.ts

fix: slack wait for registration

---

packages/engine/src/lib/helper/trigger-helper.ts
packages/pieces/framework/src/lib/context.ts

fix: create listeners

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/lib/common/index.ts

iterating through all the folders in the drive and returning them
Fixes #2892

fix(google-drive): viewing all the folders

---

packages/pieces/kizeo-forms/package.json
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-deleted.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-finished.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-pushed.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-received.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-updated.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data.trigger.ts

Fixes when creating a trigger and then publishing the flow, the flowId was missing on the third-party application's webhook.

fix(kizeo-forms): properly set flow ID to webhooks

---

tools/scripts/generate-new-piece.ts
tools/scripts/utils/files.ts

fix: generate new piece

---

packages/pieces/openai/package.json
packages/pieces/openai/src/lib/actions/send-prompt.ts

Error with OpenAI: Result is “Undefined”
Fixes #2899

fix(openai): max token error not shown

---

packages/pieces/notion/package.json
packages/pieces/notion/src/lib/common/models.ts

fix: notion number casting

---

packages/pieces/microsoft-onedrive/.eslintrc.json
packages/pieces/microsoft-onedrive/README.md
packages/pieces/microsoft-onedrive/package.json
packages/pieces/microsoft-onedrive/project.json
packages/pieces/microsoft-onedrive/src/index.ts
packages/pieces/microsoft-onedrive/src/lib/actions/download-file.ts
packages/pieces/microsoft-onedrive/src/lib/actions/list-files.ts
packages/pieces/microsoft-onedrive/src/lib/actions/list-folders.ts
packages/pieces/microsoft-onedrive/src/lib/actions/upload-file.ts
packages/pieces/microsoft-onedrive/src/lib/common/common.ts
packages/pieces/microsoft-onedrive/src/lib/triggers/new-file.ts
packages/pieces/microsoft-onedrive/tsconfig.json
packages/pieces/microsoft-onedrive/tsconfig.lib.json
tsconfig.base.json

Add the piece Microsoft OneDrive with the following actions : 
- download file
- upload file
- list files
- list folders
and trigger : 
- new file
Fixes activepieces/under-review#528

feat(microsoft-onedrive): Add Download File / Upload File / List Files / List Folders Actions and New File Trigger

---

packages/pieces/microsoft-onedrive/package.json
packages/pieces/microsoft-onedrive/project.json
packages/pieces/microsoft-onedrive/src/lib/actions/list-files.ts
packages/pieces/microsoft-onedrive/src/lib/actions/list-folders.ts
packages/pieces/microsoft-onedrive/src/lib/actions/upload-file.ts
packages/pieces/microsoft-onedrive/src/lib/common/common.ts
packages/pieces/microsoft-onedrive/src/lib/triggers/new-file.ts

Turns the parentFolder property into a dropdown for a better user-frendly experience

feat(microsoft-onedrive): turns the parentFolder prop into a dropdown

---

packages/pieces/http/package.json
packages/pieces/http/src/lib/actions/send-http-request-action.ts

fix(http): ignore body when empty

---

packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/flows/flow/flow.controller.ts
packages/backend/src/app/flows/flow/flow.service.ts
packages/shared/src/lib/common/utils/object-utils.ts
packages/shared/src/lib/flows/flow-helper.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/actions/duplicate-step-action/duplicate-step-action.component.ts
packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
packages/ui/feature-builder-store/src/lib/store/flow/flows.action.ts
packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts
packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.ts

chore: refactor duplicate step

---

packages/shared/src/lib/flows/actions/action.ts

fix: action schema

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/database/migration/common/1696245170062-add-piece-type-and-package-type-to-flow-template.ts
packages/backend/src/app/database/postgres-connection.ts
packages/engine/src/lib/action/branch-action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts

fix: branch failure & migrate flow templates

---

packages/engine/src/lib/action/action-handler.ts
packages/engine/src/lib/action/branch-action-handler.ts
packages/engine/src/lib/action/code-action-handler.ts
packages/engine/src/lib/action/loop-action-handler.ts
packages/engine/src/lib/action/piece-action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/shared/src/lib/flow-run/execution/step-output.ts

chore: refactor branch

---

.github/workflows/build-cloud-image.yml
packages/engine/src/lib/services/storage.service.ts
packages/pieces/store/package.json
packages/pieces/store/src/lib/actions/store-remove-value.ts

fix: store piece

---

turbowatch.ts

fix: load env

---

packages/pieces/openai/package.json
packages/pieces/openai/src/index.ts
packages/pieces/openai/src/lib/actions/transcriptions.ts
packages/pieces/openai/src/lib/actions/translation.ts

fixing https://community.activepieces.com/t/openai-whisper-error-is-considered-successful/728/2

fix(openai): throw error on fail

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flows/step-file/step-file.module.ts
packages/backend/src/app/flows/step-file/step-file.service.ts
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.html
packages/shared/package.json
packages/shared/src/lib/file/file.ts
packages/shared/src/lib/flows/step-file/step-file.ts

fix: test step file

---

packages/pieces/google-contacts/package.json
packages/pieces/google-contacts/src/lib/action/create-contact.ts

fixing the error in this community when creating a new contact :
https://community.activepieces.com/t/google-sheet-contacts-integration-error/383

fix(google-contacts): new contact error on creation

---

Dockerfile
package-lock.json
package.json

chore: upgrade faiss node

---

packages/pieces/framework/package.json
packages/pieces/framework/src/lib/piece.ts

Revert mention icon url, framework is supposed to be "agnostic" to frontend.

chore: reverted mention icon url

---

packages/backend/src/app/ee/billing/plans/plan.service.ts
packages/backend/src/app/ee/referrals/referral.service.ts

fix: referral bonus

---

packages/backend/src/app/helper/pagination/paginator.ts

When attempting to paginate to the second page of the data list in development mode (using SQLite), the application crashes due to a pagination error.

fix: sqllit_pagniation

---

packages/backend/src/app/helper/trigger-utils.ts

fix: schedule cron job

---

.github/workflows/build-cloud-image.yml
.github/workflows/release.yml
docker-compose.yml
docs/changelog.mdx
docs/enterprise/install.mdx
package-lock.json
package.json

feat: release 0.11.0

---

packages/pieces/airtable/package.json
packages/pieces/airtable/src/lib/actions/create-record.ts
packages/pieces/airtable/src/lib/common/index.ts

Fixes wrong mapping: https://community.activepieces.com/t/incorrect-airtable-mapping-when-writing-new-record/896

fix(airtable): fixed wrong mapping

---

.github/workflows/build-cloud-nx.yml
packages/backend/src/app/helper/logger.ts
packages/backend/src/app/webhooks/webhook-controller.ts

* fixes #2930 
* fixes logger level in dev mode

fix: webhook multipart requests

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts

fix: redirect url

---

packages/backend/src/app/ee/pieces/admin-piece-requests.ee.ts
packages/pieces/github/package.json
packages/pieces/hubspot/package.json
packages/pieces/shopify/package.json

fix(shopify): sample data is fixed

---

.github/workflows/build-cloud-image.yml
packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html

fix: delete button team members

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts
packages/backend/src/app/ee/authentication/rbac-auth-middleware.ts

fix: redirect endpoint

---

packages/backend/src/app/authentication/authentication.service.ts
packages/backend/src/app/authentication/lib/token-utils.ts
packages/backend/src/app/authentication/token-verify-middleware.ts
packages/backend/src/app/ee/firebase-auth/firebase-authentication.controller.ts
packages/backend/src/app/ee/helper/email-service.ts
packages/backend/src/app/ee/project-members/project-member.module.ts
packages/backend/src/app/ee/projects/enterprise-project-controller.ts
packages/backend/src/app/helper/engine-helper.ts
packages/shared/src/lib/authentication/model/principal-type.ts
packages/shared/src/lib/authentication/model/principal.ts

refactor(api): add projectType and projectPlatformId to access token payload

---

docs/license.mdx

Fix spelling and grammatical errors, add mailto link
Fixes spelling and grammatical error on license doc

docs: fix typos in license.mdx

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/helper/apperance-helper.ts
packages/backend/src/app/flags/flag.module.ts

feat: hide community & billing & docs

---

packages/pieces/schedule/package.json
packages/pieces/schedule/src/lib/triggers/every-day.trigger.ts

fix: schedule trigger

---

.github/workflows/build-cloud-image.yml
packages/ui/core/nginx.cloud.conf
packages/ui/core/nginx.standard.conf

chore: nginx reserve host

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/helper/apperance-helper.ts
packages/backend/src/app/flags/flag.service.ts
packages/backend/src/app/flags/theme.ts
packages/ee/auth/src/lib/auth-container/firebase-auth-container.component.html
packages/ee/auth/src/lib/ee-auth.routing.ts
packages/ui/common/src/index.ts
packages/ui/common/src/lib/environments/environment.prod.ts
packages/ui/common/src/lib/environments/environment.ts
packages/ui/common/src/lib/service/appearance-service.ts
packages/ui/common/src/lib/service/flag.service.ts
packages/ui/core/src/app/app.component.html
packages/ui/core/src/app/app.component.ts
packages/ui/core/src/app/app.module.ts
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.html
packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
packages/ui/core/src/index.html
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
packages/ui/feature-dashboard/src/lib/dashboard.routing.ts

chore: fix login fav icon & titles

---

package-lock.json
packages/pieces/discord/package.json
packages/pieces/discord/src/index.ts
packages/pieces/discord/src/lib/actions/add-role-to-member.ts
packages/pieces/discord/src/lib/actions/find-channel.ts
packages/pieces/discord/src/lib/actions/find-guild-member.ts
packages/pieces/discord/src/lib/actions/remove-member-from-guild.ts
packages/pieces/discord/src/lib/actions/remove-role-from-member.ts
packages/pieces/discord/src/lib/actions/rename-channel.ts
packages/pieces/discord/src/lib/common/index.ts
packages/pieces/discord/src/lib/common/models.ts
packages/pieces/discord/src/lib/trigger/new-message.ts

**Add additional discord actions**
Add role to user
Remove role from user
Rename channel
Find Channel
Find user

feat(discord): add role to user / remove role from user / rename channel / find channel / find user action

---

packages/pieces/google-sheets/package.json
packages/pieces/google-sheets/src/lib/actions/find-rows.ts

fix: improve google sheet props description

---

packages/pieces/open-router/package.json
packages/pieces/open-router/src/lib/actions/ask-open-router.ts

fix(open-router): load model list

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts

fix: connection status

---

package-lock.json
package.json
packages/ee/product-embed/product-sdk/src/app/enable-integration-modal/enable-integration-modal.component.html
packages/ee/product-embed/product-sdk/src/app/enable-integration-modal/enable-integration-modal.component.ts

fix: product embed error

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/database/migration/postgres/1698323987669-AddTerminationReason.ts
packages/backend/src/app/database/migration/sqlite/1698323327318-AddTerminationReason.ts
packages/backend/src/app/database/postgres-connection.ts
packages/backend/src/app/database/sqlite-connection.ts
packages/backend/src/app/flows/flow-run/flow-run-entity.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/action/action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/flow-run/execution/execution-output.ts
packages/shared/src/lib/flow-run/flow-run.ts
packages/ui/common/src/lib/components/status-icon/state-icon.component.ts
packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html

chore: change stopped to succeded

---

.github/workflows/build-cloud-image.yml
docker-compose.yml
docs/changelog.mdx
package-lock.json
package.json
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/test/integration/ee/platform/admin-platform.test.ts

feat: release 0.12.0

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/projects/enterprise-project-controller.ts

fix: exchange token to include project id

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flows/flow-run/flow-run-entity.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/engine/src/lib/action/action-handler.ts
packages/engine/src/lib/executors/flow-executor.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/flow-run/execution/execution-output.ts
packages/ui/common/src/lib/components/status-icon/state-icon.component.ts
packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html

fix: revert stopped changes

---

.github/workflows/build-cloud-image.yml
docker-compose.yml
package-lock.json
package.json
packages/backend/src/app/flows/flow-run/flow-run-entity.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/webhooks/webhook-controller.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/backend/src/app/workers/flow-worker/queues/redis/redis-queue.ts
packages/shared/package.json
packages/shared/src/index.ts

Engine were executing first step only & fix bull board

feat: release 0.12.1

---

docs/developers/development-setup/getting-started.mdx

docs: update pieces available

---

packages/pieces/talkable/package.json

fix(talkable): rename package to fix tests and deploy

---

packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
packages/ee/ui-platform/src/lib/components/platform/platform.component.ts
packages/ui/common/src/index.ts
packages/ui/common/src/lib/components/page-title/page-title.component.html
packages/ui/common/src/lib/components/page-title/page-title.component.ts
packages/ui/common/src/lib/service/dashboard.service.ts
packages/ui/common/src/lib/store/project/project.selector.ts
packages/ui/common/src/lib/ui-common.module.ts
packages/ui/feature-chatbot/src/lib/chatbots-table/chatbots-table.component.html
packages/ui/feature-dashboard/src/lib/components/page-title/page-title.component.html
packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
packages/ui/feature-dashboard/src/lib/pages/community-pieces-table/community-pieces-table.component.html
packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts

Adds project name to dashboard.

feat: add project name to dashboard

---

packages/backend/src/app/app.ts
packages/backend/src/app/webhooks/webhook-controller.ts

fix: expose headers for webhook response

---

packages/pieces/clarifai/package.json
packages/pieces/clarifai/src/index.ts
packages/pieces/common/package.json
packages/pieces/common/src/lib/http/axios/axios-http-client.ts
packages/pieces/common/src/lib/http/core/base-http-client.ts

fix(clarfai): validate auth & http query params

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flags/flag.module.ts
packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.html
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts

feat: hide oauth2 apps when platform

---

packages/pieces/facebook-leads/package.json
packages/pieces/facebook-leads/src/lib/triggers/new-lead.ts

fix(facebook-leads): update leads

---

docs/mint.json
docs/platform/manage-users.mdx
docs/platform/managed-projects.mdx
docs/platform/managed-users.mdx

docs: add managed users

---

packages/backend/src/app/database/migration/1698857968495-AddExternalIdSqlite3.ts
packages/backend/src/app/database/sqlite-connection.ts

chore: add migration for external id

---

packages/backend/test/helpers/mocks.ts
packages/backend/test/integration/ee/managed-authn/external-token.test.ts

test: more managed authn scenarios

---

docs/platform/embedding.mdx
docs/platform/managed-users.mdx
packages/backend/src/app/ee/managed-authn/lib/external-token-extractor.ts
packages/backend/src/app/ee/signing-key/signing-key-controller.ts
packages/backend/src/app/ee/signing-key/signing-key-service.ts
packages/backend/test/helpers/auth.ts
packages/backend/test/integration/ee/managed-authn/external-token.test.ts
packages/backend/test/integration/ee/signing-key/signing-key.test.ts
packages/ee/embed-sdk/project.json
packages/ee/embed-sdk/tsconfig.json

1- Removed platform id from JWT, It can be found from KID
2- embed-sdk should be umd so it's compatible with browser.

chore: remove platform id

---

.github/workflows/build-cloud-image.yml
docker-compose.yml
package-lock.json
package.json
packages/backend/src/app/ee/signing-key/signing-key-controller.ts

chore: bump version to 0.12.2

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flags/flag.module.ts
packages/ee/billing/ui/src/lib/plan-name.pipe.ts

fix: whitelabel webhook & redirect url

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flags/flag.module.ts

fix: white label webhook url

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flags/flag.module.ts

fix: webhook url protcol

---

packages/backend/src/app/ee/billing/plans/pricing-plans.ts
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.html
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.ts
packages/ee/shared/src/lib/billing/plan.ts

Adds new pricing plans for the pro plan and removes others.

chore: update pricing for pro plans

---

packages/ee/ui-platform/src/lib/components/platform-settings/platform-settings.component.html
packages/ee/ui-platform/src/lib/components/platform/platform.component.html
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html

chore: remove platform id and rename platform settings to dashboard

---

packages/ee/ui-platform/src/lib/components/projects-table/projects-table.component.html
packages/ee/ui-platform/src/lib/components/projects-table/projects-table.component.ts
packages/ui/common/src/lib/service/project.service.ts

chore: remove id column and fix rediriection

---

deploy/pulumi/index.ts

This PR corrects two issues in our Pulumi setup:
Removed unintended hyphens from a previous merge, fixing syntax errors in the project.
Revised the configuration handling to prevent the creation of stacks with empty values due to misidentified non-empty objects.

fix: Pulumi deplyment issue fix

---

packages/backend/src/app/ee/billing/plans/pricing-plans.ts
packages/ee/billing/ui/src/lib/ee-billing-ui.module.ts
packages/ee/billing/ui/src/lib/plans-page/automation-plan-card.component/automation-plan-card.component.html
packages/ee/billing/ui/src/lib/plans-page/automation-plan-card.component/automation-plan-card.component.ts
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.html
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.ts
packages/ee/billing/ui/src/lib/plans-page/utils.ts
packages/ee/shared/src/lib/billing/plan.ts

Added Platform and Enterprise plans to cloud.

feat: Adding new plans

---

packages/pieces/woocommerce/package.json
packages/pieces/woocommerce/src/index.ts
packages/pieces/woocommerce/src/lib/actions/create-coupon.ts
packages/pieces/woocommerce/src/lib/actions/create-customer.ts
packages/pieces/woocommerce/src/lib/actions/create-product.ts
packages/pieces/woocommerce/src/lib/actions/find-coupon.ts
packages/pieces/woocommerce/src/lib/actions/find-customer.ts
packages/pieces/woocommerce/src/lib/actions/find-product.ts

Add create/find: coupon, customer, product

feat(woocommerce): Create Coupon / Find Coupon / Create Customer / Find Customer / Create Product / Find Product Actions

---

packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
packages/ee/ui-platform/src/lib/components/platform-settings/signing-keys-table/signing-keys-table.component.html
packages/ee/ui-platform/src/lib/components/projects-table/projects-table.component.html
packages/ui/feature-chatbot/src/lib/chatbots-table/chatbots-table.component.html

feat: tables' buttons design debt

---

packages/pieces/chatbots/package.json
packages/pieces/chatbots/src/index.ts

chore(chatbot): update description

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/firebase-auth/firebase-authentication.controller.ts

fix: sign up

---

Dockerfile

fix: docker volume binding

---

packages/backend/src/app/authentication/authentication-service/index.ts
packages/backend/src/app/authentication/authentication.controller.ts
packages/backend/src/app/database/seeds/dev-seeds.ts
packages/backend/src/app/ee/firebase-auth/firebase-authentication.controller.ts
packages/backend/src/app/ee/project-members/project-member.service.ts
packages/backend/src/app/user/user-service.ts
packages/ee/auth/src/lib/firebase-auth.service.ts
packages/ee/auth/src/lib/sign-up/firebase-sign-up.component.ts
packages/shared/package.json
packages/shared/src/lib/common/activepieces-error.ts

fix: auto verify on invitation accept

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
packages/ui/core/src/app/guards/user-logged-in.guard.ts

fix: privacy url and terms of services

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/platform/platform.controller.ts
packages/backend/src/app/flags/flags.hooks.ts
packages/backend/src/app/pieces/piece-metadata-service/aggregated-metadata-service.ts
packages/shared/src/lib/common/utils/object-utils.ts
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.html
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.html
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts

fix: request piece button

---

.dockerignore
Dockerfile

A minor cleanup that doesn't change any logic.

chore: cleanup Dockerfile and add some dockerignore rules

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/authentication/rbac-auth-middleware.ts
packages/backend/src/app/ee/billing/usage/limits/members-limit.ts
packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
packages/backend/src/app/ee/helper/email/email-service.ts
packages/ee/components/src/lib/share-flow-template-dialog/share-flow-template-dialog.component.ts
packages/ee/project-members/src/lib/accept-invitation/accept-invitation.component.ts
packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/resolvers/connections.resolver.ts
packages/ui/common/src/lib/service/templates.service.ts
packages/ui/common/src/lib/store/project/project.effects.ts
packages/ui/common/src/lib/store/project/project.selector.ts
packages/ui/core/src/app/app.module.ts
packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts

fix: delete project member

---

packages/ui/core/src/locale/messages.de.xlf
packages/ui/core/src/locale/messages.fr.xlf
packages/ui/core/src/locale/messages.ja.xlf
packages/ui/core/src/locale/messages.xlf

New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)

feat(crowdin): New Translations

---

docs/about/i18n.mdx

docs(i18n): improve docs

---

docs/developers/architecture/repo-structure.mdx

Fixes typo
Fixes typo in docs.

docs: fixed typo in repo-structure.mdx

---

packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
packages/pieces/mailchimp/src/index.ts
packages/ui/core/nginx.cloud.conf
packages/ui/core/nginx.standard.conf
packages/ui/core/project.json
packages/ui/core/src/locale/messages.it.xlf
packages/ui/core/src/locale/messages.pt.xlf

feat(i18n): add italien and portuguese

---

.gitignore
packages/pieces/mailchimp/package.json
packages/pieces/mailchimp/src/lib/actions/add-member-to-list.ts
packages/pieces/mailchimp/src/lib/actions/add-note-to-subscriber.ts
packages/pieces/mailchimp/src/lib/actions/add-subscriber-to-tag.ts
packages/pieces/mailchimp/src/lib/actions/remove-subscriber-from-tag.ts

fix(mailchimp): add tag / remove tag / add note / add member to list

---

packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
packages/backend/src/app/ee/authentication/ee-authorization.ts
packages/backend/src/app/ee/custom-domains/custom-domain.module.ts
packages/backend/src/app/ee/firebase-auth/firebase-authentication.controller.ts
packages/backend/src/app/ee/managed-authn/managed-authn-service.ts
packages/backend/src/app/ee/oauth-apps/oauth-app.module.ts
packages/backend/src/app/ee/platform/platform.controller.ts
packages/backend/src/app/ee/platform/platform.module.ts
packages/backend/src/app/ee/projects/enterprise-project-controller.ts
packages/backend/src/app/ee/signing-key/signing-key-controller.ts
packages/backend/src/app/ee/signing-key/signing-key-module.ts
packages/backend/src/app/ee/signing-key/signing-key-service.ts
packages/backend/src/app/pieces/pieces.controller.ts
packages/backend/test/helpers/auth.ts
packages/backend/test/integration/ee/oauth-app/oauth-app.test.ts
packages/backend/test/integration/ee/piece-metadata/piece-metadata.test.ts
packages/backend/test/integration/ee/platform/platform.test.ts
packages/backend/test/integration/ee/signing-key/signing-key.test.ts
packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts
packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
packages/ee/ui-platform/src/lib/platform.resolver.ts
packages/shared/package.json
packages/shared/src/lib/authentication/model/principal.ts
packages/shared/src/lib/common/utils/assertions.ts
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/guards/show-platform-settings.guard.ts
packages/ui/common/src/lib/service/authentication.service.ts

refactor(authorization): add platform role to the jwt

---

.github/workflows/crowdin.yml
package-lock.json
package.json
tools/scripts/xlf/remove-ee-modules-from-xlf-files.ts
tools/scripts/xlf/xlf-modifier.ts

Removes platform module text from i18n

chore: added script to remove platform module from xlf files

---

packages/backend/src/app/database/migration/sqlite/1700140010475-AddUserMigrationSqlite3.ts
packages/backend/src/app/database/sqlite-connection.ts

fix: generate sqlite3

---

packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/service/locales.service.ts
packages/ui/core/src/app/app.component.ts

chore: locale fix review

---

docker-compose.yml
docs/about/changelog.mdx
package-lock.json
package.json
packages/backend/src/app/user/user-service.ts

feat: release 0.13.0

---

.github/workflows/build-cloud-image.yml
packages/ui/common/src/lib/environments/environment.prod.ts
packages/ui/common/src/lib/environments/environment.ts
packages/ui/core/nginx.cloud.conf
packages/ui/core/nginx.standard.conf
packages/ui/core/src/locale/messages.de.xlf
packages/ui/core/src/locale/messages.fr.xlf
packages/ui/core/src/locale/messages.it.xlf
packages/ui/core/src/locale/messages.ja.xlf
packages/ui/core/src/locale/messages.pt.xlf

feat: add de language by jan hogler

---

packages/pieces/youtube/package.json
packages/pieces/youtube/src/lib/triggers/new-video.trigger.ts
packages/ui/core/src/app/app.component.html
packages/ui/core/src/app/app.component.ts

fix: youtube trigger & upgrade banner

---

packages/pieces/google-calendar/package.json
packages/pieces/google-calendar/src/index.ts
packages/pieces/google-calendar/src/lib/common/helper.ts
packages/pieces/google-calendar/src/lib/common/types.ts
packages/pieces/google-calendar/src/lib/triggers/calendar-event.ts

Change Calendar Event trigger from webhook to polling
Fixes #3218

fix(google-calendar): calendar event to polling trigger

---

packages/pieces/notion/package.json
packages/pieces/notion/src/index.ts
packages/pieces/notion/src/lib/action/append-to-page.ts
packages/pieces/notion/src/lib/action/create-database-item.ts
packages/pieces/notion/src/lib/action/create-page.ts
packages/pieces/notion/src/lib/common/index.ts
packages/pieces/notion/src/lib/triggers/updated-database-item.ts

**Actions**
1. Create page
2. Append to page
**Triggers**
1. Updated database item
Closes #3220

feat(notion): create page / append to page / updated database item trigger

---

packages/backend/src/app/database/migration/postgres/1700406308445-AddPlatformDefaultLanguage.ts
packages/backend/src/app/database/postgres-connection.ts
packages/backend/src/app/ee/platform/platform.entity.ts
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/test/integration/cloud/platform/admin-platform.test.ts
packages/backend/test/integration/cloud/platform/platform.test.ts
packages/ee/shared/src/lib/platform/platform.model.ts
packages/ee/shared/src/lib/platform/platform.request.ts
packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.html
packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
packages/ui/common/src/index.ts
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/environments/environment.prod.ts
packages/ui/common/src/lib/environments/environment.ts
packages/ui/common/src/lib/service/locales.service.ts
packages/ui/common/src/lib/utils/locales.ts
packages/ui/core/src/app/app.component.html
packages/ui/core/src/app/app.component.ts

Adds platform default language for admins to choose and redirects users to correct language on login.

feat: default language for platform

---

packages/backend/src/app/database/migration/postgres/1700406308445-AddPlatformDefaultLanguage.ts

fix: language migration

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/firebase-auth/firebase-authentication.controller.ts
packages/backend/src/app/user/user-service.ts

fix: use existing account in firebase sign up

---

packages/pieces/google-calendar/package.json
packages/pieces/google-calendar/src/index.ts
packages/pieces/google-calendar/src/lib/actions/get-events.ts

Added action to get all events from a member calendar.
Params:
- calendar_id (or member email)
- event_types (Default, Out Of Office, Focus Time, Working Location)
- start_date (date from)
- end_date (date to)

feat(google-calendar): get all events action

---

.github/workflows/build-cloud-image.yml
packages/ui/core/project.json

fix: add nl language

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/ee/oauth-apps/oauth-app.module.ts
packages/backend/test/integration/cloud/oauth-app/oauth-app.test.ts
packages/ee/ui-platform/src/lib/components/smtp-settings/smtp-settings.component.ts
packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.ts
packages/ui/common/src/lib/utils/locales.ts

fix: list oauth2 apps

---

packages/backend/src/app/ee/projects/enterprise-project-controller.ts
packages/backend/src/app/project/project-service.ts
packages/backend/test/integration/cloud/project/project.test.ts
packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
packages/shared/src/lib/common/activepieces-error.ts

fix: fixed editing platform and projects names

---

packages/backend/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
packages/backend/src/app/ee/authentication/federated-authn/authn-provider/google-authn-provider.ts

The following environment variable shouldn't be required for community edition.

chore(federated-login): make environment variable optional

---

packages/ee/billing/ui/src/lib/billing-sidenav-item/billing-sidenav-item.component.html
packages/ee/billing/ui/src/lib/billing-sidenav-item/billing-sidenav-item.component.ts
packages/ee/billing/ui/src/lib/plans-page/plans-page.component.ts
packages/ee/billing/ui/src/lib/tasks-progress/tasks-progress.component.ts
packages/ee/billing/ui/src/lib/upgrade-dialog/upgrade-dialog.component.html
packages/ee/billing/ui/src/lib/upgrade-dialog/upgrade-dialog.component.ts
packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
packages/ee/shared/src/lib/billing/constants.ts
packages/shared/src/lib/common/telemetry.ts
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.html
packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts

1) Fixes issues with upgrade-note dialog #2909 
2) Added note about extra tasks pricing for Platform plan.

fix: billing ui fixes

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/helper/engine-helper.ts

fix: code await 

---

packages/backend/src/app/authentication/authentication-service/index.ts
packages/backend/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
packages/backend/src/app/ee/otp/otp-service.ts
packages/backend/src/app/helper/error-handler.ts
packages/backend/test/integration/ce/authentication/authentication.test.ts
packages/backend/test/integration/cloud/authn/cloud-authn.test.ts
packages/backend/test/integration/cloud/authn/enterprise-local-authn.test.ts
packages/shared/package.json
packages/shared/src/lib/common/activepieces-error.ts
packages/ui/common/src/lib/service/authentication.service.ts
packages/ui/feature-authentication/src/lib/pages/auth-actions/verify-email-post-sign-up/verify-email-post-sign-up.component.html
packages/ui/feature-authentication/src/lib/pages/auth-actions/verify-email-post-sign-up/verify-email-post-sign-up.component.ts
packages/ui/feature-authentication/src/lib/pages/sign-in/sign-in.component.html
packages/ui/feature-authentication/src/lib/pages/sign-in/sign-in.component.ts
packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.html
packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.ts

1) Resends email verification for sign ins.
2) Handles sign ups only via invitations.
3) Handles failing/expired verifications.

feat: resend verification email on sign in

---

packages/ee/components/src/lib/third-party-auth/third-party-auth.component.html
packages/ee/components/src/lib/third-party-auth/third-party-auth.component.ts
packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.html
packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.ts

chore: add third party sign ups

---

package-lock.json
package.json
packages/backend/src/app/app.ts

feat: add blank favicon

---

packages/backend/src/app/authentication/authentication-service/index.ts
packages/backend/src/app/ee/billing/project-plan/project-plan.service.ts
packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
packages/backend/src/app/ee/platform/lib/platform-utils.ts
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/src/app/flags/flag.module.ts
packages/backend/src/app/flags/flags.hooks.ts

fix: change default platform id for ee edition

---

packages/ee/shared/src/lib/platform/platform.model.ts
packages/ui/common/src/lib/utils/locales.ts
packages/ui/core/nginx.cloud.conf
packages/ui/core/nginx.standard.conf
packages/ui/core/project.json

feat: add spanish language

---

packages/backend/src/app/ee/otp/otp-controller.ts
packages/backend/test/integration/cloud/otp/otp.test.ts

chore: make otp controller return no content

---

docker-compose.yml
docs/about/changelog.mdx
package-lock.json
package.json
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/test/integration/cloud/platform/admin-platform.test.ts

chore: bump release version 0.14.1

---

.github/workflows/build-cloud-image.yml
packages/ui/common/src/lib/store/project/project.effects.ts

fix: use own credentials

---

.github/workflows/build-cloud-image.yml
docker-compose.yml
package-lock.json
package.json

feat: release 0.14.2

---

packages/pieces/mixpanel/.eslintrc.json
packages/pieces/mixpanel/README.md
packages/pieces/mixpanel/package.json
packages/pieces/mixpanel/project.json
packages/pieces/mixpanel/src/index.ts
packages/pieces/mixpanel/src/lib/actions/track-event.ts
packages/pieces/mixpanel/tsconfig.json
packages/pieces/mixpanel/tsconfig.lib.json
tsconfig.base.json

It add a Mixpanel piece, with the action to track events.
It is similar to the one from Zapier
Fixes #3289 

feat(mixpanel): track event action

---

packages/ui/core/src/app/app.component.html
packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.ts

fix: floating labels

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/authentication/authorization.ts
packages/backend/src/app/ee/billing/billing/billing.module.ts
packages/backend/src/app/ee/billing/billing/stripe-helper.ts
packages/backend/src/app/ee/billing/project-plan/project-plan.service.ts
packages/backend/src/app/flows/flow/flow.controller.ts
packages/ee/billing/ui/src/lib/plans-page/automation-plan-card.component/automation-plan-card.component.ts
packages/ee/shared/src/lib/billing/constants.ts

fix: stripe billing

---

.github/workflows/build-cloud-image.yml
packages/ui/core/src/index.html

fix: cloud popup window.opener

---

.github/workflows/build-cloud-image.yml
packages/ui/core/src/index.html
packages/ui/feature-connections/src/lib/services/oauth2.service.ts

fix: auth popup not closing

---

docs/developers/development-setup/codespaces.mdx

fix npm run 
npm run backend doesn't work. Changed for npm run serve:backend, same for frontend

docs: update codespace 

---

packages/pieces/wordpress/package.json
packages/pieces/wordpress/src/index.ts
packages/pieces/wordpress/src/lib/actions/get-post.action.ts

Adds a new action for the Wordpress Piece: get a post details given its Id.

feat(wordpress): get post details action

---

packages/pieces/certopus/package.json
packages/pieces/certopus/src/lib/actions/create-credential.ts

fix: dynamic fields not working in certopus piece

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/database/migration/postgres/1701794452891-AddEmbeddingFeatureToPlatform.ts
packages/backend/src/app/database/postgres-connection.ts
packages/backend/src/app/ee/api-keys/api-key-service.ts
packages/backend/src/app/ee/platform/platform.entity.ts
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/test/helpers/mocks/index.ts
packages/backend/test/integration/cloud/api-key/api-key.test.ts
packages/backend/test/integration/cloud/platform/admin-platform.test.ts
packages/backend/test/integration/cloud/platform/platform.test.ts
packages/ee/shared/src/lib/platform/platform.model.ts
packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html
packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts

feat: add platform limit

---

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts
packages/backend/src/app/database/migration/postgres/1701807681821-AddPlatformIdToFile.ts
packages/backend/src/app/database/migration/sqlite/1701808264444-AddPlatformIdToFileSqlite.ts
packages/backend/src/app/database/postgres-connection.ts
packages/backend/src/app/database/sqlite-connection.ts
packages/backend/src/app/ee/pieces/piece-service/cloud-piece-service-hooks.ts
packages/backend/src/app/ee/pieces/platform-piece-module.ts
packages/backend/src/app/file/file.entity.ts
packages/backend/src/app/file/file.service.ts
packages/backend/src/app/flows/common/piece-manager/piece-manager.ts
packages/backend/src/app/flows/common/piece-manager/registry-piece-manager.ts
packages/backend/src/app/flows/step-run/step-run-service.ts
packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/pieces/base-piece-module.ts
packages/backend/src/app/pieces/piece-metadata-entity.ts
packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
packages/backend/src/app/pieces/piece-service/index.ts
packages/backend/src/app/pieces/piece-service/piece-service-hooks.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/backend/src/app/workers/sandbox/cache/cached-sandbox.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-provisioner.ts
packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html
packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
packages/shared/package.json
packages/shared/src/lib/engine/engine-operation.ts
packages/shared/src/lib/file/file.ts
packages/shared/src/lib/pieces/piece.ts
packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts

fix: install piece in platform level

---

packages/backend/src/app/database/migration/postgres/1701261357197-migrate-ee-users-to-oldest-platform.ts
packages/backend/src/app/ee/projects/platform-project-controller.ts

fix: migrate to oldest ee platform

---

packages/backend/src/app/flows/common/piece-manager/index.ts
packages/backend/src/app/workers/sandbox/file-sandbox.ts
packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
packages/engine/src/lib/helper/piece-helper.ts

fix: execute file pieces in prod mode

---

packages/backend/src/app/app.ts
packages/backend/src/app/ee/billing/limits/members-limit.ts
packages/backend/src/app/ee/billing/limits/tasks-limit.ts
packages/backend/src/app/ee/flow-run/cloud-flow-run-hooks.ts
packages/backend/src/app/ee/flow-worker/cloud-flow-worker-hooks.ts
packages/backend/src/app/flows/flow-run/flow-run-service.ts
packages/backend/src/app/webhooks/webhook-controller.ts

fix: daily limit tasks

---

packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.html

Piece step test wasn't showing status this fixes it.

fix: display test step status

---

packages/backend/src/app/flows/flow-run/flow-run-service.ts

fix: calculation task limit

---

packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.ts

Send referring user id with sign up request

fix: send referring user id with sign up request

---

.github/workflows/release-rc.yml
package.json

chore: release 0.15.0-rc.2 version

---

.github/workflows/release-rc.yml

release: 0.15.0-rc2

---

.github/release.yml
.github/workflows/release-rc.yml

chore: edit changelog template

---

packages/ui/core/src/locale/messages.de.xlf
packages/ui/core/src/locale/messages.es.xlf
packages/ui/core/src/locale/messages.fr.xlf
packages/ui/core/src/locale/messages.it.xlf
packages/ui/core/src/locale/messages.nl.xlf
packages/ui/core/src/locale/messages.pt.xlf
packages/ui/core/src/locale/messages.vi.xlf
packages/ui/core/src/locale/messages.xlf
packages/ui/core/src/locale/messages.zh.xlf

New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)

feat(i18n): increase coverage in Japanese / Spanish / dutch languages

---

packages/ui/feature-chatbot/src/lib/chatbots-table/chatbots-table.component.html

Adds deprecation warning to chatbots table above title.

chore: add deprecation note to chatbots

---

packages/backend/src/app/authentication/authorization-middleware.ts
packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts

Switching projects wasn't working, this fixes that.

fix: switching projects

---

packages/backend/src/app/authentication/authorization-middleware.ts
packages/backend/src/app/ee/api-keys/api-key-service.ts
packages/backend/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts
packages/backend/src/app/ee/authentication/ee-authorization.ts
packages/backend/src/app/ee/managed-authn/managed-authn-service.ts
packages/backend/src/app/ee/oauth-apps/oauth-app.service.ts
packages/backend/src/app/ee/project-members/project-member.service.ts
packages/backend/src/app/ee/projects/platform-user-project-controller.ts
packages/backend/src/app/ee/signing-key/signing-key-service.ts
packages/backend/test/integration/cloud/api-key/api-key.test.ts
packages/backend/test/integration/cloud/custom-domain/custom-domain.test.ts
packages/backend/test/integration/cloud/oauth-app/oauth-app.test.ts
packages/backend/test/integration/cloud/piece-metadata/piece-metadata.test.ts
packages/backend/test/integration/cloud/platform/platform.test.ts
packages/backend/test/integration/cloud/project-members/project-members.test.ts
packages/backend/test/integration/cloud/project/project.test.ts
packages/backend/test/integration/cloud/signing-key/signing-key.test.ts
packages/shared/package.json
packages/shared/src/lib/authentication/model/principal-type.ts
packages/shared/src/lib/authentication/model/principal.ts

refactor: platform owner should check jwt role

---

packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html
packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.datasource.ts
packages/ui/common/src/lib/service/authentication.service.ts
packages/ui/common/src/lib/service/flag.service.ts

Platform admins can choose whether they want to use our own OAuth2 apps or not, when a piece OAuth2 app isn't provided.

feat: allow platform admins to choose between using our oauth2 apps or not

---

.github/workflows/release-changelog.yml
package.json

feat: release 0.15.0-rc.3

---

package.json

chore: bump version 

---

packages/ui/feature-chatbot/src/lib/chatbots-table/chatbots-table.component.html

fix: correct date for chatbots deprecation

---

packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html

fix: better explanation for the Activepieces' OAuth2 apps toggle in platform pieces table

---

packages/backend/src/app/helper/secret-helper.ts
packages/backend/src/app/helper/system/system-prop.ts

refactor: move app webhooks secrets to environent variable

---

packages/engine/package.json
packages/engine/src/lib/helper/logging-utils.ts

Fixed an issue that causes flows to fail with trigger payload is too large
Fixes #3335

fix: trigger not being trimmed when payload too large causing internal error

---

packages/ui/core/src/locale/messages.ja.xlf
packages/ui/core/src/locale/messages.nl.xlf
packages/ui/core/src/locale/messages.zh.xlf

New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)

feat(languages): Increased coverage - Japanese 100%, Dutch 100%, Simplified Chinese 18%

---

package.json

chore: bump to 0.15.0-rc.5

---

packages/backend/src/app/ee/helper/platform-domain-helper.ts
packages/backend/src/app/flows/step-file/step-file.service.ts
packages/backend/src/app/helper/domain-helper.ts
packages/engine/src/lib/helper/logging-utils.ts
packages/shared/package.json
packages/shared/src/lib/flow-run/execution/execution-state.ts

feat: release 015.0-rc.5

---

packages/engine/src/lib/helper/logging-utils.ts

fix: engine lint issue

---

packages/backend/src/app/ee/helper/platform-domain-helper.ts

fix: await api domain

---

README.md

Correct the word "Activepiece" to "Activepieces."

docs: correct a word

---

packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html

fix: show delete flow within builder in flow actions list and hide the list when showing runs

---

packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.html

corrects aspect ratio for home button to be 1:1

fix: corrects aspect ratio for home button to be 1:1

---

tools/scripts/generate-new-piece.ts
tools/scripts/utils/files.ts

Remove package.json lint from new piece project.json

fix: remove package.json lint from new piece project.json

---

packages/backend/src/app/flows/flow-run/flow-response-watcher.ts
packages/backend/src/app/helper/pubsub/memory-pubsub.ts
packages/backend/src/app/helper/pubsub/redis-pubsub.ts

fix: sync webhook works with redis pubsub

---

packages/pieces/google-gemini/.eslintrc.json
packages/pieces/google-gemini/README.md
packages/pieces/google-gemini/package.json
packages/pieces/google-gemini/project.json
packages/pieces/google-gemini/src/index.ts
packages/pieces/google-gemini/src/lib/actions/generate-content-from-image.action.ts
packages/pieces/google-gemini/src/lib/actions/generate-content.action.ts
packages/pieces/google-gemini/tsconfig.json
packages/pieces/google-gemini/tsconfig.lib.json
tsconfig.base.json

This adds a new piece to AP. It's using the new API from google to access Gemini Pro and Gemini Pro Vision. I'll be adding a chat feature soon, but for now, users can ask a "one-time question".

feat(google-gemini): generate content from image /  generate content action

---

packages/pieces/jira-cloud/.eslintrc.json
packages/pieces/jira-cloud/README.md
packages/pieces/jira-cloud/package.json
packages/pieces/jira-cloud/project.json
packages/pieces/jira-cloud/src/auth.ts
packages/pieces/jira-cloud/src/index.ts
packages/pieces/jira-cloud/src/lib/actions/create-issue.ts
packages/pieces/jira-cloud/src/lib/actions/search-issues.ts
packages/pieces/jira-cloud/src/lib/common/index.ts
packages/pieces/jira-cloud/src/lib/common/props.ts
packages/pieces/jira-cloud/src/lib/triggers/new-issue.ts
packages/pieces/jira-cloud/src/lib/triggers/updated-issue.ts
packages/pieces/jira-cloud/tsconfig.json
packages/pieces/jira-cloud/tsconfig.lib.json
packages/ui/feature-builder-form-controls/package.json
packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
tsconfig.base.json

- Fixed an issue with checkboxes not applying default value in frontend
**Actions**
1. Create Issue
2. Search Issues
**Triggers**
1. New Issue
2. Updated Issue
Fixes #608 

feat(jira-cloud): create issue and search issues actions / new issue and updated issue triggers

---

packages/pieces/imap/package.json
packages/pieces/imap/src/lib/triggers/new-email.ts

Added an option in the mailboxes dropdown to use all mailboxes for gmail users

feat(imap): add all mailboxes option for gmail users

---

packages/pieces/google-gemini/package.json
packages/pieces/google-gemini/src/index.ts
packages/pieces/google-gemini/src/lib/actions/chat-gemini.action.ts

this adds the capability to create a chat with Google Gemini Pro. For now the only model that works is gemini-pro (according to google)

feat(google-gemini): add chat action

---

packages/pieces/slack/package.json
packages/pieces/slack/src/index.ts
packages/pieces/slack/src/lib/actions/send-message-action.ts
packages/pieces/slack/src/lib/common/utils.ts

Added a new field to send message to channel action that allows user to send attachments

feat(slack): added attachment field to send message action

---

packages/pieces/kizeo-forms/package.json
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-deleted.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-finished.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-pushed.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-received.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data-updated.ts
packages/pieces/kizeo-forms/src/lib/trigger/event-on-data.trigger.ts

Added an output format property to triggers, allowing to choose between easy-to-read and more complex output.

feat(kizeo-forms): adds output format property to triggers

---

packages/ee/shared/src/lib/platform/platform.model.ts
packages/ui/common/src/lib/utils/locales.ts
packages/ui/core/nginx.standard.conf
packages/ui/core/project.json
packages/ui/core/src/locale/messages.de.xlf
packages/ui/core/src/locale/messages.es.xlf
packages/ui/core/src/locale/messages.fr.xlf
packages/ui/core/src/locale/messages.hu.xlf
packages/ui/core/src/locale/messages.id.xlf
packages/ui/core/src/locale/messages.it.xlf
packages/ui/core/src/locale/messages.ja.xlf
packages/ui/core/src/locale/messages.nl.xlf
packages/ui/core/src/locale/messages.pt.xlf
packages/ui/core/src/locale/messages.vi.xlf

feat: add new languages Indonesian, Vietnamese,  Chinese, and Portuguese

---

packages/backend/src/app/file/file.service.ts
packages/backend/src/app/flows/common/piece-manager/registry-piece-manager.ts

fix: install piece in platform level is fixed

---

package.json

feat: release 0.15.0-rc.6

---

packages/pieces/clickup/package.json
packages/pieces/clickup/src/index.ts
packages/pieces/dropbox/package.json
packages/pieces/dropbox/src/index.ts
packages/pieces/github/package.json
packages/pieces/github/src/index.ts
packages/pieces/gitlab/package.json
packages/pieces/gitlab/src/index.ts
packages/pieces/gravityforms/package.json
packages/pieces/gravityforms/src/index.ts
packages/pieces/llmrails/package.json
packages/pieces/llmrails/src/index.ts
packages/pieces/monday/package.json
packages/pieces/monday/src/index.ts
packages/pieces/moxie-crm/package.json
packages/pieces/moxie-crm/src/index.ts
packages/pieces/ntfy/package.json
packages/pieces/ntfy/src/index.ts
packages/pieces/sendfox/package.json
packages/pieces/sendfox/src/index.ts
packages/pieces/square/package.json
packages/pieces/square/src/index.ts
packages/pieces/telegram-bot/package.json
packages/pieces/telegram-bot/src/index.ts
packages/pieces/tidycal/package.json
packages/pieces/tidycal/src/index.ts

chore: update piece names to match brands

---

packages/pieces/stripe/package.json
packages/pieces/stripe/src/index.ts
packages/pieces/stripe/src/lib/actions/retrieve-customer.ts

Add action retrieve customer on stripe piece

feat(stripe): retrieve customer action

---

packages/pieces/activepieces/.eslintrc.json
packages/pieces/activepieces/README.md
packages/pieces/activepieces/package.json
packages/pieces/activepieces/project.json
packages/pieces/activepieces/src/index.ts
packages/pieces/activepieces/src/lib/actions/create-project-member.ts
packages/pieces/activepieces/src/lib/actions/create-project.ts
packages/pieces/activepieces/src/lib/actions/delete-project-member.ts
packages/pieces/activepieces/src/lib/actions/list-project-member.ts
packages/pieces/activepieces/src/lib/actions/list-project.ts
packages/pieces/activepieces/src/lib/actions/update-project.ts
packages/pieces/activepieces/tsconfig.json
packages/pieces/activepieces/tsconfig.lib.json
tsconfig.base.json

fix: lint issues in activepieces platform piece

---

packages/pieces/activepieces/.eslintrc.json
packages/pieces/activepieces/README.md
packages/pieces/activepieces/package.json
packages/pieces/activepieces/project.json
packages/pieces/activepieces/src/index.ts
packages/pieces/activepieces/src/lib/actions/create-project-member.ts
packages/pieces/activepieces/src/lib/actions/create-project.ts
packages/pieces/activepieces/src/lib/actions/delete-project-member.ts
packages/pieces/activepieces/src/lib/actions/list-project-member.ts
packages/pieces/activepieces/src/lib/actions/list-project.ts
packages/pieces/activepieces/src/lib/actions/update-project.ts
packages/pieces/activepieces/tsconfig.json
packages/pieces/activepieces/tsconfig.lib.json
tsconfig.base.json

feat(activepieces): project members action / project actions for platform edition

---

packages/pieces/slack/package.json
packages/pieces/slack/src/index.ts

fix(slack): attachment scopes

---

packages/pieces/activepieces/package.json
packages/pieces/activepieces/src/lib/actions/list-project-member.ts

Fix method of action list project members (get instead of post)

fix(activepieces): list project members

---

package.json

feat: release 0.15.0-rc.7

---

packages/pieces/text-helper/package.json
packages/pieces/text-helper/src/lib/actions/replace.ts

fix(text-helper): replace all instances of found text, and make (replace) input optional

---

packages/pieces/text-helper/package.json
packages/pieces/text-helper/src/lib/actions/replace.ts

fix: replace text action throws unexpected error

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/index.ts
packages/pieces/twitter/src/lib/actions/create-tweet.ts

Adds two extra inputs to upload media and improved instructions for authentication
closes #3475

feat(Twitter): added two extra inputs to upload media and improved instructions for authentication

---

packages/pieces/line/.eslintrc.json
packages/pieces/line/README.md
packages/pieces/line/package.json
packages/pieces/line/project.json
packages/pieces/line/src/index.ts
packages/pieces/line/src/lib/actions/push-message.ts
packages/pieces/line/src/lib/trigger/new-message.ts
packages/pieces/line/tsconfig.json
packages/pieces/line/tsconfig.lib.json
tsconfig.base.json

feat(line): send message action / new message trigger

---

packages/engine/src/lib/handler/context/engine-constants-data.ts
packages/engine/src/lib/handler/piece-executor.ts
packages/engine/src/main.ts
packages/engine/test/handler/test-helper.ts

fix: show url when testing step instead of local path

---

package.json

feat: release 0.15.0-rc.8

---

packages/pieces/google-gemini/package.json
packages/pieces/google-gemini/src/index.ts

Improves the Gemini connection validation message.

fix: improve error message for connection validation for Gemini

---

packages/pieces/stability-ai/package.json
packages/pieces/stability-ai/src/index.ts

Stability AI instruction for acquiring the API key wasn't clear, now it is better.

chore: improve authentication instructions for stability Ai

---

.vscode/settings.json
package-lock.json
package.json
packages/engine/webpack.config.js

chore: minimize engine size from 1.2mb to 500kb

---

packages/pieces/twitter/package.json
packages/pieces/twitter/src/lib/actions/create-tweet.ts

Improve error messages shown for tweeting

fix(twitter): improve error messages shown when a tweet fails

---

packages/backend/src/app/database/migration/1703713027818-UpdateStatusInUserSqlite.ts
packages/backend/src/app/database/sqlite-connection.ts

fix: update sqlite3 migration for user

---

.github/workflows/build-cloud-image.yml
docker-compose.yml
package-lock.json
package.json

feat: stable release 0.15.0

---

.gitignore
.vscode/settings.json
packages/pieces/beamer/.eslintrc.json
packages/pieces/beamer/README.md
packages/pieces/beamer/package.json
packages/pieces/beamer/project.json
packages/pieces/beamer/src/index.ts
packages/pieces/beamer/src/lib/actions/create-comment.ts
packages/pieces/beamer/src/lib/actions/create-feature-request.ts
packages/pieces/beamer/src/lib/actions/create-posts.ts
packages/pieces/beamer/src/lib/actions/create-vote.ts
packages/pieces/beamer/src/lib/common/index.ts
packages/pieces/beamer/src/lib/trigger/new-post.ts
packages/pieces/beamer/tsconfig.json
packages/pieces/beamer/tsconfig.lib.json
tsconfig.base.json

feat(beamer): add changelog and notification center tool

---

packages/backend/src/assets/emails/invitation-email.html
packages/backend/src/assets/emails/reset-password.html
packages/backend/src/assets/emails/verify-email.html

fix: add raw link to emails incase button didn't work

---

packages/pieces/airtable/package.json
packages/pieces/airtable/src/index.ts
packages/pieces/airtable/src/lib/actions/find-record.ts
packages/pieces/airtable/src/lib/common/index.ts
packages/pieces/airtable/src/lib/trigger/update-record.trigger.ts

Fixes #3471 and add updated record trigger.

feat(airtable): fix find record bug / updated record trigger

---

.github/workflows/build-cloud-image.yml
package.json

chore: release 0.16.0-rc.1

---

.github/workflows/pre-release-changelog.yml
.github/workflows/release-rc.yml

fix: release rc action

---

.github/workflows/build-cloud-image.yml

feat: release 0.16.0-rc.1

---

packages/pieces/google-docs/package.json
packages/pieces/google-docs/src/index.ts
packages/pieces/google-docs/src/lib/actions/create-document-based-on-template.action.ts

This adds the capability of creating a google document using a template and variables. 

feat(google-docs): create document using template

---

packages/pieces/text-helper/package.json
packages/pieces/text-helper/src/index.ts
packages/pieces/text-helper/src/lib/actions/replace.ts

Adds option to replace only first match and also corrects the piece version in package.json.

feat(text-helper): added option to replace only first match for (replace action)

---

packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
packages/backend/src/app/ee/helper/license-validator/index.ts
packages/backend/src/app/ee/helper/license-validator/license-validator.ts
packages/backend/src/app/ee/helper/license-validator/network-license-validator.ts
packages/backend/src/app/ee/helper/license-validator/no-op-license-validator.ts
packages/backend/src/app/ee/platform/platform.service.ts
packages/backend/src/main.ts

chore: enforce license limits

---

package.json

chore: bump rc version

---

packages/pieces/ntfy/package.json
packages/pieces/ntfy/src/lib/actions/send-notification.ts

fix(ntfy): support unicode api header

---

.github/workflows/release-rc.yml
.github/workflows/release.yml

fix: build docker image for raspberry pi arm v7/v8

---

packages/ui/common/src/lib/service/embedding.service.ts
packages/ui/core/src/assets/img/custom/dashboard/dashboard.svg
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts

fix: navigation icon from the builder

---

packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts

fix: automatically refresh runs table when there is a run still being executed

---

package.json

feat: release rc 3

---

packages/ui/feature-builder-header/src/index.ts

fix: export version history component

---

.github/workflows/build-cloud-image.yml
packages/backend/src/app/flows/flow-version/flow-version.service.ts
packages/backend/src/app/workers/flow-worker/flow-worker.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/demo-flow-template.ts

fix: auth property were not validated 

---

packages/backend/src/app/helper/engine-helper.ts
packages/backend/src/app/workers/sandbox/provisioner/sandbox-cache-key.ts

fix: code sandbox should include step name

---

packages/backend/src/app/core/security/authn/global-api-key-authn-handler.ts

fix: global api key should be optional

---

packages/ee/shared/src/lib/platform/platform.model.ts
packages/ee/shared/src/lib/platform/platform.request.ts
packages/shared/package.json
packages/shared/src/lib/common/index.ts
packages/shared/src/lib/common/locale.ts
packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
packages/ui/common/src/lib/service/locales.service.ts
packages/ui/common/src/lib/utils/locales.ts
packages/ui/core/project.json
packages/ui/core/src/locale/messages.bg.xlf
packages/ui/core/src/locale/messages.de.xlf
packages/ui/core/src/locale/messages.es.xlf
packages/ui/core/src/locale/messages.fr.xlf
packages/ui/core/src/locale/messages.hi.xlf
packages/ui/core/src/locale/messages.hu.xlf
packages/ui/core/src/locale/messages.id.xlf
packages/ui/core/src/locale/messages.ja.xlf
packages/ui/core/src/locale/messages.nl.xlf
packages/ui/core/src/locale/messages.pt.xlf
packages/ui/core/src/locale/messages.vi.xlf
packages/ui/core/src/locale/messages.zh.xlf

feat: add hungarian language

---

packages/backend/src/app/flows/flow/flow-service-hooks.ts
packages/backend/src/app/flows/flow/flow.service.ts

fix(flow): flow becomes empty on trigger hook failure

---

packages/pieces/apitable/package.json
packages/pieces/apitable/src/index.ts
packages/pieces/approval/package.json
packages/pieces/approval/src/lib/actions/wait-for-approval.ts

fix(approval): test step sample data

---

packages/pieces/schedule/package.json
packages/pieces/schedule/src/lib/triggers/every-x-minutes.trigger.ts

fix(schedule): add static dropdown for minutes selection to ensure valid values

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/index.ts
packages/pieces/google-drive/src/lib/action/export-document-as-pdf.action.ts
packages/pieces/google-drive/src/lib/action/save-file-as-pdf.action.ts

This adds a new action for the Google Drive piece for converting a file to PDF, and getting the new ID

feat(google-drive): export as pdf action

---

packages/engine/src/lib/services/files.service.ts

chore: display human readable error when the file is large

---

docs/endpoints/flows/create.mdx
docs/endpoints/flows/delete.mdx
docs/endpoints/flows/get.mdx
docs/mint.json
docs/openapi.json
packages/backend/src/app/ee/managed-authn/managed-authn-service.ts
packages/backend/src/app/flows/flow/flow.controller.ts
packages/backend/test/integration/ce/flows/flow.test.ts
packages/shared/package.json
packages/shared/src/lib/flows/dto/create-flow-request.ts
packages/shared/src/lib/flows/dto/list-flows-request.ts
packages/ui/common/src/lib/service/flow.service.ts
packages/ui/core/src/app/modules/import-flow-uri-encoded/import-flow-uri-encoded.resolver.ts
packages/ui/core/src/app/modules/import-flow/import-flow.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
packages/ui/feature-dashboard/src/lib/resolvers/are-there-flows.resolver.ts

feat: add flow api documentation

---

packages/pieces/brilliant-directories/package.json
packages/pieces/brilliant-directories/src/lib/actions/create-new-user.ts
packages/pieces/framework/package.json
packages/pieces/framework/src/lib/processors/processors.ts
packages/pieces/framework/src/lib/property/property.ts

The field "meta" is not being sent properly and needs to be converted to a JSON object. Currently, it's being parsed as string.

chore: parse string as JSON object

---

packages/pieces/instagram-business/package.json
packages/pieces/instagram-business/src/lib/common/index.ts

chore(instagram): update instagram scopes 

---

docs/developers/building-pieces/create-action.mdx

I have added the necessary dependency in the document and have created the PR as per the issue. The code look like this now and is working fine. Also resolved the linting issue.
```typescript
import { createAction, Property, PieceAuth } from "@activepieces/pieces-framework";
import { httpClient, HttpMethod } from "@activepieces/pieces-common";
export const fetchTopStories = createAction({
name: 'fetch_top_stories', // Must be a unique across the piece, this shouldn't be changed.
auth: PieceAuth.None(),
displayName:'Fetch Top Stories',
description: 'Fetch top stories from hackernews',
props: {
// Properties to ask from the user, in this ask we will take number of
number_of_stories: Property.Number({
displayName: 'Number of Stories',
description: undefined,
required: true,
})
},
async …
```

docs: add dependency in create action tutorial

---

packages/pieces/airtable/package.json
packages/pieces/airtable/src/index.ts

fix(airtable): fix auth error message

---

package.json

chore: release 0.17.0-rc

---

docs/openapi.json
packages/backend/src/app/ee/projects/platform-project-controller.ts
packages/ee/shared/src/lib/project/project-requests.ts

fix: add external id to list projects / create project endpoint

---

packages/pieces/google-drive/package.json
packages/pieces/google-drive/src/lib/action/duplicate-file.action.ts

fix(google-drive): pass folder ID in duplicate file action

---

packages/pieces/shopify/package.json
packages/pieces/shopify/src/index.ts

fix(shopify): fix authentication issue

---

packages/pieces/clickup/package.json
packages/pieces/clickup/src/index.ts
packages/pieces/clickup/src/lib/actions/tasks/get-task.ts
packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts
packages/pieces/clickup/src/lib/common/index.ts
packages/pieces/clickup/src/lib/triggers/index.ts
packages/pieces/clickup/src/lib/triggers/register-trigger.ts
packages/pieces/clickup/src/lib/triggers/task-tag-updated.ts

On task tag update, there should be a trigger for the action.
adds TASK_TAG_UPDATED trigger

feat(clickup): Get Task Action / Get Tasks Action / Task Tag Updated Trigger

---

.github/workflows/build-cloud-image.yml
packages/shared/src/lib/common/telemetry.ts
packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.html
packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts

chore: add telemetry to co-pilot

---

packages/ui/common/src/lib/service/telemetry.service.ts
packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts

chore: added google sheets telemetry to code generating prompts

---

packages/backend/src/app/copilot/copilot.service.ts
packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts
packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts

feat: ai code writer now fills inputs

---

packages/backend/src/app/ee/git-repos/git-repo.controller.ts
packages/backend/src/app/flows/flow/flow.controller.ts
packages/backend/src/app/flows/flow/flow.service.ts
packages/backend/test/integration/ce/flows/flow.test.ts
packages/shared/package.json
packages/shared/src/index.ts
packages/shared/src/lib/flows/dto/update-flow-status-request.ts
packages/shared/src/lib/flows/flow-operations.ts
packages/ui/common/src/lib/service/flow.service.ts
packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts

chore: clean update flow endpoint

---

packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts

fix: StoreCodeInsideFlow1697969398200 migration

---

packages/pieces/robolly/package.json
packages/pieces/robolly/src/lib/actions/generate-image.action.ts

This adds dynamic fields to the Generate Image action from the Robolly piece. Also, I added a dropdown for selecting templates.

feat(robolly): add properties for custom modification 

---

packages/pieces/flowlu/package.json
packages/pieces/flowlu/src/lib/actions/accounts/update-contact.ts
packages/pieces/flowlu/src/lib/actions/opportunities/create-opportunity.ts
packages/pieces/flowlu/src/lib/actions/opportunities/update-opportunity.ts
packages/pieces/flowlu/src/lib/actions/tasks/create-task.ts
packages/pieces/flowlu/src/lib/actions/tasks/update-task.ts
packages/pieces/flowlu/src/lib/common/props.ts
packages/pieces/flowlu/src/lib/common/types.ts

fix(flowlu): make name/title field optional in update actions

---

docs/endpoints/flows/update.mdx
docs/mint.json
docs/openapi.json
packages/backend/src/app/flows/flow/flow.controller.ts
packages/shared/src/lib/flows/flow-operations.ts

docs: add update flow documentation

---

packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
packages/ee/ui-platform/src/lib/components/configure-confederated-authn-card/configure-confederated-authn-card.component.html
packages/ee/ui-platform/src/lib/components/dialogs/enable-federated-authn-provider-dialog/enable-federated-authn-provider-dialog.component.html
packages/ee/ui-platform/src/lib/components/dialogs/enable-federated-authn-provider-dialog/enable-federated-authn-provider-dialog.component.ts

fix: add instructions for google & github sso

---

packages/pieces/formbricks/.eslintrc.json
packages/pieces/formbricks/README.md
packages/pieces/formbricks/package.json
packages/pieces/formbricks/project.json
packages/pieces/formbricks/src/index.ts
packages/pieces/formbricks/src/lib/triggers/index.ts
packages/pieces/formbricks/src/lib/triggers/register.ts
packages/pieces/formbricks/tsconfig.json
packages/pieces/formbricks/tsconfig.lib.json
tsconfig.base.json

Formbricks is a new opensource form builder that is growing fast and has several interested users.

feat(formbricks): Response Created, Response Updated, Response Finished triggers

---

packages/pieces/facebook-pages/package.json
packages/pieces/facebook-pages/src/index.ts
packages/pieces/instagram-business/package.json
packages/pieces/instagram-business/src/lib/common/index.ts

fix(facebook): list pages
