activepieces/activepieces

package-lock.json, packages/shared/src/lib/flow-run/execution/step-output.ts, packages/ui/common/src/lib/components/json-view/json-view.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-connection/big-add-button/big-add-button.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.html, packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/iteration-accordion/iteration-accordion.component.html, packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.html, packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
closes [#1603](https://github.com/activepieces/activepieces/issues/1603)
=> fix: Show failed iteration in case the failed step is within a loop in runs/test

packages/pieces/clickup/package.json, packages/pieces/clickup/src/index.ts, packages/pieces/clickup/src/lib/actions/tasks/delete-task.ts, packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts, packages/pieces/clickup/src/lib/common/index.ts
=> feat(clickup): delete task action, get tasks with ability to filter by a space, a list or a workspace 

packages/pieces/google-drive/package.json, packages/pieces/google-drive/src/index.ts, packages/pieces/google-drive/src/lib/action/add-permission.action.ts, packages/pieces/google-drive/src/lib/action/delete-permission.action.ts
Added capabilities to Google drive piece:
- Add permission to user by email
- Remove permission from user by email
=> feat(google-drive): add permission action / remove permission action

package-lock.json, packages/backend/src/app/workers/sandbox/file-sandbox.ts
=> fix: sandbox error on windows

packages/ui/common/src/lib/service/instance-run.service.ts, packages/ui/common/src/lib/utils/tables.utils.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
=> feat: filter runs by flow

packages/backend/src/app/copilot/copilot.service.ts
=> fix(copilot): code writer should use import for packages

package.json
=> feat: release 0.18.0-rc.1

package-lock.json, packages/backend/src/app/database/migration/common/1696245170061-add-piece-type-and-package-type-to-flow-version.ts, packages/backend/src/app/database/migration/common/1696245170062-add-piece-type-and-package-type-to-flow-template.ts, packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts, packages/backend/src/app/database/migration/postgres/1674788714498-FlowAndFileProjectId.ts, packages/backend/src/app/database/migration/postgres/1676649852890-remove-store-action.ts, packages/backend/src/app/database/migration/postgres/1677521257188-add-version-to-piece-steps.ts, packages/backend/src/app/database/migration/postgres/1678928503715-bump-fix-piece-versions.ts, packages/backend/src/app/database/migration/postgres/1679014156667-migrate-schedule.ts, packages/backend/src/app/database/migration/postgres/1681107443963-AddInputUiInfo.ts, packages/backend/src/app/database/migration/postgres/1683898241599-ChangeVariableSyntax.ts, packages/backend/src/app/database/migration/postgres/1686138629812-unifyPieceName.ts
=> fix: database migration

packages/pieces/monday/package.json, packages/pieces/onfleet/package.json, packages/pieces/woocommerce/package.json
=> fix: monday & woocommerce & onfleet triggers

packages/pieces/clickup/package.json, packages/pieces/clickup/src/index.ts, packages/pieces/clickup/src/lib/actions/custom-fields/get-accessible-custom-fields.ts, packages/pieces/clickup/src/lib/actions/custom-fields/set-custom-fields-value.ts, packages/pieces/clickup/src/lib/common/index.ts
Adds ability to list and set custom values in lists and tasks
=> feat(clickup): set custom fields action / get custom fields action

packages/ee/components/src/lib/iframe-listener/iframe-listener.component.ts, packages/ee/embed-sdk/src/index.ts, packages/ui/common/src/lib/service/embedding.service.ts
=> fix(embed): prefix should be included in routing

packages/shared/src/lib/common/locale.ts, packages/ui/common/src/lib/utils/locales.ts, packages/ui/core/nginx.standard.conf, packages/ui/core/project.json, packages/ui/core/src/locale/messages.bg.xlf, packages/ui/core/src/locale/messages.de.xlf, packages/ui/core/src/locale/messages.es.xlf, packages/ui/core/src/locale/messages.fr.xlf, packages/ui/core/src/locale/messages.hi.xlf, packages/ui/core/src/locale/messages.hu.xlf, packages/ui/core/src/locale/messages.id.xlf, packages/ui/core/src/locale/messages.it.xlf, packages/ui/core/src/locale/messages.ja.xlf, packages/ui/core/src/locale/messages.ko.xlf, packages/ui/core/src/locale/messages.pl.xlf, packages/ui/core/src/locale/messages.pt.xlf, packages/ui/core/src/locale/messages.uk.xlf, packages/ui/core/src/locale/messages.vi.xlf, packages/ui/core/src/locale/messages.zh.xlf
=> feat: add Ukrainian and Bulgarian language / update other languages

docker-compose.yml, package-lock.json, package.json, packages/ui/core/src/locale/messages.pt.xlf
=> feat: release 0.18.0

docs/mint.json, packages/ee/ui-platform/src/lib/components/signing-keys-table/signing-keys-table.component.html, packages/ee/ui-platform/src/lib/components/signing-keys-table/signing-keys-table.component.ts, packages/ee/ui-platform/src/lib/components/signing-keys-table/signing-keys-table.datasource.ts, packages/ee/ui-platform/src/lib/components/smtp-settings/smtp-settings.component.ts, packages/ee/ui-platform/src/lib/components/sso-settings/sso-settings.component.ts, packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.ts, packages/ee/ui-platform/src/lib/lib.routes.ts, packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts, packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts, packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html, packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts, packages/ee/ui-platform/src/lib/platform.resolver.ts, packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.ts, packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.html
=> chore(platform): allow users to see a disabled signing keys table with locked icon if not enabled

packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
=> fix(engine): validate auth is no longer broken in sandboxed mode

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.18.1

packages/backend/src/app/database/migration/postgres/1705586178452-RemoveUniqueonAppNameAppCredentials.ts, packages/backend/src/app/database/postgres-connection.ts, packages/backend/src/app/ee/app-credentials/app-credentials.entity.ts, packages/backend/src/app/ee/app-credentials/app-credentials.service.ts, packages/ee/shared/src/lib/product-embed/app-credentials/app-credentials-requests.ts
=> fix: remove unique app name on app credentials

docs/developers/piece-reference/custom-api-calls.mdx, packages/pieces/common/package.json, packages/pieces/common/src/lib/helpers/index.ts, packages/pieces/openai/package.json, packages/pieces/openai/src/index.ts
Adds an arbitrary http request action that can be used in all pieces. Added to OpenAI piece as example.
Fixes #1977
=> feat: arbitrary http request action

packages/pieces/clickup/package.json, packages/pieces/clickup/src/index.ts, packages/pieces/clickup/src/lib/actions/custom-fields/set-custom-fields-value.ts, packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts, packages/pieces/clickup/src/lib/common/index.ts
Uses clickup API to filter for tasks.
=> feat(clickup): add filter tasks based on criteria 

.github/workflows/release-pieces.yml, .github/workflows/validate-publishable-packages.yml, packages/backend/src/app/ee/managed-authn/managed-authn-service.ts, packages/backend/src/app/ee/project-members/project-member.controller.ts, packages/backend/src/app/ee/project-members/project-member.service.ts, tools/scripts/utils/piece-script-utils.ts, tools/scripts/validate-publishable-packages.ts
=> fix: show projects of newly invited users

packages/backend/src/app/database/redis-connection.ts
=> fix: specify maxRetriesPerRequest to null

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/index.ts, packages/pieces/community/google-drive/src/lib/action/get-file-by-id.ts
Adds support for getting a file by its id, or check if file is available.
=> feat(google-drive): get file or folder by id  action

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/index.ts
=> fix: google drive

docs/developers/development-setup/local.mdx
Fixed a tiny typo in local development section in the docs in https://www.activepieces.com/docs/developers/development-setup/local#instructions
=> docs: fixed typo in local.mdx

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/common/models.ts
Fixes https://community.activepieces.com/t/airtable-update-action-not-passing-recordid-as-an-array/2730
=> fix(airtable): fix multilink field property type

packages/backend/src/app/pieces/base-piece-module.ts, packages/engine/src/lib/helper/piece-helper.ts, packages/engine/src/main.ts, packages/shared/package.json, packages/shared/src/lib/engine/engine-operation.ts, packages/shared/src/lib/pieces/dto/piece-requests.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
=> fix: resolve variables in dynamic props

docs/developers/piece-reference/custom-api-calls.mdx, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts, packages/pieces/community/discord/package.json, packages/pieces/community/discord/src/index.ts, packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/index.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added.ts, packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/index.ts, packages/pieces/community/lead-connector/package.json, packages/pieces/community/lead-connector/src/index.ts, packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/shopify/package.json, packages/pieces/community/shopify/src/index.ts, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
Added custom API call action for:
- Google Sheets
- Jira Cloud
- LeadConnector (GoHighLevel)
- OpenAI
- Shopify
- Slack
- Discord
=> feat: Add custom API calls for Google Sheets, Jira Cloud, LeadConnector, OpenAI, Shopify, Discord and Slack

packages/engine/src/lib/handler/context/engine-constants.ts, packages/engine/src/lib/helper/piece-helper.ts, packages/engine/src/main.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/context.ts
=> feat: add external id to execute property

packages/pieces/community/crypto/.eslintrc.json, packages/pieces/community/crypto/README.md, packages/pieces/community/crypto/package.json, packages/pieces/community/crypto/project.json, packages/pieces/community/crypto/src/index.ts, packages/pieces/community/crypto/src/lib/actions/generate-password.ts, packages/pieces/community/crypto/src/lib/actions/hash-text.ts, packages/pieces/community/crypto/tsconfig.json, packages/pieces/community/crypto/tsconfig.lib.json, tsconfig.base.json
=> feat(crypto): hash to text action / generate random password action

packages/backend/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/backend/src/app/ee/app-connections/platform-oauth2-service.ts, packages/backend/src/app/flows/common/piece-manager/local-piece-manager.ts, packages/backend/src/app/helper/engine-helper.ts, packages/backend/src/app/pieces/base-piece-module.ts, packages/backend/src/app/pieces/piece-metadata-service/index.ts, packages/backend/src/app/pieces/piece-metadata-service/piece-metadata-service.ts, packages/backend/src/app/workers/flow-worker/flow-worker.ts
=> fix: loading custom archive platform pieces 

packages/shared/package.json, packages/ui/common/src/lib/utils/consts.ts, packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.html, packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.ts, packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
=> chore: add code assistant inside full screen editor and improve user experience inside generate code dialog

packages/backend/src/app/workers/flow-worker/flow-worker.ts
=> fix: reattach trigger payload when retrying on latest version

packages/pieces/community/clickup/package.json, packages/pieces/community/clickup/src/index.ts
=> feat: add custom api call for clickup

packages/pieces/community/clickup/package.json, packages/pieces/community/clickup/src/index.ts
=> fix: bump clickup

package.json
=> feat: release 0.19.0-rc.1

packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html, packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
=> fix: show edit project button

package.json
=> chore: pre release 0.19.0-rc.2

package.json
=> feat: bump to 19 rc3

.github/workflows/build-cloud-image.yml
=> chore: tag cloud image with the commit hash

packages/ui/core/nginx.standard.conf, packages/ui/core/src/app/app.module.ts
=> fix: websockets relative url

packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
=> fix: notify on flow run fail toggle wasn't being turned back on

packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/add-npm-package-modal/add-npm-package-modal.component.html
=> chore: fix typo

packages/backend/src/app/authentication/authentication-service/index.ts, packages/ui/common/src/lib/service/authentication.service.ts, packages/ui/core/src/app/app.component.html, packages/ui/core/src/app/app.component.ts
=> fix: force logout for old tokens on cloud and newsletter

packages/engine/src/lib/handler/piece-executor.ts, packages/engine/test/handler/flow-error-handling.test.ts, packages/engine/test/handler/flow-piece.test.ts
=> fix: use test method in actions

.github/release-drafter.yml, package.json
=> chore: bump pre release version to 4

packages/backend/src/app/copilot/copilot.service.ts, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
=> feat: code writer now adds packages

packages/backend/src/app/flows/trigger/hooks/disable-trigger-hook.ts, packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
There are stale runs in the production happened for legacy reasons, Now the disable is called but it seems to fail which prevent the removing of this stale jobs from the queue.
=> fix: remove stale runs

docker-compose.yml, package-lock.json, package.json, packages/backend/src/app/ee/platform/lib/platform-utils.ts
=> chore: bump release to 0.19.0

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/openai/src/lib/actions/ask-assistant.ts, packages/pieces/community/openai/src/lib/actions/generate-image.ts, packages/pieces/community/openai/src/lib/actions/send-prompt.ts, packages/pieces/community/openai/src/lib/actions/text-to-speech.ts, packages/pieces/community/openai/src/lib/actions/transcriptions.ts, packages/pieces/community/openai/src/lib/actions/translation.ts, packages/pieces/community/openai/src/lib/actions/vision-prompt.ts
- Adds ability to change baseUrl through connection
- Added support for Azure OpenAI instances
Fixes #1855 #3207
=> feat(openai): allow custom base url + azure openai support

packages/pieces/community/image-helper/package.json
=> chore: bump image helper

packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
=> fix: cloud oauth2 toggle in admin console

package-lock.json, package.json
=> fix: image helper

packages/ui/core/project.json
=> chore: turn off stats json to reduce docker image size

package-lock.json, package.json
=> chore: bump package-lock

Dockerfile
=> fix: install ssh client for git

package.json
=> chore: bump 0.20.0-rc.1

packages/backend/src/app/database/migration/postgres/1707231704973-AddCategoriesToPieceMetadataPostgres.ts, packages/backend/src/app/database/migration/sqlite/1707229986819-AddCategoriesToPieceMetadata.ts, packages/backend/src/app/database/postgres-connection.ts, packages/backend/src/app/database/sqlite-connection.ts, packages/backend/src/app/ee/pieces/admin-piece-requests.ee.ts, packages/backend/src/app/pieces/piece-metadata-entity.ts
=> fix: add categories db migration

packages/backend/src/app/authentication/authentication-service/hooks/authentication-service-hooks.ts, packages/backend/src/app/authentication/authentication-service/index.ts, packages/backend/src/app/authentication/authentication.controller.ts, packages/backend/src/app/database/seeds/dev-seeds.ts, packages/backend/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts, packages/backend/src/app/ee/authentication/authentication-service/hooks/cloud-authentication-service-hooks.ts, packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
=> fix: only check email auth if provider is email

packages/backend/src/app/pieces/base-piece-module.ts
=> fix: add categories endpoint

packages/backend/src/app/ee/pieces/enterprise-piece-metadata-service-hooks.ts
=> fix: ee filteration

package-lock.json, packages/backend/src/app/flows/flow-run/flow-run-controller.ts, packages/backend/src/app/flows/flow-run/flow-run-service.ts, packages/shared/package.json, packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts, packages/ui/common/src/lib/service/instance-run.service.ts, packages/ui/common/src/lib/utils/tables.utils.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts, packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
=> feat: date range filter in runs page

packages/pieces/community/interfaces/src/index.ts
=> fix: add minimum support for interfaces

packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
Adds a snackbar that appears after the user submits the interface form successfully, the snackbar appears only when not waiting for response
=> fix: snackbar after interface submission received

packages/backend/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts, packages/pieces/community/salesforce/package.json, packages/pieces/community/salesforce/src/index.ts
=> fix: salesforce authentication popup

packages/backend/src/app/workers/flow-worker/flow-worker.ts
=> fix: wrrong payload retry latest version

packages/pieces/community/mailer-lite/package.json, packages/pieces/community/mailer-lite/src/index.ts, packages/pieces/community/mailer-lite/src/lib/actions/create-or-update-subscription.ts, packages/pieces/community/mailer-lite/src/triggers/triggers.ts
Triggers:
- subscriber.created
- subscriber.unsubscribed
- subscriber.added_to_group
=> feat(mailerlite): subscriber created,subscriber unsubscribed and subscriber added to group triggers

package.json
=> chore: bump to rc 0.19.0-rc.3

packages/backend/src/app/flags/flag.service.ts, packages/backend/src/app/helper/secret-helper.ts
=> fix: rebuild rc3

packages/ui/core/src/assets/scss/ng-material-override.scss, packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.html
=> feat: decrease spacing between inputs in the builder and their sizes in all of the app.

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/openai/src/lib/actions/ask-assistant.ts, packages/pieces/community/openai/src/lib/actions/generate-image.ts, packages/pieces/community/openai/src/lib/actions/send-prompt.ts, packages/pieces/community/openai/src/lib/actions/text-to-speech.ts, packages/pieces/community/openai/src/lib/actions/transcriptions.ts, packages/pieces/community/openai/src/lib/actions/translation.ts, packages/pieces/community/openai/src/lib/actions/vision-prompt.ts, packages/pieces/community/openai/src/lib/common/common.ts
=> fix(openai): revert azure openai implementation

packages/ui/feature-builder-canvas/src/lib/components/canvas-utils/drawing/draw-common.ts, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.scss, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.ts
=> fix: decrease steps visual space in builder

packages/pieces/community/whatsable/.eslintrc.json, packages/pieces/community/whatsable/README.md, packages/pieces/community/whatsable/package.json, packages/pieces/community/whatsable/project.json, packages/pieces/community/whatsable/src/index.ts, packages/pieces/community/whatsable/src/lib/actions/send-message.ts, packages/pieces/community/whatsable/tsconfig.json, packages/pieces/community/whatsable/tsconfig.lib.json, tsconfig.base.json
=> feat(whatsable): send message action

packages/backend/src/app/database/migration/postgres/1707614902283-AddAuditEvents.ts
=> fix: audit log migration

packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
=> fix: build webhookUrl with flowId instead of versionId

packages/backend/src/app/ee/connection-keys/connection-key.service.ts
=> fix: add props to connection card

packages/ee/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.html
Disable spellcheck / autocorrect on email invite field
=> chore: disable spellcheck on email invite field

packages/ui/feature-authentication/src/lib/pages/sign-in/sign-in.component.html, packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.html
Fixes the issue of the email form field not being autofilled by password managers.
Fixes # (3881)
=> fix: fixed email autofill issue

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/index.ts, packages/pieces/community/smtp/src/lib/actions/send-email.ts
=> fix(smtp): connection timeout

packages/backend/src/app/flags/flag.service.ts, packages/backend/src/app/pieces/base-piece-module.ts, packages/backend/src/app/pieces/piece-metadata-entity.ts, packages/backend/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts, packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
=> fix(pieces-search): weighted search, sorting by name

packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
=> fix: only search in pieces name & description

packages/pieces/community/linkedin/package.json, packages/pieces/community/linkedin/src/index.ts
=> feat(linkedin): add custom api call

docker-compose.yml, package-lock.json, package.json
=> chore: release 0.20.1

packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/step-output.ts, packages/ui/canvas-utils/src/lib/panning/panner.service.ts, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
=> fix: panning when zoom in/out

packages/pieces/community/approval/package.json, packages/pieces/community/csv/package.json, packages/pieces/community/data-mapper/package.json, packages/pieces/community/date-helper/package.json, packages/pieces/community/delay/package.json, packages/pieces/community/file-helper/package.json, packages/pieces/community/math-helper/package.json, packages/pieces/community/store/package.json, packages/pieces/community/tags/package.json, packages/pieces/community/text-helper/package.json
=> fix: hide error handling for core pieces

packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
=> fix: panning animation

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.20.2

package-lock.json, packages/server/api/src/app/webhooks/webhook-service.ts
=> fix: remove duplicate sample data in webhook trigger

packages/server/api/src/app/helper/jwt-utils.ts
=> fix: force logout old tokens

package-lock.json, packages/ui/canvas-utils/src/lib/canvas-utils.component.ts, packages/ui/canvas-utils/src/lib/panning/panner.service.ts, packages/ui/canvas-utils/src/lib/zooming/zooming.service.ts
=> fix: panning offset is wrong when zoom out

packages/ui/canvas-utils/src/lib/panning/panner.service.ts
=> fix: panner zoom

packages/server/api/src/app/helper/jwt-utils.ts
=> chore: validate special token

packages/pieces/community/dust/.eslintrc.json, packages/pieces/community/dust/README.md, packages/pieces/community/dust/package.json, packages/pieces/community/dust/project.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/tsconfig.json, packages/pieces/community/dust/tsconfig.lib.json
Add a Piece to integrate with [Dust](https://dust.tt) (AI assistants that can plug into your internal data, e.g. Slack, Notion, Drive, etc. and leverage different models from OpenAI, Anthropic, Mistral…)
=> feat(dust): create conversation action 

packages/engine/src/lib/handler/piece-executor.ts
=> fix(engine): set flow run status to `FAILED` if resolving inputs fails

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/common/index.ts, packages/pieces/community/airtable/src/lib/trigger/new-record.trigger.ts, packages/pieces/community/airtable/src/lib/trigger/update-record.trigger.ts
Fixes https://community.activepieces.com/t/airtable-trigger-sos-limit-to-a-specific-view/3148
=> feat(airtable): add table view option for triggers

packages/server/api/src/app/pieces/piece-metadata-service/hooks/index.ts, packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
=> fix: search sorting

packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
=> chore: make error handling param optional

docs/handbook/engineering/hiring.mdx, docs/handbook/engineering/how-we-work.mdx, docs/handbook/engineering/stack.mdx, docs/handbook/engineering/team.mdx, docs/handbook/overview.mdx, docs/handbook/people/time.mdx, docs/handbook/values.mdx, docs/mint.json
=> docs: add handbook

docs/handbook/engineering/hiring.mdx
=> docs: fix format in hiring

packages/server/api/src/app/helper/jwt-utils.ts
This breaks the embed token signed by the cloud users
=> fix: revert old token

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.20.3

packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Issue : https://community.activepieces.com/t/bcc-emails-not-being-sent-nor-is-sent-by-showing-desired-input/2176
Solution : https://github.com/nodemailer/nodemailer/issues/1342
=> fix(gmail): resolve issue with BCC emails not being sent

packages/pieces/community/mysql/package.json, packages/pieces/community/mysql/src/lib/actions/execute-query.ts, packages/pieces/community/postgres/package.json, packages/pieces/community/postgres/src/lib/actions/run-query.ts
=> fix(postgres): recommend parametrized queries

packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/helper/redis-system-job.ts, packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
=> chore(license): track project / user usage daily

packages/ee/shared/src/lib/audit-events/index.ts, packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.ts, packages/server/api/src/app/authentication/authentication.controller.ts, packages/server/api/src/app/ee/audit-logs/audit-event-service.ts, packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts, packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts, packages/server/api/src/app/helper/application-events/index.ts
=> feat(audit-log): track sign up events

packages/server/api/src/app/workers/flow-worker/flow-worker.ts
=> fix: retry internal server

packages/server/api/src/app/ee/billing/limits/tasks-limit.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> chore: use query to limit instead of stored record

packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
=> fix: track platform usage on cloud

packages/ee/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.html, packages/ui/common/src/lib/utils/consts.ts, packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
=> chore: improve spacing between inputs in forms

packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts, packages/server/api/src/app/ee/billing/project-billing/project-billing.service.ts
=> fix: update project billing with limits

docs/openapi.json
=> docs: update opanapi spec

packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts
=> fix: appsumo billing

packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
=> fix: opening new connection

package-lock.json, packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts, packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/ee/project-plan/tasks-limit.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts, packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts, packages/server/api/src/app/project/usage/project-usage-service.ts
=> fix: use redis for task limit

packages/server/api/src/app/ee/authentication/authentication-service/hooks/cloud-authentication-service-hooks.ts, packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts, packages/server/api/src/app/ee/billing/appsumo/appsumo.service.ts
=> fix: persist plan on registration

packages/pieces/community/acumbamail/.eslintrc.json, packages/pieces/community/acumbamail/README.md, packages/pieces/community/acumbamail/package.json, packages/pieces/community/acumbamail/project.json, packages/pieces/community/acumbamail/src/index.ts, packages/pieces/community/acumbamail/src/lib/actions/add-subscriber.ts, packages/pieces/community/acumbamail/src/lib/actions/create-subscriber-list.ts, packages/pieces/community/acumbamail/src/lib/actions/delete-subscriber-list.ts, packages/pieces/community/acumbamail/src/lib/actions/delete-subscriber.ts, packages/pieces/community/acumbamail/src/lib/actions/duplicate-template.ts, packages/pieces/community/acumbamail/src/lib/actions/search-subscriber.ts, packages/pieces/community/acumbamail/src/lib/common/constants.ts, packages/pieces/community/acumbamail/src/lib/common/index.ts, packages/pieces/community/acumbamail/src/lib/common/types.ts, packages/pieces/community/acumbamail/tsconfig.json, packages/pieces/community/acumbamail/tsconfig.lib.json, tsconfig.base.json
=> feat(acumbamail): create/delete list, add/update/delete/search subscriber and duplicate template actions

packages/server/api/src/app/ee/authentication/rbac-auth-middleware.ts
=> fix(api): wrong resource name for app-connections

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/index.ts, packages/pieces/community/smtp/src/lib/actions/send-email.ts, packages/pieces/community/smtp/src/lib/common/index.ts
=> fix(smtp): preset ports as dropdown

packages/pieces/community/afforai/.eslintrc.json, packages/pieces/community/afforai/README.md, packages/pieces/community/afforai/package.json, packages/pieces/community/afforai/project.json, packages/pieces/community/afforai/src/index.ts, packages/pieces/community/afforai/src/lib/actions/ask-chatbot.ts, packages/pieces/community/afforai/tsconfig.json, packages/pieces/community/afforai/tsconfig.lib.json, tsconfig.base.json
https://community.activepieces.com/t/afforai-integration/1073/4
=> feat(afforai): ask chatbot action

packages/ee/pieces/microsoft-dynamics-crm/package.json, packages/ee/pieces/microsoft-dynamics-crm/src/index.ts, packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/constants.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/ui/feature-connections/src/lib/dialogs/managed-oauth2-connection-dialog/managed-oauth2-connection-dialog.component.ts, packages/ui/feature-connections/src/lib/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.ts
=> fix(microsoft-dynamics): infer scope from props

packages/server/api/src/app/ee/audit-logs/audit-event-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts, packages/shared/src/lib/authentication/model/principal-type.ts
=> fix: check for audit log

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/index.ts, packages/pieces/community/smtp/src/lib/common/index.ts
This broke previous smtp connections
https://github.com/activepieces/activepieces/issues/4053
=> fix: requireTLS should be TLS

packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/ee/project-plan/tasks-limit.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/project/usage/project-usage-service.ts
=> fix: tasks usage reset after deleting flows

packages/ee/shared/src/lib/git-repo/index.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/database/migration/postgres/1709151540095-add-slug-to-git-repo.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/git-repos/git-repo.controller.ts, packages/server/api/src/app/ee/git-repos/git-repo.entity.ts, packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/test/helpers/mocks/index.ts, packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts, packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.html, packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.ts
=> feat: use `slug` instead of `projectId` for git sync

package.json
=> feat: release 0.21.0-rc.1

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/actions/upload-file.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/common/utils.ts, packages/server/api/src/app/project/usage/project-usage-service.ts
=> fix: bump slack version 

packages/server/api/src/app/ee/helper/redis-system-job.ts, packages/server/api/src/app/flows/flow/flow.service.ts
=> fix: increase update flow timeout to 30 seconds

docs/developers/development-setup/codespaces.mdx
=> docs: update codespace documentation

packages/pieces/community/wootric/package.json, packages/pieces/community/wootric/src/index.ts, packages/pieces/community/wootric/src/lib/actions/create-survey.ts, tsconfig.base.json
=> fix: wootric name

packages/server/api/src/app/flows/flow/form/form.controller.ts, packages/ui/feature-templates/src/index.ts
=> refactor: lint forms and fix typo

packages/server/api/src/app/database/migration/1709505632771-SetNotNullOnPlatform.ts, packages/server/api/src/app/database/migration/postgres/1709500873378-DropUnusedPlatformIndex.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/project/project-entity.ts
=> fix: remove unused index

packages/server/shared/src/lib/exception-handler.ts
=> chore: filter noisy error

packages/server/api/src/app/ee/flow-worker/cloud-flow-worker-hooks.ts, packages/server/api/src/app/flows/trigger/hooks/execute-trigger-hooks.ts, packages/server/api/src/app/workers/flow-worker/flow-queue-consumer.ts, packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts, packages/server/shared/src/lib/exception-handler.ts
=> fix: fallback to full search for removing job key

packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
=> fix: noisy errors and stale jobs

packages/server/api/src/app/database/migration/common/1709581196563-migrate-webhook.ts
=> fix: webhook migration

package.json
=> chore: build 0.21.0-rc.2

packages/ee/shared/src/lib/git-repo/index.ts, packages/server/api/src/app/database/migration/postgres/1709753080714-AddMappingStateToGit.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/git-repos/git-repo.entity.ts, packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.html
=> fix(git-sync): move mapping state to db

docs/developers/piece-reference/properties.mdx, packages/engine/src/lib/helper/piece-helper.ts, packages/engine/src/main.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/framework/src/lib/property/input/dropdown/dropdown-prop.ts, packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/common/common.ts, packages/server/api/src/app/pieces/base-piece-module.ts, packages/shared/package.json, packages/shared/src/lib/engine/engine-operation.ts, packages/shared/src/lib/pieces/dto/piece-requests.ts, packages/ui/common/src/lib/pipe/dropdown-search.pipe.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
=> feat: support pagination in dynamic dropdown

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/upsert-document.ts, packages/pieces/community/dust/src/lib/common.ts
Allow upserting a document into a Dust data source (so it can be indexed and used by assistants)
⚠️ **depends on #4120 (stacked PR)**
=> feat(dust): add action for upserting a document into a database

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
Add action to reply to an existing conversation (possibly using a different agent)
=> feat(dust): new action to reply to existing conversation

packages/shared/src/lib/flows/flow-helper.ts
=> fix: valid undefined

package.json
=> chore: bump to 0.21.0-rc.3

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix: rerun run

packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/platform/admin-platform.controller.ts, packages/server/api/src/app/ee/platform/admin-platform.service.ts
=> chore: add admin platform module

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/props.ts
=> fix: load maximum 600 results

packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
=> fix: response 200s for stripe instead of 204

packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/connections.service.ts, packages/engine/src/lib/services/storage.service.ts
=> fix: enrich errors in the failure

packages/pieces/community/framework/src/lib/piece-metadata.ts, packages/pieces/community/framework/src/lib/piece.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/shared/package.json
=> feat: expose authors in piece

packages/pieces/community/framework/src/lib/piece-metadata.ts, packages/pieces/community/framework/src/lib/piece.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/shared/package.json
Reverts activepieces/activepieces#4138
=> revert: "feat: expose authors in piece"

packages/pieces/community/framework/src/lib/piece-metadata.ts, packages/pieces/community/framework/src/lib/piece.ts, packages/server/api/src/app/database/migration/postgres/1710098373707-AddAuthorsToPieces.ts, packages/server/api/src/app/database/migration/sqlite/1710098009544-AddAuthorsToPieces.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts, packages/server/api/src/app/pieces/piece-metadata-entity.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/test/helpers/mocks/index.ts, packages/shared/package.json
=> fix: add author to piece

packages/pieces/community/json/package.json
=> fix: bump json

packages/server/api/src/app/app.ts, packages/server/api/src/app/flows/flow-run/flow-response-watcher.ts, packages/server/api/src/app/webhooks/webhook-controller.ts, packages/server/api/src/app/websockets/websockets.service.ts, packages/ui/common/src/lib/service/websocket.service.ts, packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
=> fix: test flow stuck on running status

packages/pieces/community/image-helper/package.json, packages/pieces/community/image-helper/src/index.ts, packages/pieces/community/image-helper/src/lib/actions/compress-image.actions.ts
=> feat(image-helper): added compress image action

package.json
=> chore: bump version to 0.21.0-rc.4

packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts, packages/shared/src/lib/pieces/dto/piece-requests.ts
=> feat(api): sort pieces by create date

packages/pieces/community/google-my-business/package.json, packages/pieces/community/google-my-business/src/lib/common/common.ts, packages/pieces/community/google-my-business/src/lib/triggers/new-review.ts
=> fix(google-my-business): show all locations instead of 10

.github/workflows/automate-deploy.yml, packages/engine/src/lib/helper/logging-utils.ts
=> fix: no longer internal error status on runs with large payloads

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.21.0

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/common/utils.ts
Allow posting Slack messages as replies to a thread in a channel
=> feat(slack): allow replies in existing thread

packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
=> fix(billing): don't send project usage if the subscription is cancelled.

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
=> fix(google-sheets): improve error message

docs/developers/development-setup/codespaces.mdx, docs/developers/development-setup/dev-container.mdx, docs/developers/development-setup/local.mdx
=> docs: Include instructions for setting up piece sources variable in development environment

packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/services/storage.service.ts, packages/pieces/community/common/src/lib/polling/index.ts, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts, packages/pieces/community/metabase/src/lib/common.ts, packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts, packages/pieces/community/store/package.json, packages/pieces/community/store/src/lib/actions/common.ts, packages/pieces/community/store/src/lib/actions/store-add-to-list.ts, packages/pieces/community/store/src/lib/actions/store-append-action.ts, packages/pieces/community/store/src/lib/actions/store-get-action.ts, packages/pieces/community/store/src/lib/actions/store-put-action.ts, packages/pieces/community/store/src/lib/actions/store-remove-from-list.ts, packages/pieces/community/store/src/lib/actions/store-remove-value.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> revert: run scope for the storage in framework

package.json, packages/server/api/src/app/flows/trigger/dedupe/index.ts
=> feat: 0.22.0-rc.1

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/polling/index.ts
=> fix: throw error if polling key is not found

packages/pieces/community/imap/package.json, packages/pieces/community/imap/src/index.ts, tools/scripts/pieces/publish-pieces-to-npm.ts, tools/scripts/utils/package-pre-publish-checks.ts, tools/scripts/utils/piece-script-utils.ts, tools/scripts/validate-publishable-packages.ts
Correct small typo on the description
before : 'Receive new emaiil trigger'
after : 'Receive new email trigger'
Nothing urgent 😅
=> style: IMAP piece : Correct typo

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
=> fix: stop retry for failed connections

packages/server/api/src/app/app.ts, packages/server/api/src/main.ts
=> fix: increase plugin timeout

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
Upgrade to new Slack OAuth flow: https://api.slack.com/authentication/oauth-v2
Paves the way to finer scope configuration
=> feat(slack): upgrade to new OAuth flow

packages/engine/src/lib/helper/piece-helper.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/piece.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/main.ts
- Fixes a regression that was introduced in #4147
=> fix: framework piece metadata backward compatibility

packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/index.ts
=> fix: display # of actions / triggers

packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/validators/validators.ts, packages/pieces/community/google-gemini/package.json, packages/pieces/community/tally/package.json, packages/pieces/community/tally/src/lib/triggers/new-submission.ts
=> fix(tally): test sample data is no longer returns empty object

packages/ui/feature-pieces/src/lib/services/piece.service.ts
=> fix: has triggers and has actions

packages/ui/feature-pieces/src/lib/services/piece.service.ts
=> docs: change text to empty trigger

package.json
=> feat: prerelease 0.22.0 rc2

packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.datasource.ts, packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html, packages/ui/feature-pieces/src/lib/services/piece.service.ts
=> fix: caching piece versions in front end 

packages/server/api/src/app/ee/project-members/project-member.service.ts
=> fix: list only non deleted projects

docs/embedding/configuration/initialize-embed.mdx, packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts, packages/ee/embed-sdk/src/index.ts, packages/ui/common/src/lib/service/embedding.service.ts, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
=> feat: ability to hide logo

packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
Removed the ID from runs list
Fixes # https://github.com/activepieces/activepieces/issues/4180
=> feat: removed id from runs list

packages/server/api/src/app/ee/git-repos/git-repo.module.ts, packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts
=> test: add list git repos with api key / user

docs/openapi.json, packages/shared/src/lib/project/project.ts, packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts, packages/ui/common/src/lib/store/project/project.action.ts, packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.ts, packages/ui/feature-dashboard/src/lib/components/project-switcher/project-switcher.component.ts, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts, packages/ui/feature-git-sync/src/lib/components/sync-project/sync-project.component.ts
=> chore: update openapi spec

packages/pieces/community/wedof/.eslintrc.json, packages/pieces/community/wedof/README.md, packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/project.json, packages/pieces/community/wedof/src/index.ts, packages/pieces/community/wedof/src/lib/actions/bill-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/cancel-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-intraining.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-servicedone.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-terminated.ts, packages/pieces/community/wedof/src/lib/actions/get-minimal-session-dates.ts, packages/pieces/community/wedof/src/lib/actions/get-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/refuse-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/search-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/update-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/validate-registration-folder.ts, packages/pieces/community/wedof/src/lib/common/wedof.ts, packages/pieces/community/wedof/src/lib/triggers/new-registration-folder-created.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-accepted.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-inTraining.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-paid.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-selected.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-terminated.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-tobill.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-updated.ts, packages/pieces/community/wedof/tsconfig.json, packages/pieces/community/wedof/tsconfig.lib.json
Hello, 
We would like to contribute to a new Piece from our SaaS platform Wedof. We are commited to automate administrative work around the training / certification domain. 
We would be happy to use Activepieces as one of our solutions to help our customers to automate their work.
=> feat(wedof):  11 actions / 8 triggers

packages/ee/shared/src/lib/git-repo/index.ts, packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts, packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.html, packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.ts
=> feat: add branch type to git configuration

packages/pieces/community/file-helper/package.json, packages/pieces/community/file-helper/src/index.ts, packages/pieces/community/file-helper/src/lib/actions/create-file.ts
Add action to create a file from text content (plain text, CSV, JSON, etc.)
=> feat(file-helper): create file from text action

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/update-message.ts
Add action to update an existing message, e.g. for progress indicators, etc.
=> feat(slack): add action to update message

packages/pieces/community/wedof/.eslintrc.json, packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/project.json, packages/pieces/community/wedof/src/index.ts, packages/pieces/community/wedof/src/lib/actions/bill-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/cancel-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-intraining.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-servicedone.ts, packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-terminated.ts, packages/pieces/community/wedof/src/lib/actions/get-minimal-session-dates.ts, packages/pieces/community/wedof/src/lib/actions/get-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/refuse-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/search-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/update-registration-folder.ts, packages/pieces/community/wedof/src/lib/actions/validate-registration-folder.ts, packages/pieces/community/wedof/src/lib/common/wedof.ts, packages/pieces/community/wedof/src/lib/triggers/new-registration-folder-created.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-accepted.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-inTraining.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-paid.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-selected.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-terminated.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-tobill.ts, packages/pieces/community/wedof/src/lib/triggers/registration-folder-updated.ts, tsconfig.base.json
=> fix: rename wedof to internal repo

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
=> chore(dust): remove log

packages/pieces/community/microsoft-excel-365/package.json, packages/pieces/community/microsoft-excel-365/project.json
=> fix(microsoft-excel-365): update project json dependency config

packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html, packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts, packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.datasource.ts, packages/server/api/src/app/database/migration/postgres/1711411372480-migrateInputUiInfo.ts, packages/server/api/src/app/database/migration/sqlite/1711412511624-AddMissingInputUiInfoSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts
=> fix: add missing inputUiInfo for all triggers

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts, packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts, packages/pieces/community/google-drive/src/lib/common/index.ts
=> fix: remove console error in google drive

packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html, packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts, packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.datasource.ts
=> fix: projects loading in admin console 

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/lib/actions/send-email.ts
Fixes https://community.activepieces.com/t/html-smtp-emails/2781/3
=> feat(smtp): add html message body option

packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/index.ts, packages/pieces/community/jira-cloud/src/lib/actions/add-attachment-to-issue.ts, packages/pieces/community/jira-cloud/src/lib/actions/add-comment-to-issue.ts, packages/pieces/community/jira-cloud/src/lib/actions/assign-issue.ts, packages/pieces/community/jira-cloud/src/lib/actions/delete-issue-comment.ts, packages/pieces/community/jira-cloud/src/lib/actions/list-isssue-comments.ts, packages/pieces/community/jira-cloud/src/lib/actions/update-issue-comment.ts, packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts, packages/pieces/community/jira-cloud/src/lib/common/index.ts, packages/pieces/community/jira-cloud/src/lib/common/props.ts
=> feat(jira-cloud): update issue, assign issue, issue attachment and issue comment actions

packages/pieces/community/pdf/package.json, packages/pieces/community/pdf/project.json, packages/pieces/community/pdf/src/index.ts, packages/pieces/community/pdf/src/lib/actions/extract-text.ts
=> chore: rename parse pdf to extract text

package.json
=> feat: bump 0.22.0-rc.3

packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/src/app/ee/git-repos/git-sync-helper.ts, packages/server/api/src/app/ee/git-repos/project-diff/project-diff.service.ts
=> fix(git): use filename as unique id for flows in repo

package.json
=> feat: release 0.22.0-rc.4

packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/analytics/analytics-controller.ts, packages/server/api/src/app/ee/analytics/analytics-module.ts, packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts, packages/server/api/src/app/helper/dayjs-helper.ts, packages/server/api/src/app/helper/system-jobs/common.ts
=> feat(platform): add analytics api module

packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
=> fix: updated / created

packages/server/api/test/helpers/mocks/index.ts
=> fix: piece tests

packages/server/api/src/app/flows/flow-version/flow-version.service.ts
=> fix: markdown validation

packages/server/api/src/app/core/security/authn/access-token-authn-handler.ts, packages/server/api/src/app/core/security/authn/global-api-key-authn-handler.ts, packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts, packages/server/api/src/app/core/security/security-handler-chain.ts, packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/test/integration/cloud/core/security.test.ts, packages/server/api/test/integration/cloud/piece-metadata/piece-metadata.test.ts, packages/ui/core/project.json
=> fix: security webhooks

packages/cli/src/lib/commands/create-piece.ts, packages/cli/src/lib/utils/files.ts
=> fix(cli): fix create piece lint option error

packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/src/app/ee/git-repos/project-diff/project-mapping-state.ts
=> fix: include old git state after pulling

Dockerfile, docker-compose.yml, package-lock.json, package.json
=> chore: release 0.22.0

packages/pieces/community/telegram-bot/package.json, packages/pieces/community/telegram-bot/src/lib/trigger/new-message.ts
=> fix(telegram): sample data for trigger works

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/triggers/new-message.ts, packages/pieces/community/slack/src/lib/triggers/new-reaction-added.ts
=> fix: publish failed for new slack connections

packages/pieces/community/google-calendar/package.json, packages/pieces/community/google-calendar/src/lib/actions/update-event.ation.ts
=> fix(google-calendar): fix update event action

package.json
=> chore: bump release 0.23.0-rc.1

packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
=> fix: json values method

packages/pieces/community/lever/.eslintrc.json, packages/pieces/community/lever/README.md, packages/pieces/community/lever/package.json, packages/pieces/community/lever/project.json, packages/pieces/community/lever/src/index.ts, packages/pieces/community/lever/src/lib/actions/get-opportunity.ts, packages/pieces/community/lever/src/lib/actions/list-opportunity-forms.ts, packages/pieces/community/lever/src/lib/actions/update-opportunity-stage.ts, packages/pieces/community/lever/tsconfig.json, packages/pieces/community/lever/tsconfig.lib.json
Add integration with [Lever](https://www.lever.co), starting with auth (API keys, not OAuth), a few basic actions, and a generic "custom API action"
=> feat(lever): add Lever integration

packages/pieces/community/lever/src/index.ts, packages/pieces/community/lever/src/lib/actions/get-opportunity.ts, packages/pieces/community/lever/src/lib/actions/list-opportunity-forms.ts, packages/pieces/community/lever/src/lib/actions/update-opportunity-stage.ts
=> fix: remove commented code in lever

packages/ui/feature-connections/src/lib/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.ts
=> fix(oauth2): client credential is not saving

packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
=> fix: include properties for oauth2 in the body in client grant

.github/workflows/check-typos.yml
I added a github action workflow to check for typos except for files under database directory.
=> feat: added workflow to check for typos

package-lock.json, package.json, packages/pieces/community/elevenlabs/.eslintrc.json, packages/pieces/community/elevenlabs/README.md, packages/pieces/community/elevenlabs/package.json, packages/pieces/community/elevenlabs/project.json, packages/pieces/community/elevenlabs/src/index.ts, packages/pieces/community/elevenlabs/src/lib/actions/text-to-speech-action.ts, packages/pieces/community/elevenlabs/tsconfig.json, packages/pieces/community/elevenlabs/tsconfig.lib.json, tsconfig.base.json
This adds a new piece: [Elevenlabs](https://elevenlabs.io/)
For now, it only supports basic text to speech as requested here https://community.activepieces.com/t/elevenlabs-integration/3732 but I plan to add support for more advanced options and speech to text. 
[elevenlabs v0.2.2](https://github.com/elevenlabs/elevenlabs-js) is a new dependency
=> feat(elevenlabs): Text to Speech Action

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Add missing option to include all team drives
=> fix(google-sheets): fix missing option for trigger

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/index.ts, tools/scripts/pieces/turbowatch.ts
=> fix(turbowtach): show compilation error for pieces

docs/embedding/configuration/generate-jwt.mdx
=> feat(embedded): provide user role in jwt

packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
=> revert: filter pieces

packages/server/api/src/app/app.ts, packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
=> fix: init worker after piece sync setup

package.json
=> chore: bump version to 0.23.0-rc.2

packages/engine/src/lib/helper/piece-loader.ts, packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts, packages/server/api/src/app/app-event-routing/app-event-routing.module.ts, packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/shared/src/lib/common/activepieces-error.ts, packages/shared/src/lib/pieces/utils.ts
=> fix(google-sheets): renew notification webhooks

packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
=> chore: remove console log

.eslintignore, .eslintrc.json, nx.json, packages/cli/src/lib/commands/create-piece.ts
=> fix: create piece cli lint issue

packages/server/api/src/app/flags/flag.service.ts, packages/ui/feature-dashboard/src/lib/dashboard-container.component.html, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
=> fix: enable rewards

docs/embedding/configuration/initialize-embed.mdx, packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts, packages/ee/embed-sdk/src/index.ts, packages/ui/common/src/lib/service/embedding.service.ts, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
=> feat(embed): ability to hide flow actions

packages/pieces/community/mysql/package.json, packages/pieces/community/mysql/src/lib/actions/delete-row.ts, packages/pieces/community/mysql/src/lib/actions/find-rows.ts, packages/pieces/community/mysql/src/lib/actions/insert-row.ts, packages/pieces/community/mysql/src/lib/actions/update-row.ts
=> fix(mysql): fix delete/find/insert/update row queries

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.23.0

docs/embedding/configuration/initialize-embed.mdx, package.json, packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts, packages/ee/embed-sdk/src/index.ts, packages/ui/common/src/lib/service/embedding.service.ts, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
=> feat(embed): ability to hide flow name in the builder

packages/ui/common/src/lib/components/powered-by-activepieces/powered-by-activepieces.component.html
=> feat: make powered by not clickable and less catchy

packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
=> fix: accept renew configuration in admin pieces endpoint

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
=> fix: renew configuration is not working on cloud

packages/server/api/src/app/tags/tags-module.ts
=> fix: add permission to tags

packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts, packages/ee/project-members/src/lib/service/project-members.service.ts, packages/ui/common/src/lib/service/authentication.service.ts, packages/ui/core/src/app/app.module.ts, packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html, packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts, packages/ui/feature-pieces/package.json, packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.ts
=> fix: role value in ui

packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
=> fix: role checker in general project settings

package-lock.json, package.json
=> feat: release 0.24.0

packages/ui/feature-dashboard/src/lib/components/sidenav-route-item/sidenav-route-item.component.ts
=> fix: hide support & community

packages/pieces/community/google-docs/package.json, packages/pieces/community/google-docs/src/index.ts, packages/pieces/community/google-docs/src/lib/actions/append-text.ts, packages/pieces/community/google-docs/src/lib/common/index.ts
Added an action that appends text to the bottom of a google document.
Fixes # (4418)
=> feat: added append text action to google docs piece.

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.24.1

package-lock.json, packages/ui/common/src/lib/utils/consts.ts
=> fix: export template not showing correct json

packages/pieces/community/discord/package.json, packages/pieces/community/discord/src/index.ts, packages/pieces/community/discord/src/lib/actions/ban-a-guild-member.ts, packages/pieces/community/discord/src/lib/actions/create-guild-role.ts, packages/pieces/community/discord/src/lib/actions/delete-guild-role.ts, packages/pieces/community/discord/src/lib/actions/remove-ban-from-user.ts
https://github.com/activepieces/activepieces/pull/4412
https://github.com/activepieces/activepieces/pull/4421
https://github.com/activepieces/activepieces/pull/4423
https://github.com/activepieces/activepieces/pull/4398
=> chore: merge all discord actions into single pr

packages/pieces/community/discord/package.json, packages/pieces/community/discord/src/index.ts, packages/pieces/community/discord/src/lib/actions/create-guild-role.ts
Adds the action to create a role in a Discord guild.
=> feat(discord): add create guild role action

packages/pieces/community/discord/package.json, packages/pieces/community/discord/src/index.ts, packages/pieces/community/discord/src/lib/actions/delete-guild-role.ts
Adds the action to delete a role from a Discord guild.
=> feat(discord): add the action to delete a role from a guild

packages/pieces/community/todoist/package.json, packages/pieces/community/todoist/src/lib/actions/create-task-action.ts, packages/pieces/community/todoist/src/lib/common/client/rest-client.ts, packages/pieces/community/todoist/src/lib/common/models.ts
Add section_id to todoist create task action
=> feat(todoist): add section_id to create task action

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/index.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app.ts, packages/shared/src/lib/common/activepieces-error.ts, packages/ui/common/src/index.ts, packages/ui/common/src/lib/components/diagnostic-dialog/diagnostic-dialog.component.html, packages/ui/common/src/lib/components/diagnostic-dialog/diagnostic-dialog.component.ts, packages/ui/common/src/lib/components/json-view/json-view.component.html, packages/ui/common/src/lib/components/json-view/json-view.component.ts, packages/ui/common/src/lib/components/warning-box/warning-box.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html, packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html, packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.html, packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.ts, packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.html, packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.ts, packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.html, packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.ts
Show report issue when there is unexpected error. 
**Report Issue link now is blue**
=> feat: add report issue to connection dialog for unknown errors 

packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts, packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.html, packages/ee/embed-sdk/src/index.ts, packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
Adds connections' Iframe on connect method call and removes it once the dialog is closed
=> fix(embed-sdk): add connection iframe only when used

packages/pieces/community/github/src/index.ts, packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts
Adds the action to create a comment on a GitHub issue.
=> feat(github): add action to create comment on a issue

packages/pieces/community/github/package.json, packages/pieces/community/github/src/index.ts, packages/pieces/community/github/src/lib/actions/unlock-issue.ts
Adds the action to unlock a GitHub issue.
=> feat(github): add action to unlock an issue

packages/shared/src/lib/common/telemetry.ts, packages/ui/common/src/lib/service/telemetry.service.ts, packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.ts, packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
=> fix: add page views

packages/server/api/src/app/helper/telemetry.utils.ts
=> fix: event tracking

packages/ui/common/src/lib/service/telemetry.service.ts
=> fix: skip embed

docs/openapi.json, packages/server/api/src/app/ee/git-repos/git-sync-helper.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/flows/folder/folder.controller.ts, packages/server/api/src/app/flows/folder/folder.service.ts, packages/shared/src/lib/flows/dto/create-flow-request.ts, packages/ui/common/src/lib/service/flow.service.ts, packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
=> feat: add folder name to flow api

packages/pieces/community/http/package.json, packages/pieces/community/http/src/index.ts, packages/pieces/community/http/src/lib/actions/send-http-request-action.ts
With this, users are going to be able to use a proxy for their http requests.
=> feat: add proxy capabilities to the "send request" action

packages/ee/ui/billing/src/lib/ee-billing-ui.module.ts, packages/ee/ui/billing/src/lib/plans-page/plans-page.component.html, packages/ee/ui/platform/src/lib/components/api-keys-table/api-keys-table.component.html, packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.component.html, packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.html, packages/ee/ui/platform/src/lib/components/signing-keys-table/signing-keys-table.component.html, packages/ee/ui/platform/src/lib/components/updates/updates.component.html, packages/ee/ui/platform/src/lib/components/updates/updates.component.ts, packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.html, packages/ee/ui/platform/src/lib/pages/templates-table/templates-table.component.html, packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.html, packages/ee/ui/platform/src/lib/ui-ee-platform.module.ts, packages/ee/ui/project-members/src/lib/ee-project-members.module.ts, packages/ee/ui/project-members/src/lib/project-members-table/project-members-table.component.html, packages/ui/common/src/index.ts, packages/ui/common/src/lib/pipe/ap-date.pipe.ts, packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html, packages/ui/feature-builder-test-steps/src/lib/ui-feature-builder-test-steps.module.ts, packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.html, packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html, packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
https://community.activepieces.com/t/were-polishing-activepieces-a-rolling-announcement-19th-april/3859/12?u=abuaboud
=> feat:  new date and time format

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/index.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts, packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
=> feat(google-sheets): New/Updated Row Trigger and Insert Multiple Rows Action

packages/pieces/community/shopify/package.json, packages/pieces/community/shopify/src/index.ts, packages/ui/common/src/lib/service/flow.service.ts
=> fix: retry update flow request

packages/server/api/src/app/database/migration/postgres/1713643694049-AddUniqueNameToFolder.ts, packages/server/api/src/app/database/migration/sqlite/1713645171373-AddUniqueNameToFolderSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/folder/folder.entity.ts, packages/server/api/src/app/flows/folder/folder.service.ts, packages/ui/feature-dashboard/src/lib/validators/folderName.validator.ts
Upsert fails because the column doesn't have unique constraint on column 
https://community.activepieces.com/t/bug-new-folder-is-broken/3888
=> fix: create new folder api

packages/server/api/src/app/flows/folder/folder.service.ts
=> fix: folder update

packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control-text-item.component.ts, packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
=> feat: reordering items in the array property

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/common/index.ts
=> fix(notion):  button field causing errors in rendering database properties

packages/pieces/community/hubspot/package.json, packages/pieces/community/hubspot/src/index.ts
=> feat(hubspot): add more scopes to hubspot

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.25.0

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts, packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
=> fix(google-sheets): Add row number in response and fix find rows action

docker-compose.yml, package-lock.json, package.json, packages/server/api/src/app/database/migration/common/1709581196563-migrate-webhook.ts
the array of property in form trigger were broken
=> feat: release 0.25.1

packages/server/api/src/app/ee/projects/platform-project-service.ts
=> fix: list owned project

packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
Implements the functionality of zooming canvas on holding the CTRL + mouse wheel
=> feat: add listener to zoom on ctrl+mouse wheel

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Same as https://github.com/activepieces/activepieces/pull/4358 for other gsheet trigger 😬
=> fix(google-sheets): fix missing option for other trigger

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/index.ts, packages/pieces/community/notion/src/lib/action/find-item.ts, packages/pieces/community/notion/src/lib/common/index.ts
=> feat(notion): find database item by property value action

package.json
=> feat: 0.26.0-rc.1

packages/shared/src/lib/common/telemetry.ts, packages/ui/common/src/lib/service/contact-sales.service.ts, packages/ui/feature-dashboard/src/lib/components/contact-sales/contact-sales.component.html, packages/ui/feature-dashboard/src/lib/components/contact-sales/contact-sales.component.ts, packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
=> chore: add domain name on request trial + telemetry

packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts, packages/ui/common/src/lib/service/authentication.service.ts
=> refactor: add logging for token expired

packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
=> fix: exception null value in header

packages/pieces/community/google-docs/package.json, packages/pieces/community/google-docs/src/index.ts, packages/pieces/community/google-docs/src/lib/actions/find-documnet.ts
=> feat(google-docs): find document action

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/request-action-message.ts, packages/pieces/community/slack/src/lib/actions/request-approval-message.ts, packages/pieces/community/slack/src/lib/actions/search-messages.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/actions/update-message.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
=> feat(slack): add bot integration steps for channel actions/triggers

packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/authn-provider.ts, packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts, packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/google-authn-provider.ts, packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-service.ts, packages/server/api/src/app/platform/platform-utils.ts, packages/server/api/src/app/platform/platform.controller.ts, packages/server/api/test/integration/cloud/platform/platform.test.ts, packages/ui/common/src/lib/service/platform.service.ts
=> fix: resolve platform id for managed login

packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
=> fix: list templates

packages/pieces/community/google-calendar/package.json, packages/pieces/community/google-calendar/src/index.ts, packages/pieces/community/google-calendar/src/lib/actions/add-attendees.action.ts
=> feat(google-calendar): Add Attendees to Event Action

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/lib/actions/create-record.ts, packages/pieces/community/apitable/src/lib/actions/find-record.ts, packages/pieces/community/apitable/src/lib/actions/update-record.ts
=> fix(apitable): fail step on API error

packages/pieces/community/moxie-crm/package.json, packages/pieces/community/moxie-crm/src/lib/triggers/register-trigger.ts
=> fix(moxie-crm): Fix Test Trigger Payload Issue

package.json
=> feat: release 0.26.0-rc.2

docs/install/troubleshooting.mdx, packages/server/api/src/app/authentication/lib/password-hasher.ts, packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
=> docs: reset password instructions for sqlite3

packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
=> fix: github name can be nullable

nx.json, package-lock.json, package.json, packages/pieces/community/apollo/.eslintrc.json, packages/pieces/community/apollo/README.md, packages/pieces/community/apollo/package.json, packages/pieces/community/apollo/project.json, packages/pieces/community/apollo/src/index.ts, packages/pieces/community/apollo/src/lib/actions/enrich-company.ts, packages/pieces/community/apollo/src/lib/actions/match-person.ts, packages/pieces/community/apollo/tsconfig.json, packages/pieces/community/apollo/tsconfig.lib.json, packages/pieces/community/segment/.eslintrc.json, packages/pieces/community/segment/README.md, packages/pieces/community/segment/package.json, packages/pieces/community/segment/project.json, packages/pieces/community/segment/src/index.ts, packages/pieces/community/segment/src/lib/actions/identify-user.ts, packages/pieces/community/segment/tsconfig.json, packages/pieces/community/segment/tsconfig.lib.json, tsconfig.base.json
=> feat(segment): identify user

nx.json, package-lock.json, package.json, packages/pieces/community/apollo/.eslintrc.json, packages/pieces/community/apollo/README.md, packages/pieces/community/apollo/package.json, packages/pieces/community/apollo/project.json, packages/pieces/community/apollo/src/index.ts, packages/pieces/community/apollo/src/lib/actions/enrich-company.ts, packages/pieces/community/apollo/src/lib/actions/match-person.ts, packages/pieces/community/apollo/tsconfig.json, packages/pieces/community/apollo/tsconfig.lib.json, tsconfig.base.json
=> feat(apollo): enrich company / match person action

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/lib/actions/create-record.ts, packages/pieces/community/apitable/src/lib/actions/update-record.ts
Fixes https://community.activepieces.com/t/ai-table-integration-boolean-does-not-work-on-update/3963/2
=> fix(apitable): Fix Boolean Field Not Updating Issue

packages/pieces/community/apollo/package.json, packages/pieces/community/apollo/src/lib/actions/enrich-company.ts, packages/pieces/community/apollo/src/lib/actions/match-person.ts
=> chore(apollo): bump package json

packages/pieces/community/mailjet/.eslintrc.json, packages/pieces/community/mailjet/README.md, packages/pieces/community/mailjet/package.json, packages/pieces/community/mailjet/project.json, packages/pieces/community/mailjet/src/index.ts, packages/pieces/community/mailjet/src/lib/actions/send-email.ts, packages/pieces/community/mailjet/tsconfig.json, packages/pieces/community/mailjet/tsconfig.lib.json
Fixes #4605 
Adding a Mailjet piece
=> feat(mailjet): send action 

packages/pieces/community/webflow/package.json, packages/pieces/community/webflow/src/index.ts, packages/pieces/community/webflow/src/lib/actions/create-collection-item.ts, packages/pieces/community/webflow/src/lib/actions/delete-collection-item.ts, packages/pieces/community/webflow/src/lib/actions/find-collection-item.ts, packages/pieces/community/webflow/src/lib/actions/find-order.ts, packages/pieces/community/webflow/src/lib/actions/fulfill-order.ts, packages/pieces/community/webflow/src/lib/actions/get-collection-item.ts, packages/pieces/community/webflow/src/lib/actions/publish-collection-item.ts, packages/pieces/community/webflow/src/lib/actions/refund-order.ts, packages/pieces/community/webflow/src/lib/actions/unfulfill-order.ts, packages/pieces/community/webflow/src/lib/actions/update-collection-item.ts, packages/pieces/community/webflow/src/lib/common/client.ts, packages/pieces/community/webflow/src/lib/common/common.ts, packages/pieces/community/webflow/src/lib/common/props.ts, packages/pieces/community/webflow/src/lib/triggers/new-form-submitted.ts
=> fix(webflow): show collection fields in all items actions

package.json
=> feat: pre release 0.26.0-rc.3

packages/pieces/community/telegram-bot/package.json, packages/pieces/community/telegram-bot/src/lib/trigger/new-message.ts
=> feat(telegram): merge two prs into same one

packages/pieces/community/telegram-bot/package.json, packages/pieces/community/telegram-bot/src/lib/trigger/new-message.ts
replaced static sample with recent 5 messages in telegram bot.
Fixes # (4226)
=> feat(telegram-bot): replaced static sample with recent 5 messages

packages/pieces/community/telegram-bot/package.json, packages/pieces/community/telegram-bot/src/lib/action/send-text-message.action.ts
=> feat(telegram-bot): added checkbox to control link preview

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Fixes #3824 
ANNOUNCEMENTS=true
=> feat(google-sheets): Updated Row Trigger Based on User Provided Column

packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/pieces/community/queue/.eslintrc.json, packages/pieces/community/queue/README.md, packages/pieces/community/queue/package.json, packages/pieces/community/queue/project.json, packages/pieces/community/queue/src/index.ts, packages/pieces/community/queue/src/lib/actions/pull-from-queue.ts, packages/pieces/community/queue/src/lib/actions/push-to-queue.ts, packages/pieces/community/queue/src/lib/common.ts, packages/pieces/community/queue/tsconfig.json, packages/pieces/community/queue/tsconfig.lib.json, tsconfig.base.json
Adds a queue piece that pushes and pulls items on project level.
=> feat(queue): pull items / push items into queue

packages/pieces/community/queue/package.json, packages/pieces/community/queue/src/lib/actions/push-to-queue.ts
=> fix: queue fix

packages/pieces/community/queue/package.json, packages/pieces/community/queue/src/index.ts, packages/pieces/community/queue/src/lib/actions/clear-queue.ts
=> feat(queue): clear queue action

packages/pieces/community/apollo/package.json, packages/pieces/community/apollo/src/lib/actions/enrich-company.ts, packages/pieces/community/apollo/src/lib/actions/match-person.ts, packages/pieces/community/zerobounce/.eslintrc.json, packages/pieces/community/zerobounce/README.md, packages/pieces/community/zerobounce/package.json, packages/pieces/community/zerobounce/project.json, packages/pieces/community/zerobounce/src/index.ts, packages/pieces/community/zerobounce/src/lib/actions/validate-email.ts, packages/pieces/community/zerobounce/tsconfig.json, packages/pieces/community/zerobounce/tsconfig.lib.json, tsconfig.base.json
=> feat(zerobounce): validate email action

packages/pieces/community/queue/package.json, packages/pieces/community/queue/src/lib/actions/clear-queue.ts, packages/pieces/community/queue/src/lib/actions/push-to-queue.ts
=> fix: queue response

packages/server/api/src/app/helper/telemetry.utils.ts
=> feat: add first seen at

packages/pieces/community/github/package.json, packages/pieces/community/github/src/lib/common/index.ts
=> fix(github): load more than 100 repo

packages/pieces/community/todoist/package.json, packages/pieces/community/todoist/src/index.ts, packages/pieces/community/todoist/src/lib/actions/find-task.action.ts, packages/pieces/community/todoist/src/lib/actions/mark-task-completed.action.ts, packages/pieces/community/todoist/src/lib/actions/update-task.action.ts, packages/pieces/community/todoist/src/lib/common/client/rest-client.ts, packages/pieces/community/todoist/src/lib/common/models.ts, packages/pieces/community/todoist/src/lib/common/props.ts, packages/pieces/community/todoist/src/lib/triggers/task-completed-trigger.ts
=> feat(todoist): update task, find task and mark task completed action

packages/pieces/community/wordpress/package.json, packages/pieces/community/wordpress/src/lib/actions/create-post.action.ts, packages/pieces/community/wordpress/src/lib/actions/update-post.action.ts
=> feat(wordpress): Add ACF field option for create/update post actions

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/openai/src/lib/actions/extract-structure-data.action.ts
=> feat(openai): Extract Data from Text Action

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/index.ts, packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts, packages/server/api/src/app/core/security/authz/project-authz-handler.ts, packages/server/api/src/app/webhooks/webhook-controller.ts, packages/server/api/src/app/webhooks/webhook-service.ts, packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-service.ts, packages/ui/feature-builder-form-controls/src/lib/pipes/replace-markdown-consts.pipe.ts
=> feat(webhook): introduce production & testing url

packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
Fixes:
* Changing the step run to be in seconds instead of milliseconds
=> fix: change the step run duration to seconds

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/lib/actions/extract-structure-data.action.ts
=> feat: extract structured data

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
=> fix(notion): new updated trigger

packages/pieces/community/formbricks/package.json, packages/pieces/community/formbricks/src/index.ts, packages/pieces/community/formbricks/src/lib/triggers/register.ts
=> feat(formbricks): support self hosted instance

docs/about/changelog.mdx, packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
=> fix: webhook testing url

package-lock.json, package.json
=> feat: release 0.26.1

packages/pieces/community/slack/src/lib/actions/send-message-action.ts
=> fix(slack): message should show before threadts

packages/pieces/community/lever/package.json, packages/pieces/community/lever/src/lib/actions/add-feedback-to-opportunity.ts
Allow posting feedback even when no interview has been scheduled, using any template available
=> feat(lever): allow adding arbitrary feedback using any template available

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-question.ts, packages/pieces/community/metabase/src/lib/common.ts
Metabase 0.49 introduced a new API key auth mechanism which is simpler and safer to use
https://www.metabase.com/releases/metabase-49#authenticate-api-requests-with-api-keys
=> feat(metabase): switch to new API key auth mechanism

packages/server/api/src/app/ee/helper/license-validator/license-validator.ts, packages/server/api/src/app/ee/helper/license-validator/network-license-validator.ts, packages/server/api/src/app/platform/platform.service.ts
=> fix: add flowIssuesEnabled to the license

packages/ui/common/src/lib/service/platform.service.ts, packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
=> fix: issue feature lock

packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html, packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
=> fix: avoid flow lock when updated by api key

package-lock.json, package.json, packages/pieces/community/openai/package.json
=> feat(openai): support gpt-4o in assistant actions

packages/ee/ui/billing/src/lib/plan-name.pipe.ts, packages/server/api/src/app/ee/billing/appsumo/appsumo.service.ts
Added a new tier for AppSumo (tier 6) for our upcoming campaign
=> feat: add appsumo tier 6

packages/engine/src/lib/services/variable-service.ts
=> feat: rename censored to redacted

packages/server/api/src/app/database/migration/common/1716105958530-RemoveShowActivityLog.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/platform/platform.entity.ts
=> chore: lint server-api

packages/ui/core/src/assets/scss/scroll.scss, packages/ui/core/src/assets/scss/utlis.scss, packages/ui/core/src/styles.scss
=> fix: switch to default browser styling for scroll bars on small screens

packages/engine/src/main.ts
=> fix: sanitize functions before post message

packages/ui/core/nginx.standard.conf
=> fix: add only csp for cloud

packages/ui/core/nginx.standard.conf
Fixes #4730 -> Info issues #4,7,9,10
=> feat: add X-Content-Type-Options and caching in NGINX

packages/ui/core/nginx.standard.conf
Reverts activepieces/activepieces#4749
=> Revert "fix: nginx if in location"

packages/ui/core/nginx.standard.conf
=> fix: allow CSP for all hosts & fix static assets fetching

packages/ui/core/nginx.standard.conf
=> chore: remove nginx

packages/ui/core/nginx.standard.conf, packages/ui/core/src/app/app-routing.module.ts
=> fix: revert not found redirection 

packages/ui/common/src/lib/service/authentication.service.ts, packages/ui/common/src/lib/service/telemetry.service.ts, packages/ui/core/nginx.standard.conf
=> fix: add x-frame-option back

docker-compose.yml, package.json
=> feat: bump to 0.27.0-rc.2

packages/pieces/community/twitter/package.json, packages/pieces/community/twitter/src/index.ts
=> feat(twitter): update auth note

packages/ui/common/src/lib/service/project.service.ts
=> fix: limit project to 100 in project switcher

packages/pieces/community/trello/package.json, packages/pieces/community/trello/src/lib/common/index.ts, packages/pieces/community/trello/src/lib/triggers/cardMoved.ts, packages/pieces/community/trello/src/lib/triggers/newCard.ts
=> fix(trello): fix trigger test function to load recent sample data

packages/server/api/src/app/app.ts, packages/server/api/src/app/flows/flow-run/flow-run-module.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/flows/flow/flow-worker.controller.ts, packages/server/api/src/app/webhooks/webhook-controller.ts, packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts, packages/server/api/src/app/workers/flow-worker/webhook-response-watcher.ts, packages/server/api/test/integration/ce/flows/flow-consume.test.ts
=> chore: rename engine response watcher to webhook

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix: store time

packages/server/worker/src/lib/sandbox/file-sandbox.ts
=> fix: isolated vm in worker threads

packages/server/api/__mocks__/isolated-vm.js, packages/server/api/jest.config.ts, packages/server/worker/package.json, packages/server/worker/src/lib/sandbox/file-sandbox.ts
=> fix: isolate vm in worker threads

.github/workflows/release-rc.yml, package.json
=> feat: release 0.27.0-rc.3

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/common/utils.ts
=> feat(slack): add thread timestamp URL option

package.json
=> feat: release 0.27.0-rc.4

packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Fixes showing the notifications icon in issues section
=> fix: proper handling of showing notifications icon in issues section

packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
=> fix: platform frontend url

package.json
=> feat: 0.27.0-rc.5 release

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Fixes https://community.activepieces.com/t/google-sheet-column-trigger-not-working-triggers-all-rows-in-the-entire-column-even-though-i-didnt-change-items/4251/2
=> fix(google-sheets): fix empty row issue for updated trigger

packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
=> fix(rbac): api keys permission

packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/worker/src/lib/sandbox/file-sandbox.ts, packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html, packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html
=> fix: crash on quota exceeded & fix timeout error

package.json
=> feat: release 0.27.0-rc.6

packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-module.ts, packages/server/api/src/app/platform/platform-utils.ts
=> fix: resolve platform for saml 2.0

packages/ee/ui/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.ts, packages/ee/ui/project-members/src/lib/utils.ts
=> chore: remove external customer role from ui

packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html, packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
Fixes #4803 
* Remove the issue description as it doesn't provide any relevant data.
* Add the issue count the place of description column.
* Add "First Seen" as a column.
* Rename the "Last Occurrence" to "Last Seen".
* Fixed authenticationService being instantiated twice in the constructor.
=> feat(issues): add first seen column, count column / remove description

packages/ui/common/src/lib/guards/show-based-on-edition.guard.ts, packages/ui/common/src/lib/guards/show-based-on-role.guard.ts, packages/ui/common/src/lib/guards/show-platform-settings.guard.ts, packages/ui/core/src/app/modules/forms/forms.component.ts, packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
=> fix(rbac): operator role shouldn't show 404 on the login

docs/security/permissions.mdx, package.json
=> feat: release 0.27.0-rc.7

packages/ui/core/src/app/app.module.ts
=> fix(team): showing when existing session is expired

packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts, packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts
=> fix(saml): acs saml link in service provider

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/actions/issues/create-issue.ts, packages/pieces/community/linear/src/lib/common/client.ts, packages/pieces/community/linear/src/lib/common/props.ts
adds support for creating issues in Linear using a `templateId`
=> feat(linear): template dropdown option for create issue action

packages/ui/common/src/lib/pipe/duration-formatter.pipe.ts, packages/ui/core/src/assets/scss/scroll.scss, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts, packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts, packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/iteration-details.service.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.ts, packages/ui/feature-builder-store/src/lib/model/canvas-state.ts, packages/ui/feature-builder-store/src/lib/service/run-details.service.ts, packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.action.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts, packages/ui/feature-builder-store/src/lib/utils/flowStructureUtil.ts
Skipping changelog since this is related to real-time flow testing.
=> fix: outputs inside loops not showing

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/index.ts, packages/pieces/community/linear/src/lib/actions/raw-graphql-query.ts, packages/pieces/community/linear/src/lib/common/client.ts
Add an action to perform a raw GraphQL query on Linear
=> feat(linear): add action to perform a raw GraphQL query

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/database/migration/postgres/1676505294811-encrypt-credentials.ts, packages/server/api/src/app/database/migration/sqlite/1691706020626-add-app-connection-type-to-top-level.ts, packages/server/api/src/app/ee/oauth-apps/oauth-app.service.ts, packages/server/api/src/app/helper/encryption.ts, packages/server/api/src/app/helper/engine-helper.ts
=> refactor: encryption utils

packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.html, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts, packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts
=> fix: acs saml url

package.json, packages/server/api/test/helpers/mocks/index.ts
=> feat: 0.27.0-rc.8

packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
=> fix(saml): add missing /v1 in single sign url

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts, packages/pieces/community/zoho-crm/package.json, packages/pieces/community/zoho-crm/src/index.ts
Adding all possible scope that user's might want in the Zoho CRM.
Fixes #4839
=> feat(zoho-crm): add more scope / add India & canada 

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/triggers/new-database-item.ts, packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
=> fix(notion): fix timeout on trigger enable

packages/pieces/community/delay/package.json, packages/pieces/community/delay/src/lib/actions/delay-for-action.ts
=> fix(delay): lower the threshold to push back to the queue

packages/pieces/community/twitter/package.json, packages/pieces/community/twitter/src/index.ts, packages/pieces/community/twitter/src/lib/actions/create-reply.ts, packages/pieces/community/twitter/src/lib/actions/create-tweet.ts, packages/pieces/community/twitter/src/lib/common/index.ts
Extends the current Twitter piece to support reply to tweets.
Fixes #4842 (issue) 
=> feat(twitter):  create reply for existing tweet action

packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts, packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
Fixes double quotes on insertions and primary key postgres
=> fix: add double quotes on insertions and primary key postgres

packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts, packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts, packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
Fixes adding the EMAIL channel as string
=> fix: adding the EMAIL channel as string

packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts, packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
Fixes alerts migrations in single query
=> feat: run alerts migration in single query

packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html, packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts, packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
* Adds tooltip on alerts "Add Email" button when disabled.
* Fixes issues description.
=> fix: alerts issues tooltip

packages/pieces/community/zoho-crm/package.json, packages/pieces/community/zoho-crm/src/index.ts, packages/pieces/community/zoho-crm/src/lib/actions/read-file.ts
Add a new action to Zoho CRM piece to download file from API endpoint. A good use case is to download the backup file or attachments.
=> feat(zoho-crm): Read file action

package-lock.json, package.json
downgrade to 2.8.10
https://github.com/tngan/samlify/issues/538
=> fix(saml): login url error

packages/server/api/src/app/database/redis-connection.ts
=> fix: redis use ssl

packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html, packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
* Adds "Manage Alerts" button from runs to navigate to alerts
* Fixes tooltips in alerts section
=> feat: add set alerts button on runs page

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.27.0

docs/install/options/aws.mdx, docs/install/options/easypanel.mdx, docs/install/options/overview.mdx
=> docs: update easypanel instructions 

packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts, packages/server/api/src/app/ee/helper/email/email-service.ts, packages/server/api/src/app/ee/otp/otp-service.ts, packages/server/api/src/assets/emails/reset-password.html, packages/server/api/src/assets/emails/verify-email.html
=> fix(auth): email flooding and shorten otp expiry 

packages/pieces/community/customer-io/.eslintrc.json, packages/pieces/community/customer-io/README.md, packages/pieces/community/customer-io/package.json, packages/pieces/community/customer-io/project.json, packages/pieces/community/customer-io/src/index.ts, packages/pieces/community/customer-io/src/lib/actions/create_event.ts, packages/pieces/community/customer-io/src/lib/common/index.ts, packages/pieces/community/customer-io/tsconfig.json, packages/pieces/community/customer-io/tsconfig.lib.json
Customer-io Piece
- Create  Event
- Track Custom API
- Base Custom API
=> feat(customer-io): create event / custom track api call / custom api call action

packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/validators/validators.ts, packages/pieces/community/odoo/package.json, packages/pieces/community/odoo/src/commom/index.ts, packages/pieces/community/odoo/src/commom/type.ts, packages/pieces/community/odoo/src/lib/actions/get-records.ts, packages/pieces/community/odoo/src/lib/actions/index.ts
Add a new action to Odoo pieces to query records of any types with any criteria.
=> feat(odoo): get custom records

packages/ee/pieces/microsoft-dynamics-365-business-central/package.json, packages/ee/pieces/microsoft-dynamics-365-business-central/src/index.ts, packages/ee/pieces/microsoft-dynamics-crm/package.json, packages/ee/pieces/microsoft-dynamics-crm/src/index.ts, packages/ee/pieces/zuora/package.json, packages/ee/pieces/zuora/src/index.ts, packages/pieces/community/customer-io/package.json, packages/pieces/community/customer-io/src/index.ts, packages/pieces/community/lever/package.json, packages/pieces/community/lever/src/index.ts
=> fix: add descriptions for pieces

packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
=> fix: basic and advanced alerts note

.github/workflows/automate-deploy.yml
=> fix: run automate deploy on merge

packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts, packages/ui/common/src/lib/service/instance-run.service.ts, packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts, packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html, packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
=> feat: selectable status filter in runs and correct redirection on failed issues

packages/ee/shared/src/lib/project/project-requests.ts, packages/ee/ui/billing/src/lib/upgrade-dialog/upgrade-dialog.component.ts, packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.html, packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.ts, packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.html, packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.ts, packages/server/api/src/app/ee/project-members/project-member.service.ts, packages/server/api/src/app/ee/project-plan/members-limit.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/project/usage/project-usage-service.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/shared/src/lib/common/telemetry.ts, packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.ts, packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html, packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
=> feat: remove team member limit on non-cloud

docs/developers/building-pieces/piece-definition.mdx, docs/developers/misc/pieces-ci-cd.mdx, docs/embedding/embed-connections.mdx, docs/mint.json
=> docs: streamline pieces ci/cd

packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/ee/issues/issues-service.ts
Ensure timezone doesn't cause unexpected behavior
=> fix: sending the timezone in email

packages/pieces/community/facebook-pages/package.json, packages/pieces/community/facebook-pages/src/index.ts
Only updates the Facebook steps to get the Client ID ans Client Secret. Previous steps seams to be obsolete.
=> chore(facebook): update auth instructions 

packages/pieces/community/gmail-dev/package.json, packages/pieces/community/gmail-dev/src/index.ts, packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/index.ts, packages/pieces/community/gmail/src/lib/common/data.ts, packages/pieces/community/gmail/src/lib/common/props.ts, packages/pieces/community/gmail/src/lib/triggers/new-email.ts
=> feat(gmail): new email trigger

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/common/client.ts, packages/pieces/community/linear/src/lib/common/props.ts
=> feat(linear): add pagination for dropdown

packages/server/api/src/app/ee/alerts/alerts-module.ts, packages/server/api/src/app/ee/git-repos/git-repo.module.ts, packages/server/api/src/app/ee/issues/issues-module.ts, packages/server/api/src/app/ee/project-members/project-member.module.ts
=> feat: entities ownership pre serialization hook

packages/ee/pieces/microsoft-dynamics-365-business-central/README.md, packages/ee/pieces/microsoft-dynamics-365-business-central/package.json, packages/ee/pieces/microsoft-dynamics-crm/README.md, packages/ee/pieces/microsoft-dynamics-crm/package.json, packages/ee/pieces/sharepoint/README.md, packages/ee/pieces/sharepoint/package.json, packages/ee/pieces/snowflake/README.md, packages/ee/pieces/snowflake/package.json, packages/ee/pieces/zuora/README.md, packages/ee/pieces/zuora/package.json
=> feat: update ee pieces readme and bump versions

packages/ee/pieces/zuora/package.json, packages/ee/pieces/zuora/src/index.ts, packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts, packages/ui/common/src/lib/service/contact-sales.service.ts, packages/ui/common/src/lib/service/platform.service.ts, packages/ui/common/src/lib/utils/consts.ts, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.html, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
=> fix: remove contact sales on non- premium piece

packages/pieces/community/acumbamail/package.json, packages/pieces/community/acumbamail/src/index.ts, packages/pieces/community/acumbamail/src/lib/actions/delete-subscriber.ts, packages/pieces/community/acumbamail/src/lib/actions/really-delete-subscriber.ts, packages/pieces/community/acumbamail/src/lib/actions/unsubscribe-subscriber.ts
This adds the action to really delete a subscriber from a list. Also, renames the previous "delete subscriber" to "unsubscribe subscriber",
https://acumbamail.com/en/apidoc/function/unsubscribeSubscriber/
https://acumbamail.com/en/apidoc/function/deleteSubscriber/
https://community.activepieces.com/t/acumbamail-integration/1473/26
=> feat(acumbamail): remove subscriber from list / unsubscribe from list.

packages/pieces/community/gravityforms/package.json, packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts, packages/pieces/community/tally/package.json, packages/pieces/community/tally/src/lib/triggers/new-submission.ts
=> fix(tally): update webhook instructions

Dockerfile
=> fix: reduce docker image size by 2gb

packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/src/app/ee/git-repos/git-sync-helper.ts, packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/webhooks/webhook-service.ts
=> fix(git): remove sample data on push

packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts, packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts, packages/server/api/src/app/flows/trigger/hooks/execute-trigger-hooks.ts, packages/server/api/src/app/flows/trigger/hooks/handshake-trigger.hook.ts, packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts, packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
=> fix: allow delete flow with piece not found

packages/pieces/community/reoon-verifier/.eslintrc.json, packages/pieces/community/reoon-verifier/README.md, packages/pieces/community/reoon-verifier/package.json, packages/pieces/community/reoon-verifier/project.json, packages/pieces/community/reoon-verifier/src/index.ts, packages/pieces/community/reoon-verifier/src/lib/actions/bulk-email-verification-status.ts, packages/pieces/community/reoon-verifier/src/lib/actions/bulk-email-verification.ts, packages/pieces/community/reoon-verifier/src/lib/actions/verify-email.ts, packages/pieces/community/reoon-verifier/src/lib/common/send-util.ts, packages/pieces/community/reoon-verifier/tsconfig.json, packages/pieces/community/reoon-verifier/tsconfig.lib.json, tsconfig.base.json
This adds a new piece [Reoon Email Verifier](https://www.reoon.com/email-verifier/).
Actions:
- Verify a single email
- Verify bulk emails
> Note: The piece name is `reoon-verifier` because Reoon has several products. `Email` is omitted because `reoon-email-verifier` would be too long, and Reeon only has one product that is used for verification.
=> feat(reoon-verifier): single email and bulk email verification actions

packages/pieces/community/maileroo/package.json, packages/pieces/community/maileroo/src/index.ts, packages/pieces/community/maileroo/src/lib/actions/send-email.ts, packages/pieces/community/maileroo/src/lib/actions/send-from-template.ts, packages/pieces/community/maileroo/src/lib/actions/verify-email.ts, packages/pieces/community/maileroo/src/lib/common/send-utils.ts
- Add Maileroo email verification action
- Supports two types of API keys(Sending and Verification)
- Add Piece categories
- Add piece description
=> feat(maileroo): verify email action

packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/src/index.ts, packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
This Pull request add a new action : update a certificationFolder
=> feat(wedof): update certificationFolder action

packages/server/api/src/app/app.ts
=> fix: exit instance on missing jwt secret

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/lib/actions/send-email.ts
=> feat(smtp): add custom headers field

package-lock.json, package.json
=> chore: upgrade posthog js

packages/pieces/community/convertkit/package.json, packages/pieces/community/framework/src/lib/validators/validators.ts, packages/pieces/community/http/package.json, packages/pieces/community/pdf/package.json, packages/pieces/community/retune/package.json, packages/pieces/community/saastic/package.json, packages/pieces/community/vtiger/package.json, packages/pieces/community/webhook/package.json, packages/shared/src/lib/common/utils/utils.ts
=> fix: build issues in lodash

package.json
=> feat: 0.28.0-rc.1

packages/engine/src/main.ts, packages/server/worker/package.json, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts, packages/server/worker/src/lib/engine/threads/worker.ts
=> feat(worker): reuse same worker across runs

packages/pieces/community/poper/package.json, packages/pieces/community/poper/src/index.ts, packages/pieces/community/poper/src/lib/triggers/new-lead.ts
Provides a new way to integrate with Poper. New method relies on Webhook thus the polling overhead.
=> feat(poper): Update new lead polling trigger to a webhook trigger

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
=> feat(google-sheets): add starting row option for get rows action

packages/pieces/community/gameball/.eslintrc.json, packages/pieces/community/gameball/README.md, packages/pieces/community/gameball/package.json, packages/pieces/community/gameball/project.json, packages/pieces/community/gameball/src/index.ts, packages/pieces/community/gameball/src/lib/actions/send-event.ts, packages/pieces/community/gameball/tsconfig.json, packages/pieces/community/gameball/tsconfig.lib.json, tsconfig.base.json
=> fix: add author to gameball

packages/pieces/community/gameball/.eslintrc.json, packages/pieces/community/gameball/README.md, packages/pieces/community/gameball/package.json, packages/pieces/community/gameball/project.json, packages/pieces/community/gameball/src/index.ts, packages/pieces/community/gameball/src/lib/actions/send-event.ts, packages/pieces/community/gameball/tsconfig.json, packages/pieces/community/gameball/tsconfig.lib.json, tsconfig.base.json
This PR adds the integration with [Gameball](https://www.gameball.co) as a piece and add basic action of sending an event to gameball systems
=> feat(gameball): add gameball piece and send-event action

packages/pieces/community/datocms/.eslintrc.json, packages/pieces/community/datocms/README.md, packages/pieces/community/datocms/package.json, packages/pieces/community/datocms/project.json, packages/pieces/community/datocms/src/index.ts, packages/pieces/community/datocms/tsconfig.json, packages/pieces/community/datocms/tsconfig.lib.json, tsconfig.base.json
Add piece for DatoCMS: https://www.datocms.com/
API docs: https://www.datocms.com/docs/content-management-api
Logo: ![color_d_icon](https://github.com/activepieces/activepieces/assets/79495/64bd0496-91bf-4dba-ae31-d07e20bcee34)
=> feat(datocms): custom api call action

package.json
=> feat: pre release 0.29.0-rc.1

package-lock.json, package.json, packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts, packages/server/worker/package.json, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
=> fix: lock sandbox prepation

package.json
=> feat: 0.29.0-rc.2

packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
=> fix: test step infinity loading by enforcing minimum workers

packages/server/api/src/app/flow-worker/worker-controller.ts, packages/server/shared/src/lib/memory-lock.ts
=> fix: is timeout lock

packages/pieces/community/xero/package.json, packages/pieces/community/xero/src/index.ts
=> fix(xero): fix refresh token issue

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/props.ts
=> feat(slack): limit dropdown to 2000 channels to avoid timeout

packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts, packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts, packages/server/api/src/app/ee/helper/email/email-service.ts, packages/server/api/src/app/ee/license-keys/license-keys-module.ts, packages/server/api/src/app/ee/projects/platform-project-module.ts, packages/server/api/src/app/ee/projects/platform-project-side-effects.ts, packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts, packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts, packages/server/api/src/app/helper/system-jobs/common.ts, packages/server/api/src/app/helper/system-jobs/job-handlers.ts, packages/server/api/src/app/helper/system-jobs/memory-system-jobs.ts, packages/server/api/src/app/helper/system-jobs/redis-system-job.ts, packages/server/api/src/app/pieces/piece-sync-service.ts, packages/server/api/src/main.ts
Fixes #[5034](https://github.com/activepieces/activepieces/issues/5034)
=> fix: make handlers static and refactor system jobs

packages/pieces/community/data-summarizer/package.json, packages/pieces/community/data-summarizer/src/index.ts
This PR updated the version and changed the category for the data summarizer piece
=> chore: updated version for data summarizer and change caterogry

docs/openapi.json, packages/server/api/src/app/app.ts, packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts, packages/shared/src/lib/invitations/index.ts
=> docs: update openai & fix user invitation api

docker-compose.yml, package-lock.json, package.json, packages/server/api/src/app/app.ts, packages/server/api/src/app/pieces/piece-sync-service.ts
=> feat: release 0.29.0

packages/engine/src/lib/services/storage.service.ts
=> fix: remove value from store

packages/server/api/src/app/workers/redis/redis-consumer.ts, packages/server/worker/src/lib/flow-worker.ts
=> fix: increase drain delay to 15 seconds

package-lock.json, package.json, packages/pieces/community/rabbitmq/.eslintrc.json, packages/pieces/community/rabbitmq/README.md, packages/pieces/community/rabbitmq/package-lock.json, packages/pieces/community/rabbitmq/package.json, packages/pieces/community/rabbitmq/project.json, packages/pieces/community/rabbitmq/src/index.ts, packages/pieces/community/rabbitmq/src/lib/actions/send-message-to-exchange.ts, packages/pieces/community/rabbitmq/src/lib/actions/send-message-to-queue.ts, packages/pieces/community/rabbitmq/src/lib/common/index.ts, packages/pieces/community/rabbitmq/src/lib/triggers/message-received.ts, packages/pieces/community/rabbitmq/tsconfig.json, packages/pieces/community/rabbitmq/tsconfig.lib.json, tsconfig.base.json
Created a piece that is able to: 
- connect to a rabbitmq queue and consume messages
- publish a message on a queue
- publish a message on an exchange
Your feedback is very much appreciated as I am not experienced with activepieces and my main programming language is not javascript.
=> feat(rabbitmq):  new message trigger / publish message on queue / publish message on exchange 

package-lock.json, package.json, packages/server/worker/package.json, packages/server/worker/src/lib/api/server-api.service.ts
=> fix: retry requests on 502

packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts, packages/server/api/src/app/ee/pieces/platform-piece-module.ts
=> fix: allow install pieces on cloud platform

packages/server/worker/src/lib/utils/code-builder.ts
=> fix: ensure file exists when testing code

docker-compose.yml, package-lock.json, package.json, packages/server/worker/src/lib/utils/code-builder.ts
=> feat: release 0.29.1

docs/developers/sharing-pieces/community.mdx, docs/developers/sharing-pieces/private.mdx, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts, tools/scripts/pieces/publish-piece.ts, tools/scripts/pieces/turbowatch.ts, tools/scripts/utils/piece-script-utils.ts
=> fix: publish piece to npm & hot reload developer experience

packages/server/api/src/app/ee/helper/email/email-service.ts
=> fix: get the day of month for issue instead of day of week

packages/server/api/src/assets/emails/issues-reminder.html
=> feat: add View Issues button in reminders

packages/pieces/community/text-helper/.eslintrc.json, packages/pieces/community/text-helper/package.json, packages/pieces/community/text-helper/src/index.ts, packages/pieces/community/text-helper/src/lib/actions/find.ts, packages/pieces/community/text-helper/src/lib/actions/replace.ts, packages/pieces/community/text-helper/src/lib/actions/split.ts, packages/pieces/community/text-helper/src/lib/actions/strip-html.ts
Add action to strip HTML tags from a string
=> feat(text-helper): remove html tags from text action

packages/pieces/community/formbricks/package.json, packages/pieces/community/formbricks/src/index.ts, packages/pieces/community/formbricks/src/lib/triggers/register.ts
=> fix(formbricks):  survey dropdown error 

packages/server/worker/src/lib/flow-worker.ts
=> fix: limit to open polling connections to 10

docs/embedding/provision-users.mdx, packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
=> feat(embedding): add tasks limit to the jwt token

package-lock.json, package.json, packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/actions/add-note-to-conversation.ts, packages/pieces/community/intercom/src/lib/actions/create-contact.action.ts, packages/pieces/community/intercom/src/lib/actions/create-or-get-contact.action.ts, packages/pieces/community/intercom/src/lib/actions/reply-to-conversation.ts, packages/pieces/community/intercom/src/lib/actions/send-message.action.ts, packages/pieces/community/intercom/src/lib/common/index.ts, packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
- Switch to official SDK
- Add support for Europe and Australia regions (different URLs)
- Add actions to reply / add a note to an existing conversation
=> feat(intercom): add support for EU and AU regions, add new actions

packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts
=> fix: global lock pnpm add

packages/pieces/community/todoist/package.json, packages/pieces/community/todoist/src/lib/actions/create-task-action.ts, packages/pieces/community/todoist/src/lib/actions/update-task.action.ts, packages/pieces/community/todoist/src/lib/common/client/rest-client.ts, packages/pieces/community/todoist/src/lib/common/models.ts
Todoist API supports natural language due dates. This PR enables this for the Create Task and Update Task actions
=> feat(todoist): add support for natural language due dates

packages/server/worker/src/lib/executors/repeating-job-executor.ts
=> fix: ignore disabled flows

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts, packages/ui/common/src/lib/service/app-connections.service.ts
=> fix: support query by multiple status

package-lock.json, package.json, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts, packages/server/api/src/app/app-connection/app-connection.controller.ts, packages/server/api/src/app/ee/git-repos/git-repo.module.ts, packages/server/api/src/app/ee/project-members/project-member.controller.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/lib/flows/dto/list-flows-request.ts, packages/shared/src/lib/flows/flow-operations.ts, packages/ui/common/src/lib/service/flow.service.ts
=> chore: upgrade typebox

packages/server/shared/package.json, packages/server/worker/src/lib/piece-manager/piece-manager.ts, packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts, packages/server/worker/src/lib/utils/cache-handler.ts, packages/server/worker/src/lib/utils/code-builder.ts
=> feat: persist the cache across restarts

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/request-approval-direct-message.ts, packages/pieces/community/slack/src/lib/actions/request-approval-message.ts
=> fix(slack): fix request approval action output

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/trigger/update-record.trigger.ts
=> fix(airtable): use datetime formula to fetch updated records

packages/react-ui/src/features/flow-canvas/components/big-button.tsx, packages/react-ui/src/features/flow-canvas/components/canvas.tsx, packages/react-ui/src/features/flow-canvas/lib/flow-canvas-utils.ts
=> feat: graph rendering for loops & branches

packages/react-ui/src/features/alerts/components/add-alert-email-dialog.tsx, packages/react-ui/src/features/flow-canvas/components/canvas.tsx, packages/react-ui/src/features/flow-canvas/components/edge-with-button.tsx, packages/react-ui/src/features/flow-canvas/lib/flow-canvas-utils.ts, packages/react-ui/src/features/issues/hooks/issue-hooks.tsx, packages/react-ui/src/features/pieces/components/piece-card-info.tsx, packages/react-ui/src/features/pieces/lib/pieces-hook.ts, packages/react-ui/src/features/team/lib/project-members-api.ts, packages/server/worker/src/lib/utils/code-builder.ts
=> fix: merge rendering into feat/react

packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/react-ui/src/features/authentication/components/reset-password-form.tsx, packages/react-ui/src/features/authentication/components/username-and-password-form.tsx
=> feat: enhanche auth styling

packages/ui/core/nginx.standard.conf
There was an issue in Bull Board UI: it is not loading on self-host w/ official AP docker image
I have fixed the nginx configuration file, It was blocking the static files from being loaded.
=> chore: fix /api/ui loading static issue

packages/pieces/community/aminos/.eslintrc.json, packages/pieces/community/aminos/README.md, packages/pieces/community/aminos/package.json, packages/pieces/community/aminos/project.json, packages/pieces/community/aminos/src/index.ts, packages/pieces/community/aminos/src/lib/actions/createUser.ts, packages/pieces/community/aminos/tsconfig.json, packages/pieces/community/aminos/tsconfig.lib.json, tsconfig.base.json
=> feat(aminos): create user action

packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/react-ui/src/features/authentication/components/sign-in-form.tsx, packages/react-ui/src/features/authentication/components/sign-up-form.tsx
=> fix: separate sign in and sign up forms

packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx, packages/react-ui/src/app/builder/flow-versions/flow-versions-list.tsx, packages/react-ui/src/app/builder/run-details/flow-run-details-list.tsx, packages/react-ui/src/app/routes/flows/id/index.tsx, packages/react-ui/src/components/ui/avatar-letter.tsx, packages/react-ui/src/components/ui/card-list.tsx, packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/react-ui/src/features/authentication/components/sign-in-form.tsx, packages/react-ui/src/features/authentication/components/sign-up-form.tsx, packages/react-ui/src/features/flow-canvas/components/builder-nav-bar.tsx, packages/react-ui/src/features/flows/lib/flows-api.ts, packages/react-ui/src/lib/utils.ts, packages/react-ui/src/styles.css, packages/react-ui/tailwind.config.js
=> feat: version sidebar

packages/react-ui/src/app/builder/builder-page.tsx, packages/react-ui/src/app/builder/run-list/flow-run-card.tsx, packages/react-ui/src/features/flow-runs/components/flow-runs-table.tsx, packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx, packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts, packages/react-ui/src/hooks/builder-hooks.ts
=> feat: flow runs list

packages/react-ui/src/features/authentication/components/sign-up-form.tsx, packages/react-ui/src/features/authentication/lib/password-validation-utils.ts
=> feat: add password validator

packages/react-ui/src/features/authentication/components/sign-up-form.tsx
=> fix: handle when password first initialized in the form

packages/react-ui/src/app/builder/flow-canvas/canvas.tsx, packages/react-ui/src/app/builder/flow-canvas/edges/edge-with-button.tsx, packages/react-ui/src/app/builder/flow-canvas/edges/return-loop-edge.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
=> fix: graph stroke

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/actions/update-record.ts, packages/pieces/community/airtable/src/lib/common/index.ts
=> fix(airtable): fix linked record field update issue

packages/server/api/src/app/workers/worker-controller.ts, packages/server/shared/src/lib/job/job-data.ts
=> fix: make progress update optional for old delayed runs

packages/react-ui/src/features/flows/components/flow-actions-menu.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
=> fix: add loaders

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
=> fix: remove merge conflicts

packages/server/api/src/app/app-event-routing/app-event-routing.module.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts, packages/server/api/src/app/workers/engine-controller.ts, packages/server/api/src/app/workers/queue/queue-manager.ts, packages/server/api/src/app/workers/redis/redis-queue.ts, packages/shared/src/lib/engine/requests.ts
=> fix: worker optional progress update

packages/engine/src/lib/handler/context/engine-constants.ts, packages/server/api/src/app/project/project-service.ts, packages/server/api/src/app/workers/queue/queue-manager.ts
Change the retryExponential value from 6 to 4 & make the function get job priority to query on the platform id only instead of querying on the full project
=> feat: optimize get job priority & update retryExponential value

packages/server/api/src/app/ee/git-repos/git-repo.service.ts, packages/server/api/src/app/ee/git-repos/git-sync-helper.ts, packages/shared/src/lib/flows/flow-helper.ts
Fix overriding the secrets when pulling it from the Github Repo
=> fix(git-sync): prevent overriding secrets after being modified on production branch

docs/handbook/engineering/pre-releases.mdx, docs/mint.json, package.json
This PR adds documentation on how to create a pre-release and deploy it.
=> feat: document pre-releases

docs/handbook/engineering/pre-releases.mdx
=> docs: update the pre release steps

packages/react-ui/src/components/ui/data-table-input-popover.tsx, packages/react-ui/src/features/flow-runs/components/flow-runs-table.tsx, packages/react-ui/src/features/flows/components/flow-actions-menu.tsx, packages/react-ui/src/features/flows/components/flow-table.tsx, packages/react-ui/src/features/pieces/components/piece-table.tsx, packages/react-ui/src/features/pieces/lib/pieces-api.ts
* Fixes debouncing the input filter in table
* Fixes padding space around the dropdown action menu in the table row
* Makes clicking on flow run go to the builder by flow id
* Fixes spacing in piece table for the table header
* Delete piece functionality and allowing to delete installed pieces only and not all pieces
=> fix: polishing

packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts, packages/server/api/src/app/workers/redis/redis-queue.ts
=> fix: remove stale scheduled jobs

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
=> feat(google-sheets): add next rows action markdown

packages/pieces/community/monday/package.json, packages/pieces/community/monday/src/index.ts, packages/pieces/community/monday/src/lib/actions/upload-file-to-column.ts
=> feat(monday): upload file to column action

packages/pieces/community/google-calendar/package.json, packages/pieces/community/google-calendar/src/lib/actions/get-events.ts
=> feat(google-calendar): add search term to find events

packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts, packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts, packages/server/api/src/app/workers/memory/memory-queue.ts, packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
This PR handles when the piece is not found does not throw an exception logs the error and ignores it
The second thing is adding limitations for memory.
=> fix: handle the null when building pieces

packages/server/api/src/app/pieces/piece-metadata-service/index.ts, packages/server/shared/src/lib/system/system.ts
=> fix: resolve dropdown options by relative version

package.json
=> feat: pre release 0.30.0-rc.4

packages/pieces/community/google-forms/package.json, packages/pieces/community/google-forms/src/lib/triggers/new-form-response.ts
=> fix(google-forms): handle empty response

packages/pieces/community/amazon-s3/package.json, packages/pieces/community/amazon-s3/src/lib/actions/upload-file.ts
=> fix(amazon-s3): fix ACL type error

packages/engine/src/lib/helper/logging-utils.ts
=> fix(log-truncation): treat array as leaf node

packages/engine/src/lib/helper/error-handling.ts, packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/storage.service.ts, packages/server/worker/package.json
=> fix: mark the storage limit failure as user errors

Dockerfile, packages/pieces/community/queue/src/lib/actions/push-to-queue.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/workers/redis/redis-consumer.ts
=> fix: rebuild from engine cache

docs/flows/known-limits.mdx, docs/mint.json, packages/engine/src/lib/services/storage.service.ts, packages/pieces/community/queue/package.json, packages/server/api/src/app/store-entry/store-entry.controller.ts, packages/shared/src/lib/store-entry/store-entry.ts
=> fix: enforce store limit

packages/engine/src/lib/handler/piece-executor.ts
=> fix: count failed step

packages/react-ui/src/app/builder/builder-nav-bar.tsx, packages/react-ui/src/features/flows/components/flow-table.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx
=> fix: make the folder in builder clickable and use search params for folderId

packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/builder-nav-bar.tsx, packages/react-ui/src/app/builder/data-selector/data-selector-utils.ts, packages/react-ui/src/app/builder/data-selector/test-step-section.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts, packages/react-ui/src/app/builder/pieces-selector/piece-selector-list.tsx, packages/react-ui/src/app/builder/run-details/flow-step-details-card-item.tsx, packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx, packages/react-ui/src/app/builder/run-details/loop-iteration-input.tsx, packages/react-ui/src/app/builder/run-list/flow-run-card.tsx, packages/react-ui/src/app/builder/step-settings/step-settings-container.tsx, packages/react-ui/src/app/builder/test-step/test-action-section.tsx, packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx, packages/react-ui/src/app/builder/test-step/test-step-utils.ts, packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx, packages/react-ui/src/features/flows/components/flow-table.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx, packages/react-ui/src/lib/utils.ts
=> fix: run details view

packages/pieces/community/gravityforms/package.json, packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts
=> fix(gravity-forms): fix webhook test issue

packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix: allow leaky rate limit

packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix(redis-rate-limit): always decrease jobs on complete / failure

packages/react-ui/src/features/authentication/components/sign-up-form.tsx
=> fix: add validation for email in sign up

packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/builder-page.tsx, packages/react-ui/src/app/builder/flow-canvas/test-flow-widget.tsx, packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx, packages/react-ui/src/app/builder/piece-properties/dynamic-dropdown-piece-property.tsx, packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx, packages/react-ui/src/app/connections/new-connection-type-dialog.tsx, packages/react-ui/src/app/router.tsx, packages/react-ui/src/app/routes/runs/id/index.tsx, packages/react-ui/src/components/ui/carousel.tsx, packages/react-ui/src/features/flow-runs/components/flow-runs-table.tsx, packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx, packages/react-ui/src/features/flows/components/flow-table.tsx, packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx, packages/react-ui/src/features/pieces/components/piece-icon-list.tsx, packages/react-ui/src/features/templates/lib/templates-api.ts
=> fix: run view & dynamic props

packages/react-ui/src/features/flow-runs/components/flow-runs-table.tsx, packages/react-ui/src/features/flow-runs/lib/flow-runs-api.ts, packages/react-ui/src/lib/api.ts
=> feat: add runs action menu and wrap authorization around it

packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix(redis-rate-limiter): revert the old strategy for checking the rate limit 

packages/react-ui/src/app/builder/flow-canvas/test-flow-widget.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-with-mentions.tsx, packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx, packages/react-ui/src/styles.css, packages/react-ui/tailwind.config.js
- Added two shades for warning / primary
- Complete Settings Navigate to Invalid Step
- Run Details Show the correct Text
- Fixed the style for Test Flow and Complete Settings
=> style: test flow / complete settings button / run details snackbar

package-lock.json, package.json, packages/react-ui/src/app/app.tsx, packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/flow-canvas/flow-canvas.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/flow-canvas/test-flow-widget.tsx, packages/react-ui/src/app/builder/run-details/flow-step-details-card-item.tsx, packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx, packages/react-ui/src/app/components/allow-logged-in-user-only-guard.tsx, packages/react-ui/src/app/components/image-with-fallback.tsx, packages/react-ui/src/app/router.tsx, packages/react-ui/src/components/socket-provider.tsx, packages/react-ui/src/features/flow-runs/components/step-status-icon.tsx, packages/react-ui/src/lib/authentication-session.ts, packages/react-ui/src/styles.css, packages/server/api/src/app/webhooks/webhook-controller.ts
=> refactor: remove duplicate allowed logged in

packages/react-ui/src/app/builder/step-settings/code-settings/code-editior.tsx, packages/react-ui/src/lib/api.ts
=> fix: cors add package

packages/server/api/src/app/flows/flow-version/flow-version.service.ts
=> fix: number validation

packages/react-ui/src/app/builder/builder-publish-button.tsx, packages/react-ui/src/app/builder/flow-canvas/edges/edge-with-button.tsx, packages/react-ui/src/app/builder/flow-canvas/flow-canvas.tsx, packages/react-ui/src/app/builder/flow-canvas/flow-drag-layer.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/features/flows/components/rename-flow-dialog.tsx, packages/react-ui/src/styles.css
=> fix: drag and drop

packages/react-ui/src/app/builder/builder-page.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx, packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/step-settings/piece-settings/piece-settings.tsx, packages/react-ui/src/app/builder/step-settings/step-settings-container.tsx, packages/react-ui/src/app/connections/oauth2-connection-settings.tsx, packages/react-ui/src/components/custom/searchable-select.tsx
=> fix: add oauth2 props

packages/pieces/community/claude/package.json, packages/pieces/community/claude/src/lib/actions/send-prompt.ts
=> fix(claude): fix ask claude response error

packages/pieces/community/framework/src/lib/property/index.ts, packages/pieces/community/framework/src/lib/property/input/array-property.ts, packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
=> feat: support array of objects

packages/react-ui/src/app/builder/step-settings/code-settings/code-editior.tsx, packages/react-ui/src/app/builder/step-settings/code-settings/code-settings.tsx, packages/react-ui/src/components/ui/button.tsx, packages/react-ui/src/features/pieces/lib/pieces-api.ts
=> fix: keyboard shortcut

package-lock.json, package.json, packages/ee/shared/src/lib/audit-events/index.ts, packages/server/api/src/app/database/migration/postgres/1723489038729-MigrateAuditEventSchema.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/audit-logs/audit-event-entity.ts, packages/server/api/src/app/ee/audit-logs/audit-event-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/app/workers/redis/redis-consumer.ts, packages/server/shared/package.json, packages/server/worker/src/lib/engine/flow-enginer-util.ts, packages/shared/src/lib/flow-run/flow-run.ts, packages/shared/src/lib/pieces/dto/piece-requests.ts
=> fix: audit events schema

packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
=> fix: event routing

package.json
=> feat: 0.30.0-rc.5

packages/server/api/src/app/app-event-routing/app-event-routing.module.ts, packages/server/api/src/app/copilot/copilot.module.ts, packages/server/api/src/app/copilot/copilot.service.ts, packages/shared/src/lib/copilot/index.ts, packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.html, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html
=> fix: improve and disable ask ai on angular

packages/react-ui/src/app/builder/ai-chat/chat-message.tsx, packages/react-ui/src/app/builder/ai-chat/chat-sidebar.tsx, packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/builder-nav-bar.tsx, packages/react-ui/src/app/builder/builder-page.tsx, packages/react-ui/src/app/builder/step-settings/code-settings/code-editior.tsx
AI chatbot that generates code
=> Feat/react AI chatbot

packages/server/api/src/app/app-event-routing/app-event-routing.entity.ts, packages/server/api/src/app/app-event-routing/app-event-routing.service.ts, packages/server/api/src/app/database/migration/common/1723549873495-ChangeEventRoutingConstraint.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts
=> fix: db index on app event routing

package.json
=> feat: 0.30.0-rc.6 release

packages/pieces/community/rabbitmq/package.json, packages/pieces/community/rabbitmq/src/index.ts, packages/pieces/community/rabbitmq/src/lib/common/index.ts
Implement functionality to specify and use RabbitMQ virtual hosts.
=> feat(rabbitmq): add support for vhosts

packages/react-ui/src/app/components/header.tsx, packages/react-ui/src/app/components/platform-admin-container.tsx, packages/react-ui/src/app/components/sidebar.tsx, packages/react-ui/src/app/router.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx, packages/react-ui/src/features/folders/lib/folders-api.tsx, packages/react-ui/src/features/folders/lib/folders-hooks.tsx
=> fix: hidden folders

packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/src/index.ts, packages/pieces/community/wedof/src/lib/actions/certification-folder-survey/get-certification-folder-survey.ts, packages/pieces/community/wedof/src/lib/actions/certification-folder-survey/list-certification-folder-surveys.ts, packages/pieces/community/wedof/src/lib/common/wedof.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-answered.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-available.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-answered.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-available.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-answered.ts, packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-available.ts
=> feat(wedof): adding cfsurveys triggers / actions

packages/react-ui/src/hooks/flags-hooks.ts, packages/react-ui/src/hooks/platform-hooks.ts, packages/react-ui/src/hooks/project-hooks.ts
=> fix: add stale time

packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
=> fix: app event routing

package.json
=> feat: 0.30.0-rc.7

docs/openapi.json, packages/shared/src/lib/invitations/index.ts
=> fix: type.null() issue with swagger in user invitation

packages/react-ui/src/app/builder/flow-canvas/canvas-controls.tsx, packages/react-ui/src/app/builder/flow-canvas/index.tsx
=> feat: custom canvas control

packages/server/worker/src/lib/utils/cache-handler.ts, packages/server/worker/src/lib/utils/engine-installer.ts
=> fix: make engine reinstall across restarts and make file copying atomic

packages/react-ui/src/app/builder/run-details/flow-step-details-card-item.tsx, packages/react-ui/src/app/builder/run-details/index.tsx, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/connections/oauth2-connection-settings.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/components/ui/card-list.tsx, packages/react-ui/src/components/ui/editable-text.tsx, packages/react-ui/src/features/flows/lib/flows-api.ts, packages/react-ui/src/features/issues/components/issues-table.tsx, packages/react-ui/src/features/pieces/lib/pieces-hook.ts
=> fix: socket listener

packages/react-ui/src/app/components/platform-admin-container.tsx, packages/react-ui/src/app/components/sidebar.tsx, packages/react-ui/src/app/routes/platform/users/index.tsx
=> fix: locks on platform

packages/server/worker/package.json, packages/server/worker/src/lib/utils/cache-handler.ts, packages/server/worker/src/lib/utils/engine-installer.ts
=> fix(engine): use dest folder as installation path instead of src

packages/engine/src/lib/helper/trigger-helper.ts, packages/server/api/src/app/flags/flag.service.ts, packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts, packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts, packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts, packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts, packages/server/worker/src/lib/trigger/hooks/extract-trigger-payload-hooks.ts, packages/server/worker/src/lib/trigger/hooks/handshake-trigger.hook.ts, packages/server/worker/src/lib/trigger/hooks/renew-trigger-hook.ts, packages/shared/src/lib/engine/engine-operation.ts
=> fix: use test scope on the trigger operations

package.json
=> feat: 0.30.0-rc.8

docs/openapi.json, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
=> feat: allow filter runs by more than one flow

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/features/flows/lib/flows-api.ts
=> feat: show running stauts when run started

packages/react-ui/src/app/components/platform-admin-container.tsx, packages/react-ui/src/app/components/platform-settings-layout.tsx, packages/react-ui/src/app/router.tsx, packages/react-ui/src/app/routes/flows/id/index.tsx, packages/react-ui/src/app/routes/platform/audit-logs/index.tsx, packages/react-ui/src/app/routes/platform/projects/index.tsx, packages/react-ui/src/app/routes/platform/projects/new-project-dialog.tsx, packages/react-ui/src/app/routes/platform/settings/api-keys/index.tsx, packages/react-ui/src/app/routes/platform/settings/api-keys/new-api-key-dialog.tsx, packages/react-ui/src/app/routes/platform/settings/signing-keys/index.tsx, packages/react-ui/src/app/routes/platform/settings/signing-keys/new-signing-key-dialog.tsx, packages/react-ui/src/app/routes/platform/templates/index.tsx, packages/react-ui/src/app/routes/platform/users/index.tsx, packages/react-ui/src/components/custom/copy-to-clipboard.tsx, packages/react-ui/src/features/flow-runs/components/flow-runs-table.tsx, packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
=> feat: add api keys

packages/react-ui/src/app/routes/change-password/index.tsx, packages/react-ui/src/app/routes/forget-password/index.tsx, packages/react-ui/src/app/routes/platform/settings/branding/add-custom-domain.tsx, packages/react-ui/src/app/routes/platform/settings/branding/appearance-section.tsx, packages/react-ui/src/app/routes/platform/settings/branding/custom-domain-section.tsx, packages/react-ui/src/app/routes/platform/settings/branding/index.tsx, packages/react-ui/src/app/routes/platform/settings/branding/smtp-section.tsx, packages/react-ui/src/app/routes/sign-in/index.tsx, packages/react-ui/src/app/routes/sign-up/index.tsx, packages/react-ui/src/app/routes/templates/share-template.tsx, packages/react-ui/src/components/ui/color-picker.tsx, packages/react-ui/src/hooks/flags-hooks.ts
=> feat: introduce branding / custom domains /  mail server

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/index.ts, packages/pieces/community/google-drive/src/lib/action/delete-file.ts, packages/pieces/community/google-drive/src/lib/action/send-to-trash.ts
this adds two new actions to the GDrive piece: "Delete file" and "Trash file"
https://community.activepieces.com/t/deleting-files-in-google-drive/5588
=> feat(google-drive): delete file and send file to trash actions

packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/routes/platform/settings/branding/appearance-section.tsx
=> fix: piece validation

packages/pieces/community/http/package.json, packages/pieces/community/http/src/lib/actions/return-response.ts, packages/server/worker/package.json
=> fix(http): parse json body only if string

packages/engine/src/lib/helper/trigger-helper.ts, packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts, packages/server/worker/src/lib/trigger/hooks/handshake-trigger.hook.ts, packages/shared/src/lib/common/activepieces-error.ts, packages/shared/src/lib/flows/actions/action.ts, packages/shared/src/lib/flows/triggers/trigger.ts
=> fix: actionName or triggerName should be optional

packages/react-ui/src/app/builder/flow-canvas/index.tsx, packages/react-ui/src/app/builder/index.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/components/show-powered-by.tsx, packages/react-ui/src/features/forms/components/ap-form.tsx
=> feat: add powered by

packages/react-ui/src/components/show-powered-by.tsx, packages/react-ui/src/features/forms/components/ap-form.tsx
=> fix: built with badge

packages/ui/common/src/lib/service/telemetry.service.ts
=> feat: switch to react based on flag

packages/server/api/src/app/workers/engine-controller.ts
=> fix: include internal error in message

packages/server/api/src/app/ee/flow-template/flow-template.service.ts, packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts, packages/server/api/src/app/store-entry/store-entry.service.ts, packages/server/api/src/app/workers/engine-controller.ts, packages/shared/src/lib/common/utils/object-utils.ts
=> fix: handling unicode sequences in json-type columns of postgresql

docs/developers/piece-reference/properties-validation.mdx, packages/pieces/community/linkedin/package.json
=> docs(framework): deprecate processors

packages/shared/src/lib/common/utils/object-utils.ts
=> fix: santize null charater

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
A hardcoded 120s timeout is too limited
=> feat(dust): make timeout customizable

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/index.ts, packages/pieces/community/airtable/src/lib/actions/upload-file-to-column.ts, packages/pieces/community/airtable/src/lib/common/index.ts
Fixes [issue](https://community.activepieces.com/t/update-airtable-record-piece-error/5636/2)
=> fix(airtable): fix empty attachment field update issue and upload file action

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/lib/common/client.ts, packages/pieces/community/apitable/src/lib/common/index.ts
=> fix(apitable): fix member field options

packages/pieces/community/hubspot/package.json, packages/pieces/community/hubspot/src/lib/actions/create-deal.ts
=> feat(hubspot): add amount property for deal action

packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/services/files.service.ts, packages/server/api/src/app/flows/flow-run/log-serializer.ts
=> fix: trigger files should be stored in db

packages/react-ui/src/app/app.tsx, packages/react-ui/src/app/builder/builder-header.tsx, packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/components/allow-logged-in-user-only-guard.tsx, packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/app/components/header.tsx, packages/react-ui/src/app/components/intial-data-guard.tsx, packages/react-ui/src/app/components/locked-feature-guard.tsx, packages/react-ui/src/app/components/request-trial.tsx, packages/react-ui/src/app/routes/flows/id/index.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/app/routes/platform/audit-logs/index.tsx, packages/react-ui/src/app/routes/platform/pieces/index.tsx, packages/react-ui/src/app/routes/platform/projects/index.tsx, packages/react-ui/src/app/routes/platform/settings/api-keys/index.tsx, packages/react-ui/src/app/routes/platform/settings/branding/index.tsx, packages/react-ui/src/app/routes/platform/settings/signing-keys/index.tsx, packages/react-ui/src/app/routes/platform/settings/sso/index.tsx, packages/react-ui/src/app/routes/platform/templates/index.tsx, packages/react-ui/src/app/routes/platform/users/index.tsx, packages/react-ui/src/app/routes/settings/git-sync/index.tsx, packages/react-ui/src/components/telemetry-provider.tsx, packages/react-ui/src/components/ui/report-bugs-button.tsx, packages/react-ui/src/components/ui/user-avatar.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx, packages/react-ui/src/lib/authentication-session.ts
=> feat: enable telemetry

packages/react-ui/src/components/json-viewer.tsx, packages/react-ui/src/lib/utils.ts
=> fix: test step shouldnot change format of data

packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx, packages/react-ui/src/app/connections/custom-auth-connection-settings.tsx
=> fix: custom authentication property

docs/about/license.mdx
Commit f75e9c8f4a5316a18d70220b4cdab717a28840c0 renamed the commercial license file. This PR adjusts sources to changes.
=> docs: update commercial license reference

Dockerfile, packages/react-ui/src/lib/api.ts
=> chore: docker file for react

packages/react-ui/src/app/connections/basic-secret-connection-settings.tsx, packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx, packages/react-ui/src/app/connections/oauth2-connection-settings.tsx, packages/react-ui/src/app/connections/secret-text-connection-settings.tsx, packages/react-ui/src/app/routes/platform/settings/api-keys/index.tsx, packages/react-ui/src/app/routes/platform/settings/api-keys/new-api-key-dialog.tsx
=> fix: validate connections

packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/step-settings/branch-settings/branch-condition-group.tsx, packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx, packages/react-ui/src/app/builder/step-settings/branch-settings/index.tsx, packages/react-ui/src/components/json-viewer.tsx
=> fix: branch conditions

packages/react-ui/src/app/builder/builder-header.tsx, packages/react-ui/src/components/ui/report-bugs-button.tsx
=> fix: show support based on flag

packages/react-ui/src/components/ui/data-table.tsx
=> fix: add rows per page

docs/openapi.json, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts, packages/shared/src/lib/invitations/index.ts, packages/ui/common/src/lib/service/user-invitations.service.ts
=> feat: allow user invitation via API and control duration 

packages/pieces/community/dropbox/package.json, packages/pieces/community/dropbox/src/index.ts
=> fix(dropbox): add token_access_type param to avail refresh token

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/lib/actions/find-record.ts, packages/pieces/community/apitable/src/lib/actions/update-record.ts
=> fix(ai-table): handle empty array

package-lock.json, package.json, packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts, packages/react-ui/src/app/builder/step-settings/index.tsx
=> fix: arrays

packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
=> fix: array step selection

packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
=> fix: prevent auth from being deleted

packages/react-ui/src/app/routes/runs/index.tsx, packages/react-ui/src/components/ui/data-table.tsx, packages/react-ui/src/features/flow-runs/lib/flow-runs-api.ts, packages/server/api/src/app/flows/flow-run/flow-run-controller.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix: retry run

packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx, packages/react-ui/src/app/builder/flow-versions/index.tsx, packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx, packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx, packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx, packages/react-ui/src/app/routes/runs/index.tsx, packages/react-ui/src/components/ui/data-table.tsx
=> fix: dynamic value in connections & verison numbers

packages/react-ui/src/features/issues/components/issues-table.tsx, packages/react-ui/src/features/plans/api/billing-api.ts, packages/react-ui/src/features/plans/components/plans.tsx
=> fix: pay as you go plan

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/get-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
Return the error message (if any) and add action to simply get an existing conversation content
=> feat(dust): improve error management and add action to get existing conversation

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
=> fix(google-sheets): fix update row action input

packages/react-ui/src/app/builder/step-settings/branch-settings/index.tsx
=> fix: add or branch

packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/engine/src/lib/variables/variable-service.ts, packages/engine/test/handler/flow-with-pause.test.ts, packages/engine/test/services/variable-service.test.ts
This PR fixes the bug of executing the two branches of a conditional node
=> fix: empty variable resolving when delay is used inside loop

packages/server/api/src/app/database/migration/common/1725570317713-RemoveUniqueConstraintOnStepFile.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/step-file/step-file.entity.ts, packages/server/api/src/app/flows/step-file/step-file.service.ts
=> fix: step file should not be unique

packages/pieces/community/perplexity-ai/.eslintrc.json, packages/pieces/community/perplexity-ai/README.md, packages/pieces/community/perplexity-ai/package.json, packages/pieces/community/perplexity-ai/project.json, packages/pieces/community/perplexity-ai/src/index.ts, packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts, packages/pieces/community/perplexity-ai/tsconfig.json, packages/pieces/community/perplexity-ai/tsconfig.lib.json, tsconfig.base.json
=> feat(perplexity-ai): create chat completion action

packages/pieces/community/perplexity-ai/package.json, packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts
=> fix(perplexity-ai): change action name to Ask AI

.devcontainer/docker-compose.yml, packages/server/api/src/app/database/migration/postgres/1725639666232-LogFileRelationWithFlowRun.ts, packages/server/api/src/app/database/migration/sqlite/1725637505836-LogFileRelationWithFlowRun.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
=> fix: add constraint to log to file_run

packages/server/api/src/app/database/migration/postgres/1725639666232-LogFileRelationWithFlowRun.ts, packages/server/api/src/app/database/migration/sqlite/1725637505836-LogFileRelationWithFlowRunSqlite.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/shared/src/lib/file/file-type.ts
=> chore: remove deprecated code files

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/index.ts
=> fix(apitable): remove AI category

packages/react-ui/src/app/builder/pieces-selector/index.tsx
=> style: fix typo in piece selector

packages/pieces/community/imap/src/index.ts, packages/pieces/community/imap/src/lib/common/index.ts, packages/pieces/community/imap/src/lib/triggers/new-email.ts
=> fix(imap): enhance speed by filtering emails first

packages/pieces/community/imap/package.json
=> chore: bump imap version

.vscode/settings.json, packages/server/api/src/app/flows/flow-run/flow-run-module.ts, packages/server/api/src/app/workers/redis/redis-bullboard.ts
=> fix: batch delete run logs

packages/server/api/src/app/ee/analytics/analytics.module.ts, packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
=> fix: add piece analytics back

packages/server/api/src/app/database/migration/postgres/1725699690971-AddLogsFileIdIndex.ts, packages/server/api/src/app/database/migration/sqlite/1725699920020-AddLogsFileIdIndexSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/file/file.entity.ts, packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
=> chore: add missing index on flow run / file table

packages/pieces/community/actualbudget/package.json, packages/pieces/community/actualbudget/src/index.ts, packages/pieces/community/actualbudget/src/lib/actions/get-accounts.ts, packages/pieces/community/actualbudget/src/lib/actions/get-budget.ts, packages/pieces/community/actualbudget/src/lib/actions/get-categories.ts, packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts, packages/pieces/community/actualbudget/src/lib/actions/import-transactions.ts, packages/pieces/community/actualbudget/src/lib/common/common.ts
Corrects spelling, refactors dropdown logic and adds contributors for the Actual Budget piece
=> fix(actualbudget): refactor year/month dropdown options

docs/endpoints/flow-templates/create.mdx, docs/endpoints/flow-templates/delete.mdx, docs/endpoints/flow-templates/get.mdx, docs/endpoints/flow-templates/list.mdx, docs/endpoints/flow-templates/schema.mdx, docs/mint.json, docs/openapi.json, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts, packages/server/api/src/app/flags/flag.service.ts
=> docs: flow templates endpoint

.github/workflows/release.yml, Dockerfile, docker-compose.yml, package-lock.json, package.json, packages/engine/src/lib/variables/variable-service.ts, packages/react-ui/src/app/components/locked-feature-guard.tsx, packages/react-ui/src/app/components/project-settings-layout.tsx, packages/react-ui/src/app/components/request-trial.tsx, packages/react-ui/src/app/routes/issues/index.tsx, packages/react-ui/src/app/routes/settings/team/index.tsx, packages/react-ui/src/features/authentication/components/sign-in-form.tsx, packages/react-ui/src/features/authentication/components/sign-up-form.tsx
=> feat: release 0.30.0

packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
=> feat(user-invitation): auto accept invitation through api keys

packages/pieces/community/common/src/lib/ai/index.ts, packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts, packages/pieces/community/common/src/lib/ai/providers/openai/index.ts, packages/server/api/src/app/ai/ai-provider.module.ts
=> fix: AI proxy urls

packages/server/api/src/app/user-invitations/user-invitation.service.ts
=> fix: skip sending email on duplicate invitation

packages/server/api/src/app/app.ts
=> fix: accept other non hex characters in encryption key

packages/server/api/src/app/ee/analytics/analytics.module.ts, packages/server/api/src/app/ee/analytics/analytics.service.ts
=> fix: analytics dashboard

packages/server/api/src/app/pieces/piece-metadata-service/index.ts
=> fix: resolve options for private piece with absolute verison

packages/server/api/src/app/app-connection/app-connection.controller.ts, packages/server/api/src/app/authentication/authentication.controller.ts, packages/server/api/src/app/ee/analytics/analytics.service.ts, packages/server/api/src/app/ee/audit-logs/audit-event-service.ts, packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts, packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts, packages/server/api/src/app/ee/signing-key/signing-key-controller.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/flows/folder/folder.module.ts, packages/server/api/src/app/helper/application-events/index.ts
=> fix: signed in users in last 30 days

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.31.0

docs/endpoints/user-invitations/upsert.mdx, docs/mint.json, packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/index.ts, packages/react-ui/src/app/routes/settings/team/index.tsx, packages/react-ui/src/features/projects/components/project-switcher.tsx, packages/react-ui/src/features/team/component/invite-user-dialog.tsx, packages/react-ui/src/features/team/component/project-member-card.tsx, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/server/api/test/integration/cloud/project-members/project-members.test.ts, packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts, packages/shared/src/lib/invitations/index.ts
=> fix: send user invitation validation & remove project member endpoint

package.json
=> feat: 0.32.0-rc.1 pre release

package.json
=> feat: release 0.32.0-rc.2

packages/pieces/community/assemblyai/package.json, packages/pieces/community/assemblyai/src/index.ts, packages/pieces/community/assemblyai/src/lib/actions/files/upload.ts, packages/pieces/community/assemblyai/src/lib/actions/lemur/get-lemur-response.ts, packages/pieces/community/assemblyai/src/lib/actions/lemur/lemur-task.ts, packages/pieces/community/assemblyai/src/lib/actions/lemur/purge-lemur-request-data.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/delete-transcript.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-paragraphs.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-redacted-audio.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-sentences.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-subtitles.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-transcript.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/list-transcripts.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/transcribe.ts, packages/pieces/community/assemblyai/src/lib/actions/transcripts/word-search.ts, packages/pieces/community/assemblyai/src/lib/auth.ts, packages/pieces/community/assemblyai/src/lib/client.ts
Improve the AssemblyAI piece
- Require auth for all actions
- Update API key description
- Validate API key
- Add integration user agent
=> feat(pieces-assemblyai): add instructions / validate api keys

docs/openapi.json, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/routes/settings/pieces/index.tsx, packages/react-ui/src/components/json-viewer.tsx, packages/react-ui/src/features/authentication/components/sign-up-form.tsx, packages/react-ui/src/styles.css, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/shared/src/lib/invitations/index.ts
=> fix: tweak dark theme

package.json, packages/react-ui/src/components/theme-provider.tsx
=> feat: 0.32.0-rc.3 release

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/index.ts, packages/pieces/community/linear/src/lib/triggers/removed-issue.ts, packages/pieces/community/linear/src/lib/triggers/updated-issue.ts
We want triggers on updated and removed (deleted in the UI) linear issues.
=> feat(linear): add updated and removed issue trigger

packages/pieces/community/smaily/package.json, packages/pieces/community/smaily/src/index.ts
=> feat(smaily): custom api call action

packages/react-ui/src/app/components/request-trial.tsx, packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
=> fix: send authorization method  on (notion) oauth2 connection

docker-compose.yml, package-lock.json, package.json, packages/server/api/src/app/ee/analytics/analytics.service.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts
=> feat: 0.32.0 release

package-lock.json, package.json, packages/pieces/community/supabase/package.json, packages/pieces/community/supabase/src/index.ts
=> fix(supabase): authentication now works

packages/pieces/community/assemblyai/README.md, packages/pieces/community/assemblyai/package.json, packages/pieces/community/assemblyai/scripts/generateFromSpec.ts
Update the README.md of the AssemblyAI piece to have more info than the default Nx generated readme.
Also, update the version to 1.0.0
=> chore(assemblyai): update readme of pieces-assemblyai

packages/pieces/community/chargekeep/package.json, packages/pieces/community/chargekeep/src/index.ts
This PR updates the Piece description for ChargeKeep.
=> chore(chargekeep): update piece description

packages/pieces/community/sperse/package.json, packages/pieces/community/sperse/src/index.ts
This fixes the sperse integrations triggers not showing, as it wasn't properly imported and passed in the triggers array.
=> fix(sperse):  triggers now showing

packages/ee/shared/src/lib/billing/index.ts, packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
=> feat: add ai tokens limit to embed jwt

packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/router/project-route-wrapper.tsx, packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx, packages/react-ui/src/features/pieces/lib/pieces-api.ts, packages/react-ui/src/lib/api.ts
=> fix: upload piece through ui

packages/engine/src/lib/services/files.service.ts
=> fix: add memory files back

packages/react-ui/src/features/forms/components/ap-form.tsx
=> fix: duplicate form run

packages/pieces/community/linkedin/package.json, packages/pieces/community/linkedin/src/lib/actions/create-company-update.ts, packages/pieces/community/linkedin/src/lib/actions/create-share-update.ts, packages/pieces/community/linkedin/src/lib/common/index.ts
=> fix(linkedin): company dropdown

packages/react-ui/src/hooks/project-hooks.ts
=> fix: increase limit size in project switcher

packages/engine/jest.config.ts, packages/engine/package.json, packages/engine/src/lib/handler/branch-executor.ts, packages/engine/test/handler/branch-executor.test.ts, packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx, packages/shared/src/lib/flows/actions/action.ts
Adds branch date operators (before, after, equals) and list (empty, not empty)
=> feat: add date and list branch operators

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/common/index.ts, packages/pieces/community/airtable/src/lib/common/models.ts
=> fix(airtable): add aiText field type

docker-compose.yml, package-lock.json, package.json, packages/server/api/src/app/server.ts, packages/server/api/test/helpers/mocks/index.ts
=> feat: release 0.32.1

package-lock.json, package.json, packages/pieces/community/github/package.json, packages/pieces/community/github/src/index.ts, packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts
- Add action to perform a raw graphql query (as it's quite difficult to make it work with the "custom API call" action)
- Use Octokit official SDK
I will open a separate PR to switch existing actions to Octokit (much easier to use / add actions)
NB: I could not use the latest Octokit 4 release because of build issues (they switched to ESM which ActivePieces does not support)
=> feat(github): add octokit sdk and raw graphql action

packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/triggers/conversation-rated.ts
Add trigger for when a conversation is rated
=> feat(intercom): add conversation.rated trigger

packages/pieces/community/nifty/package.json, packages/pieces/community/nifty/src/lib/actions/create-task.ts
- Gives users the option of providing a description ( optional ) when creating tasks using the Nifty piece.
=> feat(nifty): add description field for create task action

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts
=> fix(google-sheeet): fix clear sheet action

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/common.ts
Provide more context when conversation content cannot be retrieved for some reason
=> feat(dust): improve error management

packages/engine/src/lib/operations.ts, packages/react-ui/src/lib/utils.ts
=> fix: iterations should not show up

Dockerfile, packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
=> fix: match isolated-vm version

package.json
=> feat: release 0.33.0-rc.1

packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/storage.service.ts, packages/pieces/community/framework/src/lib/validators/errors.ts, packages/react-ui/src/app/connections/secret-text-connection-settings.tsx, packages/server/api/src/app/server.ts, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
=> fix: validate storage keys

packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
=> fix: remove gap in piece search

packages/react-ui/src/app/builder/piece-properties/multi-select-piece-property.tsx
=> fix: ui crash on clickup multi dropdown

packages/pieces/community/github/package.json, packages/pieces/community/github/src/lib/trigger/index.ts
Add trigger when there is a push to a repo branch
=> feat(github): add trigger on new push

packages/engine/test/services/variable-service.test.ts
=> fix: tests in the engine

packages/engine/src/lib/helper/logging-utils.ts
=> fix: logging utils

package-lock.json, package.json, packages/pieces/community/text-helper/package.json, packages/pieces/community/text-helper/src/index.ts, packages/pieces/community/text-helper/src/lib/actions/slugify.ts
Add slugify action - using https://www.npmjs.com/package/slugify
=> feat(text-helper): add slugify action

packages/pieces/community/activepieces/package.json, packages/pieces/community/activepieces/src/index.ts, packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/create-project.ts, packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project.ts, packages/pieces/community/activepieces/src/lib/actions/update-project.ts
- Add `baseUrl` param to connections
- Use base URL in actions
=> feat(activepieces): add customizable base URL to use on self-hosted platforms

packages/pieces/community/activepieces/package.json, packages/pieces/community/activepieces/src/index.ts, packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/create-project.ts, packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project.ts, packages/pieces/community/activepieces/src/lib/actions/update-project.ts
Reverts activepieces/activepieces#5712
=> Revert "feat(Activepieces): add base url and api key secret"

packages/pieces/community/activepieces/package.json, packages/pieces/community/activepieces/src/index.ts, packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/create-project.ts, packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project.ts, packages/pieces/community/activepieces/src/lib/actions/update-project.ts
Reverts activepieces/activepieces#5713
=> Revert "Revert "feat(Activepieces): add base url and api key secret""

packages/server/api/src/assets/invalid-code.js, packages/server/worker/src/lib/utils/code-builder.ts
=> fix: move invalid code template to local variable

packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/index.tsx, packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx, packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx, packages/react-ui/src/components/ui/skeleton.tsx
[Reverts activepieces/activepieces#5715 ](https://github.com/activepieces/activepieces/pull/5682)
=> fix: validate dynamic properties in step settings

packages/pieces/community/customer-io/package.json, packages/pieces/community/customer-io/src/index.ts, packages/pieces/community/customer-io/src/lib/actions/create_event.ts, packages/pieces/community/customer-io/src/lib/common/index.ts
Add support for EU-based CustomerIO accounts
=> feat(customer-io): add support for EU workspaces

.github/workflows/automate-deploy.yml, docs/embedding/customize-pieces.mdx, docs/embedding/embed-builder.mdx, docs/embedding/embed-connections.mdx, docs/embedding/provision-users.mdx, packages/ee/ui/embed-sdk/package.json, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/routes/embed/index.tsx, packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/server/api/src/app/user/user-service.ts, packages/server/api/test/integration/ce/authentication/authentication.test.ts, packages/server/api/test/integration/cloud/authn/cloud-authn.test.ts, packages/server/api/test/integration/cloud/managed-authn/external-token.test.ts, packages/server/api/test/integration/ee/authn/ee-authn.test.ts
=> feat(sdk): enhance pieces filteration & email is optional & secure token exchange

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.33.0

packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts, packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts, packages/shared/src/lib/flow-run/execution/flow-execution.ts
=> fix: tasks count during test flow

packages/pieces/community/airtable/package.json, packages/pieces/community/airtable/src/lib/common/index.ts
=> fix(airtable): fix multiselect field causing overwriting of existing values

packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix: rate limit per project is not based on ids not counter to be error bullet proof

packages/react-ui/src/app/builder/step-settings/code-settings/code-editor.tsx
=> fix: hide npm if they are not allowed
