packages/server/api/project.json
=> fix: generate source map for backend

docs/handbook/engineering/customer-support.mdx, docs/handbook/engineering/how-we-work.mdx, docs/handbook/engineering/on-call.mdx, docs/handbook/engineering/pre-releases.mdx, docs/handbook/hiring/compensation.mdx, docs/handbook/hiring/hiring.mdx, docs/handbook/hiring/levels.mdx, docs/handbook/hiring/team.mdx, docs/mint.json
=> docs: add on-call schedule

packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts, packages/server/api/src/app/flags/flag.service.ts
=> fix: host url in ee edition

packages/server/api/src/app/ai/ai-provider-proxy.ts
=> fix: openai 401 caused by duplicate auth headers

packages/server/api/src/app/file/s3-helper.ts
=> fix: force path style

package.json
=> feat: 0.34.0-rc.1

packages/server/api/src/app/pieces/piece-metadata-service/pieces-builder.ts
As discussed on Discord, this fixes weird shenanigans when setting up a dev environment on Windows. See [this StackOverflow answer](https://stackoverflow.com/a/59830014/10434371).
Keeping this as a draft for now to investigate the best way to avoid an RCE oopsie.
=> fix: dev setup on windows

packages/react-ui/src/features/connections/lib/oauth2-apps-api.ts, packages/react-ui/src/features/connections/lib/oauth2-apps-hooks.ts
=> fix: send edition with apps

package-lock.json, package.json, packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/lib/actions/send-prompt.ts, packages/pieces/community/openai/src/lib/common/common.ts
=> chore: remove non-llm models and use max_completion_tokens

packages/react-ui/src/app/routes/platform/settings/signing-keys/new-signing-key-dialog.tsx
=> fix: add missing spacing in the signing key dialog

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
Fixes instructions in slack trigger
=> feat(slack): update custom slack channel ID instruction and ignore bot message option for trigger

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/triggers/new-mention.ts
=> feat(slack): new mention trigger

packages/react-ui/src/lib/authentication-session.ts
=> fix: update role when switching project

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.34.0

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/triggers/new-mention.ts
=> fix(slack): fix new mention trigger test

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts, packages/pieces/community/text-ai/package.json
=> fix: anthropic auth header

packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/property/input/array-property.ts
=> feat: allow file property inside array

packages/server/api/src/app/authentication/authorization.ts, packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts, packages/server/api/src/app/flows/flow-run/flow-run-controller.ts, packages/server/api/src/app/flows/flow-run/flow-run-module.ts, packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
=> refactor: minor clean up for list runs endpoint

packages/react-ui/src/app/builder/piece-properties/array-property.tsx
=> fix(array-property): append on array of object makes data disappear

packages/pieces/community/image-ai/package.json, packages/pieces/community/image-ai/src/lib/actions/extract-data.ts
=> fix(image-ai): add prompt guide

package-lock.json, package.json, packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/files.service.ts
=> fix(engine): apply error handling & retries on files service

docker-compose.yml, package-lock.json, package.json, packages/engine/src/lib/services/files.service.ts
=> feat: release 0.34.1

packages/react-ui/src/app/builder/run-list/index.tsx, packages/react-ui/src/app/routes/settings/appearance/index.tsx, packages/react-ui/src/app/routes/settings/general/index.tsx
=> style(settings): remove general settings from inside card

packages/pieces/community/file-helper/package.json, packages/pieces/community/file-helper/src/lib/actions/read-file.ts
=> fix(file-helper): read file

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts, packages/react-ui/src/app/routes/chat/index.tsx
=> fix(chat): send correct structure to sync endpoint

packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts, packages/server/api/src/app/flows/flow-run/flow-run-module.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/helper/system-jobs/common.ts, packages/server/api/src/app/helper/telemetry.utils.ts, packages/shared/src/lib/common/telemetry.ts
=> fix(telemetry): aggregate telemetry before sending

packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
=> fix(chat): hot fix for type error in chat trigger

.devcontainer/Dockerfile, Dockerfile, packages/pieces/community/pdf/package.json, packages/pieces/community/pdf/src/index.ts, packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
=> feat(pdf): convert pdf to image

packages/pieces/community/image-ai/package.json, packages/pieces/community/image-ai/src/lib/actions/extract-data.ts
=> fix(image-ai): extract data error handling

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/lib/actions/return-file.ts, packages/pieces/community/forms/src/lib/actions/return-markdown.ts, packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts, packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
=> fix(human-input): rename human-input actions and triggers

docs/admin-console/manage-projects.mdx, packages/react-ui/src/app/routes/runs/index.tsx
closes https://github.com/activepieces/activepieces/issues/5711
=> chore: use more expressive icons in runs table for re-runs

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts, packages/pieces/community/forms/src/lib/triggers/form-trigger.ts, packages/react-ui/src/app/routes/chat/index.tsx, packages/react-ui/src/components/ui/chat/chat-bubble.tsx, packages/shared/package.json, packages/shared/src/lib/common/activepieces-error.ts
=> fix(chat): add proper error handling

packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
=> feat(pdf): option to concat all images

tools/scripts/pieces/update-pieces-metadata.ts, tools/scripts/utils/piece-script-utils.ts
=> feat: speed up release pieces ci/cd

packages/engine/src/lib/variables/variable-service.ts, packages/engine/test/services/variable-service.test.ts
=> fix(framework): resolving array of objects

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/index.ts, packages/pieces/community/forms/src/lib/actions/return-file.ts, packages/pieces/community/forms/src/lib/actions/return-markdown.ts, packages/react-ui/src/app/routes/chat/index.tsx, packages/react-ui/src/components/custom/copy-to-clipboard.tsx, packages/react-ui/src/components/ui/copy-button.tsx, packages/react-ui/src/features/human-input/components/ap-form.tsx, packages/react-ui/src/features/human-input/lib/human-input-api.tsx, packages/shared/src/lib/forms/index.ts
- View Images
- Download Files
- Fix Copy Button
- Respond File use links instead of Base64
=> feat(human-input): allow chat ui to view images

packages/engine/src/lib/handler/flow-executor.ts, packages/engine/src/lib/helper/piece-loader.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/operations.ts, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts, packages/pieces/community/common/src/lib/http/core/http-request.ts, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/framework/src/lib/trigger/trigger.ts, packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/actions/call-flow.ts, packages/pieces/community/subflows/src/lib/actions/respond.ts, packages/pieces/community/subflows/src/lib/common.ts, packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
=> feat(subflow): remove timeout restriction

packages/engine/src/lib/handler/flow-executor.ts, packages/engine/src/lib/helper/piece-loader.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/operations.ts, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/framework/src/lib/trigger/trigger.ts
=> feat: add onStart for runs

packages/pieces/community/common/package.json, packages/pieces/community/framework/package.json, packages/pieces/community/subflows/package.json
=> fix: bump subflows

packages/pieces/community/date-helper/package.json, packages/pieces/community/date-helper/src/lib/common/index.ts
=> fix(date-helper): add custom formats

packages/pieces/community/activepieces/src/index.ts
=> chore: admin-console typo

package-lock.json, package.json, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/markdown-to-slack-format.ts
Slack has a weird pseudo-markdown syntax that is often confusing to users - so we're adding a dedicated action to convert from standard Markdown (when possible)
=> feat(slack): add action to convert markdown text to Slack custom format

packages/pieces/community/village/package.json, packages/pieces/community/village/src/index.ts, packages/pieces/community/village/src/lib/actions/fetch-companies-paths.ts, packages/pieces/community/village/src/lib/actions/fetch-people-paths.ts
=> chore(village-piece): minor content updates: title, description, etc

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/index.ts, packages/pieces/community/apitable/src/lib/common/index.ts
=> feat(apitable): add auth validation and empty multiselect condition

packages/server/api/src/app/database/redis-connection.ts
=> fix(redis): set max retries to zero

packages/shared/src/lib/flows/sample-data/index.ts
=> fix: accept undefined sample data

packages/react-ui/src/app/builder/test-step/test-action-section.tsx, packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx, packages/shared/src/lib/flows/sample-data/index.ts
=> fix(sample-data): skip saving undefined

packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
=> fix: build pieces on initial load

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts
=> fix(google-sheets): cast sheet ID to number

packages/pieces/community/village/package.json, packages/pieces/community/village/src/index.ts
=> fix(village): fix piece category

Dockerfile
=> feat: upgrade docker image to node 20

Dockerfile
=> chore: upgrade to 20.16 bulleye

packages/server/api/src/app/app.ts, packages/server/api/src/app/helper/system-validator.ts
=> fix: validate system props type

packages/pieces/community/text-helper/package.json, packages/pieces/community/text-helper/src/lib/actions/concat.ts, packages/pieces/community/text-helper/src/lib/actions/find.ts, packages/pieces/community/text-helper/src/lib/actions/replace.ts, packages/pieces/community/text-helper/src/lib/actions/split.ts
=> fix: handle concat texts might be undefined

docs/install/configuration/hardware.mdx, docs/mint.json
=> docs: add hardware requirements

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/index.ts, packages/pieces/community/google-sheets/src/lib/actions/create-worksheet.ts
=> feat(google-sheets): create worksheet action

docker-compose.yml, package.json
=> feat: release 0.34.5

packages/react-ui/src/app/routes/platform/settings/branding/smtp-section.tsx
=> fix: smtp port issue

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/index.ts, packages/pieces/community/google-sheets/src/lib/actions/create-spreadsheet.ts
=> feat(google-sheets): create blank spreadsheet action

docs/install/options/elestio.mdx, docs/install/overview.mdx, docs/mint.json
=> docs: add elestio as installation option 

packages/server/api/src/app/workers/engine-controller.ts
=> fix(webhook): resolve "too long to reply" issue and incorrect response message in /sync calls

docker-compose.yml, package.json
=> feat: release 0.35.6

package-lock.json, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts, packages/pieces/community/slack/src/lib/actions/get-channel-history.ts, packages/pieces/community/slack/src/lib/actions/request-action-message.ts, packages/pieces/community/slack/src/lib/actions/request-approval-message.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/actions/update-message.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/triggers/new-mention.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
Improves previous doc instruction that was not clear to indicate the need for curly braces and arrays
=> feat(slack): update slack custom channel id info

packages/pieces/community/activepieces/package.json, packages/pieces/community/activepieces/src/index.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/test/integration/ce/flows/flow.test.ts
=> feat: the ability to export the flow template

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
=> feat: fast replace for step / trigger

packages/engine/src/lib/handler/loop-executor.ts, packages/engine/src/lib/operations.ts, packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx
=> fix: add validation for items in the "Loop on Items" piece

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts, packages/react-ui/src/app/routes/chat/file-input-preview.tsx, packages/react-ui/src/app/routes/chat/file-message.tsx, packages/react-ui/src/app/routes/chat/image-dialog.tsx, packages/react-ui/src/app/routes/chat/index.tsx, packages/react-ui/src/app/routes/chat/messages-list.tsx, packages/react-ui/src/app/routes/chat/text-message.tsx, packages/react-ui/src/components/ui/chat/chat-input.tsx, packages/react-ui/src/components/ui/chat/chat-message-list.tsx, packages/react-ui/src/components/ui/scroll-area.tsx, packages/react-ui/src/features/human-input/lib/human-input-api.tsx, packages/react-ui/tailwind.config.js, packages/server/api/src/app/webhooks/webhook-controller.ts
https://github.com/user-attachments/assets/6103beec-eee9-4ceb-9a4b-197abd39b187
=> feat: support files in the chat

packages/ee/shared/src/lib/product-embed/connection-keys/connection-requests.ts, packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx, packages/react-ui/src/app/connections/connection-table.tsx, packages/react-ui/src/components/ui/avatar-letter.tsx, packages/react-ui/src/components/ui/user-fullname.tsx, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app-connection/app-connection.controller.ts, packages/server/api/src/app/app-connection/app-connection.entity.ts, packages/server/api/src/app/database/migration/postgres/1725699690971-AddLogsFileIdIndex.ts, packages/server/api/src/app/database/migration/postgres/1726445983043-AddAiProviderTable.ts, packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts, packages/server/api/src/app/database/migration/sqlite/1730121414658-AddConnectionOwnerSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/ee/connection-keys/connection-key.service.ts, packages/server/api/src/app/helper/security-helper.ts, packages/shared/src/lib/app-connection/app-connection.ts, packages/shared/src/lib/flows/flow-version.ts
=> feat: add owner for the connection

packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts, packages/shared/src/lib/store-entry/dto/store-entry-request.ts
=> fix: callable flow stuck in running in testing mode

docker-compose.yml, package.json
=> feat: release 0.34.8

packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts
=> fix: user migration

package.json
=> feat: 0.34.9

docker-compose.yml, package-lock.json, package.json
=> feat: 0.35.0-rc.1

docs/admin-console/overview.mdx
Tiny fix I noticed while going through the docs.
=> docs: Update overview.mdx to remove additional `:`

packages/server/api/src/app/app-connection/app-connection.entity.ts, packages/server/api/src/app/database/migration/postgres/1730627612799-AppConnectionsSetNull.ts, packages/server/api/src/app/database/migration/sqlite/1730627777709-AppConnectionsSetNullSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts
=> fix(connections): set owner id to null when deleted

packages/pieces/community/pdf/package.json, packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
=> fix: pdf failed to delete folder

package-lock.json, packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts, packages/server/api/src/app/flows/flow-run/flow-run-entity.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix(bulk-retry): change listing flow runs to be ordered by created date

packages/pieces/community/pdf/package.json, packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
=> fix: convert pdf to image too many files error

docs/install/overview.mdx
We recently added Activepieces due to demand from our community. Also adding it here, so others can find it easily.
=> docs: Add pikapods.com hosting option

packages/server/api/src/app/database/migration/postgres/1730760434336-AddFlowSchemaVersion.ts, packages/server/api/src/app/database/migration/sqlite/1730760312426-AddFlowSchemaVersionSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/flow-version/flow-version-entity.ts, packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/shared/src/lib/flows/dto/flow-template-request.ts, packages/shared/src/lib/flows/flow-version.ts
=> feat: add schema version for the flow version

packages/react-ui/src/app/routes/flows/index.tsx
=> fix(menu-actions): refresh flows after rename, duplicate, move, delete

packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx, packages/react-ui/src/features/templates/components/share-template.tsx, packages/server/api/src/app/ee/git-sync/git-sync-helper.ts, packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/shared/src/lib/flows/operations/index.ts
=> fix: import flow should specify schema

docs/developers/piece-reference/properties.mdx
=> docs(properties): added markdown variant options

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/index.ts, packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts, packages/pieces/community/common/src/lib/ai/providers/openai/index.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/property/input/dynamic-prop.ts, packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts, packages/server/shared/package.json, packages/server/worker/package.json
=> feat(utility-ai): advanced structured data

packages/pieces/community/shopify/package.json, packages/pieces/community/shopify/src/index.ts, packages/pieces/community/shopify/src/lib/actions/get-customers.ts, packages/pieces/community/shopify/src/lib/common/index.ts
Adding a new Action to Shopify Piece to get all the customer. Similar to my other PR. It get the list of customer and handle the pagination.
=> feat(shopify):  Get Customers action

packages/server/api/src/app/app-event-routing/app-event-routing.module.ts, packages/server/api/src/app/webhooks/webhook-controller.ts, packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-service.ts, packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-side-effects.ts, packages/server/api/src/app/workers/worker-controller.ts, packages/server/shared/src/lib/job/job-data.ts, packages/server/worker/src/lib/executors/webhook-job-executor.ts, packages/server/worker/src/lib/utils/webhook-utils.ts
=> chore(webhook): modify the logic to save sample data

packages/pieces/community/google-calendar/package.json, packages/pieces/community/google-calendar/src/index.ts, packages/pieces/community/google-calendar/src/lib/actions/get-events.ts
Add options to Goolgle Calendar Get Events to expand recurring events or not similar to Google Calendar Trigger
=> feat: google-calendar add `Expand Recurring Event` option

packages/server/worker/src/lib/executors/webhook-job-executor.ts
=> fix: save sample data when flow is not published

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/lib/actions/return-response.ts
=> fix(webhook): hide headers when response type is redirect

packages/server/api/src/app/flows/flow/flow.service.ts
=> fix: speed up deletion

packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/react-ui/src/features/flows/lib/trigger-events-api.ts
=> feat(flows): Support Files and Zip Format

packages/react-ui/src/app/components/platform-admin-container.tsx, packages/react-ui/src/app/components/platform-settings-layout.tsx, packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/routes/platform/notifications/ai-notification.tsx, packages/react-ui/src/app/routes/platform/settings/license-key/index.tsx, packages/react-ui/src/components/ui/alert.tsx, packages/react-ui/src/components/ui/data-table/index.tsx
=> feat: reorganize platform admin

docker-compose.yml, package.json
=> feat: release 0.35.0

packages/pieces/community/claude/package.json, packages/pieces/community/claude/src/lib/actions/send-prompt.ts
=> feat(claude): add claude 3.5 haiku model

package-lock.json, package.json, packages/react-ui/project.json, packages/react-ui/src/app/builder/flow-canvas/edges/branch-label.tsx, packages/react-ui/src/app/builder/flow-canvas/edges/router-start-edge.tsx, packages/react-ui/src/app/builder/flow-canvas/flow-canvas-utils.ts, packages/react-ui/src/app/builder/flow-canvas/types.ts, packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts, packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx, packages/react-ui/src/app/builder/test-step/test-action-section.tsx, packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx, packages/react-ui/src/app/routes/platform/settings/license-key/activate-license-dialog.tsx, packages/react-ui/src/app/routes/platform/templates/upsert-template-dialog.tsx, packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx, packages/react-ui/src/app/routes/settings/git-sync/index.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx, packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx, packages/react-ui/src/features/pieces/lib/pieces-hook.ts, packages/react-ui/src/features/platform-admin-panel/lib/platform-user-api.ts, packages/react-ui/src/features/team/lib/project-members-hooks.ts, packages/shared/src/lib/flows/trigger-events/trigger-event.ts
=> chore: fix type checks in react-ui

packages/server/api/src/app/copilot/copilot.service.ts
=> fix: graceful error handling

packages/react-ui/src/app/builder/builder-header.tsx, packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/server/api/src/app/copilot/copilot.module.ts, packages/server/api/src/app/copilot/copilot.service.ts
=> fix: overwrite flow when importing from context menu

packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
=> fix(flows): import flow redirection

Dockerfile
https://github.com/laverdet/isolated-vm/issues/424
=> fix: revert to node18 to fix seg fault

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.35.1

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
=> fix(google-sheets): fix shared drive file notification

packages/server/api/src/app/flows/flow/flow.service.ts
=> fix: pieces should be unique in the template

packages/pieces/community/gravityforms/package.json, packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts, packages/pieces/community/moxie-crm/package.json, packages/pieces/community/moxie-crm/src/lib/triggers/register-trigger.ts, packages/pieces/community/poper/package.json, packages/pieces/community/poper/src/lib/triggers/new-lead.ts, packages/pieces/community/reachinbox/package.json, packages/pieces/community/reachinbox/src/lib/triggers/campaign-completed.ts, packages/pieces/community/reachinbox/src/lib/triggers/email-bounced.ts, packages/pieces/community/reachinbox/src/lib/triggers/email-opened.ts, packages/pieces/community/reachinbox/src/lib/triggers/email-sent.ts, packages/pieces/community/reachinbox/src/lib/triggers/lead-interested.ts, packages/pieces/community/reachinbox/src/lib/triggers/lead-not-interested.ts, packages/pieces/community/reachinbox/src/lib/triggers/reply-received.ts, packages/pieces/community/tally/package.json, packages/pieces/community/tally/src/lib/triggers/new-submission.ts
=> chore: update webhook triggers desc

package-lock.json, packages/react-ui/src/app/routes/platform/projects/index.tsx, packages/react-ui/src/app/routes/platform/templates/index.tsx, packages/react-ui/src/features/connections/lib/app-connections-api.ts
=> feat: bulk delete on projects / templates table

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.36.0

packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/actions/call-flow.ts, packages/pieces/community/subflows/src/lib/actions/respond.ts, packages/pieces/community/subflows/src/lib/common.ts, packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
=> fix(subflows): testing flow experience

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/lib/actions/send-email.ts
Adds support for sending multiple email attachments.
Not yet tested!
=> feat(smtp): add support for multiple attachments in SMTP Piece

packages/server/api/src/app/ee/git-sync/git-sync-helper.ts, packages/shared/src/index.ts, packages/shared/src/lib/flows/operations/index.ts, packages/shared/src/lib/flows/operations/migrations/index.ts
=> fix: apply migration before importing

docker-compose.yml, package.json
=> feat: release 0.36.1

packages/pieces/community/apify/package.json, packages/pieces/community/apify/src/index.ts, packages/pieces/community/apify/src/lib/actions/get-actors.ts, packages/pieces/community/apify/src/lib/actions/get-dataset-items.ts, packages/pieces/community/apify/src/lib/actions/get-last-run.ts, packages/pieces/community/apify/src/lib/actions/start-actor.ts
added start actor method
minor changes - mainly returning response.body.data instead of response.body
=> feat(apify): start actor action

packages/pieces/community/qdrant/package.json, packages/pieces/community/qdrant/src/lib/actions/add-points.ts
=> fix(qdrant): fix embedding ids field parsing error

package-lock.json, package.json, packages/pieces/community/azure-communication-services/.eslintrc.json, packages/pieces/community/azure-communication-services/README.md, packages/pieces/community/azure-communication-services/package.json, packages/pieces/community/azure-communication-services/project.json, packages/pieces/community/azure-communication-services/src/index.ts, packages/pieces/community/azure-communication-services/src/lib/actions/send-email.ts, packages/pieces/community/azure-communication-services/tsconfig.json, packages/pieces/community/azure-communication-services/tsconfig.lib.json, tsconfig.base.json
Adding a new Azure Communication Services piece and its first action : **Send email**
=> feat(azure-communication-services): send email

packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
=> fix(embed): stop task override when it is undefined in jwt

packages/pieces/community/azure-openai/package.json, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/validation/index.ts, packages/pieces/community/date-helper/package.json, packages/pieces/community/delay/package.json, packages/pieces/community/google-sheets/package.json, packages/pieces/community/jira-cloud/package.json, packages/pieces/community/math-helper/package.json, packages/pieces/community/openai/package.json, packages/pieces/community/perplexity-ai/package.json, packages/pieces/community/sendy/package.json, packages/pieces/community/store/package.json, packages/pieces/community/text-helper/package.json, packages/pieces/community/twitter/package.json
https://community.activepieces.com/t/chatgpt-error-when-writing-seo-article-using-the-template/6917/7
=> fix(pieces): revert validation in the piece

package-lock.json, package.json, packages/server/api/src/app/workers/redis/redis-queue.ts
=> chore: upgrade bullmq

docker-compose.yml, package.json
=> feat: release 0.36.2

package-lock.json, packages/engine/src/lib/handler/piece-executor.ts
=> fix: allow empty response in pause

packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/storage.service.ts
=> fix(engine): handle empty value in store

packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/storage.service.ts, packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
=> fix: remove invalid key error in the engine and handle null key

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts, packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
=> fix(utility-ai): add raw message for data extraction error

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
=> fix(google-sheets): fix duplicates option error

packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
=> fix: smtp port

package.json
=> feat: release 0.36.3

packages/server/api/src/app/file/file.module.ts, packages/server/api/src/app/file/file.service.ts, packages/server/api/src/app/flows/flow-run/flow-run-module.ts, packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts, packages/server/api/src/app/helper/system-jobs/common.ts, packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
=> fix: simplify delete stale data logic

package-lock.json, packages/server/api/src/app/database/migration/postgres/1732324567513-AddIndiciesToRunAndTriggerData.ts, packages/server/api/src/app/database/migration/sqlite/1732324359348-AddIndiciesToTriggerEventSqlite.ts, packages/server/api/src/app/database/migration/sqlite/1732324481815-AddIndiciesToRunSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/file/file.service.ts, packages/server/api/src/app/flows/flow-run/flow-run-entity.ts, packages/server/api/src/app/flows/trigger-events/trigger-event.entity.ts
=> fix: index trigger events & runs to speed up delete

packages/server/api/src/app/file/file.module.ts, packages/server/api/src/app/file/file.service.ts, packages/server/api/src/app/file/s3-helper.ts
=> fix: delete s3 object when file is deleted

docker-compose.yml, package.json
=> feat: release 0.36.4

package-lock.json, packages/react-ui/src/app/components/platform-settings-layout.tsx, packages/react-ui/src/app/components/worker-configs-dialog.tsx, packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/routes/platform/settings/workers/index.tsx, packages/react-ui/src/app/routes/platform/settings/workers/worker-configs-dialog.tsx, packages/react-ui/src/components/custom/circular-icon.tsx, packages/react-ui/src/features/platform-admin-panel/lib/workers-api.ts, packages/react-ui/src/lib/utils.ts, packages/server/api/src/app/workers/machine/machine-controller.ts, packages/server/api/src/app/workers/machine/machine-service.ts, packages/server/shared/src/lib/system/system.ts, packages/server/worker/package.json, packages/server/worker/src/lib/utils/heartbeat.ts, packages/shared/src/lib/workers/index.ts
rovide an easy user interface on the platform admin to provide monitoring on top of workers.
Fixes #6036
=> feat: Flow Execution & Workers observability

packages/ee/shared/src/lib/audit-events/index.ts, packages/ee/shared/src/lib/project-members/project-member.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts, packages/server/api/src/app/ee/authentication/project-role/rbac-middleware.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts, packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts, packages/server/api/src/app/ee/pieces/platform-piece-module.ts, packages/server/api/src/app/ee/project-members/project-member.entity.ts, packages/server/api/src/app/ee/project-members/project-member.service.ts, packages/server/api/src/app/ee/project-role/project-role.controller.ts, packages/server/api/src/app/ee/project-role/project-role.service.ts, packages/server/api/src/app/ee/signing-key/signing-key-controller.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/helper/application-events/index.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/shared/src/lib/invitations/index.ts, packages/shared/src/lib/project-role/project-role.request.ts, packages/shared/src/lib/project/project.ts
=> refactor: minr ui change

packages/react-ui/src/app/routes/platform/settings/workers/index.tsx, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
=> feat(import-flow): add folder selection to import flow dialog

packages/react-ui/src/app/routes/platform/notifications/ai-notification.tsx, packages/react-ui/src/app/routes/platform/projects/index.tsx, packages/react-ui/src/app/routes/platform/setup/pieces/piece-actions.tsx, packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx, packages/react-ui/src/app/routes/platform/users/index.tsx, packages/react-ui/src/features/team/component/project-role-select.tsx, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/ee/projects/platform-user-project-controller.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/shared/package.json, packages/shared/src/lib/project/project.ts
Reverts activepieces/activepieces#6125
=> Revert "Revert "feat: add active flows and activated users columns to projects table in admin platform""

packages/engine/src/lib/handler/context/engine-constants.ts, packages/engine/src/lib/handler/flow-executor.ts, packages/engine/src/lib/services/progress.service.ts
=> fix: disable live update

packages/pieces/community/file-helper/package.json, packages/pieces/community/file-helper/src/lib/actions/change-file-encoding.ts
=> fix(file-helper): fix change encoding

packages/server/shared/src/lib/pieces/file-pieces-utils.ts, packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
=> fix: speed up local piece development

packages/ee/shared/src/lib/project-members/project-member-request.ts, packages/react-ui/src/app/routes/settings/team/index.tsx, packages/react-ui/src/features/platform-admin-panel/lib/project-role-api.ts, packages/react-ui/src/features/team/component/edit-role-dialog.tsx, packages/react-ui/src/features/team/component/project-member-card.tsx, packages/react-ui/src/features/team/lib/project-members-api.ts, packages/react-ui/src/hooks/authorization-hooks.ts, packages/server/api/src/app/ee/project-members/project-member.controller.ts, packages/server/api/src/app/ee/project-members/project-member.service.ts, packages/server/api/src/app/ee/project-role/project-role.controller.ts, packages/server/api/src/app/ee/project-role/project-role.service.ts, packages/server/api/test/integration/cloud/project-members/project-members.test.ts, packages/server/api/test/integration/cloud/project-role/project-role.test.ts, packages/shared/src/lib/project-role/project-role.request.ts
=> feat(rbac): allow to update project role in teams page

packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/server/api/src/app/database/seeds/role-seed.ts, packages/shared/package.json, packages/shared/src/lib/project/project-member.ts
=> fix: rename project roles and fix import flow dialog styling

packages/react-ui/src/features/human-input/components/ap-form.tsx
=> feat(form): fill the form with data from query params

packages/engine/src/lib/variables/processors/index.ts, packages/engine/src/lib/variables/processors/object.ts, packages/engine/test/services/props-validator.test.ts
=> fix: add object validation processor

packages/react-ui/src/features/flows/lib/sample-data-api.ts, packages/server/api/src/app/file/file.service.ts, packages/server/api/src/app/flows/step-run/sample-data.controller.ts, packages/server/api/src/app/flows/step-run/sample-data.service.ts, packages/shared/package.json, packages/shared/src/lib/flows/sample-data/index.ts
=> fix(sampledata): fix sample data attachment response

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts, packages/pieces/community/google-sheets/src/lib/actions/create-spreadsheet.ts, packages/pieces/community/google-sheets/src/lib/actions/create-worksheet.ts, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts, packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
=> fix(google-sheets): duplicate & overwrite

packages/react-ui/src/app/routes/platform/setup/branding/add-custom-domain.tsx, packages/react-ui/src/features/platform-admin-panel/lib/custom-domain-api.ts, packages/server/api/src/app/ee/custom-domains/custom-domain.module.ts, packages/server/api/src/app/ee/custom-domains/custom-domain.service.ts, packages/server/api/src/app/ee/platform/admin-platform.service.ts, packages/server/api/test/integration/cloud/custom-domain/custom-domain.test.ts, packages/shared/src/lib/platform/platform.request.ts
=> chore: automate trial onboarding

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.37.0

packages/server/api/src/app/database/migration/postgres/1731424289830-CreateProjectRoleTable.ts
=> fix: rbac migration for ce edition

docker-compose.yml, package-lock.json, package.json, packages/server/worker/package.json
=> feat: release 0.37.1

packages/pieces/community/imap/package.json, packages/pieces/community/imap/src/lib/triggers/new-email.ts
=> fix(imap): fix attachments response

packages/server/worker/src/lib/utils/heartbeat.ts
=> fix: memory usage in pod

packages/pieces/community/imap/package.json, packages/pieces/community/imap/src/lib/triggers/new-email.ts
=> feat(imap): remove binary attachments

package-lock.json, packages/server/api/src/app/database/migration/postgres/1731424289830-CreateProjectRoleTable.ts, packages/server/api/src/app/database/migration/postgres/1732790673766-AddProjectRelationInUserInvitation.ts, packages/server/api/src/app/database/migration/sqlite/1732791068873-AddProjectRelationInUserInvitationSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/ee/project-members/project-member.entity.ts, packages/server/api/src/app/user-invitations/user-invitation.entity.ts
=> fix: add project relation to user invitation

packages/engine/src/lib/variables/processors/object.ts, packages/engine/test/services/props-resolver.test.ts, packages/engine/test/services/props-validator.test.ts
=> fix(engine): parsing objects

docker-compose.yml, package.json
=> feat: release 0.37.2

package-lock.json, packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
=> fix: template endpoint scope

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts
=> feat(onedrive): add subfolders in dropdown

packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/property/input/array-property.ts
=> feat: support json in array inputs

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/validation/index.ts
=> fix(common): use async validation in zod

packages/pieces/community/salesforce/package.json, packages/pieces/community/salesforce/src/index.ts
Add custom API call for Salesforce
=> feat(salesforce): add custom API call action

packages/cli/src/lib/commands/create-piece.ts
=> fix: change validation of piece names

packages/server/api/src/app/copilot/tools/code/code-agent.ts, packages/server/api/src/app/copilot/tools/code/code-generate.ts
=> feat(copilot) - add context & deal with them 

packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
=> fix(gmail): fix \n adding <br> in mail body issue

packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/actions/call-flow.ts, packages/pieces/community/subflows/src/lib/actions/respond.ts, packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
=> feat(callable-flow): add simple/advanced modes to callable flow

packages/pieces/community/crypto/package.json, packages/pieces/community/crypto/src/index.ts, packages/pieces/community/crypto/src/lib/actions/hmac-signature.ts
Adding a new **Hmac Signature** action in **Crypto** piece
=> feat(crypto): generate hmac signature

packages/pieces/community/bamboohr/.eslintrc.json, packages/pieces/community/bamboohr/README.md, packages/pieces/community/bamboohr/package.json, packages/pieces/community/bamboohr/project.json, packages/pieces/community/bamboohr/src/index.ts, packages/pieces/community/bamboohr/tsconfig.json, packages/pieces/community/bamboohr/tsconfig.lib.json, tsconfig.base.json
Add basic piece for [BambooHR](https://www.bamboohr.com) (HRIS)
Logo to be hosted at https://cdn.activepieces.com/pieces/bamboohr.png
=> feat(bamboohr): add BambooHR piece with custom api call action

packages/pieces/community/scenario/.eslintrc.json, packages/pieces/community/scenario/README.md, packages/pieces/community/scenario/package.json, packages/pieces/community/scenario/project.json, packages/pieces/community/scenario/src/index.ts, packages/pieces/community/scenario/tsconfig.json, packages/pieces/community/scenario/tsconfig.lib.json, tsconfig.base.json
Add very basic piece (to mostly handle the authentication safely) for https://app.scenario.com
Logo (to be hosted at https://cdn.activepieces.com/pieces/scenario.png)
=> feat(scenario): add Scenario piece with custom api call action

packages/pieces/community/ashby/.eslintrc.json, packages/pieces/community/ashby/README.md, packages/pieces/community/ashby/package.json, packages/pieces/community/ashby/project.json, packages/pieces/community/ashby/src/index.ts, packages/pieces/community/ashby/tsconfig.json, packages/pieces/community/ashby/tsconfig.lib.json, tsconfig.base.json
Basic piece for [Ashby](https://www.ashbyhq.com) (ATS)
Logo to be hosted at https://cdn.activepieces.com/pieces/ashby.png
=> feat(ashby): add basic Ashby piece

packages/server/shared/src/lib/pieces/file-pieces-utils.ts, packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
=> fix: local piece caching not clearing

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/request-action.ts
The returned payload of the "request action" actions was inconsistent and made it impossible to test the step and build the rest of the flow
=> fix(slack): fix request action

packages/engine/src/lib/helper/error-handling.ts
=> fix: prevent crashing

docs/openapi.json, package-lock.json, packages/react-ui/src/features/team/component/invitation-card.tsx, packages/server/api/src/app/user-invitations/user-invitation.service.ts
=> fix: include project role in user invitation

package-lock.json, packages/ee/shared/package.json, packages/ee/shared/src/lib/project-members/project-member-request.ts, packages/react-ui/src/app/routes/platform/security/project-role/project-members-dialog.tsx, packages/react-ui/src/features/team/lib/project-members-hooks.ts, packages/server/api/src/app/ee/project-members/project-member.controller.ts, packages/server/api/src/app/ee/project-members/project-member.service.ts, packages/server/api/src/app/user-invitations/user-invitation.module.ts
=> fix(project-member-dialog): fetch project members by project role

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts, packages/pieces/community/google-sheets/src/lib/actions/find-row-by-num.ts, packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts, packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts, packages/server/shared/src/lib/system/system.ts
=> refactor: google sheets

packages/pieces/community/pipedrive/package.json, packages/pieces/community/pipedrive/src/index.ts, packages/pieces/community/pipedrive/src/lib/common/types.ts, packages/pieces/community/pipedrive/src/lib/trigger/new-activity.ts, packages/pieces/community/pipedrive/src/lib/trigger/new-deal.ts, packages/pieces/community/pipedrive/src/lib/trigger/new-person.ts, packages/pieces/community/pipedrive/src/lib/trigger/updated-deal.ts, packages/pieces/community/pipedrive/src/lib/trigger/updated-person.ts
=> feat(pipedrive): add filters for updated deal trigger

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/update-row.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts
=> fix(google-sheets): insert & update

docs/developers/misc/build-piece.mdx, docs/developers/misc/publish-piece.mdx, docs/developers/sharing-pieces/private.mdx, docs/mint.json, package.json, packages/cli/src/index.ts, packages/cli/src/lib/commands/build-piece.ts, packages/cli/src/lib/commands/publish-piece.ts, packages/cli/src/lib/commands/sync-pieces.ts, packages/cli/src/lib/utils/piece-utils.ts
=> feat(cli): add build and publish piece commands, update docs

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/lib/actions/return-response.ts
=> fix(webhooks): return response redirect should work without protocl

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
=> fix(google-sheets): optimize metadata response

packages/engine/src/lib/variables/props-resolver.ts, packages/shared/src/lib/common/utils/object-utils.ts
=> feat: avoid deep cloning in engine

packages/server/api/src/app/helper/system-jobs/redis-system-job.ts, packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/shared/package.json, packages/server/shared/src/lib/job/index.ts, packages/server/worker/package.json, packages/shared/src/lib/common/utils/object-utils.ts
=> chore: remove completed system jobs

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/lib/actions/send-email.ts
=> fix(smtp): retry on connection refused

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/lib/actions/send-email.ts, packages/pieces/community/smtp/src/lib/common/index.ts, packages/server/api/src/app/helper/dayjs-helper.ts, packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/api/types/fastify.d.ts
=> test: backend tests

docs/developers/misc/pieces-ci-cd.mdx, packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
=> feat(piece-dialog): improve the error message

.devcontainer/Dockerfile, Dockerfile, package-lock.json, package.json
=> chore: upgrade pnpm to 9.15.0

packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
=> fix(utility-ai): fix empty text error

packages/server/api/src/assets/etc/resolv.conf
=> chore: switch cloudflare to google dns in sandbox

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/index.ts, packages/pieces/community/forms/src/lib/triggers/form-trigger.ts, packages/react-ui/src/features/human-input/components/ap-form.tsx, packages/react-ui/src/features/human-input/lib/human-input-api.tsx, packages/server/api/src/app/flows/flow/human-input/human-input.service.ts, packages/shared/src/lib/flows/form.ts
=> fix(human-input): files should be sent as form data

packages/engine/src/lib/helper/logging-utils.ts, packages/pieces/community/activepieces/src/index.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/shared/src/lib/flow-run/execution/execution-output.ts
=> fix(truncation): allow max log size to be configurable

package-lock.json, packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx, packages/react-ui/src/app/routes/settings/pieces/index.tsx, packages/react-ui/src/features/pieces/lib/pieces-hook.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix: pieces tables filtering

packages/pieces/community/forms/package.json, packages/pieces/community/forms/src/lib/triggers/form-trigger.ts, packages/react-ui/src/features/human-input/components/ap-form.tsx, packages/react-ui/src/features/human-input/lib/human-input-api.tsx, packages/shared/package.json, packages/shared/src/lib/forms/index.ts
=> fix(forms): validate using same input names

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts, packages/pieces/community/google-sheets/src/lib/actions/update-row.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts, packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
=> feat(google-sheets): insert the missing headers in JSON mode

packages/pieces/community/microsoft-outlook-calendar/.eslintrc.json, packages/pieces/community/microsoft-outlook-calendar/README.md, packages/pieces/community/microsoft-outlook-calendar/package.json, packages/pieces/community/microsoft-outlook-calendar/project.json, packages/pieces/community/microsoft-outlook-calendar/src/index.ts, packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/create-event.ts, packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/delete-event.ts, packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/list-events.ts, packages/pieces/community/microsoft-outlook-calendar/src/lib/common/common.ts, packages/pieces/community/microsoft-outlook-calendar/tsconfig.json, packages/pieces/community/microsoft-outlook-calendar/tsconfig.lib.json, tsconfig.base.json
Add a new piece `microsoft-outlook-calendar` with create/delete/list events actions.
=> feat(microsoft-outlook-calendar): create/delete/list events

packages/react-ui/src/app/builder/pieces-selector/index.tsx
=> fix: search result should not tort alpha

packages/pieces/community/linkedin/package.json, packages/pieces/community/linkedin/src/lib/common/index.ts
=> fix(linked-in): update api version

packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/webhooks/webhook-controller.ts
=> fix: quota exceeded response & metadata for file

packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/src/lib/common/wedof.ts
=> fix(wedof-piece): fixing api link

packages/pieces/community/google-search-console/package.json, packages/pieces/community/google-search-console/src/index.ts, packages/pieces/community/google-search-console/src/lib/actions/search-analytics.ts
https://community.activepieces.com/t/issue-with-google-search-console-start-end-date-functionality-making-pieces-useless/7174
=> fix(google-search-console): fix date range format error

packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
=> fix: log sso sign ups events

docker-compose.yml, package.json
=> feat: release 0.38.0

packages/pieces/community/qdrant/package.json, packages/pieces/community/qdrant/src/index.ts, packages/pieces/community/qdrant/src/lib/actions/add-points.ts
=> fix(qdrant): fix content/payload field for add points action

packages/server/api/src/app/file/s3-helper.ts, packages/server/api/src/app/helper/system-validator.ts
Add  s3 configuration validation
Fixes (https://github.com/activepieces/activepieces/issues/6393))
=> feat(s3-validation): add s3 conifguration validation

docker-compose.yml, package.json
=> feat: 0.38.2

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts
Fixes https://community.activepieces.com/t/get-new-rows-row-data-stuck-at-row-1/7206/4
=> fix(google-sheets): fix row number response

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/actions/create-database-item.ts, packages/pieces/community/notion/src/lib/common/index.ts
=> fix: ignore values whose types are not compatible with AP

docs/endpoints/git-repos/configure.mdx, docs/endpoints/git-repos/pull.mdx, docs/endpoints/project-releases/create.mdx, docs/endpoints/project-releases/schema.mdx, docs/mint.json, docs/openapi.json, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/project-release/git-sync/git-sync.module.ts, packages/server/api/src/app/ee/project-release/project-release.controller.ts
=> docs: add project release docs and add git-sync configuration

packages/ee/shared/src/lib/git-repo/index.ts, packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/project-release/git-sync/git-sync.service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts
=> feat: support bulk push to git-sync

docs/operations/git-sync.mdx
=> docs: update Enivroments & Releases docs

docker-compose.yml, package.json
=> feat: Release v0.38.4

packages/pieces/community/text-helper/package.json, packages/pieces/community/text-helper/src/index.ts, packages/pieces/community/text-helper/src/lib/actions/default-value.ts
Default value action in text helper piece.
Fixes #5418
=> feat: add default value action

packages/server/api/src/app/database/migration/postgres/1735262417593-AddExternalIdForFlow.ts
=> fix: check if git_repo table exists before dropping mapping column

docker-compose.yml, package.json, packages/react-ui/src/components/custom/markdown.tsx
=> feat: new version 0.38.6 with bug fixes

packages/server/api/src/app/database/migration/postgres/1735262417593-AddExternalIdForFlow.ts
=> fix: casting the mapping in externalId migration

packages/server/api/src/app/ai/ai-provider-proxy.ts, packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts, packages/server/api/src/app/ee/platform-billing/usage/usage-service.ts
=> fix: ai tokens billing

packages/react-ui/src/lib/api.ts
=> chore: add global error handler

packages/server/api/src/app/worker.ts, packages/server/worker/src/lib/flow-worker.ts
=> chore: merge init & start in one function

package-lock.json, packages/pieces/community/matrix/package.json, packages/pieces/community/matrix/src/lib/actions/send-message.ts, packages/pieces/community/matrix/src/lib/common/common.ts
💅 Add markdown support to the matrix piece
=> feat(matrix): enable markdown formatting

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.39.0

packages/engine/src/main.ts, packages/server/worker/src/lib/engine/threads/worker.ts
=> fix: rollback child process to worker threads

docker-compose.yml, package.json
=> feat: release 0.39.1

docs/openapi.json, package-lock.json, packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx, packages/server/api/src/app/ee/project-release/git-sync/git-sync.module.ts, packages/server/api/src/app/server.ts, packages/shared/src/lib/common/base-model.ts, packages/shared/src/lib/project-release/project-release.request.ts
=> fix: rollback request

packages/server/api/src/app/database/migration/postgres/1735590074879-AddUserIdentity.ts
=> fix: user identity migration for ce postgres

docker-compose.yml, package.json
=> feat: release 0.39.2

packages/pieces/community/todoist/package.json, packages/pieces/community/todoist/src/lib/triggers/task-completed-trigger.ts
=> fix(todoist): fix task completed trigger

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/common/index.ts
=> fix(Google-Drive): Show latest files when testing New File trigger

packages/pieces/community/crypto/package.json, packages/pieces/community/crypto/src/index.ts, packages/pieces/community/crypto/src/lib/actions/hash-text.ts
Add SHA3-512 hash to crypto piece
=> feat(cryto): add SHA3-512 hash

package-lock.json, package.json, packages/pieces/community/claude/package.json, packages/pieces/community/claude/src/index.ts, packages/pieces/community/claude/src/lib/actions/extract-structured-data.ts
=> feat(claude): extract structured data action with PDF support

packages/cli/src/lib/utils/piece-utils.ts
=> fix: create-trigger command for windows users

packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts, packages/server/api/src/app/ee/custom-domains/domain-helper.ts
=> fix: custom domain is no longer required for saml

.all-contributorsrc
update profile link of osamahaikal
=> docs: update profile

packages/pieces/community/seven/.eslintrc.json, packages/pieces/community/seven/README.md, packages/pieces/community/seven/package.json, packages/pieces/community/seven/project.json, packages/pieces/community/seven/src/action/lookup.ts, packages/pieces/community/seven/src/action/send-voice-call.ts, packages/pieces/community/seven/src/action/sms-send.ts, packages/pieces/community/seven/src/action/tts-call.ts, packages/pieces/community/seven/src/common/index.ts, packages/pieces/community/seven/src/index.ts, packages/pieces/community/seven/src/trigger/sms-inbound.ts, packages/pieces/community/seven/tsconfig.json, packages/pieces/community/seven/tsconfig.lib.json, tsconfig.base.json
Hi,
this PR adds a piece for [seven](https://www.seven.io) - a multi-channel communication service.
Hope this helps!
=> feat(seven): send SMS, lookup numbers, send voice call actions and new SMS trigger 

packages/pieces/community/scrapegrapghai/.eslintrc.json, packages/pieces/community/scrapegrapghai/README.md, packages/pieces/community/scrapegrapghai/package.json, packages/pieces/community/scrapegrapghai/project.json, packages/pieces/community/scrapegrapghai/src/index.ts, packages/pieces/community/scrapegrapghai/src/lib/actions/local-scraper.ts, packages/pieces/community/scrapegrapghai/src/lib/actions/markdownify.ts, packages/pieces/community/scrapegrapghai/src/lib/actions/smart-scraper.ts, packages/pieces/community/scrapegrapghai/tsconfig.json, packages/pieces/community/scrapegrapghai/tsconfig.lib.json, tsconfig.base.json
add scrapegraphapi which can scrape websites using ai prompts and extract structued content or convert websites to markdown
=> feat(scrapegraphapi ): smart scraper, local scraper and Markdownify actions

packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/project-release/project-state.ts
=> fix: handle undefined connections state in old releases

docker-compose.yml, package.json
=> feat: release v0.39.5

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/lib/actions/text-to-speech.ts
- added types from openai SDK for voice and response format
- programmatically change tts filename output 
Fixes #6543
=> feat(openai): output file name property for text to speech action

packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
=> fix: empty divs take up space on license key page.

packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
=> fix: upsert user identity and hash email

docker-compose.yml, package.json
=> feat: release 0.39.6

packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/platform-billing/platform-billing.controller.ts, packages/server/api/src/app/ee/stripe-billing/stripe-billing.controller.ts, packages/server/api/src/app/ee/stripe-billing/stripe-billing.module.ts
add new endpoint for public stripe callback
=> fix: stripe webhook for activating subscriptions

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/lib/triggers/new-file.ts
=> fix(onedrive): fix new file trigger

packages/react-ui/src/app/routes/platform/billing/index.tsx, packages/react-ui/src/components/ui/progres-bar.tsx, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/platform-billing/platform-billing.controller.ts, packages/server/api/src/app/ee/platform-billing/platform-billing.module.ts, packages/server/api/src/app/ee/platform-billing/stripe-billing.controller.ts, packages/server/api/src/app/ee/stripe-billing/stripe-billing.module.ts
=> feat(paltform-billing-design-enhancement): design enhancement

packages/server/api/src/app/authentication/user-identity/user-identity-service.ts
=> fix: auto verify google / saml / jwt login

packages/pieces/community/graphql/.eslintrc.json, packages/pieces/community/graphql/README.md, packages/pieces/community/graphql/package.json, packages/pieces/community/graphql/project.json, packages/pieces/community/graphql/src/index.ts, packages/pieces/community/graphql/src/lib/actions/query.ts, packages/pieces/community/graphql/src/lib/common/props.ts, packages/pieces/community/graphql/tsconfig.json, packages/pieces/community/graphql/tsconfig.lib.json, tsconfig.base.json
**Add GraphQL Support to ActivePieces Community Library**
Description:
This PR introduces a new feature for the ActivePieces community library to add GraphQL support. It includes the necessary components to integrate GraphQL functionality, allowing users to easily query and manipulate data within the ActivePieces ecosystem using GraphQL.
Changes:
Implemented GraphQL support as a new piece within the ActivePieces community library.
Added relevant GraphQL queries and variables.
Ensured compatibility with existing ActivePieces components and pieces.
=> feat(graphql): send GraphQL request action

packages/react-ui/src/lib/authentication-session.ts
=> fix: read platform id from the jwt

README.md
I was very nicely added to the documentation (_thanks 🙏🏻_ ) but the domain on my profile was wrong. I am updating the extension.
=> fix: domain extension of my website

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> chore: make the retry strategy of from failed step to retry the same run

packages/server/api/src/app/ee/platform-billing/usage/usage-service.ts
=> refactor: billing logic

packages/server/api/src/app/authentication/authentication.service.ts, packages/server/api/src/app/ee/project-members/project-member.service.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/platform/platform.controller.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/api/src/app/project/project-service.ts, packages/server/api/test/helpers/mocks/index.ts, packages/server/api/test/integration/cloud/authn/cloud-authn.test.ts, packages/server/api/test/integration/cloud/managed-authn/external-token.test.ts, packages/server/api/test/integration/cloud/project-members/project-members.test.ts, packages/server/api/test/integration/cloud/project/project.test.ts, packages/server/api/test/integration/ee/authn/ee-authn.test.ts
=> fix: stripe helper tests

docker-compose.yml, package.json
=> feat: release 0.39.7

packages/pieces/community/beamer/package.json, packages/pieces/community/beamer/src/index.ts, packages/pieces/community/beamer/src/lib/actions/create-vote.ts
=> fix(beamer): fix create vote action

docs/install/architecture/overview.mdx
fix: change angular to react in documentation in docs/install/architecture/overview
=> fix: overview text in docs/install/architecture/overview

packages/pieces/community/jotform/package.json, packages/pieces/community/jotform/src/index.ts, packages/pieces/community/jotform/src/lib/common/index.ts
This adds a new API region for HIPAA complaints forms in the Jotform piece
Fixes https://community.activepieces.com/t/jotform-piece-add-hipaa-endpoint/8547
=> feat(jotform): add HIPPA API url for authentication

packages/pieces/community/kallabot-ai/.eslintrc.json, packages/pieces/community/kallabot-ai/README.md, packages/pieces/community/kallabot-ai/package.json, packages/pieces/community/kallabot-ai/project.json, packages/pieces/community/kallabot-ai/src/index.ts, packages/pieces/community/kallabot-ai/src/lib/actions/get-call-details.ts, packages/pieces/community/kallabot-ai/src/lib/actions/make-call.ts, packages/pieces/community/kallabot-ai/tsconfig.json, packages/pieces/community/kallabot-ai/tsconfig.lib.json, tsconfig.base.json
- Added ESLint configuration for code quality.
- Created package.json and project.json for library metadata.
- Implemented TypeScript configuration files for type safety.
- Developed core actions: `makeCall` and `getCallDetails` for API interactions.
- Added README for library usage instructions.
=> feat(kallabot-ai): make call and get call details action

docs/embedding/sdk-changelog.mdx, package-lock.json, packages/ee/ui/embed-sdk/README.md, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/router/project-route-wrapper.tsx, packages/react-ui/src/app/routes/embed/index.tsx
=> fix: sync resolving configure method in embed-sdk with user authentication

packages/react-ui/src/components/ui/data-table/data-table-options-filter.tsx
=> fix: sync input field value with search params on page load

packages/react-ui/src/app/routes/settings/pieces/index.tsx
=> fix: styling for manage pieces button, delete empty spaces

packages/react-ui/src/app/routes/settings/general/index.tsx, packages/server/api/src/app/project/project-service.ts, packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
=> fix: empty externalId should make unable to update project

docker-compose.yml, package.json, packages/server/api/src/app/authentication/authentication.service.ts, packages/server/api/src/app/authentication/user-identity/user-identity-service.ts
=> feat: deploy a new release 0.39.8

packages/react-ui/src/app/routes/connections/index.tsx, packages/react-ui/src/components/ui/data-table/data-table-select-popover.tsx, packages/react-ui/src/features/connections/lib/app-connections-api.ts, packages/react-ui/src/features/connections/lib/app-connections-hooks.ts, packages/react-ui/src/lib/platforms-api.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app-connection/app-connection.controller.ts, packages/server/api/src/app/authentication/user-identity/user-identity-service.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/api/src/app/user/user-service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/app-connection/app-connection.ts, packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts
=> feat: connections page additional filters

package-lock.json, packages/react-ui/src/app/routes/project-release/apply-plan.tsx, packages/react-ui/src/app/routes/project-release/index.tsx, packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx
=> fix: add searching filter for projects when creating a release from one

packages/pieces/community/confluence/package.json, packages/pieces/community/confluence/src/index.ts, packages/pieces/community/confluence/src/lib/common/index.ts, packages/pieces/community/confluence/src/lib/common/props.ts, packages/pieces/community/confluence/src/lib/triggers/new-page.ts
Adds confluence new page trigger
=> feat(confluence):  new page trigger and custom API call action

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
=> fix(google-sheets): fix csv parsing for multiple rows action

docker-compose.yml, package.json
=> feat: release 0.39.9

package-lock.json, packages/server/api/src/app/authentication/authorization.ts, packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts, packages/server/worker/package.json, packages/server/worker/src/lib/api/server-api.service.ts
=> fix: wrong error for missing projectId in api key authn

package.json
=> feat: pre-release 0.40.0-rc.1

packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/worker/src/lib/api/server-api.service.ts
=> fix: increase p limit and remove linear search

packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx, packages/server/api/src/app/workers/redis/redis-queue.ts
=> fix: decouple update flow status permission

packages/server/api/src/app/workers/memory/memory-queue.ts, packages/server/api/src/app/workers/queue/queue-manager.ts, packages/server/api/src/app/workers/redis/redis-migration.ts, packages/server/api/src/app/workers/redis/redis-queue.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix: migrate bullmq repeatable to new api

docker-compose.yml, package.json
=> feat: release v0.40.0

packages/server/api/src/app/workers/redis/redis-migration.ts
=> fix: broken jobs in redis

package-lock.json, packages/server/api/src/app/ee/platform-billing/platform-billing.module.ts
=> fix: speed up platform billing queries

docs/developers/misc/build-piece.mdx, docs/mint.json, package.json, packages/cli/src/lib/commands/build-piece.ts
=> fix: improve build-piece command using inquirer and enhance documentation styling

docs/handbook/customer-support/handle-requests.mdx
=> docs: handle request priority

docs/handbook/customer-support/handle-requests.mdx
=> docs: add warning about screenshots with sensitive info

packages/server/api/src/app/authentication/authentication.service.ts
=> fix: provision invitation based on sso

package.json, packages/engine/src/main.ts, packages/server/worker/src/lib/engine/threads/worker.ts
Many libraries has issues with worker threads, which might cause the full application to crash, process will be resilient against such issues as it's in separate process. 
=> feat: replace worker threads with child processes 

package.json
=> feat: release 0.41.0 rc

packages/react-ui/src/app/builder/flow-canvas/utils/flow-canvas-utils.ts
=> fix: straight typo

packages/react-ui/src/app/builder/index.tsx
=> fix: fix sidebarbarClosed typo

packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
=> fix: multiple typo fixes

packages/react-ui/src/app/routes/platform/setup/branding/smtp-section.tsx, packages/react-ui/src/hooks/platform-hooks.ts, packages/react-ui/src/lib/platforms-api.ts, packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/platform/platform.model.ts, packages/shared/src/lib/platform/platform.request.ts
closes [#6722](https://github.com/activepieces/activepieces/issues/6722)
=> feat: added button to disable mail server with confirmation beforehand

docs/embedding/embed-builder.mdx, docs/embedding/sdk-changelog.mdx, packages/ee/ui/embed-sdk/package.json, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/app.tsx, packages/react-ui/src/app/components/embedding-font-loader.tsx, packages/react-ui/src/app/components/font-loader.tsx, packages/react-ui/src/app/components/sidebar.tsx, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/components/embed-provider.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx
=> feat: added ability for embedding sdk to specify font family used in Activepieces

docker-compose.yml, package.json
=> feat: release 0.41.0

package.json
=> feat: release 0.42.0-rc.1

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/get-file-by-id.ts
Adds the ability to get Google teamdrive files.
=> feat(google-drive): add teamdrive to get-file-by-id step

packages/cli/src/lib/commands/build-piece.ts, packages/cli/src/lib/commands/create-action.ts, packages/cli/src/lib/commands/create-piece.ts, packages/cli/src/lib/commands/create-trigger.ts, packages/cli/src/lib/commands/publish-piece.ts, packages/cli/src/lib/commands/sync-pieces.ts, packages/cli/src/lib/utils/piece-utils.ts
=> feat: Adding support for syncing specific pieces

packages/pieces/community/common/package.json, packages/pieces/community/metabase/package.json
- Update both patch versions for metabase and common pieces.
Related changes in this [PR](https://github.com/activepieces/activepieces/pull/6792).
=> fix: update common and metabase pieces patch versions

.husky/commit-msg, .husky/pre-push, packages/server/worker/package.json, packages/server/worker/src/lib/api/server-api.service.ts
=> fix: speed up submitting payloads

docs/embedding/sdk-changelog.mdx, package.json
=> feat: rc release

packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts, packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
=> fix: update flow status when republishing again in project release

docker-compose.yml, package.json
=> feat: release 0.42.0

docs/handbook/engineering/incident-response.mdx, docs/mint.json
=> feat: enhance engineering handbook docs

packages/react-ui/src/app/builder/flow-canvas/widgets/incomplete-settings-widget.tsx
=> feat: remove duplicated tw class "border"

packages/react-ui/src/app/builder/flow-canvas/edges/branch-label.tsx
=> feat: remove duplicated tw-sudo class "items-center"

docs/handbook/engineering/onboarding/downtime-incident.mdx, docs/mint.json
=> feat: add downtime incident guide

packages/pieces/community/thankster/.eslintrc.json, packages/pieces/community/thankster/README.md, packages/pieces/community/thankster/package.json, packages/pieces/community/thankster/project.json, packages/pieces/community/thankster/src/index.ts, packages/pieces/community/thankster/src/lib/actions/send-cards.ts, packages/pieces/community/thankster/tsconfig.json, packages/pieces/community/thankster/tsconfig.lib.json, tsconfig.base.json
This adds a new piece to be able to integrate with thankster.com
This is the logo we prefere:
https://thankster-prod.s3.amazonaws.com/public_images/images/Thankster-favicon_3@512.png
Please don't hesitate to leave any further requests
=> feat(thankster): send cards action

packages/pieces/community/grist/package.json, packages/pieces/community/grist/src/index.ts
Just a typo in piece description
=> chore(grist): fix typo

packages/server/api/src/app/ee/platform-billing/platform-billing.service.ts
=> fix: billing update metho

packages/engine/src/lib/helper/execution-errors.ts, packages/server/api/src/app/database/migration/postgres/1739546878775-RestrictPieces.ts, packages/server/api/src/app/database/migration/sqlite/1739544872722-RestrictPiecesSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/ee/license-keys/license-keys-service.ts, packages/server/api/src/app/pieces/base-piece-module.ts, packages/server/api/src/app/pieces/piece-metadata-entity.ts, packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
=> fix: restrict delete piece on file deletion

docs/endpoints/sample-data/get.mdx, docs/endpoints/sample-data/save.mdx, docs/mint.json, docs/openapi.json, package-lock.json, package.json, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/builder/test-step/index.tsx, packages/react-ui/src/app/builder/test-step/test-action-section.tsx, packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx, packages/react-ui/src/app/routes/flows/id/index.tsx, packages/react-ui/src/app/routes/runs/id/index.tsx, packages/react-ui/src/features/flows/lib/sample-data-hooks.ts, packages/server/api/src/app/flows/step-run/sample-data.controller.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/common/base-model.ts, packages/shared/src/lib/flows/sample-data/index.ts, packages/shared/src/lib/platform/platform.model.ts
=> feat: allow SERVICE scope for sample-data endpoints

packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
=> feat: support multiple functions in v8 code SANDBOX_CODE_ONLY

packages/react-ui/src/app/components/request-trial.tsx, packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx, packages/react-ui/src/app/routes/platform/setup/pieces/piece-actions.tsx, packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx, packages/react-ui/src/app/routes/settings/pieces/index.tsx, packages/react-ui/src/components/ui/button.tsx, packages/react-ui/src/components/ui/locked-alert.tsx, packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
allow users install pieces on their platform
=> feat: allow the user to install piece on their platform

docker-compose.yml, package.json
=> feat: upgrade to release v0.43.0

packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx, packages/react-ui/src/app/routes/settings/pieces/index.tsx
=> feat(allow-user-install-piece): fix render locked alert

packages/server/api/src/app/flows/flow-version/flow-version.service.ts
=> fix: loading different piece versions for the same piece

docker-compose.yml, package.json
=> feat: release v0.44.0

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/utils.ts, packages/pieces/community/slack/src/lib/triggers/new-mention.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
=> fix(slack): fix new message trigger test data order

packages/pieces/community/perplexity-ai/package.json, packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts
=> fix(perplexity-ai): Remove deprecated models

packages/pieces/community/confluence/package.json, packages/pieces/community/confluence/src/index.ts, packages/pieces/community/confluence/src/lib/actions/create-page-from-template.ts, packages/pieces/community/confluence/src/lib/actions/get-page-content.ts, packages/pieces/community/confluence/src/lib/common/index.ts, packages/pieces/community/confluence/src/lib/common/props.ts, packages/pieces/community/confluence/src/lib/triggers/new-page.ts
=> feat(confluence): create page from template action

.husky/pre-push
=> revert: linting before push

packages/pieces/community/github/package.json, packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts, packages/pieces/community/github/src/lib/actions/create-issue.ts, packages/pieces/community/github/src/lib/actions/get-issue-information.ts, packages/pieces/community/github/src/lib/actions/lock-issue.ts, packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts, packages/pieces/community/github/src/lib/actions/unlock-issue.ts, packages/pieces/community/github/src/lib/common/index.ts, packages/pieces/community/github/src/lib/trigger/register-trigger.ts
=> fix(github): fix sdk import

package-lock.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/lib/common/index.ts
=> fix: jira cloud fetching all pages of projects 

packages/pieces/community/respaid/package.json, packages/pieces/community/respaid/src/lib/actions/stop_collection_client_paid_directly.ts, packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_instalment_payment.ts, packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_partial_payment.ts, packages/pieces/community/respaid/src/lib/common/index.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts
Added new optional field for Respaid actions: invoice_number.
=> fix: new stop actions field invoice_number

packages/pieces/community/respaid/package.json, packages/pieces/community/respaid/src/lib/actions/create_new_campaign.ts
Added new boolean field "Agency collection?" for the new campaign creation
=> fix(respaid): added is_agency_collection property to create_new_campaign

docs/endpoints/global-connections/delete.mdx, docs/endpoints/global-connections/list.mdx, docs/endpoints/global-connections/schema.mdx, docs/endpoints/global-connections/update.mdx, docs/endpoints/global-connections/upsert.mdx, docs/mint.json, docs/openapi.json, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/global-connections/global-connection-module.ts
=> feat: enable api key access for global connections endpoints

packages/engine/.test.env, packages/engine/jest.config.ts, packages/engine/src/lib/handler/router-executor.ts, packages/engine/test/handler/router-branching.test.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/step-output.ts
=> chore: enhance router output for test step

packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx, packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx, packages/react-ui/src/app/connections/new-connection-dialog.tsx, packages/react-ui/src/app/connections/reconnect-button-dialog.tsx, packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
Fixes https://github.com/activepieces/activepieces/issues/6907
=> fix: connection created event for sdk was always resolved to undefined

packages/engine/test/handler/flow-branching.test.ts
=> fix: test branches with new output

docs/embedding/embed-builder.mdx, docs/embedding/embed-connections.mdx, docs/embedding/sdk-changelog.mdx, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx, packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx, packages/react-ui/src/app/connections/new-connection-dialog.tsx, packages/react-ui/src/app/connections/reconnect-button-dialog.tsx, packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/features/connections/lib/utils.ts, packages/react-ui/src/lib/utils.ts
=> feat: open new window for embed connection

docs/developers/building-pieces/create-trigger.mdx, docs/developers/piece-reference/triggers/polling-trigger.mdx
=> docs: fix polling trigger syntax

packages/pieces/community/github/package.json, packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts, packages/pieces/community/github/src/lib/actions/create-issue.ts, packages/pieces/community/github/src/lib/actions/get-issue-information.ts, packages/pieces/community/github/src/lib/actions/lock-issue.ts, packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts, packages/pieces/community/github/src/lib/actions/unlock-issue.ts, packages/pieces/community/github/src/lib/common/index.ts, packages/pieces/community/github/src/lib/trigger/register-trigger.ts
=> fix(github): fix github sdk build issue

packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts
=> fix: jira-cloud typos

packages/pieces/community/devin/.eslintrc.json, packages/pieces/community/devin/README.md, packages/pieces/community/devin/package.json, packages/pieces/community/devin/project.json, packages/pieces/community/devin/src/index.ts, packages/pieces/community/devin/src/lib/actions/create-session.ts, packages/pieces/community/devin/src/lib/actions/get-session-details.ts, packages/pieces/community/devin/src/lib/actions/send-message.ts, packages/pieces/community/devin/tsconfig.json, packages/pieces/community/devin/tsconfig.lib.json, tsconfig.base.json
This PR adds a new integration for Devin AI, an AI-powered engineering assistant that helps automate development tasks, generate code, and handle technical conversations.
- **Authentication**: Secure API key-based authentication
- **Actions**:
- Create Session: Initiates a new Devin AI session
- Get Session Details: Retrieves information about an existing session
- Send Message: Communicates with the Devin AI assistant
This integration enables Activepieces users to leverage Devin AI's capabilities for automated development tasks and technical assistance directly within their workflows.
=> feat(devin): create session, get session and send message action

packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/auth.ts
=> fix: jira cloud auth error message

packages/server/api/src/app/server.ts
=> fix: add body limit again after accidental remove

packages/engine/src/lib/handler/piece-executor.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/lib/actions/return-response.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/flow-execution.ts
=> feat: add respond piece framework and return response action

packages/server/api/src/app/ee/license-keys/license-keys-service.ts, packages/server/api/src/app/ee/license-keys/license-keys-trial.service.ts
automatically activate a trial key when the platform is deployed on the cloud
=> feat(auto-trial-activation): automatically activate a trial key when the platform is deployed on the cloud

packages/engine/src/lib/handler/code-executor.ts
=> fix: we should always use importFresh in code executor

docker-compose.yml, package-lock.json, package.json, packages/engine/src/lib/handler/code-executor.ts
=> feat: new release 0.46.1

packages/react-ui/src/components/custom/json-editor.tsx
=> fix: editorTheme typo

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/lib/actions/return-response.ts
=> revert: remove respond from webhook piece

packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/index.ts, packages/pieces/community/webhook/src/lib/actions/return-response.ts
=> feat: add respond to webhook return response action

packages/shared/src/lib/flows/util/flow-piece-util.ts
=> fix: get used piecess

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
=> fix: list owners should be only for ee

packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts, packages/server/worker/src/lib/piece-manager/local-piece-manager.ts
=> feat: optimize fetching /options for pieces by using cache

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.46.2

packages/cli/src/lib/commands/create-trigger.ts, tsconfig.base.json
https://community.activepieces.com/t/issue-with-piece-creation-in-activepieces-cli/8820/3
=> fix(cli): fix gelato piece creation command

packages/ee/shared/src/lib/authn/access-control-list.ts, packages/react-ui/src/hooks/authorization-hooks.ts, packages/react-ui/src/lib/authentication-api.ts
=> fix: add folder permission to default roles

package-lock.json, packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
=> fix: show dynamic value toggle in trigger input settings

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.46.4

docs/developers/piece-reference/properties.mdx, packages/pieces/community/framework/src/lib/property/input/custom-property.ts, packages/pieces/community/framework/src/lib/property/input/index.ts, packages/pieces/community/framework/src/lib/property/input/property-type.ts, packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx, packages/react-ui/src/app/builder/piece-properties/custom-property.tsx, packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
Adds a custom property that allows piece developers to add their own JS script to manipulate UI.
Go to packages/pieces/community/webhook/src/lib/actions/return-response.ts
and replace the code with this to test it: 
```
import {
DynamicPropsValue,
Property,
createAction,
} from '@activepieces/pieces-framework';
import { StopResponse } from '@activepieces/shared';
import { StatusCodes } from 'http-status-codes';
enum ResponseType {
JSON = 'json',
RAW = 'raw',
REDIRECT = 'redirect',
}
export const returnResponse = createAction({
name: 'return_response',
displayName: 'Return Response',
description: 'return a response',
props: {
responseType: Property.StaticDropdown({
displayName: 'Response Type',
required: false,
defaultValue: 'json',
options: {
disabled: false,
options: [
{
label: 'JSON', …
```
=> feat: introduce custom property

docs/about/breaking-changes.mdx, docs/embedding/navigation.mdx, docs/embedding/sdk-changelog.mdx, package-lock.json, packages/react-ui/src/app/components/initial-data-guard.tsx, packages/react-ui/src/app/components/loading-screen.tsx, packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx, packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/components/embed-provider.tsx, packages/react-ui/src/components/ui/dialog.tsx
closes [6997](https://github.com/activepieces/activepieces/issues/6997)
=> fix: stop flickering on SDK connect method call

packages/server/api/src/app/database/migration/1741357285896-ProjectIdNullableInTemplate.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/flow-template/flow-template.entity.ts, packages/server/api/src/app/ee/flow-template/flow-template.service.ts, packages/shared/src/lib/flows/dto/flow-template-request.ts
=> fix: nullable project id

packages/pieces/community/claude/package.json, packages/pieces/community/claude/src/lib/actions/extract-structured-data.ts, packages/pieces/community/claude/src/lib/actions/send-prompt.ts, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/providers/index.ts
=> feat: add support for claude 3.7 sonnet model

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
=> fix(google-drive): support shared drive files in list files action

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
=> fix(project-release): update connection name without deleting credentails

packages/react-ui/src/app/builder/builder-flow-status-section/index.tsx
=> fix: correct BuilderFlowStatusSection component displayName

packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts, packages/server/shared/package.json
=> fix: sync flow status with project state in project release

docker-compose.yml, package.json
=> feat: release v0.46.8

packages/pieces/community/assemblyai/package.json, packages/pieces/community/assemblyai/src/lib/actions/transcripts/transcribe.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/flow-execution.ts
=> fix: revert stop response type for webhook piece

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.46.9

packages/pieces/community/tables/package.json, packages/pieces/community/tables/src/index.ts, packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/routes/ap-tables/id/index.tsx, packages/react-ui/src/app/routes/ap-tables/index.tsx, packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx, packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx, packages/react-ui/src/components/ui/dropdown-menu.tsx, packages/react-ui/src/features/flows/lib/flows-hooks.ts, packages/react-ui/src/features/flows/lib/flows-utils.tsx, packages/react-ui/src/features/tables/components/ap-table-actions-menu.tsx, packages/react-ui/src/features/tables/components/column-header.tsx, packages/react-ui/src/features/tables/components/new-field-popup.tsx, packages/react-ui/src/features/tables/components/rename-table-dialog.tsx, packages/react-ui/src/features/tables/lib/utils.tsx, packages/react-ui/src/lib/utils.ts, packages/server/api/src/app/tables/table/table.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/tables/dto/tables.dto.ts
=> fix: allow deleting single tables + introduce actions menu in /tables route

packages/react-ui/src/app/components/usage-limits-button.tsx
=> fix: progress bar value usage limits

packages/server/api/src/app/database/migration/postgres/1741963410825-UpdateNotifyStatusOnEmbedding.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/alerts/alerts-handler.ts, packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts, packages/server/api/src/app/ee/projects/ee-project-hooks.ts, packages/server/api/src/app/project/project-service.ts
=> feat: allow to manual override notify status for embed users

packages/react-ui/src/hooks/user-hooks.ts, packages/react-ui/src/lib/authentication-session.ts, packages/shared/src/lib/authentication/model/principal.ts
=> fix: check if jwt expired in current user

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.47.0

package.json
=> feat: release 0.47.1

packages/pieces/community/tables/src/lib/common/index.ts
This fixes tables triggers issue, it still doesn't make create record trigger work because it currently creates empty records
=> fix(tables): common formatRecord

packages/pieces/community/tables/package.json, packages/pieces/community/tables/src/lib/actions/find-records.ts
Fixes "response.body.map is not a function" error.
=> fix(tables): fix find records action

packages/react-ui/src/app/components/sidebar.tsx, packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
=> fix: project switcher enterprise is filtering wrong projects

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.47.3

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/lib/actions/download-file.ts, packages/pieces/community/microsoft-onedrive/src/lib/actions/list-files.ts
=> fix(onedrive): fix download file and list files action

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/retrieve-thread-messages.ts
- Add retrieve thread messages action in slack piece.
Fixes #7081
=> feat(slack): retrieve slack thread messages action

packages/pieces/community/chainalysis-api/.eslintrc.json, packages/pieces/community/chainalysis-api/README.md, packages/pieces/community/chainalysis-api/package.json, packages/pieces/community/chainalysis-api/project.json, packages/pieces/community/chainalysis-api/src/index.ts, packages/pieces/community/chainalysis-api/src/lib/actions/check-address-sanction.ts, packages/pieces/community/chainalysis-api/tsconfig.json, packages/pieces/community/chainalysis-api/tsconfig.lib.json, tsconfig.base.json
This PR introduces a new integration for Chainalysis Screening API, enabling users to check blockchain addresses against sanctions lists.
- **Authentication**: API Key authentication
- **Actions**:
- Check Address Sanction: Verify if a blockchain address is sanctioned
This integration allows Activepieces users to:
- Screen blockchain addresses against sanctions lists
- Integrate compliance checks into their automation workflows
- Automate AML (Anti-Money Laundering) verification processes
- Automated KYC/AML compliance checks
- Pre-transaction screening
- Risk assessment automation
This integration helps organizations maintain regulatory compliance by automating blockchain address screening against Chainalysis's comprehensive sanctions database.
=> feat(pieces): Add Chainalysis Screening API integration piece

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/actions/find-spreadsheets.ts, packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts, packages/pieces/community/google-sheets/src/lib/common/common.ts
=> fix(google-sheets): fix special characters breaking columns dropdown

packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
=> fix: smtp port not found when inviting user

packages/react-ui/src/app/builder/data-selector/utils.ts
=> fix: prevent crashing in data selector

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.48.0

packages/server/api/src/app/database/database-connection.ts
=> fix: remove exported database connection

docker-compose.yml, package.json
=> feat: release 0.48.2

packages/pieces/community/eth-name-service/.eslintrc.json, packages/pieces/community/eth-name-service/README.md, packages/pieces/community/eth-name-service/package.json, packages/pieces/community/eth-name-service/project.json, packages/pieces/community/eth-name-service/src/index.ts, packages/pieces/community/eth-name-service/src/lib/actions/list-ens-domains.ts, packages/pieces/community/eth-name-service/src/lib/common/common.ts, packages/pieces/community/eth-name-service/tsconfig.json, packages/pieces/community/eth-name-service/tsconfig.lib.json, tsconfig.base.json
This ENS data represents Ethereum Name Service (ENS) domain records with key details:
- Human-readable & Hashed Names: Some names are readable (virgil.eth), while others are hashed ([a2085d6c...].portalid.eth).
- Hierarchy & Subdomains: Domains like virgil.eth have multiple subdomains (mm.virgil.eth, x.virgil.eth, etc.).
- Resolvers & Addresses: Some names resolve to Ethereum addresses (virgil.eth → 0xea97bb...), while others (eth.eth, devcon.eth) do not.
- Migration Status: Indicates whether the domain is on the new ENS registry.
- Parent-Child Structure: Shows domain ownership and nesting under .eth.
This data helps track ENS domain registrations, resolutions, and hierarchy.
```
[
{
"createdAt": "1542787359",
"id": "0x24d67eecd6fd1452e07a50e40f4a33ab09761fecdda9ddfcd317a079bab82769", …
```
=> feat(ethereum name service): List ENS Domains action

packages/pieces/community/pipedrive/package.json, packages/pieces/community/pipedrive/src/lib/common/index.ts, packages/pieces/community/pipedrive/src/lib/trigger/updated-deal-stage.ts
=> fix(pipedrive): add api version for webhook

packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/features/flows/lib/use-flows-bulk-actions.tsx, packages/react-ui/src/features/git-sync/components/published-tooltip.tsx, packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx, packages/server/api/src/app/ee/project-release/git-sync/git-sync.service.ts, packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
1) All flows must be published before pushing to Git
2) All flows created or updated from Release will be Enabled.
=> fix: make sure all flows are published before pushing to git

docs/openapi.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/common/base-model.ts
=> fix: discriminated type was taking undefined values

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.48.5

packages/react-ui/src/app/routes/platform/users/index.tsx, packages/server/api/src/app/user/user-service.ts
=> fix: disable platform admin from being deactivated

package-lock.json, package.json, packages/pieces/community/mailchain/.eslintrc.json, packages/pieces/community/mailchain/README.md, packages/pieces/community/mailchain/package.json, packages/pieces/community/mailchain/project.json, packages/pieces/community/mailchain/src/index.ts, packages/pieces/community/mailchain/src/lib/actions/get-authenticated-user.ts, packages/pieces/community/mailchain/src/lib/actions/send-email.ts, packages/pieces/community/mailchain/src/lib/common/common.ts, packages/pieces/community/mailchain/tsconfig.json, packages/pieces/community/mailchain/tsconfig.lib.json, tsconfig.base.json
This PR introduces a new integration for Mailchain, a decentralized communications protocol that enables blockchain-based email functionality.
- **Authentication**: API Key authentication
- **Categories**: Blockchain/Cryptocurrency, Communication
- **Actions**:
- Get Authenticated User: Retrieve user information
- Send Email: Send blockchain-based emails through Mailchain
This integration allows Activepieces users to:
- Send decentralized emails through the Mailchain protocol
- Retrieve authenticated user information
- Integrate blockchain-based communication into their workflows
- Automated Web3 notifications
- Decentralized mailing lists
- Blockchain-verified communication
- DAO member communications
- DeFi notifications
This integration brings decentralized communication capabilities …
=> feat(pieces): Add Mailchain integration piece

packages/server/api/src/app/user/user-service.ts, packages/server/api/test/integration/ce/user/platform-user-community.test.ts, packages/server/worker/package.json
=> fix: broken community test

packages/pieces/community/google-gemini/package.json, packages/pieces/community/google-gemini/src/lib/common/common.ts
=> feat(google-gemini): add gemini 2.0 flash models

packages/server/api/src/app/project/project-service.ts, packages/server/api/src/app/user/user-service.ts, packages/server/api/src/app/webhooks/webhook.service.ts
=> fix: check if project were soft deleted in webhooks

packages/react-ui/src/app/builder/pieces-selector/dialog-guides/create-todo-guide.tsx, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts, packages/react-ui/src/app/builder/pieces-selector/steps-card-list.tsx, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flows/util/flow-structure-util.ts
=> fix: hide wait for approval step in pieces selector and handle adding steps

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.49.0

packages/react-ui/src/app/builder/pieces-selector/dialog-guides/create-todo-guide.tsx, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx, packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx, packages/react-ui/src/app/builder/pieces-selector/steps-card-list.tsx
=> fix: hide actions in search suggestions and enhance create todo guide

packages/pieces/community/text-ai/package.json, packages/pieces/community/utility-ai/package.json
=> feat: add claude 3.7 in Universal AI pieces

docs/install/configuration/troubleshooting.mdx
=> fix(troubleshooting): update PostgreSQL commands and password reset instructions

packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
=> fix: dialog doesn't open when clicking on create todo action from search suggestions

packages/react-ui/src/app/components/dashboard-container.tsx
=> fix(mcp): Remove mcp from sidebar

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.49.1

packages/react-ui/src/app/routes/settings/mcp/mcp-instruction.tsx, packages/server/api/src/app/ee/mcp/mcp-controller.ts, packages/server/api/src/app/ee/mcp/mcp-module.ts, packages/server/api/src/app/ee/mcp/mcp-server.ts, packages/server/api/src/app/ee/mcp/mcp-session-manager.ts, packages/server/api/src/app/ee/mcp/mcp-sse-controller.ts, packages/server/api/src/app/helper/keyvalue/index.ts, packages/server/api/src/app/helper/keyvalue/memory-store.ts, packages/server/api/src/app/helper/keyvalue/redis-store.ts, packages/server/api/src/app/helper/keyvalue/store.ts
It does no longer require the load balancer to be sticky
=> feat: make mcp stateless

README.md, packages/react-ui/src/app/components/allow-logged-in-user-only-guard.tsx, packages/react-ui/src/app/router/default-route.tsx, packages/react-ui/src/app/routes/settings/mcp/mcp-instruction.tsx, packages/react-ui/src/features/authentication/components/auth-form-template.tsx, packages/react-ui/src/features/authentication/components/sign-in-form.tsx
=> fix: redirect to page after login

docker-compose.yml, package.json, packages/react-ui/src/app/routes/settings/mcp/index.tsx
=> feat: release 0.50.0

packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/src/index.ts, packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts, packages/pieces/community/wedof/src/lib/actions/me.ts, packages/pieces/community/wedof/src/lib/actions/my-organism.ts
feat(wedof):
- add me & myOrganism endpoints
- update package.js
- fix tiersTemps required false
=> feat: Update wedof pieces

packages/pieces/community/wedof/package.json, packages/pieces/community/wedof/src/lib/common/wedof.ts
Add inTrainingStarted & inTrainingEnded
=> feat(wedof): add 2 triggers events on certificationFolders

packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
=> fix: increase connection limit in ConnectionSelect component

packages/server/api/src/app/workers/machine/machine-controller.ts, packages/server/api/src/app/workers/machine/machine-service.ts, packages/shared/src/lib/workers/index.ts
=> fix: listing workers

packages/cli/src/lib/utils/piece-utils.ts
=> fix: build piece cli on windows

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/common/request-action.ts
=> fix(slack): fix request action response for published flow

package-lock.json, package.json, packages/pieces/community/actualbudget/package.json, packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts
This pull request updates the actualbudget api to the latest version. This update includes fixes to bundle issues with actualbudget
This PR also introduces improvements to the importTransaction function by adding validation for the date field and updating the amount conversion logic to use a utility function.
https://github.com/actualbudget/actual/issues/3384
=> fix(actualbudget): Update actual-app/api to latest

packages/server/api/src/app/pieces/piece-sync-service.ts
log the actual error object  in the piece-sync-service
=> fix: error logging

packages/pieces/community/todos/package.json, packages/pieces/community/todos/src/lib/actions/create-todo-and-wait.ts, packages/pieces/community/todos/src/lib/utils/utils.ts, packages/react-ui/src/app/routes/todos/id/index.tsx, packages/react-ui/src/app/routes/todos/todo-details.tsx, packages/server/api/src/app/todos/todo.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/todos/index.ts
=> feat: be able to decide if the status option should continue flow or not

docker-compose.yml, package.json
=> feat: release 0.50.1

package-lock.json, packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
=> fix: should apply connections changes before flows to avoid auth validation error

docker-compose.yml, package-lock.json, package.json, packages/react-ui/src/features/tables/components/fields-mapping.tsx, packages/react-ui/src/features/tables/components/import-csv-dialog.tsx, packages/react-ui/src/features/tables/lib/records-api.ts, packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx, packages/react-ui/src/features/tables/lib/utils.tsx, packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/tables/record/record.controller.ts, packages/server/api/src/app/tables/record/record.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/tables/dto/records.dto.ts
=> feat: release 0.50.2

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/common/get-file-content.ts
=> chore(google-drive): fix typo

packages/pieces/community/intercom/package.json
I forgot to bump the version in #7345 🤦 
=> fix(intercom): bump piece version

packages/react-ui/src/app/routes/mcp/mcp-tools-section.tsx
=> fix: rename MCP Connection to MCP App

packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
=> fix: hide request piece in piece selector when in embedding mode

packages/react-ui/src/features/connections/lib/app-connections-hooks.ts
=> fix: hide platform admins when listing connection owners in embedding

packages/react-ui/src/app/builder/data-selector/data-selector-node.tsx, packages/react-ui/src/app/builder/data-selector/data-selector-size-togglers.tsx, packages/react-ui/src/app/builder/pieces-selector/ask-ai.tsx
=> fix: type in the code

nx.json
=> fix: enhance nx pipeline by adding cache

docs/install/configuration/environment-variables.mdx, packages/server/api/src/app/flags/flag.service.ts
=> fix: delete env variable for show changelog

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts
=> fix(onedrive): fix parent folder dropdown

packages/server/api/src/app/mcp/mcp-sse-controller.ts
=> fix: mcp timeout

nginx.react.conf
=> fix: disable caching for MCP endpoints only

nginx.react.conf
=> revert: disable caching for api requests

nginx.react.conf
=> fix: disable buffering and caching for MCP SSE controller only

nginx.react.conf
=> revert: disable buffering and caching for MCP SSE controller

packages/server/api/src/app/mcp/mcp-server.ts
=> fix: update mcp tool name to match regex

packages/pieces/community/todos/package.json, packages/server/api/src/app/database/migration/postgres/1745272231418-RenameTodoPostiveVariantName.ts, packages/server/api/src/app/database/migration/sqlite/1745269828603-RenameTodoVariantName.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts
=> fix: make a database migration to fix type of positive variant name

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/lib/actions/list-files.ts, packages/pieces/community/microsoft-onedrive/src/lib/actions/list-folders.ts, packages/pieces/community/microsoft-onedrive/src/lib/actions/upload-file.ts, packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts, packages/pieces/community/microsoft-onedrive/src/lib/triggers/new-file.ts
=> fix(onedrive): add limit for parent folder dropdown

docs/embedding/mcps.mdx, packages/pieces/community/mcp/package.json, packages/pieces/community/mcp/src/lib/triggers/mcp-tool.ts, packages/react-ui/src/app/mcp/mcp-flow-card.tsx, packages/react-ui/src/app/mcp/mcp-piece-dialog.tsx, packages/react-ui/src/app/mcp/mcp-piece.tsx, packages/react-ui/src/app/mcp/mcp-tools-section.tsx, packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx, packages/react-ui/src/components/simple-json-viewer.tsx
=> fix: polishing mcp info

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.50.6

packages/react-ui/src/app/mcp/mcp-piece.tsx
=> fix: mcp connection required condition

packages/server/api/src/app/changelog/changelog.service.ts
=> fix: update changelog fetching to 5 minutes instead of 1 day

docker-compose.yml, package.json
=> feat: release 0.50.8

packages/server/worker/src/lib/engine/threads/worker.ts
=> fix: only clean up after exit

docker-compose.yml, package.json
=> feat: release 0.50.9

README.md
Fixed urls for resources images
It fixes urls for images used in the README.md file.
=> fix: missing images in README.md

docker-compose.yml, package.json
=> feat: release 0.50.10

packages/ee/shared/src/lib/authn/access-control-list.ts, packages/react-ui/src/app/mcp/mcp-piece.tsx, packages/react-ui/src/app/mcp/mcp-tools-section.tsx, packages/react-ui/src/app/routes/mcp/index.tsx, packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx, packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx, packages/server/api/src/app/mcp/mcp-piece-controller.ts, packages/server/api/src/app/mcp/mcp-server-controller.ts
=> feat: support mcp permissions

docker-compose.yml, package.json
=> feat: release 0.50.11

packages/engine/src/lib/operations.ts, packages/server/worker/src/lib/executors/flow-job-executor.ts, packages/shared/src/lib/engine/engine-operation.ts
=> feat: enhance flow execution with new payload handling and format option

docker-compose.yml, package.json
=> feat: release 0.50.12

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/triggers/new-command.ts, packages/pieces/community/slack/src/lib/triggers/new-mention.ts, packages/pieces/community/slack/src/lib/triggers/new-message-in-channel.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
=> fix(slack): fix trigger for private channel

package-lock.json, packages/pieces/community/dust/package.json, packages/pieces/community/straico/package.json, packages/pieces/community/straico/src/index.ts, packages/pieces/community/straico/src/lib/actions/rag-create.ts, packages/pieces/community/straico/src/lib/actions/rag-delete.ts, packages/pieces/community/straico/src/lib/actions/rag-get-by-id.ts, packages/pieces/community/straico/src/lib/actions/rag-list.ts, packages/pieces/community/straico/src/lib/actions/rag-prompt-completion.ts, packages/pieces/community/straico/src/lib/actions/rag-update.ts
This PR adds Retrieval-Augmented Generation (RAG) capabilities to the Straico integration, allowing users to create and query document-based AI knowledge bases.
- Added RAG creation, update, and query actions
- Implemented customizable document chunking options
- Integrated with Straico's API for AI-powered document processing
- Create RAG: Upload documents (PDF, DOCX, CSV, TXT, XLSX, PY) with configurable chunking parameters
- Query RAG: Send natural language prompts to retrieve AI-generated answers with source references
- Update RAG: Add new files to existing knowledge bases
- Customer Support: Create knowledge bases from FAQs and documentation to quickly answer customer questions
- Research: Extract insights from academic papers or datasets using natural language queries
- Content …
=> feat(straico): add RAG actions and API integration for Straico

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/app-connection/app-connection.ts, packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
=> chore: skip validation for missing connections in project release

packages/pieces/community/rss/package.json, packages/pieces/community/rss/src/index.ts, packages/pieces/community/rss/src/lib/common/getId.ts, packages/pieces/community/rss/src/lib/common/props.ts, packages/pieces/community/rss/src/lib/common/sampleData.ts, packages/pieces/community/rss/src/lib/triggers/new-item-list-triggers.ts, packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts
We created a new trigger that allow a list instead of a single link feed for rss
=> feat(rss): new trigger, take a list of feed

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/providers/openai/index.ts, packages/pieces/community/text-ai/package.json, packages/pieces/community/utility-ai/package.json
=> feat(text-ai): add reasoning models 

packages/react-ui/src/app/connections/flows-connection-dialog.tsx, packages/react-ui/src/app/connections/replace-connections-dialog.tsx, packages/react-ui/src/app/routes/connections/index.tsx, packages/react-ui/src/app/routes/platform/setup/connections/index.tsx, packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx, packages/react-ui/src/features/connections/components/rename-connection-dialog.tsx, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/app-connection/app-connection.ts
=> fix(connection): add flows count column, improve delete confirmation dialog

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.52.1

packages/react-ui/src/app/router/index.tsx, packages/react-ui/src/app/routes/mcp/index.tsx, packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
=> fix: show localhost for mcp server url if no public instance url is set

packages/server/worker/src/lib/engine/threads/worker.ts
=> fix: improve worker management and error handling

packages/server/api/src/app/database/migration/postgres/1746543299109-ChangeMcpPieceForeignKey.ts, packages/server/api/src/app/database/migration/sqlite/1746543346220-ChangeMcpPieceForeignKey.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/mcp/mcp-piece-entity.ts, packages/server/api/src/app/tables/field/field.entity.ts
=> fix: naming of indices for mcp piece entity

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/actions/get-conversation.ts, packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/upsert-document.ts, packages/pieces/community/dust/src/lib/common.ts
Dust now supports a EU region, with a different base URL
=> feat(dust): add support for EU region

packages/pieces/community/twin-labs/package.json, packages/pieces/community/twin-labs/src/lib/actions/start-browsing-task.ts
This PR updates :
- the API URL
- the polling process
- you send your request to the /browse endpoint
- you get a URL in response to follow the task status
=> feat(twin-labs): new API url and new polling process

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts, packages/server/api/src/app/flows/flow-version/flow-version.service.ts
=> fix: update flows on connection merge without republish

packages/pieces/community/netsuite/.eslintrc.json, packages/pieces/community/netsuite/README.md, packages/pieces/community/netsuite/package.json, packages/pieces/community/netsuite/project.json, packages/pieces/community/netsuite/src/index.ts, packages/pieces/community/netsuite/src/lib/actions/get-customer.ts, packages/pieces/community/netsuite/src/lib/actions/get-vendor.ts, packages/pieces/community/netsuite/src/lib/oauth.ts, packages/pieces/community/netsuite/tsconfig.json, packages/pieces/community/netsuite/tsconfig.lib.json, tsconfig.base.json
Add some basic capabilities to query netsuite's restful API for records
https://system.netsuite.com/help/helpcenter/en_US/APIs/REST_API_Browser/record/v1/2024.2/index.html#tag-customer
Fetching information from netsuite / running automations based on information from netsuite
=> feat(netsuite): get vendor and get customer actions

package-lock.json, package.json, packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts, packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
Replace puppeteer by playwright for the metabase action to get a graph. As discussed [here](https://alanhealth.slack.com/archives/C06F3QW2AG5/p1745396420767769), we check if chromium is installed, if not, we don't display the action at all.
Fixes Q-1275
=> feat(metabase): get graph action modifications

packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts
=> refactor: simplify app connection replacement

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.52.3

packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/flows/flow/flow.service.ts
=> fix: search by name and connection ids

packages/server/api/src/app/database/migration/sqlite/1746367601605-AddExternalIdForTablesAndFieldsSQLITE.ts
=> feat: add externalId column to temporary_table migration for SQLite

packages/server/api/src/app/database/database-connection.ts
=> fix: array contains in postgres

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.52.5

packages/react-ui/src/app/routes/flows/flows-table/columns.tsx, packages/react-ui/src/app/routes/flows/flows-table/index.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx
Reverts activepieces/activepieces#7621
=> revert: "feat: flow table actions issue"

packages/react-ui/src/app/routes/flows/flows-table/columns.tsx, packages/react-ui/src/app/routes/flows/flows-table/index.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/folders/component/folder-filter-list.tsx
Reverts activepieces/activepieces#7626
=> Revert "revert: "feat: flow table actions issue""

packages/ee/shared/src/lib/audit-events/index.ts, packages/engine/test/handler/flow-with-response.test.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/property/authentication/custom-auth-prop.ts, packages/react-ui/src/app/builder/pieces-selector/ask-ai.tsx, packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx, packages/react-ui/src/app/builder/step-settings/index.tsx, packages/react-ui/src/app/builder/step-settings/router-settings/branches-list.tsx, packages/react-ui/src/app/builder/step-settings/router-settings/index.tsx, packages/react-ui/src/components/ui/sortable.tsx, packages/server/api/src/app/ee/authentication/project-role/rbac-middleware.ts, packages/server/api/test/helpers/mocks/index.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flows/operations/index.ts, packages/shared/src/lib/flows/operations/move-branch.ts, packages/shared/src/lib/flows/operations/swap-branch.ts
=> feat: reorder branches

packages/server/worker/src/lib/api/server-api.service.ts, packages/server/worker/src/lib/executors/repeating-job-executor.ts
=> feat: skip cache for flow version when polling

.github/workflows/build-cloud-nx.yml, packages/server/api/test/integration/ce/flows/flow.test.ts
=> fix: make testing ci run in parallel

.github/workflows/build-cloud-nx.yml
=> fix: upgrade nx to extra large 

packages/pieces/community/respaid/package.json, packages/pieces/community/respaid/src/lib/common/index.ts
Removed invoice_number from action validation as required parameter
=> fix: respaid - removed invoice_number from action validation

packages/engine/test/handler/flow-piece.test.ts
=> fix: increase timeout for flow-piece.test.ts

package-lock.json, package.json, packages/pieces/community/clarifai/package-lock.json, packages/pieces/community/clarifai/package.json, packages/pieces/community/clarifai/project.json
=> refactor: move clarifai sdk to piece package.json

package-lock.json, package.json, packages/pieces/community/amazon-sqs/package-lock.json, packages/pieces/community/amazon-sqs/package.json, packages/pieces/community/amazon-sqs/project.json, packages/pieces/community/amazon-sqs/src/index.ts, packages/pieces/community/amazon-sqs/src/lib/actions/send-message.ts
=> refactor: replace (& move) aws sdk with client-sqs in piece package.json

packages/server/worker/src/lib/executors/flow-job-executor.ts
=> feat: make quota exceeded retryable by storing trigger payload

packages/react-ui/src/app/builder/builder-header.tsx
=> fix: hide the flow menu when flow name is hidden

packages/server/api/src/app/flows/flow/flow-service-side-effects.ts, packages/server/api/src/app/webhooks/webhook.service.ts
=> fix(handshake): handle undefined payload by fetching data when necessary

packages/server/api/src/app/ee/project-release/git-sync/git-sync-helper.ts
=> fix(project-releases): fallback to id in case external Id is not null

packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts, packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts
=> fix(project-state): skip overriding auth for empty trigger

packages/server/api/src/app/flows/flow/flow.service.ts
=> fix(flow): improve case-insensitive search for flow display names

docker-compose.yml, package.json
=> feat: release 0.54.0

packages/pieces/community/dust/src/index.ts, packages/pieces/community/intercom/package.json
=> feat(dust): add custom api call action

packages/server/api/src/app/webhooks/webhook-handler.ts
=> refactor: update webhook handler to improve payload saving logic

packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/i18n.ts
Reverts activepieces/activepieces#7728
=> Revert "chore: add more logs to framework"

package-lock.json, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/i18n.ts
Reverts activepieces/activepieces#7727
=> Revert "chore: add logging to framework when extracting i18n"

packages/react-ui/src/app/connections/replace-connections-dialog.tsx
=> chore: update replace connections dialog message

docs/handbook/engineering/onboarding/onboarding-check-list.mdx, docs/mint.json
Add On-boarding check list section to docs.
=> docs: Add on-boarding check list

packages/pieces/community/dropbox/package.json, packages/pieces/community/dropbox/src/index.ts, packages/pieces/community/dropbox/src/lib/actions/download-file.ts
Created a new action that allows the user to download a file
The action downloads a file from the specified dropbox path. There was a previous action: "Get temporary file link", but this action doesn't return an ActivePieces file so it could not be linked to other pieces and/or actions.
- Download a file from Dropbox
=> feat(dropbox): download file action

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
=> fix: retry run on latest version should not copy logs

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
We need the `links:*` scopes for some custom API calls
=> feat(slack): add links:* scope

docker-compose.yml, package.json, packages/server/api/src/app/database/migration/common/1747312147549-ChangeExternalIdsForTables.ts, packages/server/api/src/app/database/migration/common/1747346473000-ChangeExternalIdsForTables.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts
=> feat: release 0.55.0

packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts
=> fix: replace connections to be exact match

package-lock.json, packages/react-ui/src/features/tables/components/ap-table-state-provider.tsx, packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
=> fix: fetch all table records when listing

packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx, packages/react-ui/src/features/projects/components/project-switcher.tsx
=> fix: project switcher width

packages/react-ui/src/app/routes/authenticate/index.tsx, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/app/routes/redirect.tsx, packages/react-ui/src/features/authentication/components/sign-in-form.tsx, packages/react-ui/src/features/authentication/components/sign-up-form.tsx, packages/react-ui/src/hooks/project-hooks.ts, packages/react-ui/src/lib/ap-browser-storage.ts, packages/react-ui/src/lib/authentication-session.ts
=> chore: switching embedding to use session storage instead of local storage

packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/lib/triggers/new-labeled-email.ts
=> fix(gmail): fix new labeled trigger

package-lock.json, package.json, packages/pieces/community/dust/package-lock.json, packages/pieces/community/dust/package.json, packages/pieces/community/dust/project.json
=> refactor: move dust client to piece package.json

package-lock.json, package.json, packages/pieces/community/actualbudget/package-lock.json, packages/pieces/community/actualbudget/package.json, packages/pieces/community/actualbudget/project.json
=> refactor: move actualbudget sdk to piece package.json

package-lock.json, package.json, packages/pieces/community/contentful/package-lock.json, packages/pieces/community/contentful/package.json, packages/pieces/community/contentful/project.json
=> refactor: move "contentful-management" sdk to piece package.json

packages/pieces/community/saleor/.eslintrc.json, packages/pieces/community/saleor/README.md, packages/pieces/community/saleor/package.json, packages/pieces/community/saleor/project.json, packages/pieces/community/saleor/src/index.ts, packages/pieces/community/saleor/src/lib/actions/add-note-to-order.ts, packages/pieces/community/saleor/src/lib/actions/get-order.ts, packages/pieces/community/saleor/src/lib/actions/raw-graphql-query.ts, packages/pieces/community/saleor/tsconfig.json, packages/pieces/community/saleor/tsconfig.lib.json, tsconfig.base.json
Add a new piece Saleor with a graphql api call.
Also added new actions to get an order and add a message to it.
=> feat(saleor): new piece implementation

packages/pieces/community/azure-openai/package-lock.json, packages/pieces/community/azure-openai/package.json, packages/pieces/community/azure-openai/project.json
=> fix: add tiktoken package to azure-openai piece package.json

packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
=> fix: ignore patch version when comparing piece versions in project release diff

packages/server/api/src/app/ee/projects/project-release/project-release.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts, packages/server/api/src/app/flows/flow/human-input/human-input.service.ts, packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts, packages/server/worker/src/lib/engine/flow-engine-util.ts, packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts, packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
=> refactor: improve the flow changed function

packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
=> refactor: enhance version comparison logic in project diff service

packages/server/api/test/helpers/flow-generator.ts, packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts, packages/server/api/test/unit/app/ee/git-repos/operations/project-diff.test.ts
=> fix: failed unit tests

docs/embedding/embed-builder.mdx, docs/embedding/sdk-changelog.mdx, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/components/embed-provider.tsx, packages/react-ui/src/components/ui/home-button.tsx, packages/react-ui/src/lib/utils.ts
=> feat: added a method to override home button being clicked in embedding

packages/pieces/community/tables/package.json, packages/pieces/community/tables/src/lib/common/index.ts, packages/server/api/src/app/server.ts, packages/server/api/src/app/tables/record/record.service.ts
https://community.activepieces.com/t/bug-when-using-table-in-0-56-version/9773
=> fix(tables): find-records action & use qs query parser

packages/server/api/src/app/ee/platform/platform-plan/platform-plan.service.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/api/test/helpers/mocks/index.ts, packages/server/api/test/integration/cloud/audit-event/audit-event.test.ts, packages/server/api/test/integration/cloud/authn/cloud-authn.test.ts, packages/server/api/test/integration/cloud/flow-templates/flow-templates.test.ts, packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts, packages/server/api/test/integration/cloud/global-connection/global-connection.test.ts, packages/server/api/test/integration/cloud/managed-authn/external-token.test.ts, packages/server/api/test/integration/cloud/platform/platform.test.ts, packages/server/api/test/integration/cloud/project-members/project-members.test.ts, packages/server/api/test/integration/cloud/project/project.test.ts, packages/server/api/test/integration/cloud/signing-key/signing-key.test.ts, packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts, packages/server/api/test/integration/ee/authn/ee-authn.test.ts
=> fix: integration tests with new platform plan schema 

packages/server/api/src/app/mcp/mcp-server.ts, packages/server/api/src/app/mcp/mcp-sse-controller.ts
=> feat(mcp): add streamable http transport

packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts, packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx, packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
=> fix: show oauth2 configure button condition

packages/pieces/community/framework/src/lib/property/index.ts, packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
=> refactor: remove unused export

packages/engine/src/lib/operations.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/webhooks/webhook-handler.ts, packages/server/api/src/app/workers/worker-controller.ts, packages/server/shared/src/lib/job/job-data.ts, packages/server/worker/src/lib/executors/flow-job-executor.ts, packages/shared/src/lib/engine/engine-operation.ts
=> fix: test webhook google drive

packages/pieces/community/coda/package.json, packages/pieces/community/coda/src/index.ts
=> feat(coda): custom api call action

packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
=> feat(flow-run): sync webhook didn't extract payloads

packages/pieces/community/motion/.eslintrc.json, packages/pieces/community/motion/README.md, packages/pieces/community/motion/package.json, packages/pieces/community/motion/project.json, packages/pieces/community/motion/src/index.ts, packages/pieces/community/motion/src/lib/actions/create-project.ts, packages/pieces/community/motion/src/lib/actions/create-task.ts, packages/pieces/community/motion/src/lib/actions/find-task.ts, packages/pieces/community/motion/src/lib/actions/get-task.ts, packages/pieces/community/motion/src/lib/actions/move-task.ts, packages/pieces/community/motion/src/lib/actions/update-task.ts, packages/pieces/community/motion/src/lib/common/props.ts, packages/pieces/community/motion/src/lib/triggers/task-created.ts, packages/pieces/community/motion/tsconfig.json, packages/pieces/community/motion/tsconfig.lib.json, tsconfig.base.json
What does this PR do?
Trigger:
-  Task Created: Kick off automations like CRM updates or reporting when a task is added in Motion.
Write Actions:
- Create Task: Auto-generate tasks from tickets, forms, or emails.
- Update Task: Modify tasks when external updates occur.
- Create Project: Launch projects triggered by external events.
- Move Task: Transfer tasks between workspaces.
Search Action:
- Find Task: Lookup tasks by name/ID to prevent duplicates or enable conditional logic.
Fixes #7864
/claim #7864
=> feat: implement motion piece with actions and triggers

packages/ee/shared/package.json, packages/ee/shared/src/lib/git-repo/index.ts, packages/react-ui/src/app/routes/connections/connection-actions-menu.tsx, packages/react-ui/src/app/routes/connections/index.tsx, packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection-side-effects.ts, packages/server/api/src/app/app-connection/app-connection.controller.ts, packages/server/api/src/app/ee/connection-keys/connection-key.module.ts, packages/server/api/src/app/ee/global-connections/global-connection-module.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-helper.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.module.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.service.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/tables/table/table.controller.ts
=> fix: sync git connection deletion on release and support git push

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.59.1

packages/server/api/src/app/ee/projects/project-members/project-member.service.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/project/project-service.ts
=> fix: ignore project memebers associated with soft deleted projects

docker-compose.yml, package-lock.json, package.json
=> feat: release v0.60.1

packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/index.ts, packages/pieces/community/jira-cloud/src/lib/actions/get-issue-attachment.ts
=> feat(jira-cloud): get attachment action

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
=> fix(slack): expose actions and triggers

packages/engine/test/handler/flow-error-handling.test.ts, packages/pieces/community/webhook/package.json, packages/pieces/community/webhook/src/lib/actions/return-response-and-wait-for-next-webhook.ts, packages/pieces/community/webhook/src/lib/actions/return-response.ts
=> fix: missing body in return response and wait for next webhook

packages/react-ui/src/app/mcp/mcp-connect/index.tsx, packages/react-ui/src/app/mcp/mcp-connect/mcp-server-url-box.tsx
=> feat:  update mcp instructions for claude 

packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
=> fix: handle undefined values in versionSetTwo to prevent startsWith error

packages/react-ui/src/components/ui/data-table/index.tsx, packages/react-ui/src/features/tables/components/import-csv-dialog.tsx, packages/server/api/src/app/database/database-connection.ts, packages/server/api/src/app/database/migration/postgres/1749128866314-AddMcpToolFlowCascadeDelete.ts, packages/server/api/src/app/database/migration/sqlite/1749129178686-AddMcpToolFlowCascadeDeleteSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts
=> fix: add cascade delete to mcp tool flow

packages/server/api/src/app/ai/ai-provider.module.ts, packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
=> refactor: handle undefined by using Map instead of Record in flow change check

docs/about/breaking-changes.mdx, packages/pieces/community/claude/package.json, packages/pieces/community/claude/src/index.ts, packages/pieces/community/common/package.json, packages/pieces/community/common/src/index.ts, packages/pieces/community/openai/package-lock.json, packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/index.ts, packages/pieces/community/utility-ai/src/lib/actions/check-moderation.ts, packages/pieces/community/utility-ai/src/lib/actions/classify-text.ts, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts, packages/server/api/src/app/ai/ai-provider.module.ts
=> fix: update pieces to new AI SDK

packages/server/api/src/app/workers/queue/queue-manager.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix: rate limit jobs should have ultra low priority

packages/server/worker/package.json, packages/shared/package.json
=> fix: bump shared version

.github/workflows/validate-publishable-packages.yml
=> fix: apply validate-publishable-packages to all packages

packages/pieces/community/claude/package.json, packages/pieces/community/image-ai/package.json, packages/pieces/community/openai/package-lock.json, packages/pieces/community/openai/package.json, packages/pieces/community/text-ai/package.json, packages/pieces/community/utility-ai/package.json
=> fix: bump versions for AI pieces

packages/pieces/community/common/package.json, packages/pieces/community/image-ai/package.json, packages/pieces/community/text-ai/package.json, packages/pieces/community/utility-ai/package.json, packages/server/worker/package.json, packages/shared/package.json
=> fix: bump version of @activepieces/pieces-common to 0.5.0

packages/pieces/community/amazon-s3/package.json, packages/pieces/community/amazon-s3/src/index.ts, packages/pieces/community/amazon-s3/src/lib/actions/generate-signed-url.ts
It will allow to create a signed URL for an object in a bucket s3.
=> feat(amazon-s3): new action generate signed url

docs/ai/mcp.mdx, docs/embedding/embed-builder.mdx, docs/embedding/navigation.mdx, docs/embedding/sdk-changelog.mdx, docs/handbook/engineering/onboarding/on-call.mdx, docs/handbook/teams/overview.mdx, docs/mint.json, packages/ee/ui/embed-sdk/src/index.ts, packages/react-ui/src/app/app.tsx, packages/react-ui/src/app/builder/builder-header/builder-header.tsx, packages/react-ui/src/app/components/flow-actions-menu.tsx, packages/react-ui/src/app/routes/embed/index.tsx, packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx, packages/react-ui/src/components/embed-provider.tsx, packages/react-ui/src/components/ui/home-button.tsx
=> feat: added ability to set locale in embedding + set light/dark mode + hide duplicate flow

packages/react-ui/src/app/routes/flows/issues-table/columns.tsx, packages/server/api/src/app/database/migration/postgres/1750025401754-MakeStepNameOptional.ts, packages/server/api/src/app/database/migration/sqlite/1750025280435-MakeStepNameOptionalSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/flow-run/flow-run-controller.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/flows/issues/issues-entity.ts, packages/server/api/src/app/flows/issues/issues-service.ts
=> fix: make stepName optional in issues and update related queries

packages/server/api/src/app/database/migration/postgres/1750093037011-RemoveUniqueOnFlow.ts, packages/server/api/src/app/database/migration/sqlite/1750093133906-RemoveUniqueOnFlowSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/flows/issues/issues-entity.ts
=> fix: remove unique constraint on issue

packages/react-ui/src/app/components/sidebar/index.tsx, packages/react-ui/src/app/routes/agents/index.tsx, packages/react-ui/src/app/routes/tables/index.tsx, packages/react-ui/src/app/routes/todos/index.tsx, packages/react-ui/src/components/custom/beta-badge.tsx
=> feat: rename beta to new

packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/index.tsx
=> fix(mcp): mcp with connectionless pieces

packages/react-ui/src/app/builder/builder-hooks.ts, packages/react-ui/src/app/builder/flow-canvas/index.tsx, packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
=> feat: animate runs

packages/react-ui/src/app/builder/run-details/flow-step-io/flow-step-agent.tsx, packages/react-ui/src/app/builder/run-details/index.tsx, packages/react-ui/src/app/builder/test-step/custom-test-step/test-todo-dialog.tsx, packages/react-ui/src/app/routes/todos/todo-details/index.tsx, packages/react-ui/src/app/routes/todos/todo-details/todo-timeline-comment-skeleton.tsx, packages/react-ui/src/app/routes/todos/todo-details/todo-timeline.tsx, packages/react-ui/src/features/todos/lib/todos-activity-hook.ts, packages/server/api/src/app/todos/todo.controller.ts, packages/server/api/src/app/todos/todo.service.ts, packages/shared/src/lib/todos/todos-request.ts
=> feat: polish agents & output in the builder

packages/server/api/src/app/ai/providers/openai.ts
=> fix: revert include_usage in openai stream

docker-compose.yml, package-lock.json, package.json
=> feat: release 0.64.2

packages/pieces/community/xero/package.json, packages/pieces/community/xero/src/index.ts
=> feat(xero): add attachments and settings scopes

packages/ee/shared/src/lib/billing/index.ts, packages/ee/shared/src/lib/billing/plan-limits.ts, packages/react-ui/src/app/components/sidebar/usage-limits-button.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/app/routes/platform/billing/index.tsx, packages/react-ui/src/components/ui/badge.tsx, packages/react-ui/src/features/billing/components/ai-credit-usage.tsx, packages/react-ui/src/features/billing/components/extra-user-seats-dialog.tsx, packages/react-ui/src/features/billing/components/plan-card.tsx, packages/react-ui/src/features/billing/components/success.tsx, packages/react-ui/src/features/billing/components/trial-dialog.tsx, packages/react-ui/src/features/billing/components/usage-cards.tsx, packages/react-ui/src/features/billing/lib/api.ts, packages/react-ui/src/features/billing/lib/billing-hooks.ts, packages/react-ui/src/hooks/project-hooks.ts, packages/server/api/src/app/database/migration/postgres/1751021111433-addPaymentMethodToPlatformPlan.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts, packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts, packages/server/api/src/app/ee/helper/email/email-service.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.entity.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.service.ts, packages/server/api/src/app/ee/platform/platform-plan/stripe-billing.controller.ts, packages/server/api/src/app/ee/platform/platform-plan/stripe-helper.ts, packages/server/api/src/assets/emails/trial-ending-reminder.html, packages/shared/src/lib/platform/platform.model.ts
=> feat: trial experience

packages/react-ui/src/components/custom/json-editor.tsx, packages/react-ui/src/features/agents/agent-card.tsx
=> fix: json input was overgrowing the dialog for generating webhook sample data

Dockerfile
=> feat(docker): optimize build cache by reordering COPY and npm ci

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node-status.tsx, packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/pieces-selector/create-agent-action-item.tsx, packages/react-ui/src/app/builder/pieces-selector/create-todo-dialog.tsx, packages/react-ui/src/app/builder/pieces-selector/custom-piece-selector-items-utils.ts, packages/react-ui/src/app/builder/pieces-selector/piece-actions-or-triggers-list.tsx, packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx, packages/react-ui/src/app/builder/pieces-selector/run-agent-action-item.tsx, packages/react-ui/src/app/builder/step-settings/step-card.tsx, packages/react-ui/src/app/components/dashboard-container.tsx, packages/react-ui/src/app/routes/agents/builder/agent-settings.tsx, packages/react-ui/src/app/routes/agents/builder/index.tsx, packages/react-ui/src/app/routes/agents/index.tsx, packages/react-ui/src/components/ui/drawer.tsx, packages/react-ui/src/features/agents/agent-card.tsx, packages/react-ui/src/features/agents/create-agent-button.tsx, packages/react-ui/src/features/agents/lib/agents-api.ts, packages/react-ui/src/features/flows/lib/flows-hooks.ts, packages/react-ui/src/features/pieces/lib/pieces-hooks.ts, packages/react-ui/src/features/pieces/lib/step-utils.tsx, packages/react-ui/src/features/pieces/lib/steps-hooks.ts, packages/react-ui/src/hooks/platform-hooks.ts, packages/react-ui/src/lib/types.ts, packages/server/api/src/app/agents/agent-controller.ts
=> feat: implement agent selector

docs/endpoints/users/list.mdx, docs/endpoints/users/schema.mdx, docs/mint.json, docs/openapi.json, packages/server/api/src/app/app.ts, packages/server/api/src/app/ee/license-keys/license-keys-service.ts, packages/server/api/src/app/user/platform/platform-user-controller.ts, packages/server/api/src/app/user/user-service.ts, packages/shared/src/lib/user/index.ts
=> feat: list users endpoint by external id

packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/services/progress.service.ts, packages/pieces/community/agent/package.json, packages/pieces/community/agent/src/lib/agent-executor.ts, packages/react-ui/src/features/agents/agent-use-button.tsx, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/flags/flag.service.ts, packages/server/api/src/app/todos/todo.controller.ts, packages/server/api/src/app/todos/todo.service.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/agents/index.ts, packages/shared/src/lib/engine/requests.ts, packages/shared/src/lib/todos/index.ts
=> fix: agent execution message and output

packages/react-ui/src/app/components/sidebar/usage-limits-button.tsx, packages/react-ui/src/lib/api.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/shared/src/lib/project/project.ts
=> fix(hot): skip platformPlan info fetch in project dashboard

packages/server/api/src/app/ee/platform/platform-usage-service.ts
=> fix: ai credits redis increment floats

package-lock.json, packages/server/api/src/app/ai/ai-provider.module.ts, packages/server/api/src/app/ai/providers/openai.ts
=> fix: openai streaming always include usage

packages/ee/shared/src/lib/billing/plan-limits.ts, packages/react-ui/src/app/components/dashboard-container.tsx, packages/react-ui/src/app/components/sidebar/usage-limits-button.tsx, packages/react-ui/src/app/routes/flows/index.tsx, packages/react-ui/src/features/billing/components/trial-dialog.tsx, packages/react-ui/src/features/billing/lib/api.ts, packages/react-ui/src/features/billing/lib/billing-hooks.ts, packages/server/api/src/app/app.ts, packages/server/api/src/app/database/migration/1751394161203-AddTrialFlagInPlatform.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.entity.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.service.ts, packages/server/api/src/app/ee/platform/platform-plan/stripe-billing.controller.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/flows/step-run/sample-data.controller.ts, packages/server/api/src/app/websockets/websockets.service.ts, packages/shared/src/lib/platform/platform.model.ts, packages/shared/src/lib/project/project.ts
=> feat: refactor trial

packages/pieces/community/agent/package.json, packages/pieces/community/agent/src/lib/agent-executor.ts, packages/server/api/src/app/ai/ai-provider.module.ts, packages/shared/package.json, packages/shared/src/lib/ai/index.ts
=> fix: agent error handling

packages/engine/src/lib/handler/code-executor.ts, packages/server/shared/src/lib/crypto.ts, packages/server/worker/src/lib/cache/code-builder.ts, packages/server/worker/src/lib/cache/execution-files.ts
=> feat: optmize code builds

packages/pieces/community/amazon-s3/package.json, packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts
=> fix(s3): update trigger strategy to time based for duplicate  file issue

packages/react-ui/src/features/agents/agent-tool-block.tsx, packages/server/api/src/app/mcp/mcp-server/mcp-server.ts, packages/server/api/src/app/mcp/mcp-utils.ts
=> fix: improve MCP parameter extraction prompt

packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/components/changelog-provider.tsx, packages/react-ui/src/lib/changelog-api.ts, packages/server/api/src/app/changelog/changelog.controller.ts, packages/server/api/src/app/user-invitations/user-invitation.service.ts, packages/shared/src/lib/changelog/changelog.request.ts, packages/shared/src/lib/changelog/changelog.ts, packages/shared/src/lib/changelog/index.ts
=> fix: user can't dismiss changelog announcement to themselves

packages/engine/src/lib/handler/code-executor.ts, packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/engine/src/lib/handler/flow-executor.ts, packages/engine/src/lib/handler/loop-executor.ts, packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/handler/router-executor.ts, packages/shared/src/lib/flow-run/execution/step-output.ts
=> feat(executors): add duration tracking for action execution steps

packages/react-ui/src/app/builder/index.tsx, packages/react-ui/src/app/components/request-trial.tsx, packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
=> fix: request trial button + text color on role dialog

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/list-users.ts
Add new action to just list all users (optionally including bots and/or disabled users)
=> feat(slack): add action to list all users of a workspace

packages/react-ui/src/app/routes/tables/id/index.tsx, packages/react-ui/src/components/ui/drawer.tsx, packages/react-ui/src/features/tables/components/ap-table-header.tsx, packages/react-ui/src/features/tables/components/new-field-popup.tsx, packages/react-ui/src/features/tables/components/table-columns.tsx
=> feat: polish tables

packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-flow-tool.tsx, packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-piece-tool.tsx, packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-tools-section.tsx, packages/react-ui/src/app/routes/mcp-servers/mcp-tools-icon.tsx, packages/react-ui/src/features/mcp/lib/mcp-hooks.ts
=> feat: group mcp tools by piece name

packages/pieces/community/dimo/src/index.ts
Update DIMO descriptions and fixing typos
=> fix(demo): description

.github/workflows/pre-prod-automate-deploy.yml
=> feat: add pre-prod automate deploy workflow

docker-compose.yml, package.json
=> feat: release 0.66.2

packages/server/api/src/app/database/migration/sqlite/1751475726665-AddPlatformIdToAIUsageSqlite.ts
=> fix: ai usage sqlite migration

.github/workflows/e2e-tests.yml, tools/scripts/format-checkly-report.js
=> fix: pass environment to discord notifications on e2e tests failure

packages/ee/shared/src/lib/billing/index.ts, packages/server/api/src/app/ee/platform/platform-plan/platform-plan.module.ts, packages/server/api/src/app/ee/platform/platform-plan/stripe-billing.controller.ts, packages/server/api/src/app/ee/platform/platform-usage-service.ts, packages/server/api/src/app/helper/system-jobs/common.ts
=> feat: ai credits reset threshold

docker-compose.yml, package.json
=> feat: release 0.66.4

packages/server/api/src/app/mcp/mcp-server/mcp-server.ts, packages/server/api/src/app/mcp/mcp-utils.ts
=> fix: handle optional props, support string/object in MCP dropdown

packages/server/api/src/app/ee/platform/platform-plan/stripe-billing.controller.ts
=> fix: ignore unknown subscriptions

packages/react-ui/src/app/routes/agents/index.tsx, packages/react-ui/src/features/agents/agent-card.tsx, packages/server/api/src/app/agents/agent-runs/agent-run.entity.ts, packages/server/api/src/app/agents/agent-runs/agent-runs-service.ts, packages/server/api/src/app/agents/agents-service.ts, packages/server/api/src/app/database/migration/postgres/1753400133786-AddIndexForAgentTable.ts, packages/server/api/src/app/database/migration/sqlite/1753400496920-AddIndexForAgentTableSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/shared/src/lib/agents/index.ts
=> feat: add runCompleted property to Agent and AgentCard components,

packages/server/api/src/app/tables/table/table.service.ts
=> fix(tables): enrich agent in tables

packages/react-ui/src/app/routes/platform/billing/index.tsx
=> feat: ai credits usage table for enterprise

packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/lib/actions/check-moderation.ts, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts, packages/server/api/src/app/ai/ai-provider-service.ts, packages/server/api/src/app/ai/ai-provider.module.ts, packages/server/api/src/app/ai/providers/openai.ts, packages/server/api/src/app/ai/providers/types.ts
=> fix(ai proxy): utility ai openai moderation requests

packages/pieces/community/utility-ai/package.json, packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
=> feat(utility ai): support pdf in extract structured data action

packages/react-ui/src/features/tables/components/ap-table-header.tsx, packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
Fixes [Import Table > Nothing Happens](https://community.activepieces.com/t/import-table-nothing-happens/10344)
=> fix: import csv dialog not showing up

packages/server/api/src/app/pieces/base-piece-module.ts
=> fix: allow piece to work with api

packages/react-ui/src/app/routes/platform/billing/index.tsx
=> fix(ai usage): remove duplicate table on cloud

packages/engine/src/lib/operations.ts, packages/engine/test/handler/test-helper.ts, packages/react-ui/src/app/builder/piece-properties/dynamic-dropdown-piece-property.tsx, packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx, packages/react-ui/src/features/pieces/lib/piece-selector-utils.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/mcp/mcp-server/mcp-server.ts, packages/server/api/src/app/pieces/piece-metadata-service/index.ts, packages/server/api/src/app/workers/machine/machine-controller.ts, packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts, packages/server/worker/src/lib/api/flow-worker-cache.ts, packages/server/worker/src/lib/api/piece-worker-cache.ts, packages/server/worker/src/lib/api/server-api.service.ts, packages/server/worker/src/lib/executors/flow-job-executor.ts, packages/server/worker/src/lib/executors/repeating-job-executor.ts, packages/server/worker/src/lib/executors/user-interaction-job-executor.ts, packages/server/worker/src/lib/executors/webhook-job-executor.ts, packages/server/worker/src/lib/runner/index.ts, packages/server/worker/src/lib/utils/flow-engine-util.ts, packages/shared/src/lib/engine/engine-operation.ts, packages/shared/src/lib/flows/actions/action.ts, packages/shared/src/lib/flows/triggers/trigger.ts, packages/shared/src/lib/pieces/dto/piece-requests.ts, packages/shared/test/flow/flow-helper.test.ts
=> fix: refactor flow cache / piece cache & remove package type

package-lock.json, packages/engine/src/lib/services/flows.service.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/context.ts, packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/actions/call-flow.ts, packages/pieces/community/subflows/src/lib/common.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/workers/engine-controller.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/flows/dto/list-flows-request.ts
=> fix: use external id in call flow action

packages/pieces/community/stripe/package.json, packages/pieces/community/stripe/src/index.ts, packages/pieces/community/stripe/src/lib/actions/search-subscriptions.ts
Adds a new stripe action `subscription search` with different filters like [creationDate, status, customerId, ...]
=> feat(stripe): subscription search action

packages/pieces/community/amazon-s3/package.json, packages/pieces/community/amazon-s3/src/lib/actions/upload-file.ts
Improved content type and file extension handling of the Amazon S3 File Upload piece.
=> fix(amazon s3): improve content type and file extension handling

packages/server/worker/src/lib/runner/index.ts, packages/server/worker/src/lib/utils/flow-engine-util.ts
=> fix: install piece from registry timing out

packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/config-display.tsx, packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/index.tsx, packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/mcp-connect-utils.tsx
=> fix: enhance claude instructions in mcp connect

package-lock.json, packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx, packages/react-ui/src/components/custom/multi-select-piece-property.tsx, packages/react-ui/src/components/custom/multi-select.tsx, packages/react-ui/src/features/pieces/lib/form-utils.tsx
=> fix: multiselect dropdown was reseting to intial value after clearing it

package-lock.json, package.json, packages/server/api/src/app/workers/redis/redis-consumer.ts, packages/server/api/src/app/workers/redis/redis-queue.ts
=> feat: introduce open telemetry for bullmq

packages/react-ui/src/features/pieces/lib/pieces-hooks.ts
=> fix: show pinned pieces at the top under (Highlights)

packages/pieces/community/missive/.eslintrc.json, packages/pieces/community/missive/README.md, packages/pieces/community/missive/package.json, packages/pieces/community/missive/project.json, packages/pieces/community/missive/src/index.ts, packages/pieces/community/missive/src/lib/actions/create-contact.ts, packages/pieces/community/missive/src/lib/actions/create-draft-post.ts, packages/pieces/community/missive/src/lib/actions/create-task.ts, packages/pieces/community/missive/src/lib/actions/find-contact.ts, packages/pieces/community/missive/src/lib/actions/update-contact.ts, packages/pieces/community/missive/src/lib/common/auth.ts, packages/pieces/community/missive/src/lib/common/client.ts, packages/pieces/community/missive/src/lib/common/dynamic-dropdowns.ts, packages/pieces/community/missive/src/lib/triggers/new-comment.ts, packages/pieces/community/missive/src/lib/triggers/new-contact-book.ts, packages/pieces/community/missive/src/lib/triggers/new-contact-group.ts, packages/pieces/community/missive/src/lib/triggers/new-contact.ts, packages/pieces/community/missive/src/lib/triggers/new-message.ts, packages/pieces/community/missive/tsconfig.json, packages/pieces/community/missive/tsconfig.lib.json, tsconfig.base.json
=> feat: missive piece

packages/pieces/community/subflows/package.json, packages/pieces/community/subflows/src/lib/common.ts
=> fix(subflows): update trigger type import

packages/react-ui/src/app/builder/data-selector/data-selector-node-content.tsx, packages/react-ui/src/app/builder/data-selector/data-selector-size-togglers.tsx, packages/react-ui/src/app/builder/flow-canvas/canvas-controls.tsx, packages/react-ui/src/app/builder/flow-canvas/index.tsx, packages/react-ui/src/components/custom/tutorials-dialog.tsx
=> fix: data selector values not being visible when deeply nested

deploy/activepieces-helm/templates/deployment.yaml, deploy/activepieces-helm/values.yaml
=> chore: remove leftover TRIGGER_FAILURES_THRESHOLD variables

packages/pieces/community/image-ai/package.json, packages/pieces/community/image-ai/src/index.ts, packages/pieces/community/text-ai/package.json, packages/pieces/community/text-ai/src/index.ts, packages/shared/package.json
=> chore: bump minimumSupportedRelease

packages/server/api/src/app/ee/pieces/filters/piece-filtering-utils.ts, packages/server/api/test/integration/ce/flows/flow.test.ts
=> fix: slow database queries

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/openai/src/lib/actions/send-prompt.ts
=> chore: bump minimumSupportedRelease for openai

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts, packages/pieces/community/openai/src/lib/actions/send-prompt.ts
Reverts activepieces/activepieces#8713
=> rever: bump minimumSupportedRelease for openai

packages/server/api/src/app/ee/platform/platform-usage-service.ts, packages/server/api/src/app/platform/platform.controller.ts, packages/server/api/src/app/platform/platform.service.ts
=> fix: speed up usage

packages/pieces/community/openai/package.json, packages/pieces/community/openai/src/index.ts
=> chore: bump openai version

docker-compose.yml, package-lock.json, package.json, packages/server/api/src/app/ee/pieces/filters/piece-filtering-utils.ts, packages/server/api/src/app/ee/platform/platform-usage-service.ts, packages/server/api/test/integration/ce/flows/flow.test.ts, packages/server/shared/package.json, packages/server/worker/package.json
=> feat: release 0.67.0

packages/react-ui/src/app/routes/project-release/apply-plan.tsx, packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx, packages/react-ui/src/app/routes/project-release/create-release-dialog/operation-change.tsx, packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx, packages/server/api/src/app/agents/agents-service.ts, packages/server/api/src/app/database/migration/postgres/1754214833292-AddExternalidToMCPToolPostgres.ts, packages/server/api/src/app/database/migration/sqlite/1754220095236-AddExternalidToMCPToolSQLite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/ee/projects/project-release/project-release.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-state-helper.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-state.service.ts, packages/server/api/src/app/mcp/mcp-service.ts, packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts, packages/shared/src/lib/agents/index.ts, packages/shared/src/lib/mcp/tools/mcp-tool.ts, packages/shared/src/lib/project-release/project-state.ts
=> feat(project releases): support agents and mcp

packages/server/api/src/app/ee/solutions/solutions.controller.ts, packages/shared/src/lib/common/utils/object-utils.ts, packages/shared/src/lib/project-release/project-state.ts
=> refactor: clean up imports and improve code formatting

packages/engine/src/lib/handler/context/engine-constants.ts, packages/engine/src/lib/handler/piece-executor.ts, packages/engine/test/handler/test-helper.ts, packages/pieces/community/framework/src/lib/context.ts, packages/server/api/src/app/flows/flow-run/flow-run-service.ts, packages/server/api/src/app/workers/memory/memory-queue.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/src/lib/engine/engine-constants.ts, packages/shared/src/lib/flow-run/execution/flow-execution.ts
=> fix: reply to webhook only if trigger is matching

packages/pieces/community/krisp-call/package.json, packages/pieces/community/krisp-call/src/index.ts, packages/pieces/community/krisp-call/src/lib/actions/add-contact.ts, packages/pieces/community/krisp-call/src/lib/actions/delete-contacts.ts, packages/pieces/community/krisp-call/src/lib/actions/send-mms.ts, packages/pieces/community/krisp-call/src/lib/actions/send-sms.ts, packages/pieces/community/krisp-call/src/lib/triggers/index.ts
=> feat(krispcall): update to new V3 API URL

packages/react-ui/src/app/components/sidebar/index.tsx
=> fix: align sidebar group with side bar items

package-lock.json, packages/pieces/community/amazon-ses/project.json, packages/pieces/community/subflows/package.json
=> fix: amazon-ses piece build & bump subflows piece

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts
=> fix: fix custom API call response format

packages/pieces/community/openai/package-lock.json, packages/pieces/community/openai/package.json
=> chore: bump openai package version to 0.6.0

docker-compose.yml, package.json
=> feat: release 0.67.4

docker-compose.yml, package.json
=> feat: release 0.67.5

packages/shared/src/lib/flows/operations/migrations/migrate-v5-http-to-webhook.ts
Return response in http piece ver >= 0.5 and ver <0.5 are different, so this migration handles that
=> fix: migration from http piece to webhook piece for return response 

package-lock.json, packages/engine/test/handler/flow-rerun.test.ts, packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx, packages/react-ui/src/app/routes/project-release/create-release-dialog/operation-change.tsx, packages/server/api/src/app/agents/agent-controller.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-handler.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-helper.ts, packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.service.ts, packages/server/api/src/app/ee/projects/project-release/project-release.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/diff/agent-diff.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts, packages/server/api/src/app/ee/projects/project-release/project-state/project-state.service.ts, packages/server/api/src/app/flows/flow/flow.controller.ts, packages/server/api/src/app/tables/table/table.controller.ts, packages/server/shared/package.json, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/project-release/project-state.ts, packages/shared/src/lib/tables/table.ts
=> fix: use externalId instead of id and correct state comparison in all project states

packages/pieces/community/pipedrive/package.json, packages/pieces/community/pipedrive/src/lib/trigger/updated-deal.ts
=> fix(pipedrive): fix custom field filtering for deal trigger

packages/pieces/community/microsoft-365-people/package.json, packages/pieces/community/microsoft-365-people/src/lib/common/auth.ts, packages/pieces/community/microsoft-dynamics-365-business-central/package.json, packages/pieces/community/microsoft-dynamics-365-business-central/src/index.ts, packages/pieces/community/microsoft-dynamics-crm/package.json, packages/pieces/community/microsoft-dynamics-crm/src/index.ts, packages/pieces/community/microsoft-excel-365/package.json, packages/pieces/community/microsoft-excel-365/src/index.ts, packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/index.ts, packages/pieces/community/microsoft-onenote/package.json, packages/pieces/community/microsoft-onenote/src/index.ts, packages/pieces/community/microsoft-outlook-calendar/package.json, packages/pieces/community/microsoft-outlook-calendar/src/index.ts, packages/pieces/community/microsoft-outlook/package.json, packages/pieces/community/microsoft-outlook/src/lib/common/auth.ts, packages/pieces/community/microsoft-power-bi/package.json, packages/pieces/community/microsoft-power-bi/src/index.ts, packages/pieces/community/microsoft-sharepoint/package.json, packages/pieces/community/microsoft-sharepoint/src/index.ts, packages/pieces/community/microsoft-teams/package.json, packages/pieces/community/microsoft-teams/src/index.ts, packages/pieces/community/microsoft-todo/package.json, packages/pieces/community/microsoft-todo/src/index.ts
=> fix: add description for microsoft auth 

packages/server/api/src/app/ee/projects/project-release/project-release.service.ts
=> fix: apply all flows in project release if no selected flows are provided

packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts, packages/server/api/test/unit/app/ee/git-repos/operations/table-diff.test.ts
=> fix(project-releases): ignore table id in diff

packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
=> fix(google-sheets): handle onDisable error to allow flow saving

docker-compose.yml, package.json
=> feat: release 0.68.3

packages/pieces/community/textcortex-ai/.eslintrc.json, packages/pieces/community/textcortex-ai/README.md, packages/pieces/community/textcortex-ai/package.json, packages/pieces/community/textcortex-ai/project.json, packages/pieces/community/textcortex-ai/src/index.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-code.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-email.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-paraphrase.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-product-description.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-social-caption.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-summary.ts, packages/pieces/community/textcortex-ai/src/lib/actions/create-translation.ts, packages/pieces/community/textcortex-ai/src/lib/actions/send-prompt.ts, packages/pieces/community/textcortex-ai/src/lib/common/auth.ts, packages/pieces/community/textcortex-ai/src/lib/common/client.ts, packages/pieces/community/textcortex-ai/src/lib/common/common.ts, packages/pieces/community/textcortex-ai/tsconfig.json, packages/pieces/community/textcortex-ai/tsconfig.lib.json, tsconfig.base.json
TextCortex AI is a generative writing assistant that helps automate content creation code, emails, summaries, translations, paraphrases, product descriptions, social captions, and custom prompts.
This integration enables Activepieces workflows to generate rich, AI-powered text outputs across various use cases without manual writing.
Fixes #9052
/claim #9052
=> feat: textcortex-ai piece

packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
=> fix: remove db call on check for pieces cache

Dockerfile, docker-entrypoint.sh
=> chore: use pm2 to cluster app server instances (process per core)

packages/server/api/src/app/ai/providers/anthropic.ts, packages/server/api/test/integration/cloud/ai/proxy.test.ts
=> fix(ai providers): non search anthropic requests

packages/server/api/src/app/workers/redis/redis-bullboard.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> refactor: remove cleanup queue from redis rate limiter

packages/server/api/src/app/workers/queue/migration/unify-old-queues-to-one.ts, packages/server/api/src/app/workers/redis/redis-consumer.ts, packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
=> fix: rate limit clean up

packages/pieces/community/docsbot/package.json
=> chore(docsbot): bump piece version to 0.0.2

docker-compose.yml, package.json
=> feat: release 0.69.0

packages/pieces/community/aidbase/.eslintrc.json, packages/pieces/community/aidbase/README.md, packages/pieces/community/aidbase/package.json, packages/pieces/community/aidbase/project.json, packages/pieces/community/aidbase/src/index.ts, packages/pieces/community/aidbase/src/lib/actions/add-faq-item.ts, packages/pieces/community/aidbase/src/lib/actions/add-video.ts, packages/pieces/community/aidbase/src/lib/actions/add-website.ts, packages/pieces/community/aidbase/src/lib/actions/create-chatbot-reply.ts, packages/pieces/community/aidbase/src/lib/actions/create-faq.ts, packages/pieces/community/aidbase/src/lib/actions/start-training.ts, packages/pieces/community/aidbase/src/lib/common/auth.ts, packages/pieces/community/aidbase/src/lib/common/client.ts, packages/pieces/community/aidbase/src/lib/common/props.ts, packages/pieces/community/aidbase/src/lib/common/types.ts, packages/pieces/community/aidbase/src/lib/triggers/email-priority-changed.ts, packages/pieces/community/aidbase/src/lib/triggers/email-received.ts, packages/pieces/community/aidbase/src/lib/triggers/email-sent.ts, packages/pieces/community/aidbase/src/lib/triggers/email-status-changed.ts, packages/pieces/community/aidbase/src/lib/triggers/ticket-created.ts, packages/pieces/community/aidbase/src/lib/triggers/ticket-new-comment.ts, packages/pieces/community/aidbase/src/lib/triggers/ticket-priority-changed.ts, packages/pieces/community/aidbase/src/lib/triggers/ticket-status-changed.ts, packages/pieces/community/aidbase/tsconfig.json, packages/pieces/community/aidbase/tsconfig.lib.json, tsconfig.base.json
=> feat(aidbase): Implement piece

packages/pieces/community/vlm-run/.eslintrc.json, packages/pieces/community/vlm-run/README.md, packages/pieces/community/vlm-run/package.json, packages/pieces/community/vlm-run/project.json, packages/pieces/community/vlm-run/src/index.ts, packages/pieces/community/vlm-run/src/lib/actions/analyze-audio.ts, packages/pieces/community/vlm-run/src/lib/actions/analyze-document.ts, packages/pieces/community/vlm-run/src/lib/actions/analyze-image.ts, packages/pieces/community/vlm-run/src/lib/actions/analyze-video.ts, packages/pieces/community/vlm-run/src/lib/actions/get-file.ts, packages/pieces/community/vlm-run/src/lib/common/index.ts, packages/pieces/community/vlm-run/src/lib/common/properties.ts, packages/pieces/community/vlm-run/src/lib/common/schemas.ts, packages/pieces/community/vlm-run/src/lib/common/types.ts, packages/pieces/community/vlm-run/tsconfig.json, packages/pieces/community/vlm-run/tsconfig.lib.json, tsconfig.base.json
This PR delivers the full implementation of the VLM Run integration, completing all the required actions with strong validation and type safety.
All actions were fully implemented and carefully validated with Zod schemas to prevent invalid requests. Every function is strongly typed according to the TypeScript SDK (although I'm not using it, as the code doesn't run with it), ensuring reliability and maintainability.
https://github.com/user-attachments/assets/783f9530-fbc1-43d0-bf5c-962c095c2f1e
Fixes #9214
/claim #9214
=> feat(pieces): implement VLM Run piece

packages/pieces/community/slidespeak/.eslintrc.json, packages/pieces/community/slidespeak/README.md, packages/pieces/community/slidespeak/package.json, packages/pieces/community/slidespeak/project.json, packages/pieces/community/slidespeak/src/index.ts, packages/pieces/community/slidespeak/src/lib/actions/create-presentation.ts, packages/pieces/community/slidespeak/src/lib/actions/edit-presentation.ts, packages/pieces/community/slidespeak/src/lib/actions/get-task-status.ts, packages/pieces/community/slidespeak/src/lib/actions/upload-document.ts, packages/pieces/community/slidespeak/src/lib/common/constants.ts, packages/pieces/community/slidespeak/src/lib/triggers/new-presentation.ts, packages/pieces/community/slidespeak/tsconfig.json, packages/pieces/community/slidespeak/tsconfig.lib.json, tsconfig.base.json
Fixes #9206 
/claim #9206  
https://github.com/user-attachments/assets/573209e1-3af2-476b-ab9e-4af1361c15ae
=> feat: Slidespeak

packages/react-ui/src/app/components/project-dashboard-layout.tsx
=> fix: project dashboard scroll

packages/pieces/community/tables/package.json, packages/pieces/community/tables/src/lib/actions/update-record.ts, packages/pieces/community/tables/src/lib/triggers/updated-record.ts
=> fix(tables): update record data fields should not depend on record id

packages/react-ui/src/app/builder/index.tsx, packages/react-ui/src/app/builder/run-list/index.tsx, packages/react-ui/src/app/components/sidebar/builder/flows-navigation.tsx, packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx, packages/react-ui/src/features/flows/lib/flows-hooks.ts
=> fix: inserting templates in platform admin

.github/workflows/remove-environment.yml, .github/workflows/setup-environment.yml, packages/engine/src/main.ts
=> feat: enhance preview environments github actions

packages/pieces/community/woocommerce/package.json, packages/pieces/community/woocommerce/src/lib/triggers/index.ts, packages/pieces/community/woocommerce/src/lib/triggers/register-trigger.ts
=> fix(woocommerce): add test data func for triggers

CONTRIBUTING.md
updating broken link in contributing section
=> docs: update contributing guide link to the building pieces section

.github/workflows/e2e.yml
=> refactor: test CI

.github/workflows/tests-e2e-ce.yml, packages/server/api/src/app/authentication/authentication-utils.ts, packages/tests-e2e/pages/builder.page.ts
=> fix: test ci

docker-compose.yml, package.json
=> feat: release 0.70.1

.github/workflows/e2e.yml, .github/workflows/tests-e2e-ce.yml, .github/workflows/tests-e2e-cloud.yml, .github/workflows/tests-e2e-ee.yml, packages/tests-e2e/playwright.config.ts, packages/tests-e2e/scenarios/cloud/dummy.spec.ts, packages/tests-e2e/scenarios/ee/dummy.spec.ts
=> chore: test e2e ci

.github/workflows/automate-deploy.yml
Confirmation prompt was making the CI fail.
=> fix: checkly automate deploy using force

packages/tests-e2e/scenarios/ce/flows/webhook-should-return-response.spec.ts
=> fix: update webhook test to use waitFor method

packages/server/api/src/app/ee/platform/platform-plan/stripe-helper.ts
=> feat: allow promotion codes in checkout session

package-lock.json, package.json, packages/pieces/community/datadog/.eslintrc.json, packages/pieces/community/datadog/README.md, packages/pieces/community/datadog/package.json, packages/pieces/community/datadog/project.json, packages/pieces/community/datadog/src/index.ts, packages/pieces/community/datadog/src/lib/actions/send-multiple-logs.ts, packages/pieces/community/datadog/src/lib/actions/send-one-log.ts, packages/pieces/community/datadog/src/lib/common.ts, packages/pieces/community/datadog/tsconfig.json, packages/pieces/community/datadog/tsconfig.lib.json, tsconfig.base.json
- We add a new piece for [Datadog API](https://docs.datadoghq.com/api/latest/?tab=java) integration - [Datadog is a cloud monitoring service](https://www.datadoghq.com/)
- This pieces provides three actions:
- Send one (or multiple) logs - since the logs API is meant to receive multiple logs, while we can leverage Activepieces UI for better parsing of fields
- Custom API call 
- Logo of Datadog is [here](https://www.datadoghq.com/about/resources/) (either white or purple background)
purple | white 
--- | ---
- New datadog piece
- Authentication: relies on API key, app key & site
- Actions: 
- for now, only logs API is integrated (possible to add other actions in the future) - we rely on their typescript SDK
- + a custom API Call to be able to request other non integrated APIs …
=> feat(pieces): add new piece for Datadog integration and logs API actions

packages/server/api/src/app/database/migration/common/1759392852559-AddIndexForAppEvents.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/trigger/app-event-routing/app-event-routing.entity.ts
=> fix: add index for app events

docker-compose.yml, package.json
=> feat: release 0.70.3

packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Reverts activepieces/activepieces#9565
=> revert: "refactor: get flow-run displayName from publishedVersion"

.github/workflows/build-cloud-nx.yml, .github/workflows/remove-environment.yml, .github/workflows/setup-environment.yml, Dockerfile, nx.json
=> fix: disable nx cloud for forks / docker build
