activepieces/activepieces

src/worker/packages/components/src/apps/gmail/actions/send-email-action.ts
I retrieved the email using the access token + get request to [https://www.googleapis.com/oauth2/v1/userinfo](https://www.googleapis.com/oauth2/v1/userinfo?access_token=), I tested this locally and it worked.
=> removed from as a config

docs/mint.json
Error messages fixed: There is an extra # in one of the colors and a group name is missing.
Mintlify doesn't use ultralight and ultradark any more so those are safe to delete instead of just removing the extra #
=> Fix mint.json issues

docs/pieces/custom-pieces.mdx
Fix building pieces guide broken link in custom pieces page.
=> docs: fix building pieces guide broken link

packages/backend/src/app/flow-run/flow-run-side-effects.ts, packages/backend/src/app/helper/trigger-utils.ts, packages/backend/src/app/store-entry/store-entry.service.ts, packages/backend/src/app/webhooks/webhook-service.ts, packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts, packages/backend/src/app/workers/flow-worker/job-data.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/services/storage.service.ts
There is an issue where if trigger is used twice in same collection, they will share the storage.
So all store in context are now prefixed by flow by default.
=> Add flow id prefix store

.github/workflows/release-backend.yml, .github/workflows/release-frontend.yml
Opening PR against main can be an accident as it's default branch, It should be trigger manually to avoid trigger build flows.
=> fix(build): release flow should be triggered manually

packages/backend/src/app/flows/flow-service.ts, packages/backend/src/app/helper/trigger-utils.ts, packages/backend/src/app/instance/instance-side-effects.ts, packages/backend/src/app/workers/flow-worker/flow-queue.ts
If the flow is deleted, the published flow side effects will not run for their triggers, the expected behavior to run the side effects on deleted flow.
=> fix: run instance side effect on flow deletion

.github/workflows/build-everything.yml, packages/engine/webpack.config.js
- Push `IgnoreDynamicRequire` to `plugins` array instead of overriding it.
- The webpack compilation fails on ts errors now so removed redundant engine compilation step from the pipeline
=> chore: fix engine webpack config

packages/frontend/.eslintrc.json
Eslint wasn't working on the frontend package ever since we switched to nx, I had to have a local copy of tsconfig.json in the root of the repo.
After leading https://nx.dev/recipes/other/eslint  I found out I had to set parserOptions.project in eslint.json of the package, to be packages/frontend/tsconfig.*?.json which solves the issue and enables eslint.
run nx lint frontend
=> fix: fixed frontend eslint

docs/contributing/building-pieces/quickstart.mdx
Fixed an incorrect command found when attempting to `cd` into the hackernews example directory
You can test this by navigating to the create first piece page and viewing the Piece Definition commands and seeing if the && cd... is updated with the new uri
=> [DOCS]: Fix incorrect CD command on 'Create First Piece' Page

packages/pieces/apps/src/lib/airtable/common/index.ts
Removes unused function from Airtable common, addresses  #621
=> chore: remove Drip url from Airtable commmon

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.html
Addresses #599 
1)Have a piece with no connections.
2)Create a connection from the add button inside the dropdown
=> fix: new connection is selected when creating one from within dropdown

packages/pieces/apps/src/index.ts, packages/pieces/apps/src/lib/google-tasks/actions/new-task.ts, packages/pieces/apps/src/lib/google-tasks/common/index.ts, packages/pieces/apps/src/lib/google-tasks/google-tasks.mdx, packages/pieces/apps/src/lib/google-tasks/index.ts
Add a new Google Tasks piece which has 1 action so far: create a new task in a specific task list.
Closes #651.
=> feat(google-tasks): add create new task action

packages/frontend/src/app/app.module.ts, packages/frontend/src/app/modules/common/model/flow-builder/flow-item.ts, packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/step-type-sidebar/step-type-sidebar.component.ts, packages/frontend/src/app/modules/flow-builder/store/builder/builder.selector.ts, packages/frontend/src/app/modules/flow-builder/store/builder/flow-item-details/flow-items-details.action.ts, packages/frontend/src/app/modules/flow-builder/store/builder/flow-item-details/flow-items-details.effects.ts, packages/frontend/src/app/modules/flow-builder/store/builder/flow-item-details/flow-items-details.reducer.ts, packages/frontend/src/app/modules/flow-builder/store/model/flow-items-details-state.model.ts
Moves http and storage pieces to the "Core" category in the list shown once the user wants to add a step.
Add a storage and an http piece and everything will work the same, and tested backwards compatibility.
=> feat: moved http and storage to core in the add new step list

packages/frontend/src/app/modules/common/components/configs-form/configs-form.component.ts
So basically, if someone edits a refresher of a dynamic property, we return a new list of properties to render, the issue is the value of the previous list stays, so this PR fixes that.
=> fix: remove controls from previous value

docs/pieces/apps/generatebanners.mdx, packages/pieces/apps/src/index.ts, packages/pieces/apps/src/lib/generatebanners/actions/renderTemplate.action.ts, packages/pieces/apps/src/lib/generatebanners/index.ts
Adds a new piece to make the GenerateBanners service available to Activepiece users. GenerateBanners is a solution to generate images, pdf documents and videos from visual templates.
Unlocked thanks to https://github.com/activepieces/activepieces/issues/524.
New feature (non-breaking change which adds functionality)
=> feat: added the GenerateBanners piece

packages/pieces/openai/src/index.ts, packages/pieces/openai/src/lib/actions/send-prompt.ts
Currently, some of the properties are hardcoded. This change adds the ability for the user to configure properties such as:
- Model
- Top P
- Frequency penalty
- Presence penalty
P.S. Descriptions are taken from hints in the Open AI playground.
- Create a new flow
- Add piece "Open AI"
- Add "Optional Inputs"
- Test flow
=> Open AI Piece: additional optional inputs

tools/deploy.sh
On Mac OS, executing the command `sh tools/deploy.sh` causes the errors:
```sh
sed: 1: ".env": invalid command code .
sed: 1: ".env": invalid command code .
sed: 1: ".env": invalid command code .
A .env file containing random passwords and secrets has been successfully generated.
```
This change performs checking that the operating system is [macOS](https://wikipedia.org/wiki/Mac OS) and executes `sed ...` in a different way as described [here](https://stackoverflow.com/a/19457213).
- use Mac OS :)
- clone the repo
- `sh tools/deploy.sh`
=> chore: sed: 1: ".env": invalid command code

packages/backend/src/main.ts
The `code` parameter shall be URL encoded using `encodeURIComponent()` before being reflected in the `reply.send()` call, in order to escape special characters that can be rendered as malicious JS.
Sending `code` parameter with value `test' },'*')} else alert(1);//` will cause cross-site scripting.
=> chore: added url encoding for code parameter

packages/backend/.env, packages/backend/src/app/pieces/piece-metadata-loader.ts, packages/frontend/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.html, packages/frontend/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.scss, packages/frontend/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts, packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/flow-right-sidebar.component.html, packages/frontend/src/app/modules/flow-builder/store/builder/builder.selector.ts
Fixes importing pieces, so it doesn't fully fail when importing on package fails to import.
Fixes an issue with overflowing on right side bar, any step other than webhook height wasn't 100%.
=> fix: importing pieces was failing if one import fails

packages/pieces/gmail/package.json, packages/pieces/gmail/src/lib/common/props.ts
=> chore: bump gmail version to 0.1.4

packages/frontend/src/app/modules/flow-builder/page/flow-builder/canvas-utils/horizontal-sidebar-separator/horizontal-sidebar-separator.component.ts, packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/edit-step-sidebar/edit-step-accordion/edit-step-accodion.component.html, packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/flow-right-sidebar.component.html, packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/flow-right-sidebar.component.ts
Fixes the following UI issues:
1)If the webhook URL is too long it overflows, I truncated it.
2)If someone resizes the test step section switches steps then goes back to the webhook trigger step, it looks messy. so I reset the size on step change.
=> fix: truncate webhook url + reset test step section height 

packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
Polling triggers are processed in sync order one by one, this pr make it configurable.
=> fix: increase repeatable flow worker concurrency

packages/frontend/src/app/modules/flow-builder/page/flow-builder/flow-right-sidebar/flow-right-sidebar.component.html
Fixes a bug when editing a webhook piece trigger, wouldn't show all the fields.
Before:
After:
=> fix: added additional condition to adjust top-resizer-section height

packages/pieces/smtp/package.json, packages/pieces/smtp/src/lib/actions/send-email.ts
Number and Text are currently treated same, and number is not currently supported in in custom auth.
This is released as temporary to fix until we support it in next release. 
=> fix(smtp): change port to text temporary

packages/shared/package.json, packages/shared/src/lib/pieces/property/custom-auth-prop.ts
Number property is unsupported in custom auth.
=> chore: remove number prop from custom auth

packages/pieces/telegram-bot/package.json, packages/pieces/telegram-bot/src/lib/action/send-text-message.action.ts
Since the telegram piece action doesn't run successfully without the message field, I've changed it to 'required'
Fixes #1038
=> Make Message Input Required in Telegram Piece Action

packages/backend/src/app/flows/common/piece-installer.ts, packages/backend/src/app/workers/flow-worker/flow-worker.ts
Pnpm link doesn't work inside dev container as the path starts with /workspace/ and not /usr/src/app
=> chore: fix pnpm link for dev container

packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts, packages/ui/feature-builder-test-steps/src/lib/test-webhook-trigger/test-webhook-trigger.component.html, packages/ui/feature-builder-test-steps/src/lib/test-webhook-trigger/test-webhook-trigger.component.ts
Testing core webhook trigger wasn't saving and also added a little bit of space between the results dropdown and the output viewer.
=> fix: Webhook testing section fix

packages/pieces/gmail/package.json, packages/pieces/gmail/src/lib/actions/send-email-action.ts
Replaces new lines in the body text of gmail send email action with a <br> tag
Fixes #1102
=> fix: gmail piece send email new line

README.md, docs/contributing/overview.mdx, docs/pieces/custom-pieces.mdx
Update the documentation links for the "Building piece" documentation page. It appears it had been moved.
=> docs: update links to 'Building pieces'

packages/pieces/postgres/package.json, packages/pieces/postgres/src/lib/actions/run-query.ts
This PR adds a new checkbox to enable or disable SSL connection. Previously the connection would always attempt an SSL connection.
The "Enforce Encryption" has also been changed to "Verify server certificate", as that is more appropriate.
=> feat(piece/postgres): add checkbox to toggle SSL on or off

packages/backend/src/app/database/migration/1678492809093-removeCollectionVersion.ts, packages/backend/src/app/database/migration/1680986182074-RemoveCollections.ts
Using repository in migration requires us to have the entity in database connection which is no longer there, this cause fresh installs to fail.
=> fix: collection metadata not found 

packages/ui/feature-dashboard/src/lib/pages/flows-table/move-flow-to-folder-dialog/move-flow-to-folder-dialog.component.ts, packages/ui/feature-dashboard/src/lib/store/folders/folders.actions.ts, packages/ui/feature-dashboard/src/lib/store/folders/folders.reducer.ts
We had an issue when moving folders while displaying all flows, counting flows wasn't getting calculated correctly.
=> fix: added flow folder id in move action as param

docs/contributing/building-pieces/create-action.mdx
The repo structure link on this page actually goes to Introduction page which is meant for users, not developers: https://www.activepieces.com/docs/contributing/building-pieces/create-action
This PR fixes the link
=> Fix link to repo structure page in docs

packages/ui/common/src/lib/service/test-step.service.ts, packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.html, packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.ts
Shows different UI when testing a piece action step fails, continuation of [feat/action-test-status](https://github.com/activepieces/activepieces/pull/1081)
=> chore: added error response ui for test piece step

packages/engine/src/lib/action/branch-action-handler.ts, packages/engine/src/lib/action/code-action-handler.ts, packages/engine/src/lib/action/loop-action-handler.ts, packages/engine/src/lib/action/piece-action-handler.ts, packages/engine/src/lib/services/variable-service.ts
Censor authentication data seen in the run logs of pieces. The step input now shows `"**CENSORED**"` in place of the authentication field.
Fixes # (1019)
=> feat: censor connection data from run logs

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Default value for optional JSON piece property wasn't being stringified before it was passed to code mirror control.
=> fix: stringify json default value

packages/ee/billing/backend/usage.entity.ts
This PR fixes the unique constraint generated by TypeORM on the one-to-one relation
Tested and no unique constraint generated after switching to `many-to-one`
=> fix: update project_usage <-> project relation as many-to-one

docker-compose.dev.yml, packages/backend/README.md, packages/backend/project.json, packages/backend/src/app/database/database-connection.ts, packages/backend/src/app/database/migration/1683199709317-list-flow-runs-indices.ts, packages/backend/src/app/flows/flow-run/flow-run-controller.ts, packages/backend/src/app/flows/flow-run/flow-run-entity.ts, packages/backend/src/app/flows/flow-run/flow-run-service.ts, packages/shared/package.json, packages/shared/src/lib/common/index.ts, packages/shared/src/lib/common/utils/index.ts, packages/shared/src/lib/common/utils/object-utils.ts, packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
- Add optional filters for flow run: `flowId`, and `status`
- Also added compound indices to cover the following queries:
- list flow runs by `projectId`, `environment`, and `created` DESC
- list flow runs by `projectId`, `environment` , `status`, and `created` DESC
- list flow runs by `projectId`, `flowId`, `environment`, and `created` DESC
- list flow runs by `projectId`, `flowId`, `environment` , `status`, and `created` DESC
- example for `explain` before indices
```
2023-05-03 19:54:06.866 UTC [414] LOG:  execute <unnamed>: SELECT "flow_run"."id" AS "flow_run_id", "flow_run"."created" AS "flow_run_created", "flow_run"."updated" AS "flow_run_updated", "flow_run"."projectId" AS "flow_run_projectId", "flow_run"."flowId" AS "flow_run_flowId", "flow_run"."flowVersionId" AS …
```
=> feat: filter flow runs by `flowId`

packages/backend/src/app/flows/flow-version/flow-version.service.ts, packages/backend/src/app/flows/flow/flow.controller.ts, packages/backend/src/app/flows/flow/flow.service.ts, packages/backend/src/app/webhooks/webhook-service.ts, packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/lib/flows/actions/action.ts, packages/shared/src/lib/flows/dto/list-flows-request.ts, packages/shared/src/lib/flows/flow-helper.ts, packages/shared/src/lib/flows/flow-operations.ts, packages/shared/src/lib/flows/folders/list-folders-response.ts, packages/shared/src/lib/flows/sample-data.ts, packages/shared/src/lib/flows/triggers/trigger.ts, packages/ui/core/src/app/app.module.ts, packages/ui/core/src/app/modules/import-flow/import-flow.component.html, packages/ui/core/src/app/modules/import-flow/import-flow.component.ts
This PR adds support for both exporting and importing templates. Importing templates is particularly important for AI.
Current Template JSON
```json
{
"template": {
// Data returned from GET /flows/id/template
}
}
```
Tests:
=> feat: add templates

packages/shared/src/index.ts, packages/shared/src/lib/flows/actions/action.ts, packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
Static sample data wasn't being saved for app-webhook triggers, this PR fixes that.
Tested this by stopping filterAppWebhooks method inside ActionMetaService, then added a slack trigger, selected "new message"   and switched to another step where I saw that the sample data was now being fetched in the autocomplete dropdown.
=> fix: save static sample data with app-webhook trigger

packages/pieces/matrix/package.json, packages/pieces/matrix/src/lib/actions/send-message.ts, packages/pieces/matrix/src/lib/common/common.ts
This PR uses the Room alias in place of the Room id.
The room internal id is something which depends on the client you are using and it's a bit uncomfortable to work with. Internally I just added a getRoomId function, which takes the internal id from the Room alias with an additional api call.
Say for example you have two matrix clients, a personal one and a bot, you can get the Room alias from your personal client without opening at all your bot account with a client to get your internal room id.
=> [Matrix] Ability to send a message via room alias instead of room id

packages/backend/src/app/workers/code-worker/code-runner.ts, packages/backend/src/assets/code-executor.js, packages/ui/feature-builder-test-steps/src/lib/test-code-step/test-code-step.component.ts
Closes #1216 
Testing:
Created a code step and returned falsey values (undefined/null/0/false), and threw errors, but NaN are returned as null.
=> fix: corrected test code results to return falsey values instead of empty strings

packages/pieces/ntfy/.eslintrc.json, packages/pieces/ntfy/README.md, packages/pieces/ntfy/package.json, packages/pieces/ntfy/project.json, packages/pieces/ntfy/src/index.ts, packages/pieces/ntfy/src/lib/actions/send-notification.ts, packages/pieces/ntfy/tsconfig.json, packages/pieces/ntfy/tsconfig.lib.json, tsconfig.base.json
This PR adds support for Ntfy: https://docs.ntfy.sh/
- topic
- message
- title
- priority
- tags
- icon (an absolute url to the icon)
- actions (an action button as specified at https://docs.ntfy.sh/publish/#action-buttons)
- click (a url to open when the notification is clicked)
- delay (schedule the notification once received by ntfy, e.g. 10m means 10 minutes since received by ntfy)
Auth uses an optional access token, which the user can generate from their web panel, or using ntfy's cli tool.
=> feat: add ntfy

packages/pieces/pushover/.eslintrc.json, packages/pieces/pushover/README.md, packages/pieces/pushover/package.json, packages/pieces/pushover/project.json, packages/pieces/pushover/src/index.ts, packages/pieces/pushover/src/lib/actions/send-notification.ts, packages/pieces/pushover/tsconfig.json, packages/pieces/pushover/tsconfig.lib.json, tsconfig.base.json
This PR adds support for Pushover notifications.
- message
- title
- url
- url_title
- timestamp
- device
- priority (when set to 2, it needs 2 additional parameters set: retry and expire)
Pushover uses an API Token plus a User Key (or a Group Key).
More info at https://pushover.net/
=> feat: added Pushover support

packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
=> fix: fixed typo in webhook icon url

packages/backend/src/app/flows/flow-instance/flow-instance.service.ts, packages/backend/src/app/flows/flow-version/flow-version.service.ts, packages/backend/src/app/flows/flow/flow.service.ts, packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/lib/flows/dto/clone-flow-version-request.ts, packages/shared/src/lib/flows/flow-helper.ts, packages/shared/src/lib/flows/flow-operations.ts
This PR addresses two issues:
1. Code Artifacts: Currently, when the original draft is modified, the associated code artifacts in published version are deleted. To fix this, the solution involves duplicating the version along with its artifacts when a draft is created.
2. Publishing: The current process of publishing doesn't obtain the update lock, leading to potential issues. To resolve this, an operation that locks the flow during publishing is implemented as the solution.
=> fix(code): published code artifacts get deletd when draft is edited

packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
[BUG]: "Success" to "Succeeded" #1311
closes #1311 
It's inconsistent with Failed:
=>  changed success to succeeded

packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
Show the draft version by default, when entering the builder instead of the published version, so it doesn't confuse people who edit their flows then refresh.
=> chore: view draft by default while entering the flow builder

packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html, packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
Closes #1250 
Opens flows in a new tab if you middle click on the row, and if you right click on the name you will see "open in new tab".
=> chore: added open in new tab on middle mouse click and on right clicking flow name

packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/branch-line-connection/branch-line-connection.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/branch-line-connection/branch-line-connection.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/flow-item-connection.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/flow-item-connection.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/loop-line-connection/loop-line-connection.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/loop-line-connection/loop-line-connection.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/simple-line-connection/simple-line-connection.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/simple-line-connection/simple-line-connection.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item.component.ts, packages/ui/feature-builder-test-steps/src/lib/test-code-step/test-code-step.component.html
Closes #1195.
This PR fixes the issue of white space under branches when they are empty and in a readonly view (runs or published),
it also solves a problem where errors were not being shown inside the test section of a code step.
=> Empty branches debug issue 1195

packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
Logos in connections table were a list of observables that don't get completed and are used with a forkJoin.
=> fix: fixed logos observable in connections table

packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
Fixed typo in webhook trigger markdown.
=> fix: replaced image.png with the correct text

packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
Closes #1082.
Property types tested:
1)Any singular property using the textTemplate.
2)All dropdowns including multiselect and static versions.
3)Authentication dropdown.
4)Dictionary.
5)Array. 
6)Checkbox (slide toggle)
7)JSON.
I haven't accounted for optional dynamic properties, as I don't know how to handle removing a refresher atm.
I have this suggestion:
1)Make compilation of pieces throw an error if an optional dynamic property is used.
2)Throw an error if a refresher is an optional property, so basically any optional property should have an empty array of refreshers if it is of type (dropdown, multiselect dropdown or dynamic) .
=> feat: add remove button to optional properties

docs/contributing/building-pieces/publish-piece.mdx
I fixed the `npm add user`
And I took the liberty of adding some additional tips which I think are useful. Tell me if you want me to change them.
=> docs: fix publish piece docs npm login

packages/ui/core/src/assets/scss/ng-material-override.scss, packages/ui/feature-builder-canvas/src/lib/test-flow-widget/test-flow-widget.component.html, packages/ui/feature-builder-canvas/src/lib/test-flow-widget/test-flow-widget.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts, packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html, packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.ts
Currently, if the flow's trigger is not tested, it gets sample data from the sample data within the code for the trigger, this PR stops that and asks the user to test the trigger if it doesn't have selected sample data, unless it is a schedule, and fixes minor issues with templates dialog. 
Closes #1508
=> feat: Disable taking sample data by default from piece triggers

packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html, packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts, packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
Inside the builder if you press the folder name you can go back to the dashboard (flows table) with the folder selected.
=> feat: open dashboard to folder from builder

packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/add-button-core.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/big-add-button/big-add-button.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/big-add-button/big-add-button.component.ts, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/small-add-button/small-add-button.component.html, packages/ui/feature-builder-canvas/src/lib/flow-item-tree/flow-item/flow-item-connection/small-add-button/small-add-button.component.ts, packages/ui/feature-builder-store/src/lib/model/canvas-state.ts, packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.action.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts, packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
Currently if you click on an add button within the flow, you would need to remember the add button you clicked to know where the step will be placed.
To fix this this PR adds an indicator to show where the new step will be placed.
=> feat: show indicator for add btn

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.html
Stop dropdowns from closing on pressing space inside dropdown search.
=> fix: stop propagating space press inside dropdown

packages/pieces/facebook-leads/package.json, packages/pieces/facebook-leads/src/lib/common/index.ts, packages/pieces/facebook-leads/src/lib/triggers/new-lead.ts
Webhook only receives a ping on lead creation that does not contain lead form data, added code to retrieve data for incoming leads
=> fix: facebook-leadds get lead data

packages/pieces/google-sheets/package.json, packages/pieces/google-sheets/src/lib/actions/find-rows.ts
Fixed find-rows action in Google Sheets piece, it should now return the row number instead of the column name.
also changed the value returned, instead of only the key matching the search parameter, it should now return the entire row. this should be helpful if the returned data were to be used in the preceding steps in a flow.
=> fix: find rows should return row instead of single value

packages/pieces/kizeo-forms/package.json, packages/pieces/kizeo-forms/src/lib/actions/download-custom-export-in-its-original-format.ts, packages/pieces/kizeo-forms/src/lib/actions/download-standard-pdf.ts
Change the output of the download-custom-export-in-its-original-format and download-standard-pdf actions to match the File property:
**From** : JVBERi0xLjQKMS...
**To** : data:application/pdf;base64,JVBERi0xLjQKMS...
Users can now use these outputs in a File property to, for example, upload an export to their Google Drive.
=> feat(kizeo-forms): change download exports output

packages/pieces/framework/package.json
Republish v0.6.4 as v0.6.6 to override v0.6.5
=> chore: release pieces framework v0.6.6

docs/developers/piece-reference/examples.mdx
Updated docs for code reference link in piece authentication examples. 
Currently, links are referring to the root directory of the piece, not to the actual piece auth implementation.
=> docs: Update example piece auth code reference link.

packages/ui/core/src/assets/img/custom/info.svg, packages/ui/core/src/assets/scss/material-theme-helper.scss, packages/ui/core/src/assets/scss/ng-material-override.scss, packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
1) Fixes a problem related to mat-icon size, if it is not a multiple of 24px, use css transform:scale to adjust it.
2) Changes the color of the info icon inside JSON inputs to be white.
3) Added the info Icon to dropdowns.
=> chore: fixes relating to inputs info icon

packages/pieces/slack/package.json, packages/pieces/slack/src/index.ts, packages/pieces/slack/src/lib/actions/request-action-direct-message.ts, packages/pieces/slack/src/lib/actions/request-action-message.ts, packages/pieces/slack/src/lib/common/props.ts, packages/pieces/slack/src/lib/common/request-action.ts
Allows to send an approval-like message to a user/channel and wait for an action to be selected. The motivation is that the approval piece only supports two actions (approve/deny), whereas this is generic and allows multiple actions.
=> feat: support multiple slack action buttons

packages/pieces/http/package.json, packages/pieces/http/src/index.ts, packages/pieces/http/src/lib/common/props.ts, packages/ui/core/src/assets/scss/ng-material-override.scss, packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts, packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.html
1)Sets the max height of dialogs to be 65vh making it relative to screen height.
2)Converts HTTP actions dropdown to be static.
3)Fixes max width for dictionary inputs to be 50% so both key and value have equal width.
PS: Dictionary keys can't have endlines so that's why it never breaks line into two or more lines when there isn't enough space.
=> fix: Minor fixes

packages/ui/core/src/app/app.module.ts, packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/builder-autocomplete-dropdown-handler/builder-autocomplete-dropdown-handler.component.ts, packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/builder-autocomplete-mentions-dropdown/builder-autocomplete-mentions-dropdown.component.html, packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/builder-autocomplete-mentions-dropdown/builder-autocomplete-mentions-dropdown.component.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
1)Silencing import errors inside typescript editors.
2)Inserting data from data insertion popup into json editors works.
PS: imports will have type "any" now, which is something we might need to note in our docs or find a way to install types packages locally and resolve them.
=> fix: Fixed inserting data into Json inputs from data insertion popup

packages/pieces/simplepdf/.eslintrc.json, packages/pieces/simplepdf/README.md, packages/pieces/simplepdf/package.json, packages/pieces/simplepdf/project.json, packages/pieces/simplepdf/src/index.ts, packages/pieces/simplepdf/src/lib/triggers/new-submission.ts, packages/pieces/simplepdf/tsconfig.json, packages/pieces/simplepdf/tsconfig.lib.json, tsconfig.base.json
This PR introduces the SimplePDF piece.
I will amend the existing blog post once this PR is merged as it was previously using the webhook piece: https://simplepdf.eu/help/how-to/connect-simplepdf-with-activepieces-to-automate-your-pdf-forms-processing
I ran into some issues when developing, namely:
- Setting up my environment via Codespaces didn't work (a call to localhost:3000/flags kept failing and the UI was not displayed)
- My local environment failed initially because of a NX postinstall script: I had to `npm install nx` separately and then run `npm install`
- It appears that when testing the flow, even though I am returning `context.payload.body.data` in the run context, I am getting the full request (including the headers), is that expected?
=> feat: add SimplePDF piece

docs/getting-started/introduction.mdx
(Note: My first ever PR to an open-source project)
Fixed typo in docs from "**no code** user" to "**no-code** users".
=> docs: Fix typo in getting started > introduction

docs/developers/development-setup/dev-container.mdx
Ctrl+P in VSCode is used to search across the files, Ctrl+Shift+P is what brings up the command palette.
=> docs: fix wrong shortcut usage

packages/backend/src/app/helper/engine-helper.ts, packages/backend/src/app/workers/code-worker/code-builder.ts, packages/backend/src/app/workers/flow-worker/flow-worker.ts, packages/backend/src/app/workers/sandbox.ts, packages/ui/common/src/lib/components/status-icon/state-icon.component.ts
1- Failed Jobs weren't able to retry, due the error is not thrown
2- Running acquireLock should only be for draft versions and only while loading files, not while building.
=> fix: retry on internal error

packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Stop array inputs from sending empty strings to backend.
=> fix: Array inputs shouldn't send empty strings to backend

packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.html, packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.ts
When a user searches for a piece and it is not found they see "Request a piece" button which didn't work before because we removed the feedback popover from cloud.
=> chore(ui): request piece task user to  https://www.activepieces.com/pieces-roadmap

packages/pieces/sendfox/package.json, packages/pieces/sendfox/src/lib/actions/create-contact.ts
A bug where the list id shown when the user created is not used by the endpoint.
=> fix(sendfox): created contact not in the right list

packages/pieces/trello/package.json, packages/pieces/trello/src/index.ts, packages/pieces/trello/src/lib/common/index.ts, packages/pieces/trello/src/lib/common/props/card.ts, packages/pieces/trello/src/lib/triggers/cardMoved.ts, packages/pieces/trello/src/lib/triggers/newCard.ts
Creating two new triggers to handle the following:
1 - card moved to list : to inform the user when a card is moved to a specified list.
2 - new card created : to inform the user when a card is created inside a board.
in the second trigger the user can limit the scope to a certain list
=> feat(trello): card moved to list / new card created trigger

packages/pieces/linear/package.json, packages/pieces/linear/src/index.ts, packages/pieces/linear/src/lib/actions/comments/create-comment.ts, packages/pieces/linear/src/lib/actions/issues/create-issue.ts, packages/pieces/linear/src/lib/actions/issues/update-issue.ts, packages/pieces/linear/src/lib/actions/projects/create-project.ts, packages/pieces/linear/src/lib/actions/projects/update-project.ts, packages/pieces/linear/src/lib/common/client.ts, packages/pieces/linear/src/lib/common/props.ts, packages/pieces/linear/src/lib/triggers/new-issue.ts
This combination of triggers and actions allows me to:
- Get one step closer to automating client onboarding by creating a project board.
- Get notifications of new issues in my private discord server.
- Let ChatGPT brainstorm about new issues and place a comment to the issue/task with the output.
=> feat(linear): create project, update project, create comment action & new issue trigger

packages/backend/src/app/database/migration/postgres/1686138629812-unifyPieceName.ts
Just ran into this when updating from 0.3.9 to 0.8.0.
=> fix: unquoted migration parameter

packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html, packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
The Discord item in the dropdown now takes the users to community.activepieces.com.
=> fix: switch from Discord to community in user-avatar dropdown.

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html, packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/selected-auth-config.pipe.ts, packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts, packages/ui/feature-connections/src/lib/dialogs/cloud-oauth2-connection-dialog/cloud-oauth2-connection-dialog.component.html
=> fix: stopped connections dropdown from overflowing the reconnect button

packages/pieces/google-sheets/package.json, packages/pieces/google-sheets/src/lib/actions/get-rows.ts, packages/pieces/google-sheets/src/lib/common/common.ts
Calling the get next row(s) rapidly will cause a race condition in which the newer calls will user the old value of the counter.
Outbound fixed
Fixes #2751 
=> fix(google-sheet): Get next row handling out of bound

packages/pieces/open-router/package.json, packages/pieces/open-router/src/lib/actions/ask-open-router.ts
open router returns leading and trilling spaces.
Fixes #2906
=> fix(openrouter): removing the lead and trill spaces

packages/pieces/apitable/package.json, packages/pieces/apitable/src/index.ts, packages/pieces/apitable/src/lib/actions/find-record.ts
Adds filter field to `Find APITable Record` action in order to use `filterByFormula` possibility (quite important to unlock many possible use cases). 
1) Store content in ApiTable and populate with OpenAI: create datasheet with possible content topic and empty "Content" column, filter records by formula `{Content} = ""` and ask ChatGPT to write it.
2) Find specific record (such as User Profile) by slug/id
=> feat: add filter field to apitable

docs/developers/sharing-pieces/overview.mdx
Fixes some broken documentation links about piece sharing
=> fix: docs links that are broken

packages/backend/src/app/flows/step-run/step-run-service.ts
Doesn't check for sample data on empty triggers.
=> fix: trigger sample data is undefined for empty triggers

packages/pieces/framework/package.json, packages/pieces/framework/src/lib/piece.ts, packages/shared/package.json, packages/shared/src/lib/pieces/piece.ts
Adds piece categories and mention icon url to createPiece parameters.
mention icon url --> used inside mentions (using previous steps in inputs through the "insert data" pop up).
categories --> will be used for now in deciding if the piece is a core piece or not, but further expansion could include categorising the pieces in the marketing website.
=> chore: add categories and mentionIconUrl to piece

packages/pieces/common/package.json, packages/pieces/common/src/lib/http/axios/axios-http-client.ts, packages/pieces/common/src/lib/http/core/base-http-client.ts
When testing the trigger, I'm getting a 404 error because the URL is invalid. HttpClient code fixed.
Fixes #2993
=> fix(common): http doesn't add query params correctly

README.md
###PULL REQUEST TITLE
Appropriate Article Use
###ISSUE
Inappropriate Article Use
###CHANGES
an article used before "automation" word
###SOLUTION
Use an article instead of a 
I hope you look out into this and consider my contribution.
=> docs: fix an typo in readme

.dockerignore, Dockerfile
An easy change in the Dockerfile to improve layer caching of subsequent builds, and avoid cache invalidation due to unrelated files.
=> fix: improve docker layer caching and ignored files

deploy/pulumi/index.ts
1. ImageName can be defined in pulumi config or as an environment variable (unless `deployLocalBuild` is `true`)
2. Communication between the load balancer and fargate is defined through a security group instead of keeping fargate open to the entire internet
3. `apEncryptionKey` and `apJwtSecret` are defined as pulumi secrets
I think we should also change the default rules of the ALB security group, it shouldn't be completely open by default. Not sure what's the best way to configure it.
=> ci: add ImageName as optional deployment paramter and minor fixes

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
If a piece action/trigger property form control was assigned 0 as a number not as a string, they wouldn't show it and instead show an empty field.
=> fix: accept zeros as a value in piece form

.github/workflows/build-cloud-image.yml, packages/ui/feature-builder-canvas/src/lib/test-flow-widget/test-flow-widget.component.ts, packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.ts
If the log loading exceeds 1500 ms, the subsequent test flow poll will be triggered, leading to the cancellation of the log loading. This results in an infinite loading loop.
=> fix: infinite test flow loading

package-lock.json, packages/pieces/trello/package.json, packages/pieces/trello/src/index.ts
Updates the instructions to get Trello API key and token
=> fix(trello): auth instructions

packages/backend/src/app/database/migration/postgres/1691703023866-add-app-connection-type-to-top-level.ts
The database migration run before secret loading this were changed, it's better to keep the migration self isolated from application code.
=> fix: connection migration

packages/backend/src/app/helper/logger.ts
When running activepieces in docker, the AP_LOG_LEVEL variable has no affect. This is because `pino` is initialized without the log level configuration variable. This PR fixes it.
=> fix: apply log level configuration to default logger

packages/ui/common/src/lib/service/oauth-2-apps.service.ts
Not all managed oauth2 apps were being listed, this fixes that.
=> fix: increase limit for getting platform managed oauth2 apps

packages/backend/src/app/webhooks/webhook-controller.ts
=> fix: webhooks errors

packages/pieces/openai/package.json, packages/pieces/openai/src/lib/common/common.ts
Fixes an issue with fine-tuned models not being supported by tiktoken, so we manually calculate tokens for these models now
=> fix(openai): support fine-tuned model by approximate tokens length 

packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/dropdown-initial-value.pipe.ts
use deepequal to find initial values instead of usual (===) comparison
=> fix: some dropdowns don't show the selected value for step inputs

packages/pieces/airtable/package.json, packages/pieces/airtable/src/lib/actions/create-record.ts, packages/pieces/airtable/src/lib/common/index.ts
Adds typecast property to body of create record request, so text values get accepted for number fields.
=> fix(airtable): "Create record" action used to fail when there was number inputs, now it doesn't

packages/pieces/telegram-bot/package.json, packages/pieces/telegram-bot/src/index.ts, packages/pieces/telegram-bot/src/lib/action/create-invite-link.ts, packages/pieces/telegram-bot/src/lib/action/get-chat-member.ts, packages/pieces/telegram-bot/src/lib/action/send-media.action.ts, packages/pieces/telegram-bot/src/lib/common/index.ts, packages/pieces/telegram-bot/src/lib/trigger/new-message.ts
1) Explicitly define all allowed message types to avoid reusing of previous setup. For example, if external app/call setupped webhook with `allowed_updates` equal to `['callback_query']`, the activipieces webhook will follow the same filter and miss all other updates.
2) Previous (0.3.6) update of telegram-bot introduced Send Media action with critical issue in different then Image types. Current PR fix it to make possible send Video, GIF or stickersa
1) Implements **Create Invite Link** action to create invitation link with possible expiration date and member limitations
2) Implements **Get Chat Member** action to get chat member info or expected Bad Request (without run failure) 
=> feat(telegram-bot): Fixes for critical issues /  Create Invite Link Action / Get Chat Member Action

packages/pieces/twitter/package.json, packages/pieces/twitter/src/index.ts
redirect url wasn't being shown in instructions for creating connection, this fixes it.
=> fix: redirect url wasn't being shown in instructions for creating connection

.gitignore, package-lock.json, package.json, packages/pieces/google-drive/package.json, packages/pieces/google-drive/src/index.ts, packages/pieces/google-drive/src/lib/action/search-folder.action.ts
This PR adds a new action to the Google Drive piece: Search folder. Also, it introduces the googleapis package as a new dependency 
This is going to ease next developments on pieces for Google services. I plan to update all Google drive actions to use this package instead of making a "simple http request".
(Sorry for the .gitignore file)
New Dependency:
```json
"googleapis": "129.0.0"
```
```bash
npm install --save-dev @types/googleapis
```
=> feat(google-drive): search folder by name 

packages/backend/src/app/ee/flow-template/flow-template.service.ts
Adds a null check for tags when upserting templates, because tags array is not supposed to be null.
=> fix: sharing flow was broken

packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts, packages/ui/feature-dashboard/src/lib/pages/runs-table/runs.service.ts
=> fix: show correct flow status after first publish (on) and refresh runs table after a retry 

packages/pieces/google-docs/package.json, packages/pieces/google-docs/src/index.ts, packages/pieces/google-docs/src/lib/actions/create-document-based-on-template.action.ts, packages/pieces/google-docs/src/lib/actions/read-document.action.ts, packages/pieces/google-docs/src/lib/common/index.ts, packages/pieces/google-drive/package.json, packages/pieces/google-drive/src/index.ts, packages/pieces/google-drive/src/lib/action/duplicate-file.action.ts
- Rename the Create document based on template to Edit Template File
- Added the Replace images to the above action
- Added the Read document action to Google Docs to get all details from a document (and object IDs to send to the 1st action)
- Added the Duplicate File to Google drive.
=> feat(google-documents): create document based on template / read document action

packages/pieces/robolly/.eslintrc.json, packages/pieces/robolly/README.md, packages/pieces/robolly/package.json, packages/pieces/robolly/project.json, packages/pieces/robolly/src/index.ts, packages/pieces/robolly/src/lib/actions/generate-image.action.ts, packages/pieces/robolly/tsconfig.json, packages/pieces/robolly/tsconfig.lib.json, tsconfig.base.json
This adds a new piece: [Robolly](https://robolly.com/). I added one action for the generations of images. 
=> feat(robolly): generate image action

packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.html, packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.ts
On dashboard, both loaders starts loading simultaneously, even if we click any one of them. **This should be fixed!**
Initially,
```typescript
<div (click)="openToDemo()"
class="ap-flex ap-items-center ap-gap-2 ap-justify-center ap-flex-col ap-border ap-border-outline ap-h-[249px] ap-w-[200px] ap-rounded ap-bg-white ap-rounded-lg ap-cursor-pointer ap-transition-colors hover:ap-border-primary hover:ap-bg-primary-light ">
// Triggering createFlow()
<ng-container *ngIf="!createFlow$">
<svg-icon src="assets/img/custom/arrow_right.svg" [applyClass]="true"
class="ap-fill-primary ap-w-[26px]  ap-h-[26px]"></svg-icon>
<div class="ap-typography-subtitle-1 ap-text-primary" i18n>Demo flow</div>
<div class="ap-typography-subtitle-2 ap-text-description ap-px-3" i18n>
Learn from our Gelato maker demo …
```
=> fix: dashboard loaders on /flows

packages/pieces/gmail/package.json, packages/pieces/gmail/src/index.ts, packages/pieces/gmail/src/lib/actions/send-email-action.ts
add new field for changing the attachment name in gmail
=> feat(gmail): add capability to change attachment name for send email

docs/about/changelog.mdx
The latest update in the changelog has 4/1/2023 so I changed it to 4/1/2024
=> chore: fixed wrong date in changelog

packages/backend/src/app/flows/common/piece-manager/local-piece-manager.ts, packages/backend/src/app/helper/package-manager.ts, packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
The issue is that pnpm uses relative symbolic links. When isolating the directory, it gets bound to `/root/`, which is different from where the relative link is constructed, causing it to fail. This change aims to replace all relative symbolic links with absolute paths after linking using pnpm.
Additionally, unrelated to the bug, this PR restricts the bound folder to `node_modules`, `dist`, and `.pnpm`.
=> fix: isolate mode with local file pieces

docs/developers/piece-reference/examples.mdx
Pieces were moved to community folder, links in website point to previous file location
=> docs: fix broken links. Changes to links to point to new community folder

packages/pieces/community/matomo/package.json, packages/pieces/community/matomo/src/lib/api.ts
Matomo v5 was released and the API token needs to be added to the POST request parameters. This fixes the integration to support v5. 
=> fix(matomo): Ensure compatibility with v5 API

packages/backend/src/app/database/migration/common/1696245170061-add-piece-type-and-package-type-to-flow-version.ts, packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts, packages/backend/src/app/flows/flow-version/flow-version-side-effects.ts
The '?' Style is not supported in postgres, and it used in common migration
=> fix: use $ syntax instead of ? in database migration

packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
Array data, in the storage piece, is stored as a string ( despite the JSONB column data type ). This makes it impossible for the user to use the add-to-list action, which assumes that the data retrieved from the storage is an array ( if not empty ) and tries to push items to it.
Fixes #3759
=> fix(storage-piece): "Key <key> is not an array" error when using add-to-list action

package.json, packages/backend/src/app/ee/pieces/platform-piece-module.ts, packages/backend/src/app/helper/error-handler.ts, packages/backend/src/app/pieces/base-piece-module.ts, packages/backend/src/app/pieces/piece-service/index.ts, packages/cli/src/index.ts, packages/cli/src/lib/commands/sync-pieces.ts, packages/cli/src/lib/utils/piece-utils.ts
This will sync all pieces in customer folder to your platform, example usage.
AP_API_KEY=PLATFORM_API_KEY npm run sync-pieces -- --apiUrl http://localhost:3000
=> feat: allow to sync custom pieces folder to platform

packages/engine/src/lib/handler/context/engine-constants.ts, packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/engine/src/lib/handler/loop-executor.ts, packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/main.ts, packages/engine/test/handler/flow-rerun.test.ts, packages/engine/test/handler/flow-with-pause.test.ts, packages/engine/test/handler/test-helper.ts, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/step-output.ts
Remove the dependencies on execution type. It's poor to depend on that state as the flow can alternate between them. For example, if you have two delay steps after the first delay, the execution type will be resume and it will skip the other delay. 
Solution: Check if the flow is paused from the execution state and decide the state. 
This discovered a hidden bug that if there is a delay inside a loop, it will redo all the steps inside the loop as it overwrites the iteration object inside the loop with an empty one each time the loop is executed, so instead now we try to reuse old loop state if it exists and skip emptying the iteration object.
=> fix: multiple delays should work

packages/pieces/community/image-helper/package.json, packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
fixes the description of the degree field in rotate image action found inside image-helper piece.
=> fix: rotate image degree description

docs/openapi.json, packages/engine/src/lib/handler/branch-executor.ts, packages/engine/test/handler/flow-branching.test.ts, packages/shared/package.json, packages/shared/src/lib/flows/actions/action.ts
I added the "(number) is equal to" to the conditions of a branch step.
I get you can do the same with the "(Text) exactly matches", but I think is better to have a dedicated condition for numbers... I mean, you could use the "(Text) exactly matches" for booleans too but instead, we have two separate conditions.
=> feat(branch): add new condition "(number) is equal to"

packages/ui/core/src/app/app.module.ts
=> fix: show step icons in import flow page 

packages/pieces/community/metabase/.eslintrc.json, packages/pieces/community/metabase/README.md, packages/pieces/community/metabase/package-lock.json, packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/project.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-question.ts, packages/pieces/community/metabase/src/lib/common.ts, packages/pieces/community/metabase/tsconfig.json, packages/pieces/community/metabase/tsconfig.lib.json
Add Metabase piece with action to get results from a "question"
Metabase auth scheme requires a session token (with a fixed duration) that is delivered by a specific endpoint (using email + password)
The Piece will automatically get the token and refresh it when a HTTP 401 error is received, as per Metabase documentation
The token is encrypted (using code which is very similar to `encryption.ts`) and stored at the Project scope
https://www.metabase.com/learn/administration/metabase-api#authenticate-your-requests-with-a-session-token
=> feat(metabase): Get Question Action

packages/pieces/community/generatebanners/package.json, packages/pieces/community/generatebanners/src/lib/actions/renderTemplate.action.ts
- Removed the `video` format as GenerateBanners only supports generating PNG/JPEG/PDFs at the moment.
- Removed the `audio_url` field for the same reason
=> fix(GenerateBanners): remove deprecated fields

packages/ui/canvas-utils/src/lib/panning/panner.service.ts, packages/ui/canvas-utils/src/lib/zooming/zooming.service.ts, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html, packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
I know zooming in and out is now without animation and is centered on flow not canvas, will fix this soon.
=> fix: reset zoom and fit to screen on all screen sizes

packages/server/api/src/app/flows/flow-version/flow-version.service.ts, packages/shared/src/lib/flows/flow-version.ts, packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html, packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.ts
Display editor's email in a flow's version history
=> feat: display editor in versions history

docs/embedding/embed-builder/embed-iframe.mdx, packages/ee/embed-sdk/src/index.ts
This was preventing the user from accessing flow by url directly, as the initial route will always override the href route, this should fix it.
=> fix: remove initial route from embedding sdk

packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/helper/pagination/paginator.ts, packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.html
=> feat: sort flows by enabled first

packages/pieces/community/http/package.json, packages/pieces/community/http/src/lib/actions/send-http-request-action.ts
=> fix(http): add failsafe option back

packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts, packages/pieces/community/slack/src/lib/actions/send-message-action.ts, packages/pieces/community/slack/src/lib/actions/upload-file.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/common/utils.ts
- Add a standalone "upload file" action which does not automatically share the file
- Add arbitrary blocks support for "send message" actions
=> feat(slack): add upload file action and arbitrary blocks support

packages/pieces/community/stable-diffusion-webui/.eslintrc.json, packages/pieces/community/stable-diffusion-webui/README.md, packages/pieces/community/stable-diffusion-webui/package.json, packages/pieces/community/stable-diffusion-webui/project.json, packages/pieces/community/stable-diffusion-webui/src/index.ts, packages/pieces/community/stable-diffusion-webui/src/lib/actions/text-to-image.ts, packages/pieces/community/stable-diffusion-webui/tsconfig.json, packages/pieces/community/stable-diffusion-webui/tsconfig.lib.json, tsconfig.base.json
Add Piece to use the text-to-image API from [Stable Diffusion web UI](https://github.com/AUTOMATIC1111/stable-diffusion-webui) - returns base64 images (similar to image-helper)
=> feat(stable-diffusion-web-ui): text to image action

packages/ui/common/src/lib/components/json-view/json-view.component.html, packages/ui/common/src/lib/components/json-view/json-view.component.scss, packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.ts
Added wrap-text for Test output window and prettified nested thrown errors for readability.
**Before**
**After**
Note:
- Did not add word wrapping for extended output module
=> chore: add text wrap to test output window and format thrown error message

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/upload-file.ts, packages/pieces/community/slack/src/lib/common/utils.ts
Properly fail when Slack reports an API error (HTTP code may be 200)
This is probably a breaking change for some flows (hence the version change)
=> fix(slack): properly propagate Slack API errors

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts, packages/pieces/community/common/src/lib/http/core/base-http-client.ts
This PR add support for the same query parameter to be used multiple times in the same request. When an endpoint we are using has a query parameter that expects an array, generally the request looks like:
- '...?key=value1&key=value2'
We cannot support this using a Record object. So I changed it to a URLSearchParams object
=> fix(piece-framework): axios http client to support array query parameter multiple times

packages/engine/src/lib/handler/code-executor.ts, packages/engine/src/lib/handler/context/engine-constants.ts, packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/helper/error-handling.ts, packages/engine/src/lib/helper/execution-errors.ts, packages/engine/src/lib/services/connections.service.ts, packages/engine/src/lib/services/storage.service.ts, packages/engine/test/handler/flow-error-handling.test.ts, packages/engine/test/handler/flow-piece.test.ts, packages/server/api/src/app/store-entry/store-entry.controller.ts, packages/server/api/src/app/workers/flow-worker/flow-worker.ts, packages/shared/package.json, packages/shared/src/lib/flow-run/execution/flow-execution.ts, packages/shared/src/lib/store-entry/dto/store-entry-request.ts
- Introduces `Retryable` and `NonRetryable` execution errors for the engine
- Refactors step retry logic to not retry `NonRetryable` errors
- Fixes `maxAttempts` being set to 1 for step retries
- Fixes #4137
=> feat: retryable errors for engine execution

docs/embedding/configuration/initialize-embed.mdx
there was an error in json config minor one you guys putted a ; instead of ,
There was a jus a minor syntax error.
=> docs: update initialize-embed.mdx

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/search-messages.ts
Add action to search messages using Slack's query syntax
Pagination is handled
_You will need to re-authenticate your connection to get the extra `search:read` scope_
=> feat(slack): add search message action

packages/server/api/src/app/ee/git-repos/git-repo.module.ts
Allow using the `api/v1/git-repos` endpoint using an API key (for continuous deployment purpose)
=> feat: allow retrieving project git config using API token

packages/server/api/src/app/ee/projects/platform-project-controller.ts, packages/server/api/src/app/ee/projects/platform-project-service.ts, packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
Enable pagination for the list projects endpoint (which currently only returns 50 projects)
=> feat: add pagination support for project list endpoint

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
Add support for fragments, i.e. additional context to pass to the assistant that can be referenced in the conversation
- initial fragment can be passed when creating a new conversation
- new action to add a fragment to an existing conversation
=> feat(dust): add support for fragments

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts, packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts, packages/pieces/community/google-drive/src/lib/common/index.ts
Add missing option to support team drives when duplicating a file
=> fix(google-drive): add missing option to support team drives

docs/about/changelog.mdx, packages/pieces/community/wordpress/package.json, packages/pieces/community/wordpress/src/index.ts, packages/pieces/community/wordpress/src/lib/actions/create-page.action.ts, packages/pieces/community/wordpress/src/lib/actions/create-post.action.ts, packages/pieces/community/wordpress/src/lib/actions/get-post.action.ts, packages/pieces/community/wordpress/src/lib/common/index.ts, packages/pieces/community/wordpress/src/lib/trigger/new-post.trigger.ts
WordPress is written with a capital P. In some cases, this was done correctly but inconsistently so. This pull tries to fix that. Most annoyingly, the trigger was listed with a lowercase p, and as a long-time WordPress core contributor, this pained me :)
=> feat(WordPress): rename piece to WordPress, with a capital P

packages/ui/common/src/lib/components/dialogs/import-flow-dialog/import-flow-dialog.component.ts
Fixes #4311 
Initially had written the code below
```
catchError((err: HttpErrorResponse) => {
const status = err?.status;
if (status === StatusCodes.BAD_REQUEST) {
this.snackBar.open($localize`The uploaded template is invalid`);
this.loading = false;
}
return of(void 0);
})
```
However when I tried different json files, sometimes instead of an HTTPErrorResponse, it was giving a TypeError, as shown below:
Hence instead of looking for any particular type of error, I decided to just show the message as long as we get any error. Hope that is ok.
=> feat: display error invalid template

packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.html
When you switch the language to Japanese, you will notice that the word "コネクション" (connection) in the sidenav is wrapped into four lines.
While in English a single word cannot be wrapped by default, in some languages like Japanese this is not the case.
This PR increases the width of the captions in the sidenav to minimize the word wrapping.
=> feat: increase sidenav caption width

packages/ui/common/src/lib/utils/utils.ts, packages/ui/feature-builder-form-controls/src/lib/components/json-control/json-control.component.ts, packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
=> fix: json form control should send value as object not string

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/search-folder-or-file.action.ts
- The google-drive "search file" action was missing a parameter to use shared drives
- Add create and modify timestamps for each file
- Don't specify a parent directory when field is empty - otherwise it only looks for files in the root directory (and not in subdirectories)
=> fix(google-drive): add missing option to search file on shared drives

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/common/index.ts, packages/pieces/community/google-drive/src/lib/triggers/new-file.ts
The "include team drives" param was not passed to the actual polling function
=> fix(google-drive): new file trigger now supports shared drives

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/upload-file.ts
Fixes issue where it was not possible to upload a file to a shared drive
=> fix(google-drive): support shared drives when uploading a file

.vscode/launch.json
It looks like the folder structure was changed in February to rename backend to server/api. This meant that when you try and attach the debugger in vscode it was giving an error (directory not found)
=> fix: wasn't able to attach a debugger to the running process

packages/pieces/community/todoist/package.json, packages/pieces/community/todoist/src/index.ts
This PR fixes issue with Todoist piece custom API call not injecting the right authorization header.
Fixes # [(4435)](https://github.com/activepieces/activepieces/issues/4435)
=> fix(todoist): wrong authorization header for custom API call

deploy/pulumi/package.json
This PR resolves the issue where the activepieces project was incorrectly defined in multiple locations within our repository. Specifically, in the root path and under deploy/pulumi. This caused build failures due to non-unique naming conflicts detected by our build tools.
* Changed the project name in `deploy/pulumi/package.json` to have a unique identifier.
* API & GUI:
```
[API]
[API]  NX   The following projects are defined in multiple locations:
[API]
[API] - activepieces:
[API]   - .
[API]   - deploy/pulumi
[API]
[API] To fix this, set a unique name for each project in a project.json inside the project's root. If the project does not currently have a project.json, you can create one that contains only a name.
[API]
[API] Because of the error the Nx daemon process has exited. The …
```
=> fix: change pulumi project name in package.json

packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/properties-controls-helper.ts, packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
Stop triggering saving when adding new form controls and prevent saving in read-only mode.
=> fix: triggering saving in read-only mode

packages/server/api/src/app/database/migration/postgres/1713221809186-RemoveUniqueEmailOnUser.ts, packages/server/api/src/app/database/migration/sqlite/1713222892743-RemoveUniqueEmailOnUser.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/user/user-entity.ts
This PR removes the platform Id is null and email is unique constraints. This change should fix the TypeORM migration for all SQLite3 migrations. Now, it will show no changes after migration instead of an infinite number of migrations.
=> chore: remove unique email and platform null constraints

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/common/index.ts
Filters folders from being polled in Google drive trigger new file action with get file content enabled.
=> fix(google-drive): exclude folders from file polling

packages/pieces/community/slack/src/lib/actions/upload-file.ts
Add optional `filename` param when uploading a file via the dedicated action - to avoid image URLs ending with `/blob` thus allowing proper image previews when sharing the URL in a message as a separate action
=> feat(slack): add optional filename param when uploading a file

packages/ui/core/src/assets/scss/ng-material-override.scss, packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control-text-item.component.ts, packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts, packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.html, packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.scss, packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.ts
Fixes 
1) Dragging an element didn't hide it in the list which made things confusing. 
2) Dragging an element didn't change the cursor to grabbing.
3) Dragging an element didn't have a limit, you could drag it anywhere which could make people think they can swap between arrays and that's not the case.
4) The remove item icon had to be clicked itself exactly without any extra space around it, so there is space added now around it a bit so you don't have to exactly click the icon.
5) Dragging wasn't animated.
6) Tooltips were not internationalised, please make sure that's the case always.
7) Remove icon wasn't changed for dictionary. 
8) Angular don't like to have passed input params to a component called "formControl", so name it something like "control" if you ever need to pass a …
=> fix: UX for reordering array

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/actions/comments/create-comment.ts, packages/pieces/community/linear/src/lib/actions/issues/create-issue.ts, packages/pieces/community/linear/src/lib/actions/issues/update-issue.ts, packages/pieces/community/linear/src/lib/actions/projects/create-project.ts, packages/pieces/community/linear/src/lib/actions/projects/update-project.ts
Enrich various Linear actions output to include the actual object (e.g. created issue, project, comment, etc.) instead of a useless internal ID
The output looks like this:
```
{
lastSyncId: <timestamp>,
success: true,
_issue: {
id: <UUID>
},
issue: {
<actual object>
}
}
```
I've kept the `_issue` proxy object to avoid breaking existing flows but it should probably be removed at some point
=> feat(linear): enrich actions output

packages/pieces/community/metabase/src/lib/common.ts
Metabase session token is automatically refreshed when a 401 error is encountered and the original query is automatically retried.
But the retry would use the previous (invalid) token, thus yielding another 401
This PR updates the retry payload to actually use the new token 🤦
=> fix(metabase): fix session token refresh

packages/pieces/community/metabase/src/lib/common.ts
Rename key under which the Metabase session token is stored to make it explicit that it "belongs" to the Metabase piece
=> chore(metabase): rename session token key in store

packages/engine/src/lib/handler/context/flow-execution-context.ts, packages/pieces/community/google-sheets/package.json, packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts, packages/server/worker/src/lib/queue/ap-memory-queue.ts
=> fix: delay step were failing after loop

package-lock.json, package.json, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts, packages/server/api/test/integration/cloud/platform/platform.test.ts
Fixes #3227 
This actions required following new scopes for Oauth2 app:
- reactions:write
=> feat(slack): add reaction to message action

packages/pieces/community/poper/.eslintrc.json, packages/pieces/community/poper/README.md, packages/pieces/community/poper/package.json, packages/pieces/community/poper/project.json, packages/pieces/community/poper/src/index.ts, packages/pieces/community/poper/src/lib/triggers/new-lead.ts, packages/pieces/community/poper/tsconfig.json, packages/pieces/community/poper/tsconfig.lib.json, tsconfig.base.json
Adds a piece to the SaaS tool "Poper," which collects data through a popup. Some of our customers requested this piece, that is why this PR.
I'll also create a help guide on [https://help.poper.ai](https://help.poper.ai) on how to use this piece.
=> feat(poper): New Lead Trigger

packages/pieces/community/trello/package.json, packages/pieces/community/trello/src/lib/actions/get-card.ts, packages/pieces/community/trello/src/lib/common/index.ts
Fixes #4638 
Trello API throws 403 error for GET request with body.[See Changelog](https://developer.atlassian.com/changelog/#CHANGE-1459)
=> fix(trello): fix boards dropdown error 

packages/pieces/community/whatsapp/.eslintrc.json, packages/pieces/community/whatsapp/README.md, packages/pieces/community/whatsapp/package.json, packages/pieces/community/whatsapp/project.json, packages/pieces/community/whatsapp/src/index.ts, packages/pieces/community/whatsapp/src/lib/actions/send-media.ts, packages/pieces/community/whatsapp/src/lib/actions/send-message.ts, packages/pieces/community/whatsapp/src/lib/common/utils.ts, packages/pieces/community/whatsapp/tsconfig.json, packages/pieces/community/whatsapp/tsconfig.lib.json, tsconfig.base.json
Added whatsapp piece for 2 actions: 
1) send a text message
2) send a media message
Implemented authentication method:
Utilized system user access token instead of OAuth 2.0 to ensure the access token is permanent and won't expire.
https://github.com/activepieces/activepieces/assets/69399787/8c9f9846-b085-4b37-90e7-bd6be0d37f34
=> feat(whatsapp-business): add sendMessage, sendMedia actions

packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
Fixes test webhooks not running when flow is not published/enabled
=> fix(webhook): distinguish test webhooks to run when flow not published/enabled

packages/pieces/community/clickup/package.json, packages/pieces/community/clickup/src/lib/actions/comments/create-task-comment.ts, packages/pieces/community/clickup/src/lib/common/index.ts
I've kept the original (weird) behaviour of setting the API user as assignee by default to not break past scenarios.
Allow people to set the assignee when posting comments on clickup.
=> feat(clickup): Assignee Dropdown for Create Comment Action

packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts, packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
Worker doesn't need access to refresh token and client secret in case the user define it (use my own credential option), this is not a vulnerability but it's always better to expose minimum number of information / secrets through api.
=> chore: remove client secret in client grant and user custom oauth2

package.json, packages/pieces/community/math-helper/package.json, packages/pieces/community/math-helper/src/lib/actions/multiplication.ts
It fixes the spelling of Multiplication in math helper which was incorrectly there as Multiplicattion
=> fix: change incorrect spelling of Multiplication in math helper

packages/ui/core/nginx.standard.conf, packages/ui/core/src/app/app-routing.module.ts
=> chore: add Content-Security-Policy and 404 status on not-found page

packages/ui/core/nginx.standard.conf
Fixes the nginx if directive in location
=> fix: nginx if in location

docs/install/options/docker-compose.mdx
Wording and formatting clarification for the Upgrading Section
Wording for step 1 was unclear. As there were two step 1.
The formatting for steps 2, 3 and 4 made it seem part of the second step 1.
Combined the step 1s into sub steps and uniformed the formatting for the other steps to mimic step 1's.
=> docs: update docker-compose.mdx / upgrading section wording and formatting

packages/ui/common/src/lib/components/json-view/json-view.component.html, packages/ui/common/src/lib/components/json-view/json-view.component.ts, packages/ui/core/src/assets/scss/json-editor-override.scss
This fixes the issue that is reported here:  https://community.activepieces.com/t/unable-to-convert-json-to-text/4233/4
=> fix: improve displaying primitive data (text, numbers and booleans) in sample data view

packages/ui/core/nginx.standard.conf
Fixes embedded forms origins with NGINX
=> fix: ignore x-frame-origin in forms

packages/pieces/community/zoho-crm/package.json, packages/pieces/community/zoho-crm/src/index.ts
In addition to previous scope added recently, two scope also need to be added to allow retrieving the backup URLS and download the backup files.
Fixes #4839
=> feat(zoho-crm): Add scope to Zoho CRM to get backup URLs and download backup file

packages/pieces/community/zoho-books/.eslintrc.json, packages/pieces/community/zoho-books/README.md, packages/pieces/community/zoho-books/package.json, packages/pieces/community/zoho-books/project.json, packages/pieces/community/zoho-books/src/index.ts, packages/pieces/community/zoho-books/tsconfig.json, packages/pieces/community/zoho-books/tsconfig.lib.json, tsconfig.base.json
Create the foundation for Zoho Books pieces. Only include Custom API Call.
Questions:
1. I'm not sure how to provide https://cdn.activepieces.com/pieces/zoho-books.png
2. For testing I used by own ClientID and Secret, but it should be possible to use the same ClientID and Secret for all Zoho pieces.
3. I've defined a fixed value for baseURL that work for US only. 
=> feat(zoho-books): custom api call action

docs/install/options/aws.mdx
Adds info on how to 1-click install Activepieces on AWS using stackstap
=> docs: Adding stacksnap as option for deploying Activepieces to AWS

packages/pieces/community/lever/package.json, packages/pieces/community/lever/src/lib/common.ts
Fix `yes-no` field type and add support for single-select dropdowns
=> feat(lever): improve add-feedback action

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/save-file-as-pdf.action.ts, packages/pieces/community/google-drive/src/lib/action/upload-file.ts
"Export to PDF" action did not work on shared drives
=> feat(google-drive): add support for all drives to pdf export action

packages/ui/core/nginx.standard.conf
This currently causing an issue for embed users, we should add it back with configurable way and currently the responsibility should be moved to load balancer to add the header.
=> chore: remove iframe options temporary

packages/pieces/community/maileroo/.eslintrc.json, packages/pieces/community/maileroo/README.md, packages/pieces/community/maileroo/package.json, packages/pieces/community/maileroo/project.json, packages/pieces/community/maileroo/src/index.ts, packages/pieces/community/maileroo/src/lib/actions/send-email.ts, packages/pieces/community/maileroo/src/lib/actions/send-from-template.ts, packages/pieces/community/maileroo/src/lib/common/send-utils.ts, packages/pieces/community/maileroo/tsconfig.json, packages/pieces/community/maileroo/tsconfig.lib.json, tsconfig.base.json
This will add a new piece for [Maileroo](https://maileroo.com) to enable user to send an email via Maileroo's email server. 
The piece has the following actions:
- Send a regular email
- Send an email template defined in Maileroo
Each action requires common mail props such as `to`, `from`, `from_name`, `subject`, `bcc`, `cc`, `reply_to`
=> feat(maileroo): send email / send email from template

packages/pieces/community/photoroom/.eslintrc.json, packages/pieces/community/photoroom/README.md, packages/pieces/community/photoroom/package.json, packages/pieces/community/photoroom/project.json, packages/pieces/community/photoroom/src/index.ts, packages/pieces/community/photoroom/src/lib/actions/remove-background.ts, packages/pieces/community/photoroom/tsconfig.json, packages/pieces/community/photoroom/tsconfig.lib.json, tsconfig.base.json
Add photoroom integration with action to remove the background of an image
=> feat(photoroom): add action to remove the background of an arbitrary image

packages/pieces/community/common/src/lib/helpers/index.ts
In some cases the auth mapping for a custom API call needs to be async (e.g. to retrieve a token or cookie dynamically)
=> feat: allow async auth mapping for custom API calls

packages/engine/src/lib/helper/trigger-helper.ts, packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts, packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
Add a new APP_WEBHOOK trigger for `intercom` to receive conversation note events
More types ("topics" for Intercom) will be added later
In order to work the `AP_APP_WEBHOOK_SECRETS` env var must be updated
```
AP_APP_WEBHOOK_SECRETS='{"@activepieces/piece-intercom": {"webhookSecret": "<your OAuth client secret>"}}'
```
=> feat(intercom): add trigger (webhook) to receive conversation notes

packages/pieces/community/smtp/package.json, packages/pieces/community/smtp/src/index.ts, packages/pieces/community/smtp/src/lib/actions/send-email.ts
In this pull request, I added a `senderName` property to the send email action. I also added a `getFrom` function that takes in a senderName and a from, and returns the from. If the senderName isn't undefined, it returns a string with the following format: "`senderName`" <`from`>, otherwise it will just return the `from` value passed.
=> feat(smtp): add senderName property

package-lock.json, package.json, packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
Add optional keyword prop
When the keyword is present, trigger only when one word or more is an exact match on the keyword (not a simple substring match)
i.e.:
- no keyword: always trigger when a new note is added
- `keyword`: trigger if note is "keyword this is a test" but NOT if it is "keyword2 this is a test"
=> feat(intercom): add optional keyword to filter incoming note hooks

packages/server/api/src/app/user-invitations/user-invitation.module.ts
When issuing a `user-invitation` via the API, `projectId` can be absent from the payload (i.e. when `type` is `PLATFORM`)
~Yet it was required by `ProjectAuthzHandler`~
Edit: instead of adding an exception in `ProjectAuthzHandler`, add proper EndpointScope
=> feat: fix creating user invitations from API

packages/pieces/community/captain-data/.eslintrc.json, packages/pieces/community/captain-data/README.md, packages/pieces/community/captain-data/package.json, packages/pieces/community/captain-data/project.json, packages/pieces/community/captain-data/src/index.ts, packages/pieces/community/captain-data/src/lib/actions/get-job-results.ts, packages/pieces/community/captain-data/src/lib/actions/launch-workflow.ts, packages/pieces/community/captain-data/src/lib/common.ts, packages/pieces/community/captain-data/tsconfig.json, packages/pieces/community/captain-data/tsconfig.lib.json, tsconfig.base.json
Add new integration with [Captain Data](https://www.captaindata.co) ([API doc](https://docs.captaindata.co/#intro))
- schedule a workflow
- retrieve results
- custom API call
=> feat(captain-data): schedule workflow and get job results actions

packages/ui/core/nginx.standard.conf
This is not required, It was added because of automated security report, but this is not needed as there is no user information stored in this route or can be cached.
=> fix: remove add pragma no cache

package-lock.json, package.json, packages/pieces/community/actualbudget/.eslintrc.json, packages/pieces/community/actualbudget/README.md, packages/pieces/community/actualbudget/package-lock.json, packages/pieces/community/actualbudget/package.json, packages/pieces/community/actualbudget/project.json, packages/pieces/community/actualbudget/src/index.ts, packages/pieces/community/actualbudget/src/lib/actions/get-accounts.ts, packages/pieces/community/actualbudget/src/lib/actions/get-budget.ts, packages/pieces/community/actualbudget/src/lib/actions/get-categories.ts, packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts, packages/pieces/community/actualbudget/src/lib/actions/import-transactions.ts, packages/pieces/community/actualbudget/src/lib/common/common.ts, packages/pieces/community/actualbudget/src/lib/common/models.ts, packages/pieces/community/actualbudget/tsconfig.json, packages/pieces/community/actualbudget/tsconfig.lib.json, tsconfig.base.json
supports; get accounts, get budget, get categories, import transaction, import transactions as json
Its important to note that the ActualBudget API requires a directory to cache your budget to. 
[link to docs](https://actualbudget.org/docs/api/#connecting-to-a-remote-server) 
[in code](https://github.com/activepieces/activepieces/pull/5093/files#diff-f44f0ad49881fc38926a6682d63f47f9d2a56da825b317a71dc90852be9347a1R6)
Fixes #5092
=> feat(actualbudget): get account / get budget / get categories / import transaction / import transactions actions 

packages/engine/src/lib/helper/trigger-helper.ts, packages/server/api/src/app/flows/flow/flow-service-side-effects.ts, packages/server/api/src/app/flows/flow/flow.service.ts, packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts, packages/server/api/src/app/workers/engine-controller.ts, packages/server/api/src/app/workers/memory/ap-memory-queue.ts, packages/server/api/src/app/workers/memory/memory-queue.ts, packages/server/shared/package.json, packages/server/shared/src/lib/job/index.ts, packages/server/worker/src/lib/api/server-api.service.ts, packages/server/worker/src/lib/trigger/hooks/extract-trigger-payload-hooks.ts, packages/server/worker/src/lib/utils/engine-installer.ts, packages/shared/package.json, packages/shared/src/lib/engine/engine-operation.ts, packages/shared/src/lib/flows/flow.ts
Added a new field called "failureCount" stored in the database to count the number of consecutive failures for every scheduled Job to use it later on removing the stuck job in the queue
=> feat: count the number of consecutive failure for every scheduled Job

packages/server/api/src/app/flows/flow/flow.service.ts
It triggers if the user exceeded the max limit of failures in executing a trigger flow it will stop it and send an email to the user to review the flow, fix it and publish it again
=> fix:  skip updateFailureCount when flow is disabled

packages/pieces/community/intercom/package.json, packages/pieces/community/intercom/src/index.ts, packages/pieces/community/intercom/src/lib/triggers/conversation-assigned.ts, packages/pieces/community/intercom/src/lib/triggers/conversation-closed.ts, packages/pieces/community/intercom/src/lib/triggers/conversation-snoozed.ts, packages/pieces/community/intercom/src/lib/triggers/conversation-unsnoozed.ts, packages/pieces/community/intercom/src/lib/triggers/new-conversation-from-user.ts, packages/pieces/community/intercom/src/lib/triggers/reply-from-admin.ts, packages/pieces/community/intercom/src/lib/triggers/reply-from-user.ts
Add triggers for additional Intercom webhooks:
- new conversation from user
- new reply from user
- new reply from admin
- conversation assigned to admin
- conversation closed
- conversation snoozed
- conversation un-snoozed
=> feat(intercom): add various conversation triggers

.github/workflows/build-cloud-nx.yml
It changes the build cloud nx file to match the new updated template from [nx docs](https://nx.dev/ci/recipes/set-up/monorepo-ci-github-actions)
=> fix: update build cloud nx with the updated template

packages/ui/feature-pieces/src/lib/services/piece.service.ts
This PR makes partial match work for more than 2 characters for piece actions names.
Partial match for searches does not work when there are not at least 4 characters when searching for piece actions keyworks. 
Example:
Fixes #5142
=> fix(piece.service): fix pieces search for action names

packages/pieces/community/clickup/package.json, packages/pieces/community/clickup/src/lib/actions/tasks/create-task.ts
According to [this](https://clickup.com/api/developer-portal/tasks/#using-markdown-in-the-task-description) section of the ClickUp API Docs, we can use `markdown_description` to apply github-style markdown syntax to customize the description. 
I'm not sure if `markdown_description` will overwrite `description` or the other way around. Either way, I made the `description` property optional since it's not required by the ClickUp API. This way the consumer of this piece can choose if they want to use `description` or `markdown_description`
=> feat(clickup): add markdown description option for create task action

package-lock.json, package.json, packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/actions/get-page-or-block-children.ts
Add option to get the markdown content of a page instead of a list of blocks
=> feat(notion): add option to convert page content to markdown

docs/install/options/easypanel.mdx
This warning should be removed as Easypanel supports [the latest version of ActivePieces](https://easypanel.io/docs/templates/activepieces#options)
=> docs: remove easypanel warning

package-lock.json, package.json
This should fix the following error that occurs when running `npm i` inside a dev container:
```
npm ERR! Error: Cannot find module '@nx/nx-linux-arm64-gnu'
```
With these changes you must run `npm i --include=optional` to install the newly added optional NX dependencies.
=> fix: nx native deps not found in dev container

packages/pieces/community/chargekeep/package.json, packages/pieces/community/chargekeep/src/index.ts, packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact-extended.ts, packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact.ts, packages/pieces/community/chargekeep/src/lib/actions/add-or-update-subscription.ts, packages/pieces/community/chargekeep/src/lib/actions/create-invoice.ts, packages/pieces/community/chargekeep/src/lib/common/common.ts, packages/pieces/community/chargekeep/src/lib/triggers/new-lead.ts, packages/pieces/community/chargekeep/src/lib/triggers/new-payment.ts, packages/pieces/community/chargekeep/src/lib/triggers/new-subscription.ts
This pull request involves changes made to chargekeep's authentication which now involves a customAuth with a static dropdown with options to select base environment URL (https://crm.chargekeep.com/ or https://beta.chargekeep.com/) and then the secret key field. Finally, making changes to the actions and triggers, to make use of the base_url selected in the connection, as well as the secret key provided, to make the api calls.
=> fix(chargekeep): updating authentication to customAuth with static dropdown

.github/workflows/automate-deploy.yml, .github/workflows/build-cloud-image.yml, .github/workflows/release-rc.yml, .github/workflows/release.yml
Removes the `ENVIRONMENT` Docker arg. Previously, you could pass `cloud` or `standard`, where it was used to copy the appropriate nginx.{$ENVIRONMENT}.conf file. That was removed in https://github.com/activepieces/activepieces/pull/3379 but the GitHub Actions still referenced it.
=> chore(ci): remove unused ENVIRONMENT build-arg

packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/helper/piece-helper.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/pieces/community/framework/src/lib/context.ts
This PR adds the flow and flow version ID to the PropertyContext. This can be useful if you want to do things dynamically with the flow ID. In my case I want to build an email address that contains the flow ID.
As discussed on Discord: https://discord.com/channels/966798490984382485/1060469824104439838/1268137709818478685
=> feat: added flow context to PropertyContext for use in DynamicProperties

packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/lib/actions/create-issue.ts, packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts, packages/pieces/community/jira-cloud/src/lib/common/index.ts
Repro scenario 1:
1. Create a jira issue
2. Create a jira sub task and enter the issue as parent key
Expected:  sub task created and attached to the parent issue
Actual: error returned "Issue type is a sub-task but parent issue key or id not specified." 
Repro scenario 2:
1. Create a jira epic
2. Create a jira issue and enter the epic as parent key
Expected:  issue created and attached to the epic
Actual: issue created but not attached to the epic
=> feat: support attaching jira tickets to parent epic/task

packages/react-ui/src/components/ui/switch.tsx, packages/react-ui/src/features/pieces/components/piece-icon.tsx
Improve dark mode for switches and piece icons.
Before: 
After:
=> fix(dark): piece icons and switch

docs/install/overview.mdx
Hey all, we're closing down StackSnap, this PR removes instructions for using it.
=> docs: removed stacksnap from overview docs

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/common/props.ts
Dropdowns that use pagination are broken after the first load, i.e. once `after` is set - because `first` is mandatory in this case
https://relay.dev/graphql/connections.htm
=> feat(linear): fix pagination bug

packages/ui/core/proxy.conf.json
Forces node to use ipv4 when proxying in dev mode. [node 17 and above prefers to resolve `localhost` as ipv6](https://github.com/nodejs/node/issues/40537). This causes vite proxy to fail because our backend server is bound to an ipv4 address. The error looks like this
```
[GUI] 4:43:19 PM [vite] http proxy error: /v1/flags
[GUI] Error: connect ECONNREFUSED ::1:3000
[GUI]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```
Notice the `::1` address.
=> fix: Use 127.0.0.1 to fix vite proxy error

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts
Dust.tt made a breaking change to their API - we now must provide a proper mime type
=> feat(dust): add mime type after breaking API change

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/find-user-by-handle.ts, packages/pieces/community/slack/src/lib/actions/set-user-status.ts, packages/pieces/community/slack/src/lib/common/props.ts, packages/pieces/community/slack/src/lib/triggers/new-message.ts
- add action to set the connected user's status
- add action to find a user by Slack handle
- make channel optional for "new message" trigger (to receive messages on **all** public channels)
=> feat(slack): set user's status, find user by slack handle  actions and make channel optional for trigger

packages/pieces/community/image-helper/package.json, packages/pieces/community/image-helper/src/lib/actions/compress-image.actions.ts, packages/pieces/community/image-helper/src/lib/actions/crop-image.action.ts, packages/pieces/community/image-helper/src/lib/actions/resize-Image.action.ts, packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
When users use this action, they can now provide a custom file name for the output image. The image will be saved with the specified name and the correct extension based on the image type.
Fixes #5303 
Changes Made:
New Property: **resultFileName**
Added a **resultFileName** property using **Property.ShortText**
Dynamic File Naming:
The file name used in **context.files.write** is now generated dynamically using the value provided in **resultFileName** and the image extension.
=> fix(image-helper): add custom file name property

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/lib/actions/upload-file.ts
The original piece slack upload-file action doesn't have a channel property. Yes, as stated in [here](https://slack.dev/node-slack-sdk/web-api/#upload-a-file), channel_id argument of slack files.upload function is optional:
"The channel_id and initial_comment aren't required, but the file either won't be shared to a channel or it won't be posted with a message if these aren't included.
In a successful response, the result.files contains an array of [shared files](https://api.slack.com/types/file). These files are "private" and available to just the token holder if no channel_id is included in the request, and are marked "public" when shared to a provided channel_id."
Unfortunately, an upload file by Activepieces slack app without shared to a channel is "private!" There is no way of a …
=> feat(slack): add channel property for upload-file action

packages/react-ui/src/features/pieces/components/piece-icon.tsx
Currently, SVG logos are rendered as 0x0 images. This fix allows it to render while still keeping its size scaled to the parent div.
Before
After
=> fix: svg piece logo rendering at 0x0

packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts, packages/engine/src/lib/variables/variable-service.ts, packages/react-ui/src/features/projects/components/project-switcher.tsx
If the context contains a function, we cannot determine how it could be possible for a piece to return functions in the output.
It will trigger a "cannot be cloned" error since V8 isolates use `structuredClone`. We sanitize it using `JSON.stringify` and `JSON.parse`.
=> fix: empty variable on resolving with v8 isolate

packages/pieces/community/chargekeep/package.json, packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact-extended.ts, packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact.ts, packages/pieces/community/chargekeep/src/lib/actions/create-invoice.ts
This pull request contains updates to the chargekeep module, including fixes to the gender input field and a new helper function.
- Replaced the previous gender input field with a static dropdown for a more standardized and controlled user input experience.
- Introduced a helper function to set default current dates, improving date handling and reducing redundant code.
- Review the changes to the gender input field to ensure the dropdown behaves as expected.
- Verify that the new helper function for default dates works as intended across all relevant parts of the application.
Your feedback and approval are appreciated.
=> fix(chargekeep): update gender input, and add helper function for default date

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/lib/actions/get-question.ts
We want to raise an error when a metabase query (called question in metabase) fails.
=> feat(metabase): raise error when question fails

packages/engine/src/lib/helper/piece-helper.ts, packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
`PieceAuth.OAuth2` will now run the `validate` hook if you provide one. This allows you to run a sanity check before saving the token to the database. For example, many API endpoints provide a `whoami`-type endpoint.
This change brings OAuth2 in line with other auth types that support the validate hook.
In the validate hook, you have full access to the `auth` object, including `access_token` and `props`.
=> feat: add optional validation check to OAuth2

packages/pieces/community/talkable/package.json, packages/pieces/community/talkable/src/lib/actions/coupons/find-coupon.ts, packages/pieces/community/talkable/src/lib/actions/loyalty/get-loyalty-redeem-actions.ts, packages/pieces/community/talkable/src/lib/actions/origins/create-event.ts, packages/pieces/community/talkable/src/lib/actions/origins/create-events-batch.ts, packages/pieces/community/talkable/src/lib/actions/origins/create-purchase.ts, packages/pieces/community/talkable/src/lib/actions/origins/create-purchases-batch.ts, packages/pieces/community/talkable/src/lib/actions/origins/refund.ts, packages/pieces/community/talkable/src/lib/actions/people/anonymize-person.ts, packages/pieces/community/talkable/src/lib/actions/people/find-person.ts, packages/pieces/community/talkable/src/lib/actions/people/unsubscribe-person.ts, packages/pieces/community/talkable/src/lib/actions/people/update-person.ts, packages/pieces/community/talkable/src/lib/actions/referrals/update_referral_status.ts
Removed the 'No Error on Failure' checkbox because it is now included by default for all pieces. 
I've removed the extra checkbox to avoid duplication and maintain a clean interface.
Cleanup
=> chore(talkable): removed 'no error on failure' checkbox property

nginx.react.conf
This was fixed in https://github.com/activepieces/activepieces/pull/5130 but was not backported to `nginx.react.conf`
=> fix: /api/ui loading static assets

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx, packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts, packages/react-ui/src/app/builder/pieces-selector/index.tsx, packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts, packages/react-ui/src/components/ui/card-list.tsx, packages/react-ui/src/components/ui/search-input.tsx, packages/react-ui/src/components/ui/skeleton.tsx, packages/react-ui/src/features/pieces/components/piece-icon-list.tsx, packages/react-ui/src/features/pieces/components/piece-operations-suggestions.tsx, packages/react-ui/src/features/pieces/components/piece-selector-card.tsx, packages/react-ui/src/features/pieces/lib/pieces-api.ts, packages/react-ui/src/features/pieces/lib/pieces-hook.ts, packages/react-ui/src/features/pieces/lib/types.ts, packages/server/api/src/app/authentication/authentication-service/index.ts, packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-service.ts, packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts, packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
The Angular version of the pieces search result included the suggestions (displayed as chips).
It was useful as the results included information such as:
- the action|trigger relevant to the search query
- the name of the piece
The Reactjs re-write no longer includes the suggestions and forces the user to perform an additional click on the piece name to reveal all available actions. To make matter worse, image that the list of available actions is very long and now the user needs to scroll down and find the search query relevant piece.
With this PR the piece search result view will list all piece suggestions together for any given piece (under with piece name), rendering the suggestions as clickable list items. This should simplify selection.
=> feat: improve piece selector experience 

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/common.ts
Allow creation of empty conversations, i.e. placeholders before adding fragments (files) and a query later
=> feat(dust): allow creation of empty conversations

packages/react-ui/src/app/components/sidebar-layout.tsx
On small viewports such as on a mobile device, the project settings is not visible. Even though the layout is not ideal, at least it's usable with this fix.
=> fix: project settings not visible on mobile

packages/engine/src/lib/handler/piece-executor.ts, packages/pieces/community/framework/src/lib/context.ts
In the [Flow Control documentation](https://www.activepieces.com/docs/developers/piece-reference/flow-control), it says Stop Flow can be called without a Response.
```ts
context.run.stop();
```
This PR makes this possible. Previously, you still had to call it with at least an empty response.
```ts
context.run.stop({
response: {}
});
```
=> fix: allow context.run.stop() to be called without params

packages/pieces/community/activepieces/package.json, packages/pieces/community/activepieces/src/index.ts, packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/create-project.ts, packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts, packages/pieces/community/activepieces/src/lib/actions/list-project.ts, packages/pieces/community/activepieces/src/lib/actions/update-project.ts
This is a pr from @AdamSelene, https://github.com/activepieces/activepieces/pull/5710, but I needed to modify properties' order in the piece auth prop.
=> feat(Activepieces): add base url and api key secret

packages/pieces/community/microsoft-onedrive/package.json, packages/pieces/community/microsoft-onedrive/src/index.ts, packages/pieces/community/microsoft-onedrive/src/lib/actions/upload-file.ts
Add support for large file upload using `Upload large files with an upload session` MS OneDrive API. ref.: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online 
Depending on the file buffer size, the piece use simple upload or chunk upload. As been tested with 100MiB, 200MiB and 512MiB file size which should be more then enough in most scenario.
Fixes #5086
=> feat: support large file upload for onedrive 

packages/engine/src/lib/handler/piece-executor.ts, packages/engine/src/lib/helper/trigger-helper.ts, packages/engine/src/lib/variables/variable-service.ts, packages/engine/test/services/variable-service.test.ts, packages/pieces/community/framework/package.json, packages/pieces/community/framework/src/lib/trigger/trigger.ts
If you have auth configured on a piece, but have an action where auth is not defined _and_ `requireAuth: false`, the action is executed with input that is without an `auth` attribute. Executing the action will result in an exception
```
TypeError: Cannot convert undefined or null to object
```
=> fix: handle case when input.auth is undefined

packages/react-ui/src/features/authentication/components/sign-in-form.tsx
Fixing an annoyance where tabbing from username field will go to Forget password? link first. Now it goes from username field, to password, to sign in button.
=> fix: tab order of the sign in field

packages/react-ui/src/app/router/project-route-wrapper.tsx
In the Issues tab, clicking on a table row redirects it to the /projects/:id/runs route but loses all the filters that were set
=> fix: project route redirect not preserving query params

packages/pieces/community/date-helper/package.json, packages/pieces/community/date-helper/src/lib/actions/add-subtract-date.ts, packages/pieces/community/date-helper/src/lib/actions/date-difference.ts, packages/pieces/community/date-helper/src/lib/actions/extract-date-parts.ts, packages/pieces/community/date-helper/src/lib/actions/format-date.ts, packages/pieces/community/date-helper/src/lib/actions/get-current-date.ts, packages/pieces/community/date-helper/src/lib/actions/next-day-of-week.ts, packages/pieces/community/date-helper/src/lib/actions/next-day-of-year.ts
It was missing the unix epoch format, `X`. When running against 0.1.0 of date-helper piece, the result is just X
=> fix(date-helper): extend dayjs with advancedFormat to support X format

packages/react-ui/src/features/authentication/components/sign-in-form.tsx
Fixes a warning on local-dev indicating that an input element is switching from uncontrolled to controlled state by providing a `defaultValues` object to useForm hook which ensures all form input values are initialized.
Reference material [here](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable).
=> fix: uncontrolled to controlled input warning in SignInForm component

packages/server/shared/src/lib/package-manager.ts
Fixes a symlink permission error when developing a piece on Windows. See for example https://github.com/nodejs/node/issues/18518#issuecomment-513866491.
=> fix: symlink permissions error on windows

packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
Long step names grow into the step node. By using `left: 100%` instead of negative `right`, we ensure the label grows to the right.
=> fix: long step name label overlapping the step node

packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
Fixes empty page when user clicks an approval link.
Before:
After:
=> fix: show non-empty page on approval

packages/server/api/src/app/pieces/piece-metadata-service/pieces-builder.ts
It fixes incorrect usage of pino, caught error was not shown.
=> fix: error logging in pieces-builder

packages/pieces/community/file-helper/package.json, packages/pieces/community/file-helper/src/lib/actions/create-file.ts
This PR adds an encoding property to the `createFile` action. We need this to convert base64 to a file. The default is still utf8, so no flows should break because of this PR.
=> feat(file-helper): Add Encoding property to createFile action

packages/pieces/community/confluence/.eslintrc.json, packages/pieces/community/confluence/README.md, packages/pieces/community/confluence/package.json, packages/pieces/community/confluence/project.json, packages/pieces/community/confluence/src/index.ts, packages/pieces/community/confluence/src/lib/actions/get-page-content.ts, packages/pieces/community/confluence/tsconfig.json, packages/pieces/community/confluence/tsconfig.lib.json, tsconfig.base.json
This PR adds confluence to activepieces. The authentication uses a Custom Auth which accepts the account email, the api token tagged to that email, and the confluence domain.
Please follow the atlassian guidelines to add the logo to your CDN. https://atlassian.design/foundations/logos. 
The integration includes the following actions:
- Get Page Content
Connecting / reconnecting credentials:
Get Page Content
=> feat: add basic confluence integration

packages/react-ui/src/features/projects/components/project-switcher.tsx
=> fix: truncate long project names in switcher button

packages/pieces/community/facebook-pages/package.json, packages/pieces/community/facebook-pages/src/index.ts
Issue:
In the below screenshot, the numbering in the markdown is affected due to a missing newline. 
This PR resolves the above issue by adding a new line to the markdown.
=> fix: facebook pages markdown rendering

packages/server/api/src/app/ai/ai-provider-proxy.ts
The proxy now serializes the response based on the original response `content-type` header supporting binary data.
=> feat: support proxy binary data

packages/pieces/community/shopify/package.json, packages/pieces/community/shopify/src/index.ts, packages/pieces/community/shopify/src/lib/common/index.ts
Current implementation of Shopify Get Products only fetch the first 50 products. I don't think this is the expected behavior. This PR add pagination support to this Action.
=> feat(shopify): handle pagination to get shopify products

packages/pieces/community/file-helper/package.json, packages/pieces/community/file-helper/src/index.ts, packages/pieces/community/file-helper/src/lib/actions/change-file-encoding.ts, packages/pieces/community/file-helper/src/lib/actions/create-file.ts, packages/pieces/community/file-helper/src/lib/common/encodings.ts
This adds an action that allows converting the encoding of a file.
I needed that because it is not possible to do that within the `code` action itself, since I could not import any node or browser package from it.
=> feat(file-helper): added an action to convert the encoding

packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts, packages/server/api/src/app/database/migration/postgres/1731711188507-AddAuditLogIndicies.ts
A few of the migration files had references to the public schema. For any deployments running Activepieces in another schema this causes the app to not start due to the migrations failing during startup.
=> fix: remove public schema reference from migration files

packages/pieces/community/gmail/package.json, packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Allows usage of custom sender email addresses configured in one's Gmail account
If the email is incorrect / not configured, then Gmail will automatically use the account's primary email - the task will NOT fail
=> feat(gmail): allow custom from address

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/move-file.ts
Option to support all drives ("team drives" in legacy terms) was not passed to the SDK
=> feat(google-drive): add option to support all drives when moving a file

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/move-file.ts
`parents` is not returned by default by the `files.get` endpoint, so we were always passing `undefined` to the `files.update` call - leading to a 400 error when trying to move the file to a subdirectory (and probably to any directory)
=> fix(google-drive): files could not be moved

packages/pieces/community/dropbox/package.json, packages/pieces/community/dropbox/src/lib/actions/upload-file.ts
It is currently impossible to upload a file in Dropbox using AP if its path contains accented characters.
Dropbox's API does not support UTF-8 characters so they need be encoded a specific way. The encoding code can be found here https://www.dropbox.com/developers/reference/json-encoding
This changes applies the proposed JS code to the `path` property.
=> fix(dropbox): fix support of accented characters in path property

packages/pieces/community/mysql/package.json, packages/pieces/community/mysql/src/index.ts
This pull request removes the requirement for the database field during authentication in the MySQL piece. By making the database field optional, users can now authenticate without specifying a database when using the “Execute Query” action. This enhancement facilitates access to multiple databases on a single MySQL server using a single set of credentials, eliminating the need to manage multiple authentications dynamically.
1. Removed the required property from the database field in the authentication settings.
2. Updated the database field description from: “The name of the database to use” to “The name of the database to use. Required if you are not using the ‘Execute Query’ Action”.
We have thoroughly tested other actions that require the database to be defined, including:
•	getTables …
=> feat(mysql): Allow MySQL Piece Authentication Without Specifying a Database for ‘Execute Query’ Action

docs/embedding/overview.mdx, docs/install/options/elestio.mdx
As mentioned in title, two small typos are fixed on docs. @AshrafSam promised an activepieces hoodie for this
=> docs: fix two minor typos in docs

packages/pieces/community/instasent/package.json, packages/pieces/community/instasent/src/index.ts, packages/pieces/community/instasent/src/lib/actions/add-or-update-contact.ts
Added a new instant parameter that allows immediate contact creation/update instead of queueing. This is useful for scenarios where users need to add events right after creating/updating a contact.
Changes:
- Added instant checkbox property
- Modified endpoint URL to include ?_sync parameter when instant is enabled
=> feat(instasent): add instant parameter to add/update contact action

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/helpers/index.ts, packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
1. add optional `extraProps` to `createCustomApiCallAction` helper and pass it to `authMapping`
2. update Slack piece: add "Use user token" checkbox to be able to call methods that require a user token (instead of a bot token) or behave differently
=> feat: add optional extra props for custom API call

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/lib/actions/get-question.ts
Allow using full path parameter of a metabase question, e.g. `1234-my-awesome-question` instead of just the ID, e.g. `1234` - in order to avoid surprises for flow builders
=> feat(metabase): allow full question id

packages/pieces/community/customer-io/package.json, packages/pieces/community/customer-io/src/lib/actions/create_event.ts
We don't want to send the customer identifier (email or ID) as event ID because CustomerIO would treat it as a duplicate
https://docs.customer.io/api/track/#operation/track
> An identifier used to deduplicate events. This value must be a ULID. If an event has the same value as an event we previously received, we won't show or process the duplicate. Note - our Python and Ruby libraries do not pass this id.
> An identifier used to deduplicate events. This value must be a [ULID](https://github.com/ulid/spec). If an event has the same value as an event we previously received, we won't show or process the duplicate. Note - our Python and Ruby libraries do not pass this id.
=> fix(customerio): don't send customer identifier as event id

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
Adds the `includeTrashed` option to the `googleDriveListFiles` action. The minor version of the Piece has been updated, since  `includeTrashed` now defaults to false, which is a breaking change. It now also returns the `trashed` field, so the user knows which files are trashed.
=> feat(google-drive): add includeTrashed option to googleDriveListFiles action

packages/server/api/src/app/database/migration/postgres/1734418823028-CreateProjectReleaseTable.ts
Removes the reference to the public schema in a recent migration file.
=> remove public schema from migration file.

packages/pieces/community/spotify/package.json, packages/pieces/community/spotify/src/index.ts, packages/pieces/community/spotify/src/lib/actions/get-saved-tracks.ts, packages/pieces/community/spotify/src/lib/actions/index.ts, packages/pieces/community/spotify/src/lib/common/client.ts, packages/pieces/community/spotify/src/lib/common/index.ts
Add a new Action to the Spotify Piece for fetching a list of the user's saved tracks, as this can't be done with the existing 'Get Playlist Items' endpoint.
Closes #6462
=> feat(spotify): get saved tracks action

packages/pieces/community/spotify/package.json, packages/pieces/community/spotify/src/lib/actions/get-playlist-items.ts, packages/pieces/community/spotify/src/lib/actions/get-playlists.ts
Fix incorrect labels for 'Offset' fields for certain Spotify Actions.
Fixes #6460
=> fix(spotify): spotify offset labels

packages/pieces/community/crypto/package.json, packages/pieces/community/crypto/src/index.ts, packages/pieces/community/crypto/src/lib/actions/hash-text.ts, packages/pieces/community/nocodb/package.json, packages/pieces/community/nocodb/src/lib/actions/create-record.ts, packages/pieces/community/nocodb/src/lib/actions/delete-record.ts, packages/pieces/community/nocodb/src/lib/actions/get-record.ts, packages/pieces/community/nocodb/src/lib/actions/search-records.ts, packages/pieces/community/nocodb/src/lib/actions/update-record.ts, packages/pieces/community/nocodb/src/lib/common/client.ts, packages/pieces/community/nocodb/src/lib/common/index.ts
This PR fixes compatibility issues with self-hosted versions of NocoDB by addressing the following:
Removes dependency on workspaces: Self-hosted versions of NocoDB do not support the workspace function, so this update eliminates the necessity of having a workspace to retrieve a base.
Adds API version selection: Users can now select which version of the NocoDB API they are using, ensuring compatibility with various versions.
Fixes # ( added compatibility with self-hosted versions)
=> fix(nocoDB): added compatibility with self-hosted versions

packages/pieces/community/krisp-call/package.json, packages/pieces/community/krisp-call/src/lib/triggers/index.ts
What does this PR do?
This PR introduces a outbound sms/mms  trigger for the krisp-call pieces. It adds functionality to monitor and record outbound sms /mms, enhancing the system's ability to log and track call activities effectively.
Fixes
Fixes # (link to the issue, if applicable).
Motivation and Context
The addition of the outbound sms/mms trigger is crucial for improving sms or mms analytics and debugging capabilities. By capturing detailed call events, this update will enable better monitoring and reporting of sms/mms activities within the krisp-call module.
Dependencies
No additional dependencies are required for this change (or list any required).
=> feat(krisp-call): new outbound sms/mms trigger

packages/pieces/community/snowflake/package.json, packages/pieces/community/snowflake/src/index.ts, packages/pieces/community/snowflake/src/lib/actions/run-multiple-queries.ts
Enhances the Snowflake piece by:
- Adding support for executing multiple SQL queries sequentially
- Introducing optional transaction handling (configurable via checkbox)
- Automatic rollback on failure when transactions are enabled
- Returning results for each executed query
=> feat: add multi-query transaction support to snowflake piece

packages/pieces/community/confluence/package.json, packages/pieces/community/confluence/src/lib/actions/get-page-content.ts
Fetches a page content and its children recursively. Children's page content is nested in `children` property
=> feat(confluence): improve get-page-content to fetch recursive children

packages/react-ui/src/app/builder/builder-flow-status-section/view-draft-or-edit-flow-button.tsx
=> fix: show (Edit Flow) button when user is testing a flow that hasn't been published

packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
Remove justyf-center as it contains a typo. However, fixing the typo to justify-center causes unwanted styling changes by centering the title, which does not match the rest of the design.
=> fix: remove justyf-center 

docs/handbook/customer-support/handle-requests.mdx, packages/pieces/community/respaid/.eslintrc.json, packages/pieces/community/respaid/README.md, packages/pieces/community/respaid/package.json, packages/pieces/community/respaid/project.json, packages/pieces/community/respaid/src/index.ts, packages/pieces/community/respaid/src/lib/actions/create_new_campaign.ts, packages/pieces/community/respaid/src/lib/actions/index.ts, packages/pieces/community/respaid/src/lib/actions/stop_collection_client_paid_directly.ts, packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_instalment_payment.ts, packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_partial_payment.ts, packages/pieces/community/respaid/src/lib/common/index.ts, packages/pieces/community/respaid/src/lib/triggers/index.ts, packages/pieces/community/respaid/src/lib/triggers/new_campaign_creation.ts, packages/pieces/community/respaid/src/lib/triggers/new_cancelled_case.ts, packages/pieces/community/respaid/src/lib/triggers/new_disputed_case.ts, packages/pieces/community/respaid/src/lib/triggers/new_payout.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_legal_officer.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_respaid.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_installment_payment_via_respaid.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_to_creditor.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_via_respaid.ts, packages/pieces/community/respaid/tsconfig.json, packages/pieces/community/respaid/tsconfig.lib.json, tsconfig.base.json
This PR adds new actions and triggers for Respaid integration, including:
- Webhook triggers (`new_payout`, `new_campaign_creation`, etc.)
- API actions for managing workflows
=> feat(respaid): add actions and triggers v0

packages/pieces/community/respaid/package.json, packages/pieces/community/respaid/src/lib/common/index.ts, packages/pieces/community/respaid/src/lib/triggers/new_campaign_creation.ts, packages/pieces/community/respaid/src/lib/triggers/new_cancelled_case.ts, packages/pieces/community/respaid/src/lib/triggers/new_disputed_case.ts, packages/pieces/community/respaid/src/lib/triggers/new_payout.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_legal_officer.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_respaid.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_installment_payment_via_respaid.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_to_creditor.ts, packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_via_respaid.ts
Ensure `context.payload.body` is parsed correctly, handling both stringified and object formats. 
Added a fallback to return the original payload if parsing fails.
=> fix(trigger): handle JSON parsing for webhook payload

packages/cli/package.json, packages/cli/src/lib/commands/publish-piece.ts, packages/cli/src/lib/commands/sync-pieces.ts, packages/cli/src/lib/utils/piece-utils.ts
This PR adds an optional `fail-on-error` flag to both the `sync-pieces` and `publish-piece` commands that changes how publishing failures are handled.
Currently, when running these commands, the process continues and exits with a status code of 0 (success) even if piece publishing fails. This means:
- CI pipelines continue to subsequent steps despite publishing failures 
- Package registry updates can proceed even when AP updates have failed
- There's potential for version mismatches between AP and package registries
Added a new `fail-on-error` flag that:
- Causes the process to exit with a non-zero status code if any piece fails to publish
- Enables CI pipelines to halt on publishing failures
- Prevents package registry updates when AP synchronization fails
This change helps maintain …
=> feat: Adding `fail-on-error` flag for `sync-pieces` and `publish-piece` tasks

packages/react-ui/src/features/flows/components/rename-flow-dialog.tsx
=> fix: make rename flow dialog default to the current flow name

packages/pieces/community/cloutly/.eslintrc.json, packages/pieces/community/cloutly/README.md, packages/pieces/community/cloutly/package.json, packages/pieces/community/cloutly/project.json, packages/pieces/community/cloutly/src/index.ts, packages/pieces/community/cloutly/src/lib/actions/send-review-invite.ts, packages/pieces/community/cloutly/tsconfig.json, packages/pieces/community/cloutly/tsconfig.lib.json, tsconfig.base.json
- PR introduces new community piece: `cloutly`
- Piece action: `SendReviewInvite` will send an email/SMS to review the business on Google/Facebook via the Cloutly Platform.
- Cloutly platform: https://cloutly.com/
- API docs: https://support.cloutly.com/en/article/getting-started-with-rest-api-k79sfu/#1-post-send-review-invite
- Cloutly has numerous integrations so it would be great to add this to the growing list in activepieces.
Fixes # N/A
=> feat(cloutly): send review invite action

packages/pieces/community/firecrawl/.eslintrc.json, packages/pieces/community/firecrawl/README.md, packages/pieces/community/firecrawl/package.json, packages/pieces/community/firecrawl/project.json, packages/pieces/community/firecrawl/src/index.ts, packages/pieces/community/firecrawl/src/lib/actions/extract-with-prompt.ts, packages/pieces/community/firecrawl/src/lib/actions/extract-with-schema.ts, packages/pieces/community/firecrawl/tsconfig.json, packages/pieces/community/firecrawl/tsconfig.lib.json, tsconfig.base.json
Adds firecrawl extraction actions - https://docs.firecrawl.dev/introduction#extraction
=> feat(firecrawl): add extract with prompt and schema

packages/server/api/src/app/file/file.service.ts, packages/server/api/src/app/flows/step-run/sample-data.service.ts
=> fix: stop throwing errors when (fetching dropdown data or saving step testing result) if sample data file is not found.

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
Add missing scope to get the members of a Slack user group 
(courtesy of @kylieatalan)
=> feat(slack): add usergroups:read Slack permission

packages/server/api/src/app/file/step-file/step-file.controller.ts
See https://fastify.dev/docs/latest/Reference/Reply/#headerkey-value
The error in our logs:
```json
{
"level": 40,
"time": 1741003493410,
"pid": 10,
"hostname": "secret",
"reqId": "secret",
"req": {
"method": "GET",
"url": "/v1/step-files/signed?token=verysecret",
"hostname": "flowbuilder.secret",
"remoteAddress": "127.0.0.1",
"remotePort": 44938
},
"res": {
"statusCode": 500
},
"err": {
"type": "TypeError",
"message": "Invalid character in header content [\"content-disposition\"]",
"stack": "TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"content-disposition\"]\n    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)\n    at new NodeError (node:internal/errors:405:5)\n    at __node_internal_ (node:_http_outgoing:635:11)\n    at storeHeader …
```
=> fix: missing encoding in Content-Disposition header when downloading step files

packages/pieces/community/linear/package.json, packages/pieces/community/linear/src/lib/triggers/updated-issue.ts
Make the `team_id` optional for the trigger Linear Issue update to listen to any team for a given automation.
The issue update is triggered with no team selected
=> feat(linear): set team_id optional on linear issue update trigger

packages/react-ui/src/app/builder/piece-properties/array-property.tsx, packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx, packages/react-ui/src/app/routes/platform/security/sso/allowed-domain.tsx, packages/react-ui/src/app/routes/platform/security/sso/oauth2-dialog.tsx, packages/react-ui/src/app/routes/platform/security/sso/saml-dialog.tsx, packages/react-ui/src/app/routes/platform/setup/ai/copilot/configure-provider-dialog.tsx, packages/react-ui/src/app/routes/platform/setup/ai/copilot/index.tsx, packages/react-ui/src/app/routes/platform/setup/ai/index.tsx, packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx, packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx, packages/react-ui/src/lib/platforms-api.ts, packages/react-ui/vite.config.ts, packages/server/api/src/app/platform/platform.controller.ts, packages/server/api/src/app/platform/platform.service.ts, packages/server/worker/package.json, packages/shared/package.json, packages/shared/src/lib/federated-authn/index.ts, packages/shared/src/lib/platform/platform.model.ts
1) We now don't pass the client secret for SSO to the frontend, so if someone has SAML and Google activated and edits one of them the other one will be broken.
2) Vite will not build if there are typescript related issues in React from now on.
=> fix: saving SSO providers + show trial license key expiration date

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-dashboard.ts
- Implements a new action that executes all questions in a Metabase dashboard with user-provided parameters and returns their results in a single response.
- The action takes a dashboard ID and parameters object, then returns results indexed by card ID for easy access and further processing.
=> feat: add Metabase get dashboard questions action

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts, packages/pieces/community/slack/src/lib/actions/get-file.ts, packages/pieces/community/slack/src/lib/triggers/new-command.ts
A different variation of `New mention` that only triggers on specific command, and can handle the arguments after the command. This prevents the need for users to write custom code to parse the slack message.
=> feat(slack): new command trigger and get file action

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts, packages/pieces/community/http/package.json
The `HTTP (Send HTTP request)` action does not support sending query params in an array style eg. `https://httpbin.org/get?ids[]=1&ids[]=2`. It ends up only sending the last element `ids[]=2` even when providing the query params explicitly on the URL.
Currently the httpClient extracts url params from the url (type `URLSearchParams`), then merges that into the provided query parameters (type `Record`/object). `URLSearchParams` supports duplicate keys but `Record` doesn't. This is passed into [`AxiosRequestConfig.params`](https://axios-http.com/docs/req_config) which supports either a plain object or a URLSearchParams object.
This PR merges the provided query params into the `URLSearchParams` object instead, supporting duplicate keys like `ids[]`.
- This should be backwards compatible for …
=> fix: support duplicate query params for arrays

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/common.ts
Dust changed their API to return an error **object** instead of a simple message
=> fix(dust): update Dust error format after API change

packages/pieces/community/pdf/package.json, packages/pieces/community/pdf/src/lib/actions/image-to-pdf.ts
There is a minor bug where the image-to-pdf action wrongly rejects valid files because the extension check is case sensitive.
eg. trying to convert `test.PNG` fails with this error but lowercasing the extension (`test.png`) passes
```
Failed to convert text to PDF: Unsupported image format: PNG
```
This PR normalizes the extension to lowercase when doing the check
=> fix: image to pdf extension check

packages/pieces/community/sftp/package.json, packages/pieces/community/sftp/src/index.ts
This MR adds a checkbox to the SFTP auth that allows to connect to ftps server with a self-signed certificate. It now also returns the actual error when the connection fails, instead of a fixed message without a real cause.
=> feat(sftp): add option to allow connecting to ftps server with a self-signed certificate

packages/server/api/src/app/webhooks/webhook-controller.ts, packages/shared/src/lib/engine/engine-operation.ts
We need the `rawBody` if we want to perform e.g. signature verification when receiving an webhook payload (for `WEBHOOK` triggers)
=> feat: add rawBody to webhook trigger payload

packages/pieces/community/personal-ai/.eslintrc.json, packages/pieces/community/personal-ai/.gitignore, packages/pieces/community/personal-ai/README.md, packages/pieces/community/personal-ai/package.json, packages/pieces/community/personal-ai/project.json, packages/pieces/community/personal-ai/src/index.ts, packages/pieces/community/personal-ai/src/lib/actions/ai_interaction/create-chatgpt-instruction.ts, packages/pieces/community/personal-ai/src/lib/actions/ai_interaction/create-custom-training.ts, packages/pieces/community/personal-ai/src/lib/actions/documents/get-document.ts, packages/pieces/community/personal-ai/src/lib/actions/documents/update-document.ts, packages/pieces/community/personal-ai/src/lib/actions/documents/upload-document.ts, packages/pieces/community/personal-ai/src/lib/actions/documents/upload-file.ts, packages/pieces/community/personal-ai/src/lib/actions/documents/upload-url.ts, packages/pieces/community/personal-ai/src/lib/actions/memory/create-memory.ts, packages/pieces/community/personal-ai/src/lib/actions/messaging/create-message.ts, packages/pieces/community/personal-ai/src/lib/actions/messaging/get-conversation.ts, packages/pieces/community/personal-ai/tsconfig.json, packages/pieces/community/personal-ai/tsconfig.lib.json, tsconfig.base.json
Personal AI offers a piece for creating customized AI personas trained on proprietary data, enhancing team efficiency and collaboration. 
Ingestion API: Facilitates the import of data from diverse sources to train Personal AI models.
Inference API: Enables interaction with trained AI models by posing questions and receiving responses.
AI-native Messaging API: Allows seamless incorporation of Personal AI into websites or applications for enhanced communication.
AI Message Endpoint: Supports sending messages to AI personas and receiving contextually relevant replies.
Upload URL Endpoint: Permits uploading content from URLs to enrich the AI's memory.
Depends on: https://github.com/activepieces/activepieces/pull/6946 PR
=> feat: add personal ai piece

packages/pieces/community/anyhook-graphql/.eslintrc.json, packages/pieces/community/anyhook-graphql/README.md, packages/pieces/community/anyhook-graphql/package.json, packages/pieces/community/anyhook-graphql/project.json, packages/pieces/community/anyhook-graphql/src/index.ts, packages/pieces/community/anyhook-graphql/src/lib/common/common.ts, packages/pieces/community/anyhook-graphql/src/lib/triggers/graphql-subscription-trigger.ts, packages/pieces/community/anyhook-graphql/src/lib/triggers/helpers.ts, packages/pieces/community/anyhook-graphql/tsconfig.json, packages/pieces/community/anyhook-graphql/tsconfig.lib.json, packages/pieces/community/anyhook-websocket/.eslintrc.json, packages/pieces/community/anyhook-websocket/README.md, packages/pieces/community/anyhook-websocket/package.json, packages/pieces/community/anyhook-websocket/project.json, packages/pieces/community/anyhook-websocket/src/index.ts, packages/pieces/community/anyhook-websocket/src/lib/common/common.ts, packages/pieces/community/anyhook-websocket/src/lib/triggers/helpers.ts, packages/pieces/community/anyhook-websocket/src/lib/triggers/websocket-subscription-trigger.ts, packages/pieces/community/anyhook-websocket/tsconfig.json, packages/pieces/community/anyhook-websocket/tsconfig.lib.json, tsconfig.base.json
This PR introduces two new integrations for AnyHook, an open-source real-time proxy server that connects data sources like GraphQL and WebSocket to webhook endpoints.
- **Categories**: Developer Tools, Real-Time Data, Integration Platforms
- **Pieces**:
- **AnyHook GraphQL**: Subscribe to GraphQL subscription events
- **AnyHook WebSocket**: Subscribe to WebSocket events
These integrations allow Activepieces users to:
- Connect to real-time data sources through the AnyHook proxy server
- Trigger workflows based on GraphQL subscription events
- Trigger workflows based on WebSocket messages
- Simplify real-time data integration into automation workflows
These integrations require a running instance of the [AnyHook proxy server](https://github.com/SwanBlocks-inc/anyhook) which needs to be …
=> feat(pieces): AnyHook Integration for Activepieces (GraphQL & WebSocket)

packages/server/api/src/app/database/migration/postgres/1732324567513-AddIndiciesToRunAndTriggerData.ts, packages/server/api/src/app/database/migration/postgres/1734355488179-TablesProduct.ts, packages/server/api/src/app/database/migration/postgres/1734969829406-FieldAndRecordAndCell_ProjectId.ts, packages/server/api/src/app/database/migration/postgres/1734971881345-AddPlatformBilling.ts, packages/server/api/src/app/database/migration/postgres/1735057498882-AddCellUniqueIndex.ts, packages/server/api/src/app/database/migration/postgres/1741669458075-CreateTableWebhooks.ts, packages/server/api/src/app/database/migration/postgres/1742304857701-AddManualTaskTable.ts, packages/server/api/src/app/database/migration/postgres/1742305104390-AddManualTaskCommentTable.ts, packages/server/api/src/app/database/migration/postgres/1742433144687-ChangeManualTasksCommentsToTodoComments.ts
The migrations file had several references to the public schema. This causes issues when being run in a schema other than public.
=> Removed all references to the public schema in migrations

packages/pieces/community/messagebird/package.json, packages/pieces/community/messagebird/src/index.ts, packages/pieces/community/messagebird/src/lib/actions/send-sms.action.ts, packages/pieces/community/messagebird/src/lib/auth.ts
Messagebird has [rebranded](https://techcrunch.com/2024/02/01/messagebird-rebrands-as-bird-and-slashes-prices-by-90-on-sms-to-take-on-twilio/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAACaAaN8j5mlMDWpYoL0aJbER5NB48Qq_0ctCOaAucrUCqigukAOaFFzz3aCF-1e_GxCJBojXGjJlgr1MCnznFlb6_HPfY7rzYPxAR5HuPWni80qaJONozb_iyoWltSsi_-O8wudshhB5YRTnsmEWsbYcBq4KVydYsvbU-r6TKj6h) to Bird and the original piece is broken if you were trying to use it against the new APIs.
I have fixed it so that the `send-sms` will successfully work with the new APIs.
=> fix(bird): fix messagebird for new APIs

packages/server/api/src/app/app.ts
This PR fixes a missing await when calling `domainHelper.getPublicApiUrl()`
=> fix: add missing await to domainHelper.getPublicApiUrl call

packages/pieces/community/google-slides/package.json, packages/pieces/community/google-slides/src/index.ts, packages/pieces/community/google-slides/src/lib/actions/generate-from-template.ts, packages/pieces/community/google-slides/src/lib/actions/get-presentation.ts, packages/pieces/community/google-slides/src/lib/actions/refresh-charts.ts, packages/pieces/community/google-slides/src/lib/commons/common.ts
Create new actions for GSlide: get, generated from template and refresh charts.
Fixes Q-1118
They can refresh all charts in a presentation easily.
They can generate a new presentation from a template and directly fill the value.
=> feat(gslide): create from template, get presentation and refresh sheets charts actions

packages/server/api/src/app/database/migration/postgres/1743128816786-AddMCP.ts
Removes additional public schema references in a migration file.
=> chore: removed public schema references

packages/pieces/community/rounded-studio/.eslintrc.json, packages/pieces/community/rounded-studio/README.md, packages/pieces/community/rounded-studio/package.json, packages/pieces/community/rounded-studio/project.json, packages/pieces/community/rounded-studio/src/index.ts, packages/pieces/community/rounded-studio/tsconfig.json, packages/pieces/community/rounded-studio/tsconfig.lib.json, tsconfig.base.json
Adds a new activepieces piece for [Rounded Studio](https://rounded.studio/) which allows only for a Custom API Call.
Fixes Q-1278
=> feat(rounded-studio): add piece with custom api call action

packages/pieces/community/intercom/src/lib/triggers/conversation-part-tagged.ts
The "conversation tagged" trigger test data had the wrong payload format, possibly because of an intercom API change
Similar to what I did for Slack a few PRs ago, I simply removed the static test data and `test` method so that we can use the built in trigger simulation (and receive real payloads)
I **think** it should be the case for all triggers but this time I only did it for one
=> fix(intercom): remove wrong test data for trigger

packages/pieces/community/common/package.json, packages/pieces/community/common/src/lib/ai/providers/openai/index.ts, packages/pieces/community/text-ai/package.json, packages/pieces/community/utility-ai/package.json
Adds support for new OpenAI GPT-4.1 models — including GPT-4.1, GPT-4.1 Mini, and GPT-4.1 Nano — in AI Pieces (Text AI and Utility AI).
Fixes #7379
=> feat: add gpt 4.1 models

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/index.ts, packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
Add a new action for metabase that allows to get the graph of a question and download it.
This is only a V1 and we might change the way we do that by parsing the HTML later. I'm waiting confirmations to know if this is enough.
There's already an action for that, but the result and method are different. Let's keep both actions until this one works perfectly.
For that we need an embedding key and that the question is embed (only possible with an admin).
I put the embedding key as a ShortText instead of a SecretText because SecretText are all mandatory (even if the required is false). But by doing this, the field isn't hidden with dots, can be an issue.
Fixes Q-1275
=> feat(metabase): new action get graph

packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
=> fix: stop logging axios errors fully in invalid oauth2 calim failure

packages/server/worker/src/lib/engine/threads/worker.ts
The missing resolve is causing one time jobs to hang and stuck for ever.
=> fix: add missing resolve when internal error happens in the flow

package-lock.json, package.json, packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/index.ts, packages/pieces/community/dust/src/lib/actions/create-conversation.ts, packages/pieces/community/dust/src/lib/actions/upload-file.ts, packages/pieces/community/dust/src/lib/common.ts
Add support for [Dust's file upload](https://docs.dust.tt/reference/post_api-v1-w-wid-files).
A new piece allows uploading a file, and uploads it to Dust, using its official SDK. As a result, the uploaded file can be referenced in downstream pieces.
The file upload concept is replacing the fragment one on Dust's side. For now we are keeping support for both.
The "create conversation" piece is also updated so we can reference a previously uploaded file (instead of fragment's content)
Also took the opportunity to use the official Dust JS SDK (instead of direct API calls). I only migrated a couple of calls though.
Getting a file/image (from a webhook, a form, ...) and using it as part of a conversation with an assistant on Dust
=> feat(dust): upload file piece

packages/pieces/community/google-slides/package.json, packages/pieces/community/google-slides/src/lib/actions/generate-from-template.ts, packages/pieces/community/google-slides/src/lib/commons/common.ts
Add a new props placeholder that will allow the user to choose between {{}} and [[]] for the variables of the template.
Also manage to also detect and change the variables in tables.
Fixes Q-1319
=> feat(Gslide): generate from template new props placeholder

packages/pieces/community/straico/package.json, packages/pieces/community/straico/src/index.ts, packages/pieces/community/straico/src/lib/actions/agent-add-rag.ts, packages/pieces/community/straico/src/lib/actions/agent-create.ts, packages/pieces/community/straico/src/lib/actions/agent-delete.ts, packages/pieces/community/straico/src/lib/actions/agent-get.ts, packages/pieces/community/straico/src/lib/actions/agent-list.ts, packages/pieces/community/straico/src/lib/actions/agent-prompt-completion.ts, packages/pieces/community/straico/src/lib/actions/agent-update.ts, packages/pieces/community/straico/src/lib/common/props.ts
This PR adds a new Agent system to the Straico piece in ActivePieces, allowing users to create and manage AI agents with RAG (Retrieval-Augmented Generation) capabilities.
The feature consists of several actions:
1. Create Agents
- Set up new agents with custom prompts and models
- Add tags for organization
2. Add RAG
- Connect agents to RAG models
- Enable document-aware responses
3. Use Agents
- Send prompts to agents
- Configure search settings
- Get responses with document references
4. Manage Agents
- List, view, update, and delete agents
- Control visibility and status
- Knowledge Assistant
- Team Setup
- Document Q&A
=> feat(straico): add new agent actions

packages/pieces/community/apitable/package.json, packages/pieces/community/apitable/src/index.ts
AITable has changed its base API URL from `https://api.aitable.ai` to `https://aitable.ai`.
=> fix(apitable): fix API baseurl

packages/pieces/community/google-docs/package.json, packages/pieces/community/google-docs/src/index.ts, packages/pieces/community/google-docs/src/lib/actions/create-document-based-on-template.action.ts
We allow the user to choose the placeholder he wants for the google doc edit action. It will be "[[]]" by default and he can also choose "{{}}".
Fixes Q-1269
=> feat(google-docs): add placeholder format choice for edit action

packages/pieces/community/dappier/.eslintrc.json, packages/pieces/community/dappier/README.md, packages/pieces/community/dappier/package.json, packages/pieces/community/dappier/project.json, packages/pieces/community/dappier/src/index.ts, packages/pieces/community/dappier/src/lib/actions/lifestyle-news.ts, packages/pieces/community/dappier/src/lib/actions/real-time-data.ts, packages/pieces/community/dappier/src/lib/actions/sports-news.ts, packages/pieces/community/dappier/src/lib/actions/stock-market-data.ts, packages/pieces/community/dappier/src/lib/common/index.ts, packages/pieces/community/dappier/tsconfig.json, packages/pieces/community/dappier/tsconfig.lib.json, tsconfig.base.json
[Dappier](https://dappier.com/) connects any LLM or your Agentic AI to real-time, rights-cleared, proprietary data from trusted sources, making your AI an expert in anything. Our specialized models include Real-Time Web Search, News, Sports, Financial Stock Market Data, Crypto Data, and exclusive content from premium publishers. Explore a wide range of data models in our marketplace at [marketplace.dappier.com](https://marketplace.dappier.com/)
This PR adds support for the **Dappier** integration to Activepieces, including 4 new actions that allow users to access real-time and personalized content across various domains directly within their workflows.
The new actions include:
* **Real-Time Web Search** – Access real-time google web search results including the latest news, weather, …
=> feat: add dappier piece

packages/pieces/community/dust/package.json, packages/pieces/community/dust/src/lib/actions/upload-file.ts
In https://github.com/activepieces/activepieces/pull/7518, I introduced a new piece to be able to upload a file to Dust. I wrongly tested on Node 20, while ActivePieces is still on Node 18.
the `new File` API doesn't exist in Node v18, so the piece is broken
This PR handles compatibility with Node v18 by switching to the `FormData` API in order to create the `File`.
Tested locally with the right version of Node this time
=> fix(dust): uploadFile piece compatibility with node v18

packages/pieces/community/metabase/package.json, packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
When using playwright to go to the iframe of a metabase graph, it doesn't let enough time for the graph to load so it only screens a loading page. Added a property wait time for the timeout.
=> feat(metabase): add timeout so graph can load

packages/server/api/src/app/database/redis-connection.ts
When using a Sentinel setup for Redis database connections, the database might require a username (depending on Redis configuration)
The (already existing) `REDIS_USER` environment variable is read and passed to the `RedisOptions` object. The variable is optional.
reference: https://github.com/redis/ioredis/blob/main/lib/redis/RedisOptions.ts 
A Redis sentinel setup where the database configuration requires password AND username.
Fixes #7722
=> fix: add username to redis sentinel setup

package-lock.json, package.json, packages/pieces/community/dust/package.json
When we started to use the SDK, we broke the possibility to create empty conversations (i.e. placeholders) because the then-current version enforced a mandatory `message` - whereas the API has no such requirement
Dust just released version 1.0.49 which fixes this discrepancy
=> feat(dust): bump dust SDK version to re-allow creating conversation with empty messages

packages/engine/src/lib/variables/processors/text.ts, packages/pieces/community/store/package.json, packages/pieces/community/store/src/lib/actions/store-append-action.ts
This was added recently for optional strings as they should be undefined and not empty for actions like update deal on husbpot, but this broke the storage (append action), the empty string used to work and it no longer does.
=> fix: update textProcessor to handle empty values of required strings

packages/pieces/community/returning-ai/package.json, packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
This PR enhances the Returning AI integration by adding support for sending messages to forum channels. It introduces dynamic fields based on channel type, specifically adding support for forum channels with topic ID selection.
The feature extends the existing "Send Message" action to handle different channel types:
1. When a user selects a channel, the system now checks the channel type
2. For forum channels, an additional "Topic ID" field appears dynamically
3. The message can then be sent to a specific topic within the forum channel
The implementation:
- Adds channel type information to the channel selection dropdown
- Introduces dynamic properties that show/hide fields based on channel type
- Modifies the API request to include forum-specific parameters when needed
1. **Forum …
=> feat(returning-ai): add forum channel send message action

packages/react-ui/src/app/mcp/mcp-piece-tool-dialog/index.tsx
This PR addresses a UI bug where the "Add Tool" dialog in the MCP section would overflow the screen on smaller viewports, making parts of the modal inaccessible. The fix ensures the modal respects screen boundaries across devices, enhancing the overall user experience.
The modal's styling was updated to include proper maximum width and height constraints, ensuring it fits within smaller screens and supports internal scrolling. This improves layout consistency and usability.
* Users working on smaller screens (e.g., laptops or small monitors) who open the "Add Tool" dialog will now see the entire content without it overflowing off-screen.
* Improves accessibility and usability across devices.
**Before:**
**After:**
Fixes #8002
=> fix: prevent dialog overflow on small screens in MCP Add Tool modal ( Issue #8002)

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/index.ts, packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts
Allows opening a csv file in google drive in google spreadsheet format by supplying an optional param when using `Duplicate File`.
In activepieces:
Result in gdrive.
- if user need to use google sheets actions on a .csv, its not possible until they open that .csv in google sheets.
=> feat(google-drive): duplicate file as a specific mime type (gdocs or gsheet)

.cursor/mcp.json, .gitignore, .vscode/settings.json, packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts, packages/server/api/test/integration/cloud/core/security.test.ts
The `extractProjectIdOrThrow` method in `packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts` was updated to refine project ID extraction and error handling based on route parameters.
*   **For routes containing an `:id` parameter**:
*   The method now attempts to extract the project ID from the resource.
*   If the resource is not found, `ErrorCode.ENTITY_NOT_FOUND` is thrown.
*   The `ENTITY_NOT_FOUND` error `params` now include `entityType` (the resource name) and `entityId` (the ID from the route), along with a descriptive message.
*   **For routes without an `:id` parameter**:
*   The method attempts to extract the project ID directly from the request (body/query).
*   If the project ID is missing, `ErrorCode.VALIDATION` is thrown with a "missing project …
=> fix: return entity not found instead of missing project id

packages/pieces/community/returning-ai/package.json, packages/pieces/community/returning-ai/src/index.ts, packages/pieces/community/returning-ai/src/lib/actions/react-message.ts, packages/pieces/community/returning-ai/src/lib/actions/reply-message.ts, packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
This PR adds a new React Message action to the Returning AI piece that allows users to add emoji reactions to messages.
The React Message action enables users to:
1. Specify a message ID to react to
2. Choose an emoji reaction (e.g. ":smile:", ":heart:", ":thumbsup:")
3. Add the reaction on behalf of a specific user
The action makes a POST request to the Returning AI API endpoint to add the reaction.
API Documentation: https://dev.returning.ai/api-17792861
- Community managers wanting to engage with user messages through emoji reactions
- Automated reaction workflows based on message content or triggers
- Adding standardized reactions to specific types of messages
- Building engagement metrics through reaction tracking
=> feat(returning-ai): add react message action

packages/pieces/community/docusign/package.json, packages/pieces/community/docusign/src/lib/actions/get-document.ts
Even when the document is a PDF, the retrieved file would be named `archive.zip`
=> fix(docusign): fix filename which was always archive.zip even for PDFs

packages/server/api/src/app/ee/platform/platform-plan/platform-plan.module.ts
Do not schedule usage report if Stripe is not configured.
Stripe is used only on Activepieces Cloud Edition. Self-hosted version might not need it.
Just an `if` validation.
Do not schedule usage report if Stripe is not configured.
Currently, it is resulting in false-positive failing jobs on `system-job-queue`:
=> chore(stripe): do not schedule usage report without stripe

packages/pieces/community/common/src/lib/helpers/index.ts
#7805 introduced a breaking change to custom API call response handling. In it's implementation, it relied on a fixed array of content-types to treat as objects. Anything that's not in the list gets treated as a file. The impact is if an API endpoint returns a non-supported content-type, you cannot chain the output because you get a "Download File" button instead in the body.
Our endpoints return content-type as `application/vnd.api+json`. This PR enhances the check to also consider vendor-prefixed content types.
=> fix: support vendor-prefixed content-type responses

packages/server/api/src/app/flows/flow/flow-service-side-effects.ts, packages/server/api/src/app/flows/flow/flow.service.ts
#7835 / #7953 introduced a bug because triggers are still enabled even if the flow is not marked as published - leading to very confusing situations (flow is running while disabled)
=> fix: dont enable triggers when flows should not be activated on publish

packages/pieces/community/slack/package.json, packages/pieces/community/slack/src/index.ts
adding Slack permissions to sync threads with linear:
- channels:history - Read message history
- groups:history - Read private channel history
- chat:write - Send messages to threads
- users:read - Map Slack users to Linear users
=> update slack scopes

packages/pieces/community/notion/package.json, packages/pieces/community/notion/src/lib/common/index.ts
In some cases we fail to generate the dynamic properties to e.g. insert a database item, returning an incomplete array.
This PR adds try/catch block so that only problematic properties are missing + we try to log a proper error message
=> feat(notion): improve error management when generating dynamic input properties

packages/react-ui/src/app/routes/platform/users/index.tsx, packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx, packages/react-ui/src/features/team/component/platform-role-select.tsx, packages/server/api/src/app/ee/projects/project-members/project-member.service.ts, packages/server/api/src/app/project/project-service.ts, packages/server/api/test/integration/cloud/project/project.test.ts, packages/shared/src/lib/user/user.ts
Fixes #7284 
This PR introduces a new platform role called **Platform Operator** - a middle-tier role between Platform Admin and Platform Member. The Platform Operator role provides automatic access to all projects within a platform without granting platform administration capabilities.
The Platform Operator role works as follows:
- **Project Access**: Operators automatically have access to all projects in their platform (similar to admins) but cannot modify platform settings
- **Role Assignment**: Platform admins can assign the Operator role to users through the user management interface
- **Permissions**: Operators get the `DefaultProjectRole.OPERATOR` role within projects they access
- **UI Integration**: The role appears in user listings, role selectors, and update dialogs with proper …
=> feat: add platform operator role

packages/react-ui/src/app/app.tsx, packages/react-ui/src/app/builder/test-step/test-step-hooks.ts, packages/react-ui/src/app/routes/platform/projects/edit-project-dialog.tsx, packages/react-ui/src/app/routes/platform/projects/new-project-dialog.tsx, packages/react-ui/src/app/routes/platform/security/api-keys/new-api-key-dialog.tsx, packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx, packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx, packages/react-ui/src/app/routes/project-release/apply-plan.tsx, packages/react-ui/src/app/routes/settings/pieces/manage-pieces-dialog.tsx, packages/react-ui/src/components/ui/toast.tsx, packages/react-ui/src/features/alerts/lib/alert-hooks.ts, packages/react-ui/src/features/billing/lib/billing-hooks.ts, packages/react-ui/src/features/connections/lib/app-connections-hooks.ts, packages/react-ui/src/features/connections/lib/global-connections-hooks.ts, packages/react-ui/src/features/flows/components/import-flow-dialog.tsx, packages/react-ui/src/features/folders/component/create-folder-dialog.tsx, packages/react-ui/src/features/folders/component/rename-folder-dialog.tsx, packages/react-ui/src/features/platform-admin/components/new-signing-key-dialog.tsx
Global error handling was always showing internal error toast even if the mutation handles the error state.
=> chore: improve global error handling

packages/pieces/community/eden-ai/.eslintrc.json, packages/pieces/community/eden-ai/package.json, packages/pieces/community/eden-ai/src/index.ts
Improves Eden AI piece metadata for better discoverability and professionalism.
- Fixed displayName capitalization: "Eden ai" → "Eden AI"
- Added description explaining Eden AI's AI services
- Added ARTIFICIAL_INTELLIGENCE and UNIVERSAL_AI categories
- Bumped version to 0.0.2
- Users browsing AI pieces can now easily find Eden AI in the correct category
- Clear description helps users understand what Eden AI offers before connecting
=> feat(eden-ai): improve piece metadata and bump version

packages/engine/src/lib/handler/router-executor.ts, packages/engine/test/handler/flow-with-pause.test.ts, packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts, packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-service.ts, packages/server/api/src/app/ee/platform/platform-plan/stripe-helper.ts
=> fix: router branches with same subflow now return correct outputs for different inputs

packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts, packages/pieces/community/microsoft-dynamics-365-business-central/src/index.ts, packages/pieces/community/microsoft-dynamics-crm/src/index.ts, packages/pieces/community/microsoft-excel-365/src/index.ts, packages/pieces/community/microsoft-onedrive/src/index.ts, packages/pieces/community/microsoft-outlook-calendar/src/index.ts, packages/pieces/community/microsoft-outlook/src/lib/common/auth.ts, packages/pieces/community/microsoft-power-bi/src/index.ts, packages/pieces/community/microsoft-sharepoint/src/index.ts, packages/pieces/community/microsoft-teams/src/index.ts, packages/pieces/community/microsoft-todo/src/index.ts, packages/react-ui/src/app/connections/oauth2-connection-settings.tsx, packages/react-ui/src/lib/oauth2-utils.ts
There was an issue where the prompt query paramater in the oAuth authentication request was always set to `consent`. Now the user can determine what to set the paramater to for each piece
There are now four available options for the prompt query parameter `consent`, `none`, `login` and `omit`. When the value is set to omit the query parameter will not be set at all. Otherwise the value will be set to whatever was chosen, defaulting to `consent` when the prompt value is not explicitly set.
- There is an issue within Microsoft where the user will end up in a consent loop if the parameter is set to `consent`
This issue is due to the way that Microsoft handles the prompt=consent query parameter, it will cause the program to always ask for consent, even when admin consent is already given. …
=> fix(oAuth): ability to alter prompt query parameter

packages/server/api/src/app/flows/flow-version/flow-version-migration.service.ts
This is a performance regression. By performing the migration first and then only checking the version, thousands of unnecessary DB calls are made each time a flow is accessed (which is all the time).
We early exit if flow schema version is equal to latest schema version.
=> fix: skip flow migration if already on latest version

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts
fixes update permission for team google drive
Bug fix on existing feature
Fixes #8374
=> fix(google-drive): team drive update permission not working

package-lock.json, package.json, packages/react-ui/src/components/custom/markdown.tsx
This PR fixes the UI bug where the tables in markdown don't render. Instead the raw markdown is rendered. 
The bug was due to new line manipulation done for rendering paragraphs properly. This breaks the tables as single new lines are converted to double. The markdown renderer is updated to use remark-breaks. Also the ReactMarkdown is provided table style to improve the output quality.
This fix also improves code blocks and block elements.
For example, for a markdown (generated by AI):
[sample.md](https://github.com/user-attachments/files/21606577/sample.md)
Current prod:
After fix:
- Users using pieces that can show rendered markdown - for example `Respond on UI` piece.
Fixes #8649
=> fix(markdown): properly render tables in markdown output

packages/pieces/community/autocalls/.eslintrc.json, packages/pieces/community/autocalls/README.md, packages/pieces/community/autocalls/package.json, packages/pieces/community/autocalls/project.json, packages/pieces/community/autocalls/src/index.ts, packages/pieces/community/autocalls/src/lib/actions/add-lead.ts, packages/pieces/community/autocalls/src/lib/actions/campaign-control.ts, packages/pieces/community/autocalls/src/lib/actions/delete-lead.ts, packages/pieces/community/autocalls/src/lib/actions/make-phone-call.ts, packages/pieces/community/autocalls/src/lib/actions/send-sms.ts, packages/pieces/community/autocalls/src/lib/triggers/get-assistants.ts, packages/pieces/community/autocalls/src/lib/triggers/inbound-call.ts, packages/pieces/community/autocalls/src/lib/triggers/phone-call-ended.ts, packages/pieces/community/autocalls/tsconfig.json, packages/pieces/community/autocalls/tsconfig.lib.json
This PR adds a new **Autocalls AI Phone Calling** integration to Activepieces, enabling users to automate voice and SMS outreach using the Autocalls.ai platform. It introduces five new actions and three triggers, allowing seamless campaign management, lead operations, and AI-driven call workflows directly from Activepieces. (https://autocalls.ai/)
* **Authentication & Setup**
Users connect their Autocalls.ai account via an API key. 
* **Actions (5 total)**
1. **Add Lead**
* Select a campaign from the user’s existing campaigns
* Provide a primary contact (with phone number) and optional custom variables
* Optionally include up to 10 secondary contacts per lead
2. **Send SMS**
* Choose from the user’s SMS-enabled phone numbers
* Send personalized text messages using custom variables
3. …
=> feat: add autocalls piece

packages/ee/shared/src/lib/billing/index.ts, packages/react-ui/src/features/billing/components/upgrade-dialog/index.tsx, packages/server/api/src/app/ee/platform/platform-usage-service.ts, packages/server/api/src/app/workers/engine-controller.ts
- decrease ai credits threshold to $15
- show the right plan on business trial
- reset usage to reset untill the start of current month
- never increase tasks on test flow and test step
Fixes #3776
=> fix: reset usage, stop testing from consuming tasks

packages/server/api/src/app/flows/flow-version/flow-version.service.ts
This PR fixes a bug in removeConnectionsFromInput where empty strings ("") were incorrectly replaced with undefined during {{connections.*}} placeholder removal.
1. Create a flow with a dataMapper piece.
2. config mapping property of dataMapper to `{
"company": {
"companyName": "",
"companyProfile": "",
"companyWebsite": "https://www.google.com"
}
}`
3. Export the flow using the “Export Flow” feature.
4. Observe that previously, empty string properties were missing from the exported JSON.
5. After this fix, empty string properties are correctly preserved in the exported JSON.
1. Added a check to preserve empty strings before applying regex replacement.
2. Non-empty strings continue to have {{connections.*}} removed.
3. Handling of arrays, objects, and other value types remains unchanged. …
=> fix: edge case of removeConnectionsFromInput function

packages/pieces/community/google-drive/package.json, packages/pieces/community/google-drive/src/lib/common/get-file-content.ts
Google Drive `read file` action was not able to read a file properly and keeps outputting a file with `.false` extension
Fixed the bug. The first call to google drive to fetch metadata about the file / mimeType requires the `supportsAllDrives` to be set. Otherwise, it will be 404 for a file in the shared drive and so the extension concatenation logic will result in a `.false`. 
I've also set `supportsAllDrives` in other parts of the action to maintain that clarity and consistency. 
https://developers.google.com/workspace/drive/api/guides/enable-shareddrives
=> fix: google drive read file from shared drive

packages/pieces/community/jira-cloud/package.json, packages/pieces/community/jira-cloud/src/lib/common/index.ts
`POST /rest/api/3/search` has been deprecated and the endpoint is now removed, resulting in ALL triggers and the Search Issues action to fail.
https://developer.atlassian.com/changelog/#CHANGE-2046
This follows the migration docs to migrate to `POST /rest/api/3/search/jql`. This just returns a list of issue ids which then needs `POST /rest/api/3/issue/bulkfetch` to retrieve the issue details.
https://community.atlassian.com/forums/Jira-articles/Avoiding-Pitfalls-A-Guide-to-Smooth-Migration-to-Enhanced-JQL/ba-p/2985433
- The outputs should be backwards compatible
- The behaviour might be different now and not be able to find issues immediately after writing. The provided solution of [Search and Reconcile](https://developer.atlassian.com/cloud/jira/platform/search-and-reconcile/) might not …
=> fix(jire): new issue trigger 

packages/server/api/src/app/database/migration/postgres/1758108135968-DeleteHandshakeFromTriggerSource.ts, packages/server/api/src/app/database/migration/sqlite/1758108281602-DeleteHandshakeFromTriggerSourceSqlite.ts, packages/server/api/src/app/database/postgres-connection.ts, packages/server/api/src/app/database/sqlite-connection.ts, packages/server/api/src/app/trigger/trigger-source/flow-trigger-side-effect.ts, packages/server/api/src/app/trigger/trigger-source/trigger-source-entity.ts, packages/server/api/src/app/trigger/trigger-source/trigger-source-service.ts, packages/server/api/src/app/trigger/trigger-source/trigger-utils.ts, packages/server/api/src/app/webhooks/handshake-handler.ts, packages/server/api/src/app/webhooks/webhook.service.ts, packages/shared/src/lib/trigger/index.ts
The bug happens because `onEnable` in the trigger is called first, and only afterward we extract the handshake information and save it in `trigger_source`. However, right after `onEnable` runs, the third-party system calls Activepieces while `trigger_source` hasn’t been created yet, which prevents it from responding correctly to the handshake.
The goal is to de-normalize and fetch the handshake configuration directly from the webhook handler.
=> fix: handshake timing issue

packages/pieces/community/hubspot/package.json, packages/pieces/community/hubspot/src/lib/triggers/deal-stage-updated.ts
Currently the `Updated Deal Stage` trigger doesn't work the way as described
> Triggers when a deal enters a specified stage.
This triggers when **any properties are updated** while the deal is in the specified stage. The technical cause is because `hs_lastmodifieddate` is used for deduplication, and that value updates when any properties are updated.
The correct field to use is `hs_v2_date_entered_current_stage`. Note that this is only available for `Professional and Enterprise only`, but otherwise this trigger would not be able to work as intended anyway.
- https://knowledge.hubspot.com/properties/stage-calculated-properties#understand-stage-calculated-properties
- https://knowledge.hubspot.com/properties/hubspots-default-deal-properties?hubs_content=knowledge.hubspot.com/properties/stag …
=> fix(hubspot): Avoid triggering on non-stage related changes

packages/server/api/src/app/workers/engine-controller.ts
When `AP_FILE_STORAGE_LOCATION` was set to DB, it #was broken
=> fix: db logs for runs

packages/pieces/community/json/package.json, packages/pieces/community/json/src/lib/actions/convert-json-to-text.ts, packages/pieces/community/json/src/lib/actions/convert-text-to-json.ts, packages/react-ui/src/app/builder/pieces-selector/generic-piece-selector-item.tsx, packages/server/api/src/app/flows/step-run/sample-data.service.ts
If you had a (JSON to text) step and tested it, then passed the result to a (Text to JSON) step, the result would still be string, because the first step was stringifying the result that was already a string.
This only happens in testing steps, not flows.
=> fix: test-step results that were string were getting stringified again

docs/handbook/engineering/playbooks/database-migration.mdx
Fix typo in migration command docs
=> fix: typo in migration command doc

packages/pieces/community/datadog/package.json, packages/pieces/community/datadog/src/lib/common.ts
Datadog's custom api call action is using the wrong header for Application Key. It should be `DD-APPLICATION-KEY` instead of `DD-APP-KEY`. That header is not recognized and will produce a 401 error if the API endpoint requires it.
https://docs.datadoghq.com/api/latest/?tab=java#api-reference
> Authenticate to the API with an API key using the header DD-API-KEY. For some endpoints, you also need an Application key, which uses the header DD-APPLICATION-KEY.
Old:
New:
=> fix(datadog): fix incorrect application key header for custom api call action

packages/pieces/community/netsuite/package.json, packages/pieces/community/netsuite/src/index.ts, packages/pieces/community/netsuite/src/lib/actions/get-customer.ts, packages/pieces/community/netsuite/src/lib/actions/get-vendor.ts, packages/pieces/community/netsuite/src/lib/oauth.ts
Currently using query params do not work because they need to be added to the signature. If query params are used, the API would throw 401 with InvalidSignature.
https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_157651396916.html#subsect_157652037988
Support signature calculation from query params either directly extracted from the URL and/or in a queryParams Record.
=> fix(netsuite): signature query params
